### DISCUSSION TITLE
SchemaLoader should not inject additional slots for slot_usage and attributes

### DISCUSSION THREAD

**Discussion by cmungall** [linkml/linkml#144] [Q&A] [answered]
Currently SchemaLoader will manipulate the SchemaDefinition object, doing many useful things. However, this can make it hard to access the intended meaning of the slot.

In particular, when slot_usage is used for `s` on `c`, this has the effect of making SL inject additional slots, `c_s`.

Currently this "leaks out" all over the place for example, e.g.

https://biolink.github.io/biolink-model/docs/SequenceVariant.html

![image](https://user-images.githubusercontent.com/50745/105741434-25d76580-5eef-11eb-92e3-68b1b93a9803.png)

`id` is shown twice, as if they are different. In fact they should **not** be treated as distinct. in fact SequenceVariant is simply defining some context-specific examples for the generic id property

```yaml
  sequence variant:
    aliases: ['allele']
...
    slot_usage:
      has gene:
        multivalued: true
        description: Each allele can be associated with any number of genes
      has biological sequence:
        description: >-
          The state of the sequence w.r.t a reference sequence
      id:
        examples:
          - value: ZFIN:ZDB-ALT-980203-1091
            description: ti282a allele from ZFIN
          - value: ClinVarVariant:17681
            description: NM_007294.3(BRCA1):c.2521C>T (p.Arg841Trp)
```

I think the datamodel should work like the owlapi

The SD object should *not* be manipulated. Instead there should be utility or wrapper classes that can be used to do things like look up something in the whole imports closure, or return inferred values of slots based on class context
