### DISCUSSION TITLE
How to inherit from a class defined in a different file?

### DISCUSSION THREAD

**Discussion by Prakash2403** [linkml/linkml#1578] [Q&A]
I have defined my base class in one YAML file, and derived classes in a separate one. I want to inherit the base class in my derived one. Here's what I am doing

```
id: http://localhost/MEX
name: MEX
prefixes:
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
  ORCID: https://orcid.org/
imports:
  - linkml:types
  - master # My base class is defined in a file named master.yaml, which is in the same directory

classes:
  MEX:
    is_a: master # My base class is named Master
    attributes:
      test_param:
        required: True
```

However, I am getting 
```
ValueError: File "mex.yaml", line 13, col 11 Class: "MEX" - unknown is_a reference: master
```

Here's my `master.yaml` file

```
id: http://localhost/master
name: Master
prefixes: 
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
  ORCID: https://orcid.org/
imports:
  - linkml:types
default_range: string
classes:
  master:
    abstract: true
    attributes:
      state:
        required: true
```
