### DISCUSSION TITLE
Constraining values using other fields

### DISCUSSION THREAD

**Discussion by PeterKraus** [linkml/linkml#1840] [Q&A]
Dear LinkML team, 
we would like to constrain the values a certain slot can have, based on the values in a different slot higher up the schema. As an example:

```yaml
all_supported_cases:
  - a
  - b
  - c
  - d
detailed_usage:
  - case: "a and b"
    supported_cases:
    - a
    - b
  - case: "c only"
    supported_cases:
    - c
```
We don't know what the `all_supported_cases` are in advance (so I'm not sure how to write an `Enum`), but we want to make sure that there are no entries listed in the individual `supported_cases` that are also not included in the `all_supported_cases`. What is the best way of doing this?

Thanks!
Peter

**Comment by cmungall** [comment]
Hi @PeterKraus - not sure I follow your example. Is your yaml showing example data or kind of a sketch of a schema?

This might be something that rules can help with:
https://linkml.io/linkml/schemas/advanced.html#rules

**Reply by PeterKraus** [reply]
Dear Chris, thanks for your reply. It's an example of the data. I think you're right, the rules will be useful, but how can I constrain the "enumeration" of allowed values in `supported_cases` to those listed in `all_supported_cases`? I know how to do it if I know `all_supported_cases` up front (it's a simple Enum), but that's also user-supplied?

**Comment by sierra-moxon** [comment]
Hi @PeterKraus - I'm not sure I understand your question fully.  

As a very simple example: are you asking if LinkML schema syntax supports a use case like:  "if slot_a > 2, then slot_b must be 'false' and if slot_a < 2, slot_b must be 'true'"?

**Comment by sierra-moxon** [comment]
e.g. 
```
classes:
  Usage:
   slots:
     - filetypes
     - command
     - setup
     - method
   rules:
     - preconditions:
         slot_conditions:
            command:
               any_of:
                  - equals_string: "yadg.extractors.biologic_extract({{ input_type }}, {{ input_path }})"
     - postconditions:
         slot_conditions:
             file_types:
                any_of:
                  - equals_string: "biologic-mpr"
                  - equals_string: "biologic-mpt"
                  
slots:
   filetypes:
      range: FiletypeEnum
enums:
   FiletypeEnum:
      permissible_values:
         - "panalytical-xrdml"
         - "biologic-mpr" 
         - "biologic-mpt"
 ```
