### DISCUSSION TITLE
LinkML slot inheritance in case of attributes

### DISCUSSION THREAD

**Discussion by uermel** [linkml/linkml#1945] [Q&A]
Hi all, I have a question regarding slot inheritance when using class attributes. 

I'm trying to re-use a slot definition in the context of a class by specifying the parent slot in the attribute's `is_a`, but this doesn't seem to work when using the generators. I know there is `slot_usage`, but I'd like to change the slot name. I could define the slot outside of the class, but this would cause name collisions in the schema, which is why I'd prefer to define attributes instead. 

Is this intended behavior, or should inheritance work when using `is_a` inside class attribute definitions?

Example schema: 
```yaml
id: id
name: example
prefixes:
  linkml: https://w3id.org/linkml/
default_range: string
default_prefix: ex

slots:
  integer_slot:
    range: integer

  a_derived_slot:
    is_a: integer_slot

classes:
  SampleClass:
    slots:
      - integer_slot
      - a_derived_slot
    attributes:
      another_derived_slot:
        is_a: integer_slot
```

Example when materialized with `gen-linkml`
```yaml
name: example
id: id
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/
default_prefix: ex
default_range: string
slots:
  integer_slot:
    name: integer_slot
    from_schema: id
    domain_of:
    - SampleClass
    range: integer
  a_derived_slot:
    name: a_derived_slot
    from_schema: id
    is_a: integer_slot
    domain_of:
    - SampleClass
classes:
  SampleClass:
    name: SampleClass
    from_schema: id
    slots:
    - integer_slot
    - a_derived_slot
    attributes:
      another_derived_slot:
        name: another_derived_slot
        from_schema: id
        is_a: integer_slot
        alias: another_derived_slot
        owner: SampleClass
        domain_of:
        - SampleClass
        range: string     # <-- range is default range, not the parent slot's range
      integer_slot:
        name: integer_slot
        from_schema: id
        alias: integer_slot
        owner: SampleClass
        domain_of:
        - SampleClass
        range: integer
      a_derived_slot:
        name: a_derived_slot
        from_schema: id
        is_a: integer_slot
        alias: a_derived_slot
        owner: SampleClass
        domain_of:
        - SampleClass
        range: integer  # <-- range is correct when inheriting outside the class context
```
