### DISCUSSION TITLE
Asserting concrete values in subclasses (is_class_field?)

### DISCUSSION THREAD

**Discussion by Natureshadow** [linkml/linkml#2085] [Q&A]
Given the following model fragment:

```yaml
classes:
  Credential:
    attributes:
      id:
        identifier: true
      description:
        required: true
        description:
          A human-readable description of this credential class
  Factor:
    attributes:
      id:
        identifier: true
      description:
        description:
          A human-readable description of this factor
      credentials:
        multivalued: true
        description:
          The credential classes this factor fulfills
        range: Credentia
```

I will later subclass `Factor`, to make, e.g., a `FooFactor`. `FooFactor` shall define a concrete set of values for the `credentials` slot, which all instances of `FooFactor` will get.

How could I model this?

I found the `is_class_field` attribute, which reads as if it should do what I want, but I am still missing the part of the puzzle where I provide the concrete values to assert from `FooFactor` on its instances.

If it helps, I could make the `credentials` slot point to an enum instead.
