### DISCUSSION TITLE
What are the default values for meta model slots?

### DISCUSSION THREAD

**Discussion by candleindark** [linkml/linkml#2147] [Q&A]
Is there a systematic way to look up the default value for a meta model slot?

I know that the [`required`](https://linkml.io/linkml-model/latest/docs/required/) meta model slot has a default of `false` from experimentation and the [`default_range`](https://linkml.io/linkml-model/latest/docs/default_range/) slot has a default of `string` from [documentation](https://linkml.io/linkml/schemas/advanced.html#linkml-any-type). However, I haven't found a way look up the default value for an arbitrary meta model slot. Is there such a way? If there is, what is it?

Ping @djarecka

**Comment by cmungall** [comment]
Some metamodel elements will have `ifabsent` explicitly declared; e.g. : [linkml:range](https://w3id.org/linkml/range)

If it doesn't have this you can assume there is no default

Booleans are a special case and this should be better documented: rather than thinking of these having a default of `false`, think of this in terms of [truthiness](https://stackoverflow.com/questions/39983695/what-is-truthy-and-falsy-how-is-it-different-from-true-and-false), i.e `None` is "falsy"

**Reply by candleindark** [reply]
@cmungall Thanks for the answer.

[`default_range`](https://linkml.io/linkml-model/latest/docs/default_range/) doesn't have a `ifabsent` declared, so it doesn't have a default, and the [documentation](https://linkml.io/linkml/schemas/advanced.html#linkml-any-type) regarding the default of `default_range` is wrong. I also confirmed the mistake in the documentation with the following schema and data instance.

`personinfo.yaml`
```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  personinfo: https://w3id.org/linkml/examples/personinfo
imports:
  - linkml:types
default_prefix: personinfo

classes:
  Person:
    attributes:
      id:
      full_name:
      aliases:
      phone:
      age:
```

`data.yaml`
```
id: ORCID:1234
full_name: Clark Kent
age: 32
phone: 555-555-5555
```

Running the following command produces no error.
```
❯ linkml-validate -s personinfo.yaml data.yaml
No issues found
```


With all that said, it is a bit strange to have `default_range` to have no default. The above schema apparently render all attributes of `Person` to have a range of [`Any`](https://linkml.io/linkml/schemas/advanced.html#linkml-any-type).
