### DISCUSSION TITLE
linkML support for requiring `slot_usage` for a slot on its definition

### DISCUSSION THREAD

**Discussion by kheal** [linkml/linkml#2159] [Ideas]
Usecase:
I have a slot, let's call it `has_input`, that's used across many classes and subclasses.  I would _love_ a mechanism in the schema to be able to declare that the`has_input` slot must have an associated `slot_usage` naming its `structured_pattern` on each class it's used on (including when it's inherited from a parent class).  

Ideally, I'd love a way to add this to the definition of the slot along the lines of this:
```
slots:
  has_input:
    must_be_set_on_induced_slots:
      - structured_pattern
```

The cherry on top would be the ability to use for subslots as well.
For example:
```
slots:
  has_connected_class:
    must_be_set_on_induced_slots:
      - structured_pattern

  has_input:
    is_a: has_connected_class

  has_output:
    is_a: has_connected_class
```
