### DISCUSSION TITLE
Explore methods on how to use DataCube vocabulary and patterns

### DISCUSSION THREAD

**Discussion by cmungall** [linkml/linkml#2194] [General]
Use case: 

For example, measurements of air temperature at different points on the globe at different altitudes.

Here we might have a schema with a class TemperatureMeasurement and slots lat, long, alt, temp

In terms of https://www.w3.org/TR/vocab-data-cube/, TemperatureMeasurement would be an observation, and  lat, long, alt would be dimensions, with temp being a measurement

See also: https://en.wikipedia.org/wiki/Tidy_data

The simplest thing to do is to add links in this schema to qb URIs; via one of:

- class/slot_uri
- conforms_to
- mappings

This is suboptimal in some situations as we may want to enforce stricter binding.

The proposal here would be to make a LinkML version of qb

This would include a minimal set of classes:

- Observation
- DataSet

And slots:

- dimension
- measurement

These may both be tagged as mixins (see below)

(Note that some parts of qb map to the metamodel rather than domain model)

domain models could then inherit from linkml-qb; e.g.

```yaml
imports:
  - linkml:qb

classes:
  TempDataset:
    mixins: [DataSet]
    observations:
     range: TempObservation
     multivalued: true
  TempObservation:
    mixins: [Observation]
    attributes:
      lat:
       mixins: [dimension]
       range: decimal
      long:
       mixins: [dimension]
       range: decimal
      alt:
       mixins: [dimension]
       range: float
       unit:
         ucum_unit: m
      temp:
       mixins: [measurement]
       range: float
       unit:
         ucum_unit: K
```

However, inheritance feels like overkill here. We should explore alternatives

- profiles, #710 
- building qb interpretations directly into the metamodel

With the latter the schema may look like:

```yaml
classes:
  TempDataset:
    statistical_role: DataSet.  ## redundant with tree_root: true?
    observations:
     range: TempObservation
     multivalued: true
  TempObservation:
    statistical_role: Observation
    attributes:
      lat:
       statistical_role: Dimension
       range: decimal
      long:
       statistical_role: Dimension
       range: decimal
      alt:
       statistical_role: Dimension
       range: float
       unit:
         ucum_unit: m
      temp:
       statistical_role: Measurement
       range: float
       unit:
         ucum_unit: K
```

(the values of statistical_role would come from a fixed enum)

this has certain advantages in that more checks could be built in at the schema level and dataset level
