### DISCUSSION TITLE
rdf:langString support in LinkML types

### DISCUSSION THREAD

**Discussion by mahdanoura** [linkml/linkml#2199] [Q&A]
In the W3C Web of Things standard, we are trying to utilise the LinkML model to describe the Thing Description standard [https://www.w3.org/TR/wot-thing-description11/]. The Thing Description document is structured as a JSON-LD document, where we need to use `rdf:langString` or the equivalent `rdf:PlainLiteral `Datatype for some of our attributes. Below, you can find the LinkML snippet I use for modelling the entity `title`, which can be either a string or a langString (e.g., "hue lamp"@en).

```
types:
  MultiLanguage:
    name: MultiLanguage
    description: Title with a language tag.
    from_schema: rdf
    exact_mappings:
    - rdf:PlainLiteral
    base: rdf:langString
    uri: rdf:langString
  title:
    description: >-
      Provides a human-readable title (e.g., display a text for UI representation) based on a default language.
    exactly_one_of:
      - range: string
      - range: MultiLanguage
    required: true
    slot_uri: td:title
```
However, the JSON Schema that is generated from this is:

```
"title": {
            "description": "Provides a human-readable title (e.g., display a text for UI representation) based on a default language.",
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "string"
                }
            ],
            "type": "string"
        }
```
Any help would be appreciated. Thank you.
