### DISCUSSION TITLE
How to define a slot whose values are comparable to a dictionary in Python?

### DISCUSSION THREAD

**Discussion by candleindark** [linkml/linkml#2239] [Q&A]
Is it possible and how to define a slot whose values are comparable to a dictionary in Python?

For example, how to express the `digest` field in the following simplified model taken from the Dandi project.

```py
from enum import Enum

from pydantic import BaseModel


class DigestType(Enum):
    """An enumeration of checksum types"""

    #: MD5 checksum
    md5 = "dandi:md5"

    #: SHA1 checksum
    sha1 = "dandi:sha1"

    #: SHA2-256 checksum
    sha2_256 = "dandi:sha2-256"

    #: SHA3-256 checksum
    sha3_256 = "dandi:sha3-256"

    #: BLAKE2B-256 checksum
    blake2b_256 = "dandi:blake2b-256"

    #: BLAKE3-256 checksum
    blake3 = "dandi:blake3"

    #: S3-style ETag
    dandi_etag = "dandi:dandi-etag"

    #: DANDI Zarr checksum
    dandi_zarr_checksum = "dandi:dandi-zarr-checksum"


class BareAsset(BaseModel):
    # A map of digests to their values
    digest: dict[DigestType, str]
```

**Comment by cmungall** [comment]
See https://linkml.io/linkml/schemas/inlining.html#inlining-as-simple-dictionaries

But this is still a bit verbose at the object level. I think this is something we want to prioritize moving forward

**Reply by candleindark** [reply]
`bare_asset.yaml`

```yaml
id: https://w3id.org/linkml/examples/bareasset
name: bareasset
prefixes:
  linkml: https://w3id.org/linkml/
  bareasset: https://w3id.org/linkml/examples/bareasset
imports:
  - linkml:types
default_range: string
default_prefix: bareasset

enums:
  DigestType:
    permissible_values:
      md5:
      sha1:
      sha2_256:
      sha3_256:
      blake2b_256:
      blake3:
      dandi_etag:
      dandi_zarr_checksum:

classes:
  Digest:
    attributes:
      type:
        range: DigestType
        key: true
      value:
        range: string
  BareAsset:
    attributes:
      digest:
        range: Digest
        multivalued: true
        inlined: true
        inlined_as_list: false
```

1. Do you mean that, currently, one has to bundle the key and value in a class definition as I did in the `Digest` class in the example above to achieve the goal mentioned?
2. Is there any limitation on the range of the key/identifier slot of the newly defined class, i.e. can the range of the slot be any type?
3. What are the difference between [the key meta slot](https://linkml.io/linkml-model/latest/docs/key/) and [the identifier meta slot](https://linkml.io/linkml-model/latest/docs/identifier/).
4. I think there is bug in this feature https://linkml.io/linkml/schemas/inlining.html#inlining-as-simple-dictionaries if my understanding is correct.
    1. Given `data.yaml`
       ```yaml
       - digest:
           md5: "md5 value"
           sha1: "sha1 value"
       - digest:
           foo: "foo value"
           sha3_256: "sha3_256 value"
       ```
    2. Run `linkml-validate -C BareAsset -s bare_asset.yaml data.yaml` produces no error even though `"foo"` is an invalid value for the `type` slot of `Digest`.
