### DISCUSSION TITLE
Possibility to indicate a slot cannot have a value/cannot exist based on constraint

### DISCUSSION THREAD

**Discussion by stanleyj-edsn** [linkml/linkml#2312] [Q&A] [answered]
Hi,
I'm looking for a way to indicate an attribute cannot exist or cannot have a value (practical use only in combination with a constraint)

Example: 
given a class MyClass, with attribute_a and attribute_b:
attribute_b is not multivalued
if attribute_a has value `foo` then attribute_b cannot have a value/is unset/does not exist.

Is it possible? It looks like a slot property like 'applicable' is needed to support a constraint like this.
Since attribute_b is not multivalued, putting a constraint maximum_cardinality = 0 would not work

If this is not supported but in scope for LinkML (backlog), let me know and I'll find workaround
If this is not supported because it is out of scope for LinkML (does not fit philosophy), let me know and I'll look for a different solution

Thanks in advance!

**Comment by pkalita-lbl** [comment, marked as answer]
A combination of [`rules`](https://linkml.io/linkml/schemas/advanced.html#rules) on a class definition and [`value_presence`](https://linkml.io/linkml-model/1.8.x/docs/value_presence/) might work for you. Something like this:

```yaml
classes:
  MyClass:
    slots:
      - attribute_a
      - attribute_b
    rules:
      - description: no attribute_b if attribute_a is foo
        preconditions:
          slot_conditions:
            attribute_a:
              equals_string: foo
        postconditions:
          slot_conditions:
            attribute_b:
              value_presence: ABSENT
```
