### DISCUSSION TITLE
How to not duplicate classes to have optional id ?

### DISCUSSION THREAD

**Discussion by ticapix** [linkml/linkml#2472] [Q&A]
Hello,

Is there a way to declare a classes to have an optional id or a simpler workaround than the one below ?

My Linkml schema `Person.yaml` file:

```yaml
id: example-schema
name: ExampleSchema
description: An example schema demonstrating a class with a slot mapped to foaf:name.
prefixes:
  linkml: https://w3id.org/linkml/
  foaf: http://xmlns.com/foaf/0.1/
  example: http://example.org/
default_prefix: example
default_range: string

imports:
  - linkml:types

classes:
  DocumentBlank:
    class_uri: foaf:Document
    slots:
      - topic

  Document:
    is_a: DocumentBlank
    class_uri: foaf:Document
    slots:
      - id

  Person:
    description: A person entity with a name.
    class_uri: foaf:Person
    slots:
      - id
      - name
      - publications

slots:
  id:
    identifier: true
    range: uriorcurie
  name:
    slot_uri: foaf:name
  topic:
    slot_uri: foaf:topic
  publications:
    domain: Person
    slot_uri: foaf:publications
    range: DocumentBlank
    multivalued: true
  ```

I generate the python code with `gen-python Person.yaml > Person.py`

And I use it as below:

```python
#!/usr/bin/env python3
from pathlib import Path
from linkml_runtime.dumpers import RDFLibDumper
from linkml_runtime.utils.schemaview import SchemaView
import Person

if __name__ == "__main__":
    doc = Person.Document(id="example:doc2", topic="doc2")

    p1 = Person.Person(id="example:p1",
                             name="foobar",
                             publications=[
                                 Person.DocumentBlank(topic="doc1"), doc
                             ])

    schema_view = SchemaView(Path(__file__).parent / 'Person.yaml')

    g = RDFLibDumper().as_rdf_graph(element=p1, schemaview=schema_view)
    print(g.serialize())
```

To finaly get

```text
@prefix example: <http://example.org/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

example:p1 a foaf:Person ;
    foaf:name "foobar" ;
    foaf:publications [ a foaf:Document ;
            foaf:topic "doc1" ],
        example:doc2 .

example:doc2 a foaf:Document ;
    foaf:topic "doc2" .
```

Is there a simple way, without having to duplicate class with a "dummy" `DocumentBlank` class ?

Thank you
Pierre
