### DISCUSSION TITLE
Modelling mutually exclusive slots

### DISCUSSION THREAD

**Discussion by multimeric** [linkml/linkml#2476] [Q&A]
How should I model "this class either has slot a or slot b or slot c"?

I tried this, but `aliases` isn't quite right. This will still allow calling the field `x` which isn't what I want:
```yaml
...
classes:
  Foo:
    slots:
      - x
slots:
  x:
    any_of:
      - range: Integer
        aliases: [a]
      - range: Boolean
        aliases: [b]
      - range: Float
        aliases: [c]
```

It seems you also can't do this, because a `ClassExpression` can't have `slots`:

```yaml
classes:
  Foo:
    any_of:
      - slots: [a]
      - slots: [b]
      - slots: [c]
slots:
  a:
    range: integer
  b:
    range: boolean
  c:
    range: float
```
