### DISCUSSION TITLE
Best practices for modeling variables in LinkML, and mapping to i-ADOPT

### DISCUSSION THREAD

**Discussion by cmungall** [linkml/linkml#2599] [General]
A subset of uses of slots in LinkML are to record variables and CDEs. LinkML, allows slots to have a [unit](http://w3id.org/linkml/unit), with range [UnitOfMeasure](http://w3id.org/linkml/UnitOfMeasure). This allows for:

```yaml
slots:
  diss_o2_mass_in_water:
    range: float
    unit:
      ucum: mg.kg-1
      has_quantity_kind: qudt:Concentration
```

However, this doesn't capture the object of interest (o2) or the "matrix" (water).

Many groups delegate this to an external ontology:

```yaml
slots:
  diss_o2_mass_in_water:
    range: float
    unit:
      ucum: mg.kg-1
      has_quantity_kind: qudt:Concentration
      exact_mappings:
       - ENVO:nnnn
```

Or using the ontology class in place of the generic quantity kind.

However, for many use cases it would be useful to inline the additional metadata

Standards such as ISO-11179-3 (which is largely followed) and [I-ADOPT](https://i-adopt.github.io/ontology) provide some way of doing this.

See for example:
https://vocab.nerc.ac.uk/collection/P01/current/DOXMZZXX/?_profile=iop&_mediatype=text/html

iop:hasProperty already corresponds to has_quantity_kind (== qudt:hasQuantityKind), but we don't have a direct equivalent for matrix and object of interest. 

- should we add these? to UnitOfMeasure?
- other aspects to add?
