### DISCUSSION TITLE
Working with dynamic enumerations - a place for discussion and FAQ

### DISCUSSION THREAD

**Discussion by sierra-moxon** [linkml/linkml#2652] [Q&A]
To seed the discussion, a question from slack:

Hi all! I'm having an issue with dynamic enums during code generation.
Here's my schema with a dynamic enum that follows the documentation pattern (https://linkml.io/linkml/schemas/enums.html#dynamic-enums):
```
enums:
  CellTypeEnum:
    reachable_from:
      source_ontology: obo:cl
      source_nodes:
        - CL:0000000
      include_self: true
      relationship_types:
        - rdfs:subClassOf
 ```
The vskit expand command works fine, but when I try to convert my data to TTL:
```
linkml-convert \
  --schema schema.yaml \
  examples.yaml \
  --output output.ttl \
  --output-format ttl
```
I get this error:

```
NameError: name 'CellTypeEnum' is not defined
```
The enum is being referenced in my CellType class:
```
  CellType:
    description: "A reference to a Cell Ontology (CL) term"
    class_uri: owl:Class
    slots:
      - id
      - label
      - has_characterizing_marker_set
    slot_usage:
      id:
        range: CellTypeEnum
        identifier: true
        required: true
```

Cory Levinson:
when you run linkml-convert there's no explicit reference to the expanded schema, and from the links you shared, the expanded schema is not listed as an import in the main schema.yaml.  I'm not 100% certain how this is expected to work, but I have spent a bit of time with semantic enums so do have some ideas...
If you add the expanded schema as an import on the main one, does that fix things?

I spent some time working with your examples / files and I think I found the root cause of the problem – it's not possible to have a slot with identifier: true also have a enum as a range.

I see two paths forward:
- be less restrictive in your id slot, and use the id_prefixes and id_prefixes_are_closed metaslots (see github issue here: https://github.com/linkml/linkml/issues/194)
- use a different slot instead of id for your CellTypeEnum value, such as cell_type_id (without using identifier: true on that slot)
In this case, you may still need some identifier for the CellType class in order to continue using your annotated_source slot as you currently do, since without an identifier slot for CellType you would need your Axiom class instances to have annotated_source values referenced inline in all examples (as opposed to reference by ID which is what your current example does)
Alternatively, you could change the range of annotated_source to be CellTypeEnum, and that should work fine as well.
