### DISCUSSION TITLE
Default values for `ifabsent` for multi-typed/multi-ranged classes.

### DISCUSSION THREAD

**Discussion by daniel-ji** [linkml/linkml#2777] [Q&A]
Hi all,

@uermel and I were wondering if there was any planned support for something along the lines of:

```yaml
id: common
name: common
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types

classes:
  sample_class:
    attributes:
      sample_attribute:
        any_of:
          - range: string
          - range: integer
        ifabsent: "test"
```

Where you can have an attribute that supports two ranges, but still has a default value. 

This currently gives an error, when trying to run something like `linkml generate pydantic test.yml`:

```
ValueError: The ifabsent value `test` of the `sample_attribute` slot could not be processed
```

Only if you specify a range value as follows, does it work:

```yaml
id: common
name: common
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types

classes:
  sample_class:
    attributes:
      sample_attribute:
        range: string
        any_of:
          - range: string
          - range: integer
        ifabsent: "hello"
```

However, this makes the `any_of` purposeless then, since the generated JSON doesn't support integers as valid input when it should:

```json
{
    "$defs": {
        "SampleClass": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "sample_attribute": {
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "integer"
                        },
                        {
                            "type": "null"
                        }
                    ],
                    "type": "string"
                }
            },
            "title": "SampleClass",
            "type": "object"
        }
    },
    "$id": "common",
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "title": "common",
    "type": "object",
    "version": null
}
```

Thank you!
