### ISSUE TITLE
YAMLGenerator creates yaml that is too verbose

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#100]
There are two issues

 1. mergeimports=False seems to fail; biolinkml.types are merged in
 2. auto-populated slots in the schema are always populated, leading to clutter

To replicate, take the following yaml:

```yaml
id: http://example.org/sample/sql

prefixes:
  ex: http://example.org/
  biolinkml: https://w3id.org/biolink/biolinkml/

default_prefix: ex
default_range: string

imports:
  - biolinkml:types
subsets:
  mysubset: {}

types:
  unitcode:
    base: str
    uri: xsd:string

classes:
  person:
    slot_usage:
      id:
        identifier: true
        required: true
      name:
        required: true
      aliases:
        multivalued: true

  employee:
    is_a: person

  organization:
    slot_usage:
      employees:
        range: employee
        multivalued: true
```

The following python:

```python
        yaml_fname = env.input_path('issue_288.yaml')
        gen = YAMLGenerator(yaml_fname, mergeimports=False)
        s = gen.serialize()
```

will generate:

```yaml
name: sql
id: http://example.org/sample/sql
imports:
- biolinkml:types
license: https://creativecommons.org/publicdomain/zero/1.0/
prefixes:
  ex:
    prefix_prefix: ex
    prefix_reference: http://example.org/
  biolinkml:
    prefix_prefix: biolinkml
    prefix_reference: https://w3id.org/biolink/biolinkml/
default_prefix: ex
default_range: string
subsets:
  mysubset:
    name: mysubset
    definition_uri: http://example.org/Mysubset
    from_schema: http://example.org/sample/sql
types:
  unitcode:
    name: unitcode
    definition_uri: http://example.org/Unitcode
    from_schema: http://example.org/sample/sql
    base: str
    uri: xsd:string
  string:
    name: string
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/String
    description: A character string
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: str
    uri: xsd:string
  integer:
    name: integer
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Integer
    description: An integer
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: int
    uri: xsd:integer
  boolean:
    name: boolean
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Boolean
    description: A binary (true or false) value
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: Bool
    uri: xsd:boolean
  float:
    name: float
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Float
    description: A real number that conforms to the xsd:float specification
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: float
    uri: xsd:float
  double:
    name: double
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Double
    description: A real number that conforms to the xsd:double specification
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: float
    uri: xsd:double
  decimal:
    name: decimal
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Decimal
    description: A real number with arbitrary precision that conforms to the xsd:decimal
      specification
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: Decimal
    uri: xsd:decimal
  time:
    name: time
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Time
    description: A time object represents a (local) time of day, independent of any
      particular day
    notes:
    - URI is dateTime because OWL reasoners don't work with straight date or time
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: XSDTime
    uri: xsd:dateTime
    repr: str
  date:
    name: date
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Date
    description: a date (year, month and day) in an idealized calendar
    notes:
    - URI is dateTime because OWL reasoners don't work with straight date or time
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: XSDDate
    uri: xsd:date
    repr: str
  datetime:
    name: datetime
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Datetime
    description: The combination of a date and time
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: XSDDateTime
    uri: xsd:dateTime
    repr: str
  uriorcurie:
    name: uriorcurie
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Uriorcurie
    description: a URI or a CURIE
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: URIorCURIE
    uri: xsd:anyURI
    repr: str
  uri:
    name: uri
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Uri
    description: a complete URI
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: URI
    uri: xsd:anyURI
    repr: str
  ncname:
    name: ncname
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Ncname
    description: Prefix part of CURIE
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: NCName
    uri: xsd:string
    repr: str
  objectidentifier:
    name: objectidentifier
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Objectidentifier
    description: A URI or CURIE that represents an object in the model.
    comments:
    - Used for inheritence and type checking
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: ElementIdentifier
    uri: shex:iri
    repr: str
  nodeidentifier:
    name: nodeidentifier
    definition_uri: https://w3id.org/biolink/biolinkml/meta/types/Nodeidentifier
    description: A URI, CURIE or BNODE that represents a node in a model.
    from_schema: https://w3id.org/biolink/biolinkml/types
    imported_from: biolinkml:types
    base: NodeIdentifier
    uri: shex:nonLiteral
    repr: str
slots:
  id:
    name: id
    from_schema: http://example.org/sample/sql
    range: string
    slot_uri: ex:id
    required: true
    identifier: true
  name:
    name: name
    from_schema: http://example.org/sample/sql
    range: string
    slot_uri: ex:name
    required: true
  aliases:
    name: aliases
    from_schema: http://example.org/sample/sql
    range: string
    slot_uri: ex:aliases
    multivalued: true
  employees:
    name: employees
    from_schema: http://example.org/sample/sql
    range: employee
    slot_uri: ex:employees
    multivalued: true
  person_id:
    name: person_id
    from_schema: http://example.org/sample/sql
    is_a: id
    domain: person
    range: string
    slot_uri: ex:id
    required: true
    identifier: true
    alias: id
    owner: person
    domain_of:
    - person
    is_usage_slot: true
    usage_slot_name: id
  person_name:
    name: person_name
    from_schema: http://example.org/sample/sql
    is_a: name
    domain: person
    range: string
    slot_uri: ex:name
    required: true
    alias: name
    owner: person
    domain_of:
    - person
    is_usage_slot: true
    usage_slot_name: name
  person_aliases:
    name: person_aliases
    from_schema: http://example.org/sample/sql
    is_a: aliases
    domain: person
    range: string
    slot_uri: ex:aliases
    multivalued: true
    alias: aliases
    owner: person
    domain_of:
    - person
    is_usage_slot: true
    usage_slot_name: aliases
  organization_employees:
    name: organization_employees
    from_schema: http://example.org/sample/sql
    is_a: employees
    domain: organization
    range: employee
    slot_uri: ex:employees
    multivalued: true
    alias: employees
    owner: organization
    domain_of:
    - organization
    is_usage_slot: true
    usage_slot_name: employees
classes:
  person:
    name: person
    definition_uri: http://example.org/Person
    from_schema: http://example.org/sample/sql
    slots:
    - person_id
    - person_name
    - person_aliases
    slot_usage:
      id:
        name: id
        from_schema: http://example.org/sample/sql
        range: string
        slot_uri: ex:id
        required: true
        identifier: true
      name:
        name: name
        from_schema: http://example.org/sample/sql
        range: string
        slot_uri: ex:name
        required: true
      aliases:
        name: aliases
        from_schema: http://example.org/sample/sql
        range: string
        slot_uri: ex:aliases
        multivalued: true
    class_uri: ex:Person
  employee:
    name: employee
    definition_uri: http://example.org/Employee
    from_schema: http://example.org/sample/sql
    is_a: person
    slots:
    - person_id
    - person_name
    - person_aliases
    class_uri: ex:Employee
  organization:
    name: organization
    definition_uri: http://example.org/Organization
    from_schema: http://example.org/sample/sql
    slots:
    - organization_employees
    slot_usage:
      employees:
        name: employees
        from_schema: http://example.org/sample/sql
        range: employee
        slot_uri: ex:employees
        multivalued: true
    class_uri: ex:Organization
metamodel_version: 1.7.0
source_file: issue_288.yaml
source_file_date: Sat Jan  9 21:02:32 2021
source_file_size: 574
generation_date: 2021-01-10 18:33
```

Note that not only does this expand and auto-populate fields, it changes names

highlighting a section of the input:

```yaml
...
 organization:
    slot_usage:
      employees:
        range: employee
...
```

this renames the slot to `organization_employees`
```yaml
...
  organization:
    name: organization
    slots:
    - organization_employees
   slot_usage:
      employees:
...
```
