### ISSUE TITLE
Provide a means of traversing non-inlined references

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1009]
Currently, if a range is not inlined, then the python object structure using inlining metadata, and thus parallels the json/yaml

E.g.

```yaml
- id: P1
  has_familial_relationships:
   - related_to: P2
      type: ...
- id: P2
   ...
```

here 

```python
p1.has_familial_relationships[0]
```

will yield a PersonId instance (which is a string) of `P2`

If we try

```python
p1.has_familial_relationships[0].name
```

this will fail

it would be useful to have a mock person object that operates over the underlying object graph rather than tree
