### ISSUE TITLE
Can not use 'name' in  part2 of tutorial.

### ISSUE THREAD

**Issue by samwalrus** [linkml/linkml#1050]
**Describe the bug**
In the exercise when I try and add 'name' to my container class the file will not validate. But it will validate if I use 'datasetname' instead.

**To Reproduce**
1. Make a personinfo.yaml file:
```
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string
  
classes:
  Person:
    attributes:
      id:
      full_name:
      aliases:
        multivalued: true
        inlined_as_list: true
      phone:
      age:
  Container:
    tree_root: true
    attributes:
      name:
      description:
      persons:
        multivalued: true
        inlined_as_list: true
        range: Person
```
        
        
3. make a data.yaml file:
```
name: My dataset
description: people in the comic
persons:
  - id: ORCID:1234
    full_name: Clark Kent
    age: 32
    phone: 555-555-5555
    aliases:
    - man of steel
    - superman
  - id: ORCID:4567
    full_name: Lois Lane
    age: 33

```
4. run : `linkml-validate -s personinfo.yaml data.yaml`
5. See error:
`Traceback (most recent call last):
  File "/Users/sn0550/Documents/linkml-tutorial/venv/bin/linkml-validate", line 10, in <module>
    sys.exit(cli())
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml/validators/jsonschemavalidator.py", line 74, in cli
    python_module = PythonGenerator(schema).compile_module()
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml/generators/pythongen.py", line 44, in __init__
    super().__init__(schema, format, **kwargs)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml/utils/generator.py", line 95, in __init__
    source_file_date=self.source_file_date, source_file_size=self.source_file_size)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml/utils/schemaloader.py", line 54, in __init__
    source_file_size=source_file_size)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml/utils/rawloader.py", line 72, in load_raw_schema
    metadata=schema_metadata)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml_runtime/loaders/loader_root.py", line 85, in load
    results = self.load_any(*args, **kwargs)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml_runtime/loaders/yaml_loader.py", line 26, in load_any
    metadata=metadata)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml_runtime/loaders/loader_root.py", line 66, in load_source
    return target_class(**data_as_dict)
  File "<string>", line 57, in __init__
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml_runtime/linkml_model/meta.py", line 493, in __post_init__
    self._normalize_inlined_as_dict(slot_name="classes", slot_type=ClassDefinition, key_name="name", keyed=True)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml_runtime/utils/yamlutils.py", line 100, in _normalize_inlined_as_dict
    self._normalize_inlined(slot_name, slot_type, key_name, keyed, False)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml_runtime/utils/yamlutils.py", line 204, in _normalize_inlined
    form_1({k: v})
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml_runtime/utils/yamlutils.py", line 153, in form_1
    order_up(key, slot_type(**as_dict(raw_obj)))
  File "<string>", line 66, in __init__
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml_runtime/linkml_model/meta.py", line 1957, in __post_init__
    self._normalize_inlined_as_dict(slot_name="attributes", slot_type=SlotDefinition, key_name="name", keyed=True)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml_runtime/utils/yamlutils.py", line 100, in _normalize_inlined_as_dict
    self._normalize_inlined(slot_name, slot_type, key_name, keyed, False)
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml_runtime/utils/yamlutils.py", line 195, in _normalize_inlined
    order_up(raw_slot[key_name], slot_type(**as_dict(raw_slot)))
  File "<string>", line 104, in __init__
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml_runtime/linkml_model/meta.py", line 1629, in __post_init__
    self.MissingRequiredField("name")
  File "/Users/sn0550/Documents/linkml-tutorial/venv/lib/python3.7/site-packages/linkml_runtime/utils/yamlutils.py", line 250, in MissingRequiredField
    raise ValueError(f"{field_name} must be supplied")
ValueError: name must be supplied`

**Expected behavior**
The files to validate.
They do validate if I change from 'name' to 'datasetname'.

**Desktop (if applicable, please complete the following information):**
 - OS: Mac
 - Version : Python 3.7

**Additional context**
Do I need to use a different version of python? Tutorial did not mention it but I thought I saw somewhere it needed a later version.
