### ISSUE TITLE
gen-doc mixins lists should use a delimiter

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1089]
The following slot definition associates four mixins with `gold_biosample_ids`

```yaml
  gold_biosample_ids:
    is_a: linking_id
    description: An identifier for a GOLD Biosample record that is identical to this instance
    mixins:
      - biosample_id
      - external_id
      - gold_identifier
      - related_id
```

The following screenshot shows that they are listed inside of [square brackets] and delimited with whitespace. I am requesting some other printing delimiter like `|`. It _could_ be a gen-doc parameter. 

<img width="657" alt="Screen Shot 2022-11-01 at 4 09 15 PM" src="https://user-images.githubusercontent.com/25185273/199359456-4513a0d3-5197-4ae3-a5d6-95aae0ac3615.png">
