### ISSUE TITLE
gen-excel issues

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1090]
- [x] There are duplicate tabs for each class. The second instance of each tab has the suffix `1`
- [ ] I have never seen the excel generation complete for the large MIxS schema
- [x] When a class uses slot usage, the corresponding Excel column header uses the mangled notation like `SoilBiosample_temperature_c`

Switching to a SchemaView approach should at least address the mangled column headers.

```yaml
  SoilBiosample:
    is_a: Biosample
    slots:
      - temperature_c
    slot_usage:
      temperature_c:
        required: true
```
