### ISSUE TITLE
pydanticgen doesn't support inlined dicts

### ISSUE THREAD

**Issue by kevinschaper** [linkml/linkml#1094]
It doesn't seem to be possible to get an inlined dictionary with a class range. 

Using this example schema:
```
classes:
  person:
    slots:
      - id
      - bikes
    attributes:
      - bikes:
          range: bike
          multivalued: true
          inlined: true
          required: true
  bike:
    slots:
      - name
      - color
    slot_usage:
      name:
        identifier: true
        required: true
slots:
  - id:
      required: true
  - name
  - color
  - bikes
```

With gen-typescript I'm getting: 

```
export interface Person  {
     id?: string,
    bikes?: {[index: BikeName]: Bike },
}
```

but gen-pydantic is producing:
```
class Person(ConfiguredBaseModel):    
    id: str = Field(None)
    bikes: List[Bike] = Field(default_factory=list)
```

I think I should get 

```
class Person(ConfiguredBaseModel):    
    id: str = Field(None)
    bikes: Dict[str, Bike] = Field(default_factory=dict)
```
