### ISSUE TITLE
Does LinkML support RDF-star (as to say Turtle*)

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1098]
Forwarding question from user:

> Does LinkML support RDF-star (as to say Turtle*)
> E.g  How can I express it with linkML:  "Bob met Mary at London in 2008"

Answer:

Currently there is no explicit support for rdfstar. However, insofar as rdfstar is syntactic sugar for rdf, this can be expressed.

E.g.

For example, given data:

```yaml
events:
  - pred: met
    subject: Bob
    object: Mary
    location: London
    year: 2008
```

Then in the schema:

```yaml
  Event:
    class_uri: rdf:Statement
    attributes:
      pred: 
       slot_uri: rdf:predicate
     sub: 
       slot_uri: rdf:subject
     obj: 
       slot_uri: rdf:object
    ...
```

however, this is only the reified statement and not the reified triple. i.e in rdfstar

`<<Bob met Mary>> location London; year 2022`

If you wanted

`{|Bob met Mary|} location London; year 2022`

then you would need the extra piece of data to assert the quoted triple.

I think a reasonable enhancement for the rdf loader/dumper is the ability to auto-assert quoted triples

(@matentzn this is actually related to your wide-table vs narrow-table semsim modeling use case)

note that you can also provide hints as to reification in a schema, e.g.

```yaml
  Event:
    attributes:
      pred: 
       relational_role: PREDICATE
     sub: 
       relational_role: SUBJECT
     obj: 
       relational_role: OBJECT
    ...
```

the goal is to allow auto-asserting of quoted statements regardless of reification vocab
