### ISSUE TITLE
Support multivalued slot constraints in JSON Schema generator

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1107]
The LinkML model slots `all_members`, `has_member`, `minimum_cardinality`, and `maximum_cardinality` all have analogous concepts in JSON Schema, but currently `JsonSchemaGenerator` does not do anything with them. 

For example, this LinkML model:
```yaml
id: http://example.org/test
name: test

imports:
  - https://w3id.org/linkml/types

slots:
  s:
    range: integer
    multivalued: true
    has_member:
      minimum_value: 0
      maximum_value: 999

classes:
  C:
    tree_root: true
    slots:
      - s
```
should produce JSON Schema with a `contains` subschema:
```javascript
"properties": {
  "s": {
    "items": {
      "type": "integer"
    },
    // ↓↓↓ this is not included currently ↓↓↓
    "contains": {
      "minimum": 0,
      "maximum": 999
    },
    // ↑↑↑ ↑↑↑
    "type": "array"
  }
},
``` 

`minimum_cardinality` and `maximum_cardinality` should map directly to `minItems` and `maxItems` respectively (https://json-schema.org/understanding-json-schema/reference/array.html#length)
