### ISSUE TITLE
Newbie help - Constraining values help needed.

### ISSUE THREAD

**Issue by samwalrus** [linkml/linkml#1112]
I would like my data to have lists of dois, orcids, and ids of classes that I have defined in my schema.
How do I say that a slot should only have these values? I think I need to use the 'values_from' but I am not sure how this works?

```

id: http://myschema.blah/
name: mytest
description: >-
  test schema

prefixes:
   ORCID: http://identifiers.org/orcid/
   doi: https://doi.org/
   myschema: http://myschema.blah/
   
default_prefix: myschema

classes:
   project:
     description: A class to describe information around a project
     slots:
      - id
      - name
      - description
      - people_orcids
      - paper_dois
      - related_projects

slots:
  id:
    identifier: true
    slot_uri: schema:identifier
    range: uriorcurie
    description: A unique identifier for a thing
  name:
    slot_uri: schema:name
    description: A human-readable name for a thing
  description:
    slot_uri: schema:description
     description: A human-readable description for a thing
  people_orcids:
    #slot_uri: ORCID:id ? What should these be to say it is a list of orcids?
    #values_from: ORCIDs ??
    range: uriorcurie
    description: The orcid ids of the people involved
    multivalued: true
    inlined: false
  paper_dois:
    #slot_uri: doi:id ? What should these be to say it is a list of dois?
    #values_from: dois ??
    range: uriorcurie
    description: The dois of papers for this project
    multivalued: true
    inlined: false
 related_projects:
    #slot_uri: myschema:id ? What should these be to say it is a list of projects?
    #values_from: myschema ??
    range: uriorcurie
    description: The curies of projects related to this project
    multivalued: true
    inlined: false

```

### example data
```
id: 123
name: project awesome
description: making things awesome
people_orcids:
  - ORCID:0000-0000-0000-0001
  - ORCID:0000-0000-0000-0002
  - ORCID:0000-0000-0000-0003
paper_dois:
  - doi:00.0001/blah
  - doi:00.0002/blah
  - doi:00.0003/blah
related_projects:
  - myschema:124
  - myschema:125
  - myschema:126
```

**Comment by turbomam** [comment]
Would you like to zoom this morning? I can read your issue and be ready within 30 minutes.

**Comment by samwalrus** [comment]
That would be great :) I'm in the uk so it's the afternoon.

**Comment by turbomam** [comment]
Is the model and data above in a code repo you can share with me?

**Comment by turbomam** [comment]
Meet in 9 minutes?

https://lbnl.zoom.us/j/7331577864?pwd=OXkvK3BtNFlxS1B3NlF0ZmdyY1liUT09

Meeting ID: 733 157 7864
Passcode: HEKFw2

**Comment by samwalrus** [comment]
This is just me trying to make a minimal example.
The model I am trying to build is here: https://github.com/alspac/alspac-data-catalogue-schema 
Great I will log into that.

**Comment by samwalrus** [comment]
Thank you for the help today.

In summary for future ref the 'slot_uri' should refer to an external definition, this can be found by using something like the ontology look up service.

The 'values_from' would not work for looking up valid orcids but could look up some ontology terms.

The range can be set to a class even if it just the ids of that class in a list.

I should maybe use inlined_as_list instead of inlined false. So that a list is output in for example RDF.

**Comment by turbomam** [comment]
Yes. I don't know whether `values_from` actually implements any lookup yet. I think that's planned but it just expresses the intentions now. Hopefully someone else will clarify that.

I will make a PR of our work back into your repo now.

**Comment by turbomam** [comment]
see https://github.com/alspac/alspac-data-catalogue-schema/pull/1/files

**Comment by turbomam** [comment]
From https://github.com/linkml/linkml-model/blob/main/linkml_model/model/schema/meta.yaml

```yaml
values_from:
  domain: definition
  multivalued: true
  range: uriorcurie
  description: >-
    The identifier of a "value set" -- a set of identifiers that form the possible values for the range of a slot.
    Note: this is different than 'subproperty_of' in that 'subproperty_of' is intended to be a single ontology term
    while 'values_from' is the identifier of an entire value set.  Additionally, this is different than an enumeration
    in that in an enumeration, the values of the enumeration are listed directly in the model itself.
    Setting this property on a slot does not guarantee an expansion of the ontological hiearchy into an
    enumerated list of possible values in every serialization of the model.
```
