### ISSUE TITLE
provide a way to specify prefix expansions in a data file

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1114]
Currently prefixes can be specified in a schema, but the schema cannot anticipate all possible prefixes in instance data in the wild.

There are a few approaches just now we could better document:

1. Use `--prefix` in linkml-convert
2. Use jsonld files with a context embedded

These may suffice for some purposes but in other cases it is desirable to communicate the prefix expansions as part of the data (not that with the 2nd approach, the expansions are not part of the *semantic* data, they are syntactic)

The most straightforward thing to do here is to allow a custom data structure to be mapped to prefix expansions. The simplest way to do this is to annotate slot_uris with sh:prefix and sh:namespace. This requires no metamodel knowledge.

Currently, performing this annotation has no effect on the actual conversion to RDF. We should make this an option in rdflib_loader. The default should be False, since there may be cases where someone wants to quote namespaces and not use them.

This mechanism should also allow for specifying a strategy for base prefixes

**Comment by sierra-moxon** [comment]
still a great idea.  
probably a low priority unless we have a community of RDF enthusiasts willing to take this on. 

concrete action items:
- [ ] familiarize Claude with rdflib_loader and get it to make a plan, including documenting how we would make these changes, so that if another good use for annotations came up, we could quickly get Claude to implement that too.

**Comment by gouttegd** [comment]
> still a great idea.

I concur, but for the sake of simplicity, could we agree to put some constraints on the proposed mechanism?

I propose that it should be, if not forbidden, at least _extremely strongly discouraged_, to do something like this:

```
# A top-level prefix section
prefix_expansions:
  CHARACTER: http://dccomics.com/characters/

persons:
  - id: CHARACTER:1234
    full_name: Clark Kent

# Somewhere else in the document
organisations:
  - name: Rebel Alliance
    # A "local" prefix section
    prefix_expansions:
      CHARACTER: http://starwars.com/characters/
    members:
      - id: CHARACTER:1234 # <- same CURIE but different IRI
        full_name: Obi-Wan Kenobi
        comment: This is not the character you are looking for
```

That is, to have _several_ prefix expansion structures throughout the document, that declare prefixes that are only valid “below” them (and take precedence over any prefix expansion structure ”above” them).

I know that JSON-LD allows this kind of things, but that doesn’t mean it is a good idea in my opinion.
