### ISSUE TITLE
`all_members` metamodel slot cannot be used to constrain primitive values

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1122]
**Describe the bug**
The range of the metamodel slot `all_members` is `SlotDefinition`. Since a `SlotDefinition` requires a `name` it's slightly unclear how to model something like "a list of integers that are 10 or less":

```yaml
slots:
  the_list:
    range: integer
    multivalued: true
    all_members:
      the_list: # ?! since a name is required
        maximum_value: 10
```

**Expected behavior**
I think it would make more sense if the range of `all_members` was `AnonymousSlotExpression`. The `has_member` slot has that range and it allows modeling "a list of integers that has at least one value of 10 or less":

```yaml
slots:
  the_list:
    range: integer
    multivalued: true
    has_member:
      maximum_value: 10
```
