### ISSUE TITLE
JSON Schema generation fails when slot uses `any_of` to combine multiple value conditions

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1127]
**Describe the bug**
The `gen-json-schema` command fails when the input schema contains a slot with an `any_of` (or likely any other boolean operator) to combine multiple value conditions. The error is:

```
AttributeError: 'AnonymousSlotExpression' object has no attribute 'multivalued'
```

**To reproduce**
With the following schema:
```yaml
# test.yaml
id: https://example.com/test/
name: test
imports:
  - linkml:types
prefixes:
  linkml: https://w3id.org/linkml/

slots:
  s:
    range: string
    any_of:
      - equals_string: s1
      - equals_string: s2
      - equals_string: s3

classes:
  Test:
    slots:
      - s
```

Run:

```shell
gen-json-schema test.yaml
```
