### ISSUE TITLE
Does linkML support logical operations

### ISSUE THREAD

**Issue by joylix** [linkml/linkml#1135]
Does linkML support logical operations, like division in 
     equals_expression: "{age_in_months} / 12"
can it support AND, OR, NOT ?
How can I implement the following expressions in linkml:
      if person.height>150 OR person.age>12 then
             ticketRequired = True
      else
             ticketRequired = False

**Comment by turbomam** [comment]
Hi, @joylix. You may start getting some good answers in a few hours, once the California team members come on line.

I don't think I have used `equals_expression` in any of my LinkML schemas yet but am happy to experiment with you.

I see you have started this GitHub repo: https://github.com/joylix/LinkML

Do you know about our [cookie-cutter approach](https://github.com/linkml/linkml-project-cookiecutter) for setting up a standardized LinkML project?

**Comment by turbomam** [comment]
here's the definition for [equals_expression](https://github.com/linkml/linkml-model/blob/28346adc9d7f312abe1c89b9d770c1197987c119/linkml_model/model/schema/meta.yaml#L1390-L1402) 

```yaml
equals_expression:
  is_a: list_value_specification_constant
  range: string
  inherited: true
  description: the value of the slot must equal the value of the evaluated expression
  comments:
    - for example, a 'length' slot may have an equals_expression with value '(end-start)+1'
  todos:
    - specify expression language
  see_also:
    - https://github.com/linkml/linkml/issues/75
  in_subset:
    - SpecificationSubset
```  

I guess it's still a little underspecified

**Comment by turbomam** [comment]
Here's an [example of generating a logical result from an expression](https://github.com/linkml/linkml-runtime/blob/597d29d3e9c77eee4d60a05f0698fbefd699775b/tests/test_utils/input/inference-example.yaml#L46-L48):

```yaml
is_juvenile:
  range: boolean
  equals_expression: "{age_in_years} < 18"
```
