### ISSUE TITLE
add `equals_boolean` to the meta model 

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#1136]
**Is your feature request related to a problem? Please describe.**

I would like to be able to check if a boolean slot value is `true` when writing pre/post condition rules.  Right now I can do something like this using `equals_string`:
```
    rules:
      - preconditions:
          any_of:
            slot_conditions:
              age_in_years:
                minimum_value: 12
              height:
                minimum_value: 150
      - postconditions:
          slot_conditions:
            ticket_required:
              equals_string: "true"
```

**Describe the solution you'd like**
Add `equals_boolean` to the metamodel and support true/false checking. 

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work
