### ISSUE TITLE
allow mappings on enum values

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#114]
I would like be able to include mappings on enum values, e.g

```yaml
enums:
  strand_enum:
    description: strand
    permissible_values:
      "+":
        description: Positive
        close_mappings:
          - faldo:ForwardStrandPosition
      "-":
        description: Negative
        close_mappings:
          - faldo:ReverseStrandPosition
      ".":
        description: Unstranded
        close_mappings:
          - faldo:BothStrandsPosition
      "?":
        description: Unknown
```

**Comment by cmungall** [comment]
I think this would require moving the 4 slots here

```yaml
  element:
    description: a named element in the model
    abstract: true
    mixins:
      - extensible
      - annotatable
      - common_metadata
    slots:
      - name
      - id_prefixes
      - definition_uri
      - aliases
      - local_names
      - conforms_to
      - mappings
      - exact mappings
      - close mappings
      - related mappings
      - narrow mappings
      - broad mappings
      - order
```

to common_metadata

OR we just redundantly state
