### ISSUE TITLE
Single key objects not correctly inferred during linkml-validate

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#1146]
```
linkml                          1.3.14
linkml-dataops                  0.1.0
linkml-runtime                  1.3.2
```

Data:
```
repositories:
  - id: https://github.com/INCATools/ontology-development-kit
```

Class:

```
Resource:
    description: >-
      A generic grouping for any identifiable entity
    slots:
      - id
      - name
      - description
      - grants
      - documentation
      - monarch_contribution
    class_uri: schema:Thing
```

```
linkml-validate ...
ValueError: JsonObj(id='https://github.com/INCATools/ontology-development-kit') is not a valid URI or CURIE
```

if you add a second key, it works:

Data:
```
repositories:
  - id: https://github.com/INCATools/ontology-development-kit
    name: ODK
```

**Comment by pkalita-lbl** [comment]
I tried filling in the missing pieces of the provided schema as best I could. Just guessing here:

```yaml
# schema.yaml
id: test
name: test
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

slots:
  id:
  name:
  description:
  grants:
  documentation:
  monarch_contribution:

classes:
  Resource:
    description: >-
      A generic grouping for any identifiable entity
    slots:
      - id
      - name
      - description
      - grants
      - documentation
      - monarch_contribution
    class_uri: schema:Thing

  Container:
    attributes:
      repositories:
        range: Resource
        multivalued: true
        inlined_as_list: true
```

And with the following data file:

```yaml
# data.yaml
repositories:
  - id: https://github.com/INCATools/ontology-development-kit
```

The `linkml-validate` command now successfully validates it:

```bash
➜ linkml-validate -s schema.yaml data.yaml
No issues found
```

With that I'm going to close this issue. @matentzn please feel free to reopen if you're still seeing this issue with the latest version of LinkML and can provide reproduction steps.
