### ISSUE TITLE
`linkml-validate` doesn't validate json keys containing hyphens (`-`)

### ISSUE THREAD

**Issue by DaoKevin** [linkml/linkml#1157]
**Describe the bug**
Validator `linkml-validate` doesn't validate json keys containing a hyphen, such as `content-type` given a schema containing `content-type`. (Even replacing `content-type` by `content_type` in the `.yaml`, it doesn't see `content-type` in the `.json`)

**To reproduce**
Running linkml through a python script:
```python
import linkml
import os

os.system('linkml-validate --schema yamlschema.yaml myjson.json --target-class Website')
```

`yamlschema.yaml`:
```yaml
id: https://example.org/test123
name: test123
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  Website:
    attributes:
      link:
        required: true
        multivalued: true
        range: DownloadLink
        inlined_as_list: true

  DownloadLink:
    attributes:
      URL:
        required: true
      content-type:
        required: true
```

`myjson.json`:
```json
{
  "link": [
        {
        "URL": "https://example.org/a",
        "content-type": "application/pdf"
    },
        {
        "URL": "https://example.org/b",
        "content-type": "application/pdf"
    }
        ]
}
```

**Expected behavior**
Validation should pass, returning:
`None`

Actual:
`ValueError: content_type must be supplied`.

I would expect `content-type` as opposed to `content_type` too, in the error report.

**About your computer (if applicable, please complete the following information):**
Linkml version: `1.3.16`

I tried looking into the issues but couldn't find any similar issue or whether this is intended behaviour, sorry if this is known already/intended!
