### ISSUE TITLE
consider allowing for anchors in yaml output

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1158]
given a schema

```yaml
id: http://example.org/
name: test-graph
default_prefix: test
prefixes:
  linkml: https://w3id.org/linkml/
  test: http://example.org/
imports:
  - linkml:types

classes:
  Person:
    attributes:
      id:
        identifier: true
      knows:
        range: Person
        multivalued: true
        inlined: true
        inlined_as_list: true
```
and data:

```python
        p1 = Person('P:1')
        p2 = Person('P:2')
        p3 = Person('P:3')
        p4 = Person('P:4')
        p1.knows.append(p2)
        p1.knows.append(p3)
        p2.knows.append(p4)
        p3.knows.append(p4)
        p4.knows.append(p1)
```

currently neither json nor yaml will export, because of cycles. The obvious way to fix this is *not* to inline `knows`, since this is a bad idea for JSON. However, when considering YAML, we may want to make use of anchors (https://blog.daemonl.com/2016/02/yaml.html)

if the last line is removed, then it is exported, but with duplication

```yaml
id: P:1
knows:
- id: P:2
  knows:
  - id: P:4
- id: P:3
  knows:
  - id: P:4
```

doing a direct yaml export (bypassing the dumpers) creates

```yaml
&id001 !!python/object:tests.test_issues.models.graph_schema.Person
id: !!python/object/new:tests.test_issues.models.graph_schema.PersonId
  args:
  - P:1
  state:
    _len: null
    _s: null
knows:
- !!python/object:tests.test_issues.models.graph_schema.Person
  id: !!python/object/new:tests.test_issues.models.graph_schema.PersonId
    args:
    - P:2
    state:
      _len: null
      _s: null
  knows:
  - &id002 !!python/object:tests.test_issues.models.graph_schema.Person
    id: !!python/object/new:tests.test_issues.models.graph_schema.PersonId
      args:
      - P:4
      state:
        _len: null
        _s: null
    knows:
    - *id001
- !!python/object:tests.test_issues.models.graph_schema.Person
  id: !!python/object/new:tests.test_issues.models.graph_schema.PersonId
    args:
    - P:3
    state:
      _len: null
      _s: null
  knows:
  - *id002
```

the question is whether to allow something like this:

```yaml
id: P:1
knows:
- id: P:2
  knows:
  - id: &id001 P:4
- id: P:3
  knows: *id001
```

see also:

https://json-ld.github.io/yaml-ld/spec/#anchors-aliases
