### ISSUE TITLE
mixing attributes and slots in a single class can cause some forward references not to be quoted in pythongen

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1166]
@turbomam noticed this on the nmdc schema repo

```yaml
  Database:
    tree_root: true
    aliases:
      - NMDC metadata object
    description: An abstract holder for any set of metadata and data. It does not
      need to correspond to an actual managed database top level holder class. When
      translated to JSON-Schema this is the 'root' object. It should contain pointers
      to other objects of interest
    slots:
      - activity_set
      - biosample_set
      - data_object_set
      - dissolving_activity_set
      - functional_annotation_set
      - genome_feature_set
      - mags_activity_set
      - material_sample_set
      - material_sampling_activity_set
      - metabolomics_analysis_activity_set
      - metagenome_annotation_activity_set
      - metagenome_assembly_set
      - metaproteomics_analysis_activity_set
      - metatranscriptome_activity_set
      - nom_analysis_activity_set
      - omics_processing_set
      - reaction_activity_set
      - read_qc_analysis_activity_set
      - read_based_taxonomy_analysis_activity_set
      - study_set
    attributes:
      frs_set:
        inlined_as_list: true
        multivalued: true
        range: FieldResearchSite
        domain: Database
      cbfs_set:
        inlined_as_list: true
        multivalued: true
        range: CollectingBiosamplesFromSite
        domain: Database
```

note we are mixing attributes and slots. This is non-idiomatic, but permitted (the linter should probably flag this)

when we run `gen-python`:

```python
@dataclass
class Database(YAMLRoot):
    """
...
    read_based_taxonomy_analysis_activity_set: Optional[Union[Dict[Union[str, ReadBasedTaxonomyAnalysisActivityId], Union[dict, "ReadBasedTaxonomyAnalysisActivity"]], List[Union[dict, "ReadBasedTaxonomyAnalysisActivity"]]]] = empty_dict()
    study_set: Optional[Union[Dict[Union[str, StudyId], Union[dict, "Study"]], List[Union[dict, "Study"]]]] = empty_dict()
    frs_set: Optional[Union[Dict[Union[str, FieldResearchSiteId], Union[dict, FieldResearchSite]], List[Union[dict, FieldResearchSite]]]] = empty_dict()
    cbfs_set: Optional[Union[Dict[Union[str, CollectingBiosamplesFromSiteId], Union[dict, CollectingBiosamplesFromSite]], List[Union[dict, CollectingBiosamplesFromSite]]]] = empty_dict()
...

...
@dataclass
class FieldResearchSite(Site):
```

note that FieldResearchSite is not quoted

It seems this *only* occurs if attributes and slots are mixed
