### ISSUE TITLE
Ensure that json schema validation works in schemas that have slot names that start with a number

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1181]
From @turbomam and @sujaypatil96 - in mixs we are using artificial field names like `x_16s` due to a limitation in `check-json-schema` (not part of core linkml tool stack)

We should allow people to use `16s` if they want to. They will have to live with mappings to some frameworks e.g. python/java field names. But json should work:

https://stackoverflow.com/questions/69847959/can-json-field-names-start-with-a-number

**Comment by cmungall** [comment]
I am unable to reproduce:

```yaml
id: http://example.org/test-schema
name: test-schema
default_prefix: http://example.org/test-schema/
see_also:
  - https://github.com/linkml/linkml/issues/1181

prefixes:
  linkml: https://w3id.org/linkml/
  
imports:
  - linkml:types

default_range: string

classes:
  C:
    tree_root: true
    slots:
      - 1x
slots:
  1x:
    comments:
      - deliberately use a field that starts with a number
```

If we run:

`poetry run gen-json-schema --closed tests/test_issues/input/linkml_issue_1181.yaml`

we get:

```json
{
  "$defs": {
    "C": {
      "additionalProperties": false,
      "description": "",
      "properties": {
        "1x": {
          "type": "string"
        }
      },
      "title": "C",
      "type": "object"
    }
  },
  "$id": "http://example.org/test-schema",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "metamodel_version": "1.7.0",
  "properties": {
    "1x": {
      "type": "string"
    }
  },
  "title": "test-schema",
  "type": "object",
  "version": null
}
```

With sample passing data:

```json
{"1x": "test"}
```

The standard CLI that comes with the core `jsonschema` library works as expected:

```bash
jsonschema -i tests/test_issues/input/linkml_issue_1181_data.json  tests/test_issues/input/linkml_issue_1181.schema.json && echo success
success
```

if we deliberately introduce:

```json
{"1x": 5}
```

we get the expected error:

```bash
jsonschema -i tests/test_issues/input/linkml_issue_1181_data.json  tests/test_issues/input/linkml_issue_1181.schema.json && echo success
5: 5 is not of type 'string'
```

so there are no issues with core libraries

Note there *is* an issue with running `linkml-validate` via this, as `linkml-validate` will run pythongen, but we already have an issue where we want to bypass python objects in validation since we want to avoid unexpected repairs.
