### ISSUE TITLE
json generation from enum instances not working

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#119]
To test this, uncomment the line below lines from test_issue_368.py From biolink/biolinkml#369:

```python
      # TODO: fix this
      # env.generate_directory('issue_368', lambda dirname: output_generator(dirname))
```

**Comment by cmungall** [comment]
here is a minimal test:

```yaml
id: https://example.org/enum_test
name: enum_test

classes:
  Organism:
    slots:
      - state
slots:
  state:
    range: StateEnum
enums:
  StateEnum:
    permissible_values:
      LIVING:
      DEAD:
```

```python
i = Organism(state='LIVING')
print(json_dumper.dumps(i))
```

makes

```json
{
  "state": {
    "text": "LIVING"
  },
  "@type": "Organism"
}
```
