### ISSUE TITLE
Help needed creating LinkML schema from vertex and edge json data.

### ISSUE THREAD

**Issue by BlakeList** [linkml/linkml#1197]
Hi there,

Firstly, thank you very much for LinkML and other amazing tools.

I am building a knowledge graph of multi-omic plant data which integrates literature, genomic, transcriptomic, metabolomic, etc. data into a common structure by defining nodes/vertices and relationships/edges based on curated database and ontology entity and relationship classes (GO, TO, PO, Kegg, etc.). 

The way I am currently structuring the data involves two types of json collections (vertex and edge), depending on whether I am modelling an entity or relationship between entities. The vertex collections are made up of documents, each containing a unique identifier, some number of ontology and/or database ids which can be mapped onto an ontology or database via LinkML enums, and some number of attributes/slots containing key-value pairs. The values can be anything from string (usually the default range) to lists of dictionaries of arbitrary depth. Similarly, the edge collections contain an id (primary identifier), "from" (the vertex id of the inbound node in the relationship), "to" (the vertex id of the outbound node in the relationship), an ontology or relationship id that can be mapped onto an ontology via LinkML enums, and some number of attributes containing the same format of key-value pairs as the vertex collection (e.g. lists of dictionaries containing relationship evidence). The data that is ingested into the graph database is either a tsv or json for each vertex and edge collection. I would like to understand best way to model this data using a LinkML schema with the idea of linking other datasets together via the same ids and ontology classes.

I have read through the LinkML docs and created a prototype schema for the above use case, but just feel that I am not doing something correctly in how the relationships are represented. In the FAQ, [How do I represent relationships in LinkML?](https://linkml.io/linkml/faq/modeling.html#how-do-i-represent-relationships-in-linkml) asks (and I have tried to answer):  

q. can my objects be related in different ways, or is there a uniform relationship type?
a. Objects will always have some unique identifier and often an identifier linking it to a database or ontology. They will contain different key-value attributes, but can often be grouped into hierarchies, e.g. gene -> gene_or_gene_product.

q. do I need to store information/metadata about the relationship itself?
a. Yes relationships need to contain any number of key-value pairs where values can be lists of dictionaries. 

q. are the related objects somehow “external”, or are they within my dataset – and if so, should this be enforced
a. Most of the entities and relationships can have ontology or external database mappings. And many of the instances of the entities can be subclasses of the ontology class.
 
It also speaks about more advanced methods for handling relationships to treat them as first class entities.

Can you please help me to understand how I can best use LinkML to represent the case I have described above? Please let me know if you need more detail.

Cheers!

**Comment by sierra-moxon** [comment]
Hi @BlakeList :) - thank you for the detailed ticket!

In my understanding of your use case, I tried to summarize the questions that need answering (please let me know if I misunderstood):

1. how do we incorporate ontology identifiers into the definition of our LinkML classes?  
2. how do we model relationships between classes (or vertexes) when the relationship itself can have metadata associated with it?

Maybe we can build up a schema, starting very simply, and answer some of these questions.  Let's say we have a schema that just relates genes to alleles, two classes, 'Gene' and 'Allele', one attribute/slot each, an id.  

```
default_prefix: my_schema

classes:
  Allele:
    slots:
      - id
  Gene:
    slots:
      - id

slots:
  id: 
    identifier: true

```
I know that many other models have defined genes, and in fact, the Sequence Ontology has a definition (in this example) that I find very close to what I want to define for my schema.  I can point to the SO via a 'exact_mappings' LinkML construct like this:

```
  Gene:
    exact_mappings:
      - SO:0000704
    slots:
      - id
```

From your description above, it sounds like you've already figured out how to constrain the values of an instance of a slot/attribute by ontologies ([via a dynamic enumeration](https://linkml.io/linkml/faq/modeling.html#how-do-i-constrain-a-slot-to-a-branch-of-an-ontology-or-a-whole-ontology)), but if you have questions on this, we can certainly answer them as well. :) 

To expand our model to document the possible relationships between an allele and a gene, that also speak to your use case of having metadata on the edge/relationship, here's one possible approach:

```
default_prefix: my_schema

classes:

  Allele:
    slots:
      - id
      
  Gene:
    exact_mappings:
      - SO:0000704
    slots:
      - id
      
  AlleleGeneRelation:
     slots:
        - subject
        - object
        - predicate
      
slots:
  id:
    identifier: true
  predicate: 
     range: predicate_enum
  subject:
     range: Allele
  object:
     range: Gene

enums:
  predicate_enum:
    permissible_values:
      allele_of: 
```

In this example, we expand our model by adding another class, the `AlleleGeneRelation` class.   Just like our other classes, this class can have an arbitrary number of slots/attributes.  This class is special because it actually defines the relationship that we're modeling between a `Allele` and a `Gene`.  Each instance of an `AlleleGeneRelation`, is going to have a `subject` slot with an identifier for an `Allele` object, and an `object` slot that is going to refer to an identifier for a `Gene` object. (we can see this requirement in the `subject` and `object` slot ranges where we define each to have a range of one of the classes above).   

The `predicate` slot above is a slot/attribute that holds the actual relationship between the `Gene` and the `Allele`.  In this example, the relationship name would be `allele_of`.

A full reading of this class would be something like:
`Allele allele_of Gene`

The point of making this a class is that we can add additional metadata to this relationship.  For example, if I wanted to add a slot to hold all the publications that documented the relationship between a specific Allele and a specific Gene I could do so, e.g.:
```
  AlleleGeneRelation:
     slots:
        - subject
        - object
        - predicate
        - publications
      
slots:
   publications: 
     multivalued: true
     range: uriorcurie
```

Tangentially, if I also wanted to store the publications that simply mention the Allele or Gene objects/instances themselves, I could include the `publications` slot on the classes directly. 

```
  Gene:
    exact_mappings:
      - SO:0000704
    slots:
      - id
      - publications
 ```

You may wish to take a look at the Biolink Model for more examples of these kinds of "relationship" classes.  In [Biolink Model](https://biolink.github.io/biolink-model/guidelines/understanding-the-model.html), we call these "[Association](https://biolink.github.io/biolink-model/docs/associations.html)" classes.   

Finally, we might want to build a bit of hierarchy into the example model to save us repeating slots on both our Allele and Gene classes:

```
default_prefix: my_schema

classes:

  Entity:
    slots: 
        - id
        - publications
  
  Allele:
    is_a: Entity
      
  Gene:
    is_a: Entity
    exact_mappings:
      - SO:0000704

  AlleleGeneRelation:
     slots:
        - subject
        - object
        - predicate
        - publications
      
slots:
  id:
    identifier: true
  predicate: 
     range: predicate_enum
  subject:
     range: Allele
  object:
     range: Gene
  publications: 
     multivalued: true
     range: uriorcurie

enums:
  predicate_enum:
    permissible_values:
      allele_of: 
```
