### ISSUE TITLE
Make it easier to work with enumerations in LinkML Runtime

### ISSUE THREAD

**Issue by jbussemaker** [linkml/linkml#1203]
**Is your feature request related to a problem? Please describe.**
Working with enumerations (subclasses of `EnumDefinitionImpl`) can be frustrating, especially when already used to how the native Python Enum classes work. For example, value comparison and hashing (for lookups) is either not supported or awkward to use.

**Describe the solution you'd like**
I would like to have support for:
1. Equality comparison between `EnumDefinitionImpl` (with a `code`), `PermissibleValues` and strings
2. Support for hashing of `PermissibleValues`
3. Support stringification
4. Checking whether some enumeration value is a valid value using `in`

For example, consider the following enumeration (automatically generated):
```python
class EnumValues(EnumDefinitionImpl):
    A = PermissibleValues(text="A")
    B = PermissibleValues(text="B")
```

Then the following tests should pass:
```python
# 1. Equality comparison
assert EnumValues.A == EnumValues("A")
assert EnumValues("A") == EnumValues.A
assert EnumValues.A == "A"
assert "A" == EnumValues.A
assert EnumValues("A") == "A"
assert "A" == EnumValues("A")

# 2. Hashing support
assert "A" in {EnumValues.A, EnumValues.B}
assert EnumValues.A in {EnumValues.A, EnumValues.B}
assert EnumValues("A") in {EnumValues.A, EnumValues.B}
assert "A" in {EnumValues("A"), EnumValues("B")}
assert EnumValues.A in {EnumValues("A"), EnumValues("B")}
assert EnumValues("A") in {EnumValues("A"), EnumValues("B")}

# 3. Stringification
assert str(EnumValues.A) == "A"
assert str(EnumValues("A")) == "A"

# 4. Checking valid values
assert EnumValues.A in EnumValues
assert EnumValues("A") in EnumValues
assert "A" in EnumValues
```

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**
Suggested modifications for `EnumDefinitionImpl` (apply `__contains__` also to `EnumDefinitionMeta`):
```python
def __eq__(self, other):
    if isinstance(other, EnumDefinitionImpl):
        return other.code == self.code
    if isinstance(other, PermissibleValues):
        return other == self.code
    return vars(self) == vars(other)

def __hash__(self):
    if not self.code:
        raise NotImplementedError
    return hash(self.code)

def __contains__(self, key):
    if isinstance(key, EnumDefinitionImpl):
        if key.code:
            key = key.code
    if isinstance(key, PermissibleValues):
        key = key.text
    return key in self.__dict__
```

Modifications for `PermissibleValues`:
```python
def __eq__(self, other):
    if isinstance(other, EnumDefinitionImpl):
        return other.code == self
    if isinstance(other, PermissibleValues):
        return other.text == self.text
    return vars(self) == vars(other)

def __hash__(self):
    return hash(self.text)

def __str__(self):
    return str(self.text)
```

**Comment by cmungall** [comment]
Thanks for the detailed analysis, we will be discussing this on the next developers call.

Related issue:

- #723

**Comment by jbussemaker** [comment]
Small bug fix in the equality comparisons:

For `EnumDefinitionImpl`:
```python
def __eq__(self, other):
    if isinstance(other, EnumDefinitionImpl):
        return other.code == self.code
    if isinstance(other, (PermissibleValues, str)):
        return other == self.code
    return vars(self) == vars(other)
```

For `PermissibleValues`:
```python
def __eq__(self, other):
    if isinstance(other, EnumDefinitionImpl):
        return other.code == self
    if isinstance(other, PermissibleValues):
        return other.text == self.text
    if isinstance(other, str):
        return other == self.text
    return vars(self) == vars(other)
```

And to confirm, you can also add these additional tests:
```python
assert EnumValues.A != "B"
assert "B" != EnumValues.A
assert EnumValues("A") != "B"
assert "B" != EnumValues("A")
```

**Comment by hsolbrig** [comment]
Is there a PR associated with this issue?

**Comment by hsolbrig** [comment]
Another use case -- I _think_ this is the same issue:
```yaml
id: https://linkml.org/testing
title: LinkML integration testing harness manifest model
name: integration

license: https://creativecommons.org/publicdomain/zero/1.0/
version: 0.1.0

prefixes:
  linkml: https://w3id.org/linkml/
  test: https://linkml.org/testing/

imports:
  - linkml:types

default_range: string

classes:
  MyModel:
    description: Enum test model
    attributes:
      name:
        range: string
        identifier: True
      category:
        range: ModuleCallers
        required: True

enums:
  ModuleCallers:
    description: Wrapper code for various modules
    permissible_values:
      Loader:
      Dumper:
      Generator:
```
```bash
gen-python model.yaml --no-slots > model.py  
```
```python
from model import MyModel, ModuleCallers

ins_tance = MyModel(name="Fred", category=ModuleCallers.Generator)

match ins_tance.category:
    case ModuleCallers.Generator:
        print("Got us a generator")
    case _:
        print("Not a generator")

# Workaround (ick)
match str(ins_tance.category):
    case ModuleCallers.Generator.text:
        print("Got us a workaround generator")
    case _:
        print("Not a workaround fgenerator")
```
```bash
python impl.py 
Not a generator
Got us a workaround generator
```
