### ISSUE TITLE
Add more documentation on single-value dictionary shortcuts

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1205]
In our current documentation on inlining as dictionaries:

https://linkml.io/linkml/schemas/inlining.html#inlining-as-a-dictionary

We describe how it's optional to include the key in the object, since it is already present as a key (see the section _Note that in the above the id field is not included in the actual organism object, as it is acting as a key for that object, it doesn’t need to be included. However, it is still legal to include it, like this_).

This shortcut is useful, and helps avoid redundancy.

However, there is an additional potential shortcut that is even more powerful, and the documentation for this is currently too buried.

Given a class that has a pair of attributes/slots, one of which is designated `key`, e.g.

```yaml
  Container:
      attributes:
         my_elements:
            range: MyDictElement
            multivalued: true
            inlined: true
  MyDictElement:
    attributes:
       my_key:
           key: true
       my_value:
            range: string
```

Given an example dataset with two elements, the *expanded* representation might be:

```yaml
my_elements:
   k1:
      my_key: k1
      my_value: v1
  k2:
      my_key: k2
      my_value: v2
```

by omitting the redundant key, as described in the documentation above, we can instead write the equivalent:

```yaml
my_elements:
   k1:
      my_value: v1
  k2:
      my_value: v2
```

We can call this the *partially contracted* serialization

LinkML allows for an even more compact serialization - this only applies in cases such as the schema above where the inlined element has two attributes, one of which is a key:

```yaml
my_elements:
   k1: v1
  k2: v2
```

This is usually preferable for authoring.

In fact most LinkML users are familiar with such contracted forms, as the metamodel uses this for things like prefixes. 

in fact if you run this through the standard loaders and dumpers:

```yaml
prefixes:
  linkml: https://w3id.org/linkml/
  skos: http://www.w3.org/2004/02/skos/core#
```

You end up with the expanded form.

Another place where these are used is `annotations`.

We need to better document the single-value dictionary shortcuts. As a separate issue, we also want to make add options to the dumpers that will contract things back in this way, but that can be handled separately.
