### ISSUE TITLE
slot table in docgen does not inherit range from slot_usage 

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1208]
When running the unit test for DocGeneratorTestCase, in FamilialRelationship.md we get:

| Name | Cardinality and Range | Description | Inheritance |
| ---  | --- | --- | --- |
| [started_at_time](started_at_time.md) | 0..1 <br/> [xsd:date](http://www.w3.org/2001/XMLSchema#date) |  | [Relationship](Relationship.md) |
| [type](type.md) | 0..1 <br/> NONE |  | [Relationship](Relationship.md) |
| [related_to](related_to.md) | 0..1 <br/> NONE |  | [Relationship](Relationship.md) |
| [ended_at_time](ended_at_time.md) | 0..1 <br/> [xsd:date](http://www.w3.org/2001/XMLSchema#date) |  | [Relationship](Relationship.md) |

The cardinality and range should not be NONE

this is what the schema has:

```yaml
  FamilialRelationship:
    rank: 5
    is_a: Relationship
    slot_usage:
      type:
        range: FamilialRelationshipType
        required: true
      related to:
        range: Person
        required: true
```

This is something in docgen, schemaview and other frameworks correctly have the inference; e.g. gen-linkml:

```yaml
     related to:
        name: related to
        from_schema: https://w3id.org/linkml/tests/kitchen_sink
        alias: related_to
        owner: FamilialRelationship
        domain_of:
        - Relationship
        range: Person
        required: true
      type:
        name: type
        from_schema: https://w3id.org/linkml/tests/kitchen_sink
        alias: type
        owner: FamilialRelationship
        domain_of:
        - Relationship
        - EmploymentEvent
        range: FamilialRelationshipType
        required: true
```
