### ISSUE TITLE
By default, gen-doc shouldn't render notes or todos

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1217]
- `todos` are meant to capture incomplete or problematic work 
- `notes` are not intended for consumption by end users

**Comment by cmungall** [comment]
```yaml
  todos:
    domain: element
    range: string
    description: Outstanding issue that needs resolution
    multivalued: true
    in_subset:
      - BasicSubset

  notes:
    domain: element
    multivalued: true
    description: editorial notes about an element intended for internal consumption
    slot_uri: skos:editorialNote
    in_subset:
      - BasicSubset
```

todos should be transparent. They should be used to alert any consumer of the schema of things that are missing and might be planned. they shouldn't be used for person or internal notes

the description for notes does indeed say intended for internal consumption, though this may not be entirely consistent with

http://www.w3.org/2004/02/skos/core#editorialNote

My recommendation for best practice is:

- regardless of whether a note is primarily internal or external, provide sufficient context. Don't write notes addressed entirely to yourself in the schema
- assume anything in the schema will leak somewhere, and author notes accordingly
- keep anything that you don't want leaking out somewhere else like a github issue (which while public is sufficiently contextualized)
- github issues can be linked via see_also
-  `#` comments over `notes` for things that are truly internal (the counterargument is that these are lost in roundtrips, but rueaml preserves, and in actual practice, roundtripping an authored schema is rarely done and will likely mess up all kinds of meaningful formatting as well as multiline strings)
