### ISSUE TITLE
ifabsent doesn't create a default value in pydantic version

### ISSUE THREAD

**Issue by djarecka** [linkml/linkml#1234]
**Describe the bug**

If I understand correctly you are using `ifabsent` as a default value for a slot, but when I'm trying to generate the pydantic version, I'm always getting `Field(None)` instead of `Field(default)`.

**To reproduce**
My `test.yaml` file:
```
id: id
name: test_info
description: just testing

prefixes:
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/

imports:
  - https://w3id.org/linkml/types

classes:
  Test:
    description: just a test
    attributes:
      attr1:
        range: integer
        ifabsent: 10
```

after running `gen-pydantic test.yaml` I get:

```
...
class Test(ConfiguredBaseModel):
    """
    just a test
    """
    attr1: Optional[int] = Field(None)
...
```

**Expected behavior**

```
...
class Test(ConfiguredBaseModel):
    """
    just a test
    """
    attr1: Optional[int] = Field(10)
...
```

**About your computer (if applicable, please complete the following information):**
 OSX
```
(linkml) MacBook-Pro-2:linkml_tests dorota$ python -V
Python 3.8.15
(linkml) MacBook-Pro-2:linkml_tests dorota$ linkml-convert -V
linkml-convert, version 0.0.0
```

cc: @sooyounga
