### ISSUE TITLE
converting inlined data to ttl

### ISSUE THREAD

**Issue by kervel** [linkml/linkml#1244]
**Describe the bug**

Hello, (i think related to #576)
When i try to convert data that was inlined_as_list to rdf i get an error.

**To reproduce**

i have the following schema:

```yaml
name: test-schema
id: http://example.org/test-schema
default_prefix: test
description: needs
prefixes:
  linkml: https://w3id.org/linkml/
  test: http://example.org/test-schema/

imports:
  - linkml:types
  
classes:
  NamedThing:
    slots:
      - id
      - full_name  

  Container:
    tree_root: true
    slots:
      - things
      
slots:
  id:
    identifier: true
    range: string
    required: true
  full_name:
    range: string
  things:
    range: NamedThing
    multivalued: true
    inlined: true
    inlined_as_list: true
```

with the following data:

```json
{
  "things": [
    {
      "id": 1,
      "full_name": "phoebe"
    },
    {
      "id": 2,
      "full_name": "University of Earth"
    }
  ]
}
```

when i do
```shell
linkml-convert  -t rdf  -s src/asset360_test/schema/schema_no_poly.yaml data-no-poly.json
```

i get `ValueError: : Unknown CURIE prefix: @base`

**Expected behavior**

I would expect to see generated IDs rather than an exception ..
