### ISSUE TITLE
gen_owl: slots are treated differently than attributes

### ISSUE THREAD

**Issue by kervel** [linkml/linkml#1245]
**Describe the bug**

When importing one schema from another and then generating OWL, it seems slots are correctly prefixed with the default prefix of the imported schema while attributes aren't.

**To reproduce**

two schema's:

a.yaml:

```yaml
name: a
id: http://example.org/a
default_prefix: a
description: a
prefixes:
  linkml: https://w3id.org/linkml/
  a: http://example.org/a/

imports:
  - linkml:types
  
classes:
  NamedThing:
    slots:
      - id
    attributes:
      full_name:
          range: string

      
slots:
  id:
    identifier: true
    range: string
    required: true
```

b.yaml

```yaml
name: b
id: http://example.org/b
default_prefix: b
description: b
prefixes:
  linkml: https://w3id.org/linkml/
  b: http://example.org/b/

imports:
  - linkml:types
  - ./a
```

output of `gen-owl src/asset360_test/schema/b.yaml` gives:

```rdf
<http://example.org/a/id> a owl:ObjectProperty,
        linkml:SlotDefinition ;
    rdfs:label "id" ;
    rdfs:range linkml:String .

b:full_name a owl:ObjectProperty,
        linkml:SlotDefinition ;
    rdfs:label "full_name" ;
    rdfs:range linkml:String .
```

**Expected behavior**
both the `id` and the `full_name` get prefixed with `http://example.org/a/`
