### ISSUE TITLE
`permissible_values` class and `is_a`/`mixins` slots mismatch in model

### ISSUE THREAD

**Issue by vincentvialard** [linkml/linkml#1261]
In the LinkML model, `permissible_value` is a base class but has slot usages for `is_a` as well as `mixins`:
```
  permissible_value:
    ...
    mixins:
      - extensible
      - annotatable
      - common_metadata
    slot_usage:
      is_a:
        range: permissible_value
      mixins:
        range: permissible_value
    ...
``` 

although both `is_a` and `mixins` are available only for `definition` instances:

```
  is_a:
    ...
    domain: definition
    range: definition
    ...
```

```
  mixins:
    ...
    domain: definition
    multivalued: true
    range: definition
    ...
```

Defining the usage of a slot the class does not have might be considered as non critical, but it sure is confusing.

Remark: I am not sure hierarchical permissible values were intended to be available or not, but they are used for instance by the BioLink model:
```
  DirectionQualifierEnum:
    permissible_values:
      increased:
      upregulated:
        is_a: increased
        ...
```
