### ISSUE TITLE
JSON Schema generator should implicitly apply value constraints to all members of multivalued slots

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1267]
**Describe the bug**
Using this schema as an example:

```yaml
id: http://example.com/test
name: test

imports:
  - https://w3id.org/linkml/types

slots:
  e_words_only:
    range: string
    multivalued: true
    pattern: "e.*"

classes:
  Container:
    slots:
      - e_words_only
```

I would expect that `gen-json-schema` would produce a JSON Schema that _fails_ validation for this data instance:

```json
{
  "e_words_only": [
    "echo",
    "foxtrot"
  ]
}
```

However that currently does not appear to be the case.

**To reproduce**
1. With the above schema as `test.yaml`: `gen-json-schema --top-class Container test.yaml > test.schema.json`
2. With the above data instance as `test.data.json`: `jsonschema -i test.data.json test.schema.json` (assuming you're in a virtual environment with https://pypi.org/project/jsonschema/)
3. Note that no validation error is produced

**Additional context**
The JSON Schema that's currently being produced for the above example contains the following:

```json
"properties": {
    "e_words_only": {
        "items": {
            "type": "string"
        },
        "pattern": "e.*",
        "type": "array"
    }
},
```

In order for the `pattern` to apply to all elements, it would need to be moved into the `items` specification.

**Comment by turbomam** [comment]
Will this solve the unexpectedly passing `test_databased_plate_invalid` from https://github.com/linkml/linkml/blob/issue-1259-min-rules/tests/test_issues/test_issue_1259.py?

`test_plate_invalid` fails as expected because it describes a `Biosample` in a plate but doesn't provide a `dna_cont_well`

`test_databased_plate_invalid` passes unexpectedly even though it describes the same `Biosample`, just wrapped inside a `biosample_set` list in a `Database` instance

**Comment by pkalita-lbl** [comment]
I think the answer is: no. This issue is about having a value constraint (e.g. `pattern`, `minimum_value`, etc) on a slot that also has `multivalued: true`. I don't see that sort of slot in your test's schema.

**Comment by turbomam** [comment]
Actually, I think this is a problem attributable to `multivalued: true`

```yaml
  Database:
    slots:
      - biosample_set
```
