### ISSUE TITLE
Documentation for "inheritable" metaslots is missing

### ISSUE THREAD

**Issue by vincentvialard** [linkml/linkml#1269]
In the linkml model, the `is_a` and `mixin` hierarchies are used to propagate _"inheritable"_ metaslots, but I was not able to find anywhere which metaslots are considered _"inheritable"_ .
```
  ...
  is_a:
    ...
    description: >-
      A primary parent class or slot from which inheritable metaslots are propagated from.
      ...
    ...
  ...
  mixins:
    ...
    description: >-
      A collection of secondary parent classes or slots from which inheritable metaslots are propagated from.
   ....
  ...
```

**Comment by cmungall** [comment]
Slots that are described with https://w3id.org/linkml/inherited

e.g.

```yaml
  range:
    aliases:
      - value domain
    domain: slot_definition
    range: element
    ifabsent: default_range
    inherited: true
```

in general the descriptions in the metamodel are too terse, and should be linked to more detail in the specification
