### ISSUE TITLE
Unions of ranges not supported in genenator-pydantic [the presence of 'default_range: string' with Union ranges raises the 'ValueError: Slot cannot have both range and any_of defined']

### ISSUE THREAD

**Issue by sadnanalmanir** [linkml/linkml#1272]
**Is your feature request related to a problem? Please describe.**
The current implementation of gen-pydantic does not seem to support [any_of](https://w3id.org/linkml/any_of) accurately. The generator fails to produce Union and only `str` type is generated. Although [Unions of ranges](https://linkml.io/linkml/schemas/advanced.html#unions-as-ranges) has been identified as an advanced feature, its use seems to be trivial.

**Describe the solution you'd like**
For example, consider the following use of `any_of`
```
classes:  
  A:
    class_uri: ...
  B:   
    class_uri: ...
  C:    
    class_uri: ...
    slots:
      - dummy_slot
    slot_usage:url
      dummy_slot: 
        multivalued: true
        any_of:
          - range: A
          - range: B
```
For `class C(...):`, instead of generating `dummy_slot: Optional[List[Union[A, B]]]`, the gen-pydantic generates `dummy_slot: Optional[List[str]]`.

**How important is this feature?** Select from the options below:
• Important - it's a blocker and can't do work without it.

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks
