### ISSUE TITLE
minting uri for enum

### ISSUE THREAD

**Issue by wdduncan** [linkml/linkml#129]
From LinkML meeting on 02/26/2021

Currently, the uri for an enum is (or seems to be) minted in the form `< ..prefix../<enum>`; e.g. `<https://w3id.org/synbio/3>`

For cases in which a dataset may contain the same enum in multiple fields, do we want the enum uri to have multiple meanings? For example:
```
enums:
  species_enum:
    permissible_values:
      #Aequorea.victoria:
      1:
        description: Aequorea victoria
        meaning: NCBITaxon:61303
      #Agrobacterium.tumefaciens:
      2:
        description: Agrobacterium tumefaciens
        meaning: NCBITaxon:365
      3:
        #Arabidopsis.thaliana:
        description: Arabidopsis thaliana
        meaning: NCBITaxon:3702
  category_enum:
    permissible_values:
      1:
        description: GOI
        meaning: synbio:GOI
      2:
        description: antibiotic resistance
        meaning: synbio:antibiotic-resistance
      3:
        description: biosynthetic
        meaning: synbio:biosynthetic
```
produces
```
<https://w3id.org/synbio/3> 
    skos:definition "Arabidopsis thaliana", "biosynthetic" ;
    meta:meaning <https://w3id.org/synbio/NCBITaxon:3702>, <synbio:biosynthetic> .
```
In one sense this is fine if we know that `skos:definition "Arabidopsis thaliana", "biosynthetic"` is valid when querying for data linked via the `category` slot. But do we want to have more control in certain cases? E.g.:
- allow us to specify a particular uri for an enum
- allow use specify a uri "scope" for a group of enums

cc @hsolbrig @cmungall @deepakunni3 @sierra-moxon
