### ISSUE TITLE
pythongen ifabsent generates incorrect values for class_curie and slot_curie

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1333]
the metamodel has a slot class_uri, with an `ifabsent` defined as follows:

```yaml
classes:
  ClassDefinition:
     slots:
       - ...
       - class_uri
       - ...
slots:       
  class_uri:
    range: uriorcurie
    description: URI of the class that provides a semantic interpretation of the element in a linked data context. The URI may come from any namespace and may be shared between schemas
    ifabsent: class_curie
```

The documentation for `ifabsent` says:

```
        * class_curie -- CURIE for the containing class
        * class_uri -- URI for the containing class
```

this means that if I would expect

```python
>>> cls = ClassDefinition("Foo")
>>> print(cls.class_curie)
myschema:Foo
```

however, with the `ifabsent_function` changes in

- #1171.   

meta.py now says:

```python
class ClassDefinition(...):
    ...
    class_curie: ... = class_class_curie
```

so the actual behavior we get is:

```python
>>> cls = ClassDefinition("Foo")
>>> print(cls.class_curie)
linkml:ClassDefinition
```

I think we revert to having the generated default being `None` for all x_uri slots.
