### ISSUE TITLE
pydanticgen generates invalid code for ifabsent=class_curie

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1334]
I think the root cause of this is the same as #1333, but it manifests differently.

given a schema:

```yaml
id: test
name: test

classes:
  ClassDefinition:
    attributes:
      class_uri:
        ifabsent: class_curie
```

pydantic gen makes:

```python
class ClassDefinition(ConfiguredBaseModel):

    class_uri: Optional[str] = Field(class_class_curie)
```

however, class_class_curie is not imported, so the code does not compile

even if it were imported, the behavior would be wrong, as per #1333.

I think the fix for 1333 will fix this but for full safety perhaps we should be especially carefully about reusing ifabsent_functions across dataclass and pydantic generation
