### ISSUE TITLE
How to represent vectors

### ISSUE THREAD

**Issue by glyg** [linkml/linkml#1357]
Hi,
Thank you for linkML, although I just started using it, it is really promising, and easy to use!

I use linkML to specify the data model for the export of datasets from the [Morphonet](https://morphonet.org) software, you can see the schema [here](https://gitlab.in2p3.fr/guillaume.gay/morphonet-schema/-/blob/main/src/morphonet_schema/schema/morphonet_schema.yaml)
 
I could not find in the documentation how to represent n-dimensional vectors and was not sure if they should be defined as types or classes.

For now I have e.g.

```yaml
classes:
  ...

  Translation:
    description: A translation defined by a 3D vector
    attributes:
      deltaX:
        range: float
      deltaY:
        range: float
      deltaZ:
        range: float
```

For some other entry, I'll also need to specify units. Is this the correct way to do it, or can I define a "3D vector" type that would be more 'natural' and translate directly to a tuple in python?

Any hint or feedback welcome!
