### ISSUE TITLE
LinkML Patterns should generate JSON Schema Patterns

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#1371]
**Describe the bug**

Specifying a [LinkML Pattern](https://linkml.io/linkml-model/docs/pattern/) in a **TypeDefinition**, for example, results in a pattern in a JSON-LD `pattern` attribute. But it doesn't generate a [JSON Schema `pattern`](https://json-schema.org/understanding-json-schema/reference/string.html#regular-expressions).

**To reproduce**
1. Create a schema with a pattern in any of the [Applicable Classes](https://linkml.io/linkml-model/docs/pattern/#applicable-classes)
2. Generate JSON-LD
3. Confirm the `pattern` attribute appears
4. Generate JSON Schema
5. Confirm the `pattern` does NOT appear

**Expected behavior**
The resulting JSON Schema has the specified pattern.

**Additional context**
JSON-LD patterns cannot be validated with COTS software. Whereas [JSON Schema `pattern` entries](https://json-schema.org/understanding-json-schema/reference/string.html#regular-expressions) can be validated with any JSON Schema validator.

**Comment by pkalita-lbl** [comment]
Hi @Silvanoc! Thanks for taking the time to write this up.

The `pattern` of a slot in a LinkML schema should be included in the generated JSON Schema. Here's a small example schema:

```yaml
# test.schema.yaml
id: http://example.org/pattern
name: pattern

imports:
  - https://w3id.org/linkml/types

slots:
  us_phone_number:
    range: string
    pattern: \d{3} \d{3} \d{4}

classes:
  Test:
    tree_root: true
    slots:
      - us_phone_number
```

When I generate a JSON Schema from that LinkML:

```shell
gen-json-schema test.schema.yaml
```

I get the following, which includes the `pattern`:

```json
{
    "$defs": {
        "Test": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "us_phone_number": {
                    "pattern": "\\d{3} \\d{3} \\d{4}",
                    "type": "string"
                }
            },
            "title": "Test",
            "type": "object"
        }
    },
    "$id": "http://example.org/pattern",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "properties": {
        "us_phone_number": {
            "pattern": "\\d{3} \\d{3} \\d{4}",
            "type": "string"
        }
    },
    "title": "pattern",
    "type": "object",
    "version": null
}
```

Can you provide an example LinkML schema where you're _not_ seeing the pattern included in the JSON Schema output?

**Comment by Silvanoc** [comment]
That's weird... I'm pretty sure I confirmed the issue before reporting it. But you're right, with the current version it works as I expect it to work.

Either the issue existed with the version I used at the time I reported it and meanwhile it's been fixed. Or I had somehow a broken installation.

Anyway, thank you for having a look at it!

**Comment by Silvanoc** [comment]
@pkalita-lbl now I've been able to reproduce the issue. I missed to notice an important detail and therefore I never mentioned it in the report: it fails if the pattern is declared in a TypeDeclaration.

If I declare following schema:
```
# test.schema.yaml
id: http://example.org/pattern
name: pattern

imports:
  - https://w3id.org/linkml/types

slots:
  us_phone_number:
    range: string
    pattern: \d{3} \d{3} \d{4}
  de_phone_number:
    range: DePhoneNumber

classes:
  Test:
    tree_root: true
    slots:
      - us_phone_number
      - de_phone_number

types:
  DePhoneNumber:
    uri: xsd:String
    base: str
    pattern: 0\d{3}-\d{8}
```

And let LinkML generate the corresponding JSON-Schema:
```
gen-json-schema test.schema.yaml
```

I get following JSON-Schema (notice the missing pattern in the `de_phone_number` slot):
```
{
    "$defs": {
        "Test": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "de_phone_number": {
                    "type": "string"
                },
                "us_phone_number": {
                    "pattern": "\\d{3} \\d{3} \\d{4}",
                    "type": "string"
                }
            },
            "title": "Test",
            "type": "object"
        }
    },
    "$id": "http://example.org/pattern",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "properties": {
        "de_phone_number": {
            "type": "string"
        },
        "us_phone_number": {
            "pattern": "\\d{3} \\d{3} \\d{4}",
            "type": "string"
        }
    },
    "title": "pattern",
    "type": "object",
    "version": null
}
```

I'm not happy to report that the issue exists, but releaved that I wasn't reporting a non-existing issue. I'm updating the description accordingly.
