### ISSUE TITLE
unrecognized range (xsd:date)

### ISSUE THREAD

**Issue by leonqli** [linkml/linkml#1386]
```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  xsd: http://www.w3.org/2001/XMLSchema#

imports:
  - linkml:types
default_range: string
  
classes:
  Person:
    slots:
      - birthdate
slots:
  birthdate:
    range: xsd:date
```
It raised the following error when running ($ gen-project -d . a.yaml)
```bash
...
...
raise ValueError(f'{TypedNode.yaml_loc(loc_str, suffix="")} {error}')
ValueError: File "a.yaml", line 17, col 12 slot: birthdate - unrecognized range (xsd:date)
```

**Comment by turbomam** [comment]
@leonqli could you please try with the bare `date` type and no prefix?

```yaml
  birthdate:
    range: date
```

I believe the implicit prefix for `date` in LinkML is actually `linkml`

If that works, it would be a possible solution. But I will leave it to others whether the `xsd` prefix should be allowed.

**Comment by leonqli** [comment]
Thanks @turbomam! Yes, linkml's date works. But I do need xsd:date instead of linkml date in my RDF..  :-(

**Comment by saxomoose** [comment]
Thank you for this open-source project.

Am encountering same issue.

See schema below:
```yaml
id: https://data.vlaanderen.be/ns/persoon
prefixes:
  dcterms: http://purl.org/dc/terms/
  locn: http://www.w3.org/ns/locn#
  person: http://www.w3.org/ns/person#
  persoon: https://data.vlaanderen.be/ns/persoon#
default_prefix: persoon
default_range: string
imports:
  # - ./oslo-adres.yaml

classes:
  Persoon:
    class_uri: person:Person
    slots:
      - heeftInwonerschap
  Inwonerschap:
    slots:
      - binnenJurisdictie
      - heeftVerblijfplaats
  Verblijfplaats:
    slots:
      - verblijfsadres

slots:
  heeftInwonerschap:
    range: Inwonerschap
  binnenJurisdictie:
    range: dcterms:Jurisdiction
  heeftVerblijfplaats:
    range: Verblijfplaats
  verblijfsadres:
    range: locn:Address
```
`gen-jsonld-context oslo-persoon.yaml` produces `ValueError: File "oslo-persoon.yaml", line 29, col 12 slot: binnenJurisdictie - unrecognized range (dcterms:Jurisdiction)`. The command also fails on `locn:Address`.

The [spec](https://linkml.io/linkml-model/latest/docs/range/) sets [Element](https://linkml.io/linkml-model/latest/docs/Element/) as the range of the range meta slot is . I also refer to the docs [here](https://linkml.io/linkml/schemas/slots.html#ranges) which confirm that in slightly different language. 

From this, it appears that it is not possible to provide a CURIE as the range of a slot. This seems like a bug but I am perhaps missing something.

**Comment by saxomoose** [comment]
Seems related to #1390, even though the latter issue relates to inheritance.

Users expect to be able to use CURIEs in `is_a` and `range` values. Otherwise, users are forced to implement external ontologies in LinkML in order to be able to use them through `imports`.

**Comment by vincentkelleher** [comment]
Hi @saxomoose & @leonqli,

I'm looking through issues as I'm currently working on a JSON-LD context generator fix and I found this one.

I usually use a "hack" to do this where I declare a class with a `class_uri` corresponding to the `range` I'm referring to, for example the following is being used in one of my tests:

```yaml
id: https://example.org/external_type
prefixes:
  linkml: https://w3id.org/linkml/
  ex: https://example.org/external_type#
  cred: https://www.w3.org/2018/credentials#

imports:
  - linkml:types

default_prefix: ex
default_range: string

slots:
  digestSRI:
    title: "Digest SRI"
    description: "Subresource Integrity hash ensuring it has won't be modified."
    range: SriString
    slot_uri: cred:digestSRI
    required: true

classes:
  SriString:
    class_uri: cred:sriString
```

That's what allows me to have the equivalent of `range: cred:sriString` in my slot 😉 

LinkML has to manage many formats and use cases so I understand that they can't implement on perfect solution that matches the needs of every output type 😇
