### ISSUE TITLE
adding inheritance from a different model

### ISSUE THREAD

**Issue by satra** [linkml/linkml#1390]
**Describe the bug**
We can't seem to add inheritance from a separately defined model. the following example dumps a lot of things on the screen but creates an empty file. in addition gen-pydantic generates pages of dumps but no direct error or a file containing classes.

**To reproduce**
```yaml
id: https://identifiers.org/brain-bican/example
name: example
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
  - https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model
default_range: string

classes:
  SomeThing:
    is_a: biolink:Gene
    description: some thing that is a gene
```

```
❯ linkml-lint example.yaml
❯ gen-python example.yaml > example.py
ValueError: File "example.yaml", line 12, col 11 Class: "SomeThing" - unknown is_a reference: biolink:Gene
```

**Expected behavior**
I expected a dataclass model that inherits from the biolink gene model

**About your computer (if applicable, please complete the following information):**
 - OS: macos
 - Version: `gen-python, version 1.5.0`

cc: @sooyounga

**Comment by caufieldjh** [comment]
In biolink-model, the class id is `gene`, so that's how it expects to be referenced from the import:
```
id: https://identifiers.org/brain-bican/example
name: example
prefixes:
  linkml: https://w3id.org/linkml/
  biolink: https://w3id.org/biolink/vocab/
imports:
  - linkml:types
  - https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model
default_range: string

classes:
  SomeThing:
    is_a: gene
    description: some thing that is a gene

```
