### ISSUE TITLE
id_prefix is not used for validation.

### ISSUE THREAD

**Issue by satra** [linkml/linkml#1391]
**Describe the bug**
`id_prefix` is not used for `id` validation. also generated code (pydantic or jsonschema) doesn't seem to reflect `id_prefixes` in any way.

**To reproduce**
```yaml
id: ENSEMBLER:ENSG00000101327
symbol: PDYN
name: prodynorphin [Source:HGNC Symbol%3BAcc:HGNC:8820]
category: biolink:Gene
```
linkml-validate example.yaml -s https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.yaml  -C "Gene"

relatedly: `gen-pydantic biolink-model.yaml > test.py` doesn't include id_prefixes for the Gene class anywhere.

**Expected behavior**
`id` should be treated as invalid since `ENSEMBLER` is not in `id_prefixes` list for class `Gene`

**Screenshots**

**About your computer (if applicable, please complete the following information):**
 - OS: MacOS
 - version: linkml 1.5.0
