### ISSUE TITLE
LinkML validation: Allow missing value codes for numeric values

### ISSUE THREAD

**Issue by Shalsh23** [linkml/linkml#1406]
**Is your feature request related to a problem? Please describe.**

For the ESS-DIVE data files that we are trying to validate using linkml, there are certain fields that have missing value codes eg. `-9999`. Since there is no way to specify missing value codes in the linkml schema, these values cause validation errors like `out of range value`. 

**Describe the solution you'd like**

We need to be able to specify missing value codes in the linkml schema for fields when applicable. These should be successfully validated even though they fall out of the max/min range values specified for those fields.

**How important is this feature?** 

Important

**When will use cases depending on this become relevant?** 

Short term - 1 month

**Additional context**

**Comment by pkalita-lbl** [comment]
Hi @Shalsh23! Thanks for taking the time to write this up. 

I don't know exactly what your schema looks like, but it might be possible to accomplish your goal with the existing features of LinkML. It's not extremely well-documented but a slot definition can include an `any_of`: https://linkml.io/linkml-model/docs/any_of/. Here's a very small example that might be helpful:

```yaml
# test.schema.yaml
id: http://example.org/any_of_example
name: any_of_example

imports:
  - https://w3id.org/linkml/types

slots:
  positive_or_missing_number:
    range: float
    any_of:
      - minimum_value: 0
      - equals_number: -9999

classes:
  Test:
    tree_root: true
    slots:
      - positive_or_missing_number
```

With that schema, this data instance will validate:

```yaml
positive_or_missing_number: 999
```

As well as this one:

```yaml
positive_or_missing_number: -9999
```

But this one will not (as expected):

```yaml
positive_or_missing_number: -999
```

If you think that's something that you can apply in your schema can you please go ahead and close this issue? Or if not can you give some more details about how that approach doesn't work?
