### ISSUE TITLE
SQL DDL foreign keys are text instead of integer

### ISSUE THREAD

**Issue by meganhmoore** [linkml/linkml#1407]
**Describe the bug**
In my YAML linkml model I have classes with slots & attributes that are references to other classes (ex. Person is a class, and another class Subject has a persons attribute of type Person) . When I use the SQL DDL generator, these tables contain foreign keys (for example persons_id that is in reference to the id for the Person table, however the persons_id is given type TEXT instead of INTEGER which causes the create table scripts to error out when they are run.

For example, these are the Person and Subject LinkML classes:
```
Person:
    is_a: Thing
    description: ''
    slots:
    - sex
    - race
    - race_other
    - ethnicity
    - country
    - race_identification_source
    slot_usage: {}
    attributes: {}
Subject:
    is_a: Thing
    description: ''
    slots:
    - honest_broker_subject_id
    - consortium
    - data_contributor_id
    - study_id
    - age_at_enrollment
    - treatment_arm
    - enrolled_status
    - data_source
    - year_at_enrollment
    - study_phase
    - study_type
    - efs_censor_status
    - age_at_censor_status
    - randomized_status
    slot_usage: {}
    attributes:
      persons:
        range: Person
        required: true
```

And this is the resultant SQL Table:
```
CREATE TABLE "Subject" (
	id INTEGER, 
	honest_broker_subject_id TEXT, 
	consortium VARCHAR(12), 
	data_contributor_id VARCHAR(12), 
	study_id VARCHAR(19), 
	age_at_enrollment INTEGER, 
	treatment_arm VARCHAR(71), 
	enrolled_status VARCHAR(12), 
	data_source VARCHAR(17), 
	year_at_enrollment INTEGER, 
	study_phase VARCHAR(12), 
	study_type VARCHAR(12), 
	efs_censor_status VARCHAR(12), 
	age_at_censor_status INTEGER, 
	randomized_status VARCHAR(14), 
	submitter_id TEXT NOT NULL, 
	type TEXT NOT NULL, 
	persons_id TEXT NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(persons_id) REFERENCES "Person" (id)
);
```
Where `persons_id TEXT NOT NULL, ` causes an error because it is expected to be an integer. 

Thank you!
