### ISSUE TITLE
"exactly_one_of" generates erroneous JSON-schema

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#1421]
**Describe the bug**
The generation of the JSON-schema corresponding a schema with a `exactly_one_of` slot/attribute is wrong.

**To reproduce**
1. Create the schema `test.schema.yaml` provided in the section *Additional context*
2. Generate the corresponding JSON schema: `gen-json-schema test.schema.yaml` (see result in the *Additional context* section)
3. See error in "oneOf" keys

**Expected behavior**
A JSON-Schema `oneOf` gets generated.

**Additional context**

```
# test.schema.yaml
id: http://example.org/pattern
name: pattern

imports:
  - https://w3id.org/linkml/types

slots:
  phone:
    exactly_one_of:
      - range: AmericanPhone
      - range: GermanPhone

classes:
  Test:
    tree_root: true
    slots:
      - phone

  AmericanPhone:
    attributes:
      phone_number:
        range: string
        pattern: \d{3} \d{3} \d{4}

  GermanPhone:
    attributes:
      phone_number:
        range: DePhoneNumber

types:
  DePhoneNumber:
    uri: xsd:String
    base: str
    pattern: 0\d{3}-\d{8}
```

Resulting JSON-schema:
```
{
    "$defs": {
        "AmericanPhone": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "phone_number": {
                    "pattern": "\\d{3} \\d{3} \\d{4}",
                    "type": "string"
                }
            },
            "title": "AmericanPhone",
            "type": "object"
        },
        "GermanPhone": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "phone_number": {
                    "type": "string"
                }
            },
            "title": "GermanPhone",
            "type": "object"
        },
        "Test": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "phone": {
                    "oneOf": [
                        {},
                        {}
                    ],
                    "type": "string"
                }
            },
            "title": "Test",
            "type": "object"
        }
    },
    "$id": "http://example.org/pattern",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "properties": {
        "phone": {
            "oneOf": [
                {},
                {}
            ],
            "type": "string"
        }
    },
    "title": "pattern",
    "type": "object",
    "version": null
}
```
