### ISSUE TITLE
If there is no default_prefix specified, then schema.name should be used as the default_prefix

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1424]
From #1041 

Given a schema

```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  Person:
    attributes:
      id:  ## note: default range is string, NOT an identifier
      full_name:
      aliases:
      phone:
      age:
```

currently the default prefix/namespace is set to be https://w3id.org/linkml/examples/personinfo, as per the metamodel. The RDF that is emitted in rdflib_dumper is correct, but we would also like an explicit prefix declaration of `personinfo: <https://w3id.org/linkml/examples/personinfo>`
