### ISSUE TITLE
pydanticgen should not have a Field(None) default is a slot is required

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1429]
@rly noticed the lack of validation of required slots; given

```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  Person:
    attributes:
      id:
        required: true
      full_name:
        required: true
      aliases:
      phone:
      age:
```

==>

```python
class Person(ConfiguredBaseModel):

    id: str = Field(None)
    full_name: str = Field(None)
    aliases: Optional[str] = Field(None)
    phone: Optional[str] = Field(None)
    age: Optional[str] = Field(None)
```

even though `Optional` is absent from id and full_name, it is possible to do `Person()` to create an invalid object
