### ISSUE TITLE
pydantic generator does not respect inherited forms

### ISSUE THREAD

**Issue by satra** [linkml/linkml#1432]
**Describe the bug**

The type annotation for relations referring to inherited classes is broken.

**To reproduce**

1. start with this

```yaml
id: https://identifiers.org/brain-bican/kb-model
name: kb-model
prefixes:
  linkml: https://w3id.org/linkml/
  biolink: https://w3id.org/biolink/
  bican: https://identifiers.org/brain-bican/vocab/
  spdx: http://spdx.org/rdf/terms#
  schema: http://schema.org/
  ncbi: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi
imports:
  - linkml:types
  - biolink:biolink-model
default_range: string
default_prefix: bican

classes:
  gene annotation:
    is_a: gene
    slots:
      - referenced in

  genome annotation:
    slots:
      - version

slots:
  referenced in:
    range: genome annotation
```
2. convert to pydantic: `gen-pydantic test.yaml > test.py`
3. the `referenced_in` slot will correctly refer to a `GenomeAnnotation` type
4. now add `is_a: Genome` to genome annotation
5. regenerate, and the `referenced_in` slot becomes a `str`

**Expected behavior**
`referenced_in` slot will continue to refer to a `GenomeAnnotation` type
