### ISSUE TITLE
JSON-schema for importing schema is missing classes

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#1440]
# Describe the bug
The generation of the JSON-schema corresponding a schema that is importing another schema results in references to classes not being included.

# To reproduce
1. Create base schema
<details>
  <summary>base.yaml</summary>

``` yaml
# base.yaml
id: https://example.org/base-schema
prefixes:
  linkml: https://w3id.org/linkml/
  base: https://example.org/base-schema/
imports:
  - linkml:types
default_prefix: base
default_range: string

classes:
  Asset:
    abstract: true
    slots:
      - asset_identifiers
  Device:
    is_a: Asset
  Identifier:
    abstract: true
  AssetIdentifier:
    is_a: Identifier
    abstract: true

slots:
  asset_identifiers:
    range: AssetIdentifier
    multivalued: true
``` 
 </details>

2. Create extended schema
<details>
  <summary>extension.yaml</summary>

``` yaml
# extension.yaml
id: https://example.org/extension-schemas

prefixes:
  extensions: https://example.org/extension-schemas/
  linkml: https://w3id.org/linkml/
  schemaorg: https://schema.org

imports:
  - linkml:types
  - base

default_prefix: extensions
default_range: string

classes:
  ManufacturedDevice:
    is_a: Device
```
 </details>

3. Generate the corresponding JSON-schema: `gen-json-schema extensions.yaml`
4. Observe in the resulting JSON-schema a reference to `#/$defs/AssetIdentifier` in both the `Device` and `ManufacturedDevice` classes.
<details>
  <summary>Resulting JSON-schema</summary>

``` json
{
    "$defs": {
        "Device": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "asset_identifiers": {
                    "items": {
                        "$ref": "#/$defs/AssetIdentifier"
                    },
                    "type": "array"
                }
            },
            "title": "Device",
            "type": "object"
        },
        "ManufacturedDevice": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "asset_identifiers": {
                    "items": {
                        "$ref": "#/$defs/AssetIdentifier"
                    },
                    "type": "array"
                }
            },
            "title": "ManufacturedDevice",
            "type": "object"
        }
    },
    "$id": "https://example.org/extension-schemas",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "title": "extension-schemas",
    "type": "object",
    "version": null
}
```
 </details>

# Expected behavior

# About your computer
 - Version: 1.5.2

# Additional context
