### ISSUE TITLE
Pydanticgen fails on range with use of any_of to limit to literal values

### ISSUE THREAD

**Issue by kevinschaper** [linkml/linkml#1471]
When attempting to generate pydantic for the sssom schema I ran into another instance of the check on both any_of and range being specified getting triggered, and in this case any_of is being used not to specify a type union (well, sort of...), but instead to provide for a limited subset of values. 

I think a desirable behavior here might be to turn the literal values into a type union in the pydantic?  Though, I'm not entirely sure how to factor the range in, clearly it's not 
```Union[EntityRange, Literal["semapv:LexicalMatching"],Literal["semapv:LogicalReasoning"]]``` 

Here is the relevant section of schema:
```
  mapping_justification:
    description: A mapping justification is an action (or the written representation of that action) of showing a mapping to be right or reasonable.
    range: EntityReference
    pattern: "^semapv:(MappingReview|ManualMappingCuration|LogicalReasoning|LexicalMatching|CompositeMatching|UnspecifiedMatching|SemanticSimilarityThresholdMatching|LexicalSimilarityThresholdMatching|MappingChaining)$"
    required: true
    any_of:
      - equals_string: semapv:LexicalMatching
      - equals_string: semapv:LogicalReasoning
      - equals_string: semapv:CompositeMatching
      - equals_string: semapv:UnspecifiedMatching
      - equals_string: semapv:SemanticSimilarityThresholdMatching
      - equals_string: semapv:LexicalSimilarityThresholdMatching
      - equals_string: semapv:MappingChaining
      - equals_string: semapv:MappingReview
      - equals_string: semapv:ManualMappingCuration
    examples:
      - value: semapv:LexicalMatching
      - value: semapv:ManualMappingCuration
```

and the error:

```
ValueError: Slot cannot have both range and any_of defined
```
