### ISSUE TITLE
enhance markdown rendering of linkml:Any slots

### ISSUE THREAD

**Issue by noelmcloughlin** [linkml/linkml#1478]
**Is your feature request related to a problem? Please describe.**

Linkml has basic support for **slots of type dictionary** via [linkml:Any ](https://linkml.io/linkml/schemas/advanced.html) (a.k.a. "MetaObject"s).  This is request to enhance markdown generator to provide richer rendering of these type of slots perhaps as configuration option. 

**Describe the solution you'd like**

Given this schema where **slot** has `range: MetaObject` and `domain: Fullname`  
``` 
classes:
  MetaObject:
    class_uri: linkml:Any

  FullName:
    slots:
      - firstName
      - lastName
    slot_usage:
      firstName:
        description: fullname firstname
      lastName:
        description: fullName lastname

slots:
  fullName:
    description: Nested domain
    range: MetaObject             <----------------- dictionary/collection object
    domain: FullName              <----------------- class modeling the MetaObject..

  firstName:
    range: string
    description: Personal firstname

  lastName:
    range: string
    description: Personal lastname
```
I would like option to display exploded slot list (`--expand-slots`) illustrated below:

![image](https://github.com/linkml/linkml/assets/13322818/103a4910-b728-41b8-85b1-adb76c93e04f)

And see more information on individual slot pages - i.e. if `range: MetaObject` and `domain: FullName` then list those class slots:

![image](https://github.com/linkml/linkml/assets/13322818/28756180-a7c6-4b82-bf8c-e57525e460e4)

**How important is this feature?** Select from the options below:

• Important - model documentation should be good

**Comment by cmungall** [comment]
What's an example of instance data for this?

**Comment by noelmcloughlin** [comment]
I don't need `linkml:Any` as agreed in #1511 because `range: Class` works. 

However I'd still like gen-doc enhanced.  In the example below `delete_options` and `proxy_headers` are classes but gen-doc does not recurse into slot:range=class to display nested slots/description.

```
api_key: 123457
ca_cert: /tmp/my_ca.crt
client_cert: /tmp/my_client.crt
client_key: /tmp/my_client_key
context: bananna
delete_options:
  delete_emptydir_data: true
  disable_eviction: false
  force: true
  ignore_daemonsets: false
  terminate_grace_period: 100
  wait_sleep: 4
  wait_timeout: 10
host: 'https://localhost:8811'
impersonate_groups:
  - group1
  - group2
impersonate_user: peter
kubeconfig: /tmp/mykubeconfig.txt
name: myhost1
no_proxy: 'localhost,.local,.example.com,127.0.0.1,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
password: secretpwd
persist_config: false
proxy: 'https://mainhost'
proxy_headers:
  basic_auth: 'username:password'
  proxy_basic_auth: 'username:password'
  user_agent: 'python-urllib3/0.6'
state: cordon
username: peter
validate_certs: true
```
