### ISSUE TITLE
Clarify how any_of interacts with previously specified ranges

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1483]
The semantics of `any_of` should be clear in the absence of other range specifications.

However, we need to clarify how this interacts with:

1. default_range
2. ranges inherited from either the slot definition or superclasses

range inheritance should always be monotonic - refine rather than override.

## default_range

default range should only be specified when there is no explicit range *or range expression*; i.e. if we have default range string, then this should not be applied if there is a any_of with ranges

This was recently fixed in pydanticgen

- #1272

## inheritance

An element of an any_of cannot be less restrictive than any inherited range constraint

## test case

Courtesy of @Silvanoc:

```yaml
id: https://w3id.org/linkml/examples/device
name: device
prefixes:
  linkml: https://w3id.org/linkml/
  device: https://w3id.org/linkml/examples/device
imports:
  - linkml:types
default_range: string
default_prefix: device

classes:
  ConnectionPoint:

  Device:
    slots:
      connection_points

  EthernetPort:
    is_a: ConnectionPoint
    slots:
      - mac_address
    defining_slots:
      - mac_address

  IpAddress:
    is_a: ConnectionPoint
    slots:
      - ip_address
    defining_slots:
      - ip_address

  EthernetDevice:
    is_a: Device
    slot_usage:
      connection_points:
        any_of:
          - range: EthernetPort
          - range: IpAddress

slots:
  connection_points:
    range: ConnectionPoint
    multivalued: true

  mac_address:

  ip_address:
```

data:

```yaml
connection_points:
  - mac_address: 00:11:22:33:44:55
  - ip_address: 192.168.178.2
```

Currently this fails to validate, for a couple of reasons:

- [ ] jsonschemagen issue where the range is interpreted as `ConnectionPoint AND (EthernetPort OR IpAddress)`. Logically this is equivalent to `(EthernetPort OR IpAddress)`. However, when this is written directly as jsonschema we need to unroll ConnectionPoint otherwise things fail
- [ ] currently the validation necessarily goes via pythongen and pythongen doesn't fully support any_of yet.
