### ISSUE TITLE
"multivalued" slot attribute gets lost on inheritance

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#1501]
# Describe the bug
"multivalued" slot attribute gets lost on inheritance.

# To reproduce
1. Create schema
<details>
  <summary>schema.yaml</summary>

``` yaml
# schema.yaml
id: https://example.org
prefixes:
  linkml: https://w3id.org/linkml/
  base: https://example.org
default_prefix: base

classes:
  SuperClass:
  SubClass:
    is_a: SuperClass
  MyClass:
    attributes:
      subslot:
        is_a: multivalued_superslot
        range: SubClass
  AnotherClass:
    slots:
      - multivalued_superslot

slots:
  multivalued_superslot:
    range: SuperClass
    multivalued: true
``` 
 </details>

2. Generate JSON-Schema
``` shell
gen-json-schema schema.yaml
```

3. Confirm that the parent slot `multivalued_superslot` is multivalued:
``` shell
gen-json-schema schema.yaml 2>/dev/null | jq -r '."$defs".AnotherClass.properties.multivalued_superslot'
```
``` json
{
  "items": {
    "$ref": "#/$defs/SuperClass"
  },
  "type": "array"
}
```

4. Confirm that the inherited sub-slot `subslot` is not multivalued:
``` shell
gen-json-schema schema.yaml 2>/dev/null | jq -r '."$defs".MyClass.properties.subslot'
```
``` json
{
  "$ref": "#/$defs/SubClass"
}
```

5. Force the subslot to be multivalued, adding `multivalued: true` to `subslot`.

<details>
  <summary>modified-schema.yaml</summary>

``` yaml
# modified-schema.yaml
id: https://example.org
prefixes:
  linkml: https://w3id.org/linkml/
  base: https://example.org
default_prefix: base

classes:
  SuperClass:
  SubClass:
    is_a: SuperClass
  MyClass:
    attributes:
      subslot:
        is_a: multivalued_superslot
        range: SubClass
        multivalued: true
  AnotherClass:
    slots:
      - multivalued_superslot

slots:
  multivalued_superslot:
    range: SuperClass
    multivalued: true
``` 
 </details>

6. Confirm that the inherited sub-slot `subslot` is now multivalued:
``` shell
gen-json-schema modified-schema.yaml 2>/dev/null | jq -r '."$defs".MyClass.properties.subslot'
```
``` json
{
  "items": {
    "$ref": "#/$defs/SubClass"
  },
  "type": "array"
}
```

# Expected behavior
A slot inheriting from another one keeps all the attributes of the superslot, unles overridden on the subslot. Specifically in this case the multivalued attribute is not being kept.

# About your computer
 - LinkML Version: 1.5.5
