### ISSUE TITLE
Guidance on slots modeling dictionaries for users

### ISSUE THREAD

**Issue by noelmcloughlin** [linkml/linkml#1511]
What is the correct way to model following data in linkml?
```
firstName: Noel
lastName: McLoughlin
addresses:
  addresses_verified: true
  addresses_primary:
    address_street: 123 Boluvard road
    address_city: Claxton, Los Angles
    address_postcode: 12456
  addresses_secondary:
    address_street: Red Log Cabin
    address_city: Harmon Canyon, Utah
    address_postcode: 75431
  addresses_workplace:
    address_street: Pixar HQ
    address_city: 400 Lexington Road, Los Angles
    address_postcode: 12456
```
Some discussion in Slack indicated most people use  "_slots whose ranges are classes, even with their own nested classes_" but validation fails for nested dictionary. 
```
ValueError:  Unknown argument: addresses_verified = True
 Unknown argument: addresses_primary = {'address_street': '123 Boluvard road', 
 Unknown argument: addresses_secondary = {'address_street': 'Red Log Cabin', 'add
 Unknown argument: addresses_workplace = {'address_street': 'Pixar HQ', 'address_
```
The solution is `Domain: Address, Range: MetaObject` [(linkml:Any)](https://linkml.io/linkml/schemas/advanced.html) from linkml documentation. Validation is skipped which is acceptable (but doc tooling would be helpful: #1478). 

However I then got confused about significance of  `class_uri: linkml:Any` after discovering that  `class_uri: linkml:Dict` and `class_uri: linkml:CuteKitten` (nonsense type) works also. 

SCHEMA with comments
```
classes:
  MetaObject:
    class_uri: linkml:Any     # linkml:Dict and linkml:CuteKitten accepted

  Address:
    class_uri: schema:PostalAddress
    attributes:
      address_street:
        description: first address line
      address_city:
        description: second address line
      address_postcode:
        description: postcode address line

  Addresses:
    attributes:
      addresses_verified:
        description: Due diligence done?
        range: boolean
      addresses_primary:
        description: primary place of residence
        range: MetaObject
        domain: Address
      addresses_secondary:
        description: secondary place of residence
        range: MetaObject
        domain: Address
      addresses_workplace:
        description: employment address
        range: MetaObject
        domain: Address

  Person:
    tree_root: true
    description: Somebody
    slots:
      - firstName
      - lastName
    attributes:
      addresses:
        # 'range: Address' causes validation error
        # consider 'range: MetaObject', Domain: Address'
        range: Address

slots:
  firstName:
    description: Personal firstname

  lastName:
    description: Personal lastname
```

**Comment by turbomam** [comment]
Thanks for this consistently through analysis, @noelmcloughlin. Your use case was discussed in Friday's LinkML developer's meeting. Nobody had either tried your approach or seen anything like it in the many schemas we see form other partners. We are all hoping you can join us for [weekly 4 pm ET Friday LinkML developer's meeting](https://docs.google.com/document/d/1OOgBRPYVwcD0hbKc79EOKP750vVCLEKAtbztSMQdC7A/edit) or the [LinkML community meeting](https://docs.google.com/document/d/1MStpDyh9LOZYJTjLtnpOsNYc3HaeU-bz0CHAI9xOjfQ/edit#heading=h.6sqkx1xhumse), which takes place on the 3rd Thursday every month at 11 am ET.

If you can't make either of those times, please suggest another time we could meet. I'm available roughly 8 am ET to 6 pm ET, and the West Coast USA people are available for a few hours after that.

**Comment by turbomam** [comment]
Could you show us how you would instantiate MetaObject/slots with dictionary ranges within Python code? Let me knwo if that's not something that you do on a regular basis.

**Comment by turbomam** [comment]
> What is the correct way to model following data in linkml?

Have you tried inferring a a schema from your example data? I would start by converting your example data from YAML to JSON with a tool like `yq`. I personally use [Mike Farah's GO-based yq](https://mikefarah.gitbook.io/yq/usage/convert), but there are numerous other ways to do this.

`yq -o=json '.' nm.yaml > nm_data.json`

Then infer a LinkML schema from that JSON data file with the [schema-automator Python package](https://linkml.io/schema-automator/packages/generalizers.html#generalizers)

`schemauto generalize-json --output nm_schema.yaml --container-class-name Person nm_data.json`

After that, I did some manual curation. Much of this could be automated with `yq`, `sed`, or custom Python code
- removed the inferred `identifier` slot assertions because I'm not certain which slots you want to serve as required, unique identifiers
- removed the inferred `unique_keys` class assertions, as above
- removed `name` and `from_schema` assertions. `name` is totally redundant with an element's key. `from_schema` doesn't add much unless you are working with a multi-file modular schema
- removed re-assertions of the default range on slots
- removed un-used inferred prefixes and added a definition of the used but undefined `schema` prefix
- manually merged in some of the annotations from your **SCHEMA with comments**
- added `AddressGroup` 

I also created a jsonschema with the [linkml-runtime package](https://pypi.org/project/linkml-runtime/)

`gen-json-schema nm_schema_curated.yaml > nm_schema_curated.schema.json`

and validated the data against that with the [check-jsonschema python package](https://pypi.org/project/check-jsonschema/). 

`check-jsonschema --schemafile nm_schema_curated.schema.json nm_data.yaml`

and applied linkml-validation

`linkml-validate --schema nm_schema_curated.yaml nm_data.yaml`

**Comment by turbomam** [comment]
In my opinion, defining slots within a class as `attributes` is only **required** when following the bad practice of slots with the same name but totally different definitions across classes. `attributes` have also been used a lot in our documentation, because it makes the snippets shorter and places the slot definitions in very close proximity to the classes that use them.

I would recommend using `slots`, not `attributes`, unless you have a compelling requirement otherwise.

**Comment by turbomam** [comment]
And then you can instantiate and manipulate within Python with either of these approaches:

```python
import nm_schema_curated as nms
import yaml
from linkml_runtime.dumpers import yaml_dumper

file_path = 'nm_data.yaml'


def read_yaml_file(file_path):
    with open(file_path, 'r') as file:
        try:
            yaml_data = yaml.safe_load(file)
            return yaml_data
        except yaml.YAMLError as e:
            print(f"Error while parsing YAML file: {e}")


nm_data = read_yaml_file(file_path)

if nm_data is not None:
    nm_person_from_file = nms.Person(**nm_data)

    print(yaml_dumper.dumps(nm_person_from_file))

    nm_person_direct = nms.Person(
        firstName="Noel",
        lastName="McLoughlin",
        addresses=nms.AddressGroup(
            addresses_verified=True,
            addresses_primary=nms.AddressesPrimary(
                address_street="123 Boluvard road",
                address_city="Claxton, Los Angles",
                address_postcode=12456,
            ),
            addresses_secondary=nms.AddressesSecondary(
                address_street="Red Log Cabin",
                address_city="Harmon Canyon, Utah",
                address_postcode=75431,
            ),
            addresses_workplace=nms.AddressesWorkplace(
                address_street="Pixar HQ",
                address_city="400 Lexington Road, Los Angles",
                address_postcode=12456,
            ),
        ),
    )

    print('\n')

    print(yaml_dumper.dumps(nm_person_direct))

```

**Comment by turbomam** [comment]
> I could join July 7th if that suits.

Great! I added the following heading in the [LinkML developer's meeting agenda](https://docs.google.com/document/d/1OOgBRPYVwcD0hbKc79EOKP750vVCLEKAtbztSMQdC7A/edit). Please add any brief details you desire.


- 2023-07-07
  - Noel McLaughlin

**Comment by noelmcloughlin** [comment]
Thanks! Appreciate the tips, particularly inferring schema.  Most of my LinkML use cases involve flat schema  (i.e. digitize a manual spreadsheet assessment process) with sample data. I see no requirement for nested dictionaries.

However I have one experiment involving dictionaries.  I'm working with a IT automation engine that consumes proprietary DSL to apply wanted configuration against system components. Features are implemented as python modules with supported configuration parameters documented in python doc-strings. There is no federated model, no ontology, no dataset, and no FAIRness.

As experiment I'm creating LinkML schema where classes are inferred from python module names and slots are inferred from their [docstrings](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameters). 

I believed only way to model this is using `Linkml:Any` (skiping validation) but then I had doubts (based on slack discussions) and got confused as my problem statement communicated.

**Comment by nlharris** [comment]
So is this really a bug?

**Comment by cmungall** [comment]
I believe that [mark's comment](https://github.com/linkml/linkml/issues/1511#issuecomment-1607592137) addresses the original question of how to model the data (of course `Any` can be used but this is not the preferred solution as you get no validation).

I will close but feel free to reopen if anyone wants (a) further clarification (b) a howto or faq entry added

**Comment by noelmcloughlin** [comment]
Hi @turbomam  thanks for your replies.

I followed your example successfully to write schema for this data (without linkml:Any).

I was unaware linkml supported this because docs had no example, so very happy.

```
api_key: 123457
ca_cert: /tmp/my_ca.crt
client_cert: /tmp/my_client.crt
client_key: /tmp/my_client_key
context: bananna
delete_options:
  delete_emptydir_data: true
  disable_eviction: false
  force: true
  ignore_daemonsets: false
  terminate_grace_period: 100
  wait_sleep: 4
  wait_timeout: 10
host: 'https://localhost:8811'
impersonate_groups:
  - group1
  - group2
impersonate_user: peter
kubeconfig: /tmp/mykubeconfig.txt
name: myhost1
no_proxy: 'localhost,.local,.example.com,127.0.0.1,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
password: secretpwd
persist_config: false
proxy: 'https://mainhost'
proxy_headers:
  basic_auth: 'username:password'
  proxy_basic_auth: 'username:password'
  user_agent: 'python-urllib3/0.6'
state: cordon
username: peter
validate_certs: true
```
