### ISSUE TITLE
Shacl generator does not support simple datatypes

### ISSUE THREAD

**Issue by anjastrunk** [linkml/linkml#1522]
**Describe the bug**
Shacl generator does not support simple datatypes, such as integer or time. The corresponding source code is empty. See [line 133 in shaclgen.py](https://github.com/linkml/linkml/blob/main/linkml/generators/shaclgen.py#L133)

**To reproduce**
Assume the following `person.yaml` file:

```yaml
id: http://example.com/person
name: person
prefixes:
  linkml: https://w3id.org/linkml/
  ex: http://example.com/
imports:
  - linkml:types
default_prefix: ex
default_range: string

classes:
  Person:
    attributes:
      age:
        range: integer
      name:
        range: string
```

`shacl-gen person.yaml` will result in:

```shacl
# metamodel_version: 1.7.0
@prefix ex: <http://example.com/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:Person a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:maxCount 1 ;
            sh:order 0 ;
            sh:path ex:age ],
        [ sh:maxCount 1 ;
            sh:order 1 ;
            sh:path ex:name ] ;
    sh:targetClass ex:Person ."
}
``` 
Shacl shape for `ex:Person` does not contain any `sh:datatype` parameter for attributes `ex:age` and `ex:name`. Datatypes of attributes are not evaluated. The validation of the following instance does **not** fail.

```json
{
  "@context": {
    "@base": "http://example.com/",
    "ex": "http://example.com/"
  },
  "@id": "John-Doe",
  "@type": "ex:Person",
  "ex:name": "John",
  "ex:age": "abc"
}
```
 
**Expected behavior**
Shacl generator should add datatype parameters to shapes. `shacl-gen person.yaml` should result in:
```
@prefix ex: <http://example.com/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:Person a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:datatype xsd:string ;
            sh:maxCount 1 ;
            sh:order 1 ;
            sh:path ex:name ],
        [ sh:datatype xsd:integer ;
            sh:maxCount 1 ;
            sh:order 0 ;
            sh:path ex:age ] ;
    sh:targetClass ex:Person .
```
