### ISSUE TITLE
Unexpected behavior of value_presence

### ISSUE THREAD

**Issue by kappe-c** [linkml/linkml#1524]
**Describe the bug**
In the following schema, when one of the non-required attributes is given, the other one should not be given. I thought I modelled this correctly with rules.

File exclusive-attributes.linkml.yaml
```yaml
id: https://example.org/exclusive-attributes
name: exclusiveattributes

prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types


classes:
  
  MyClass:
    attributes:
      my_string:
        required: false
        range: string
      my_float:
        required: false
        range: float
    rules:
      - preconditions:
          slot_conditions:
            my_string:
              value_presence: PRESENT
        postconditions:
          slot_conditions:
            my_float:
              value_presence: ABSENT
      - preconditions:
          slot_conditions:
            my_float:
              value_presence: PRESENT
        postconditions:
          slot_conditions:
            my_string:
              value_presence: ABSENT
```

However, with the following data, I get an error.

File my-object.yaml
```yaml
my_string: foo
# my_float: 1.2
```

The error message is `✗ 'my_float' is a required property in $`.

**To reproduce**
1. Save the two files in one folder.
2. Run `linkml-validate -s exclusive-attributes.linkml.yaml -C MyClass my-object.yaml`.
4. See error.

**Expected behavior**
Validation passes if exactly one of the attributes is given in the data file, and fails if both are given.

**About your computer (if applicable, please complete the following information):**
 - OS: Linux (openSUSE Leap 15.5)
 - Python 3.11.3
 - linkml-validate, version 1.5.6

**Additional context**
I guess that it may have something to do with the value_presence field, or more specifically its range: [PresenceEnum](https://linkml.io/linkml-model/docs/PresenceEnum/).
I guess that the enum values (PRESENT and ABSENT) somewhere both evaluate to true, so that even `value_presence: ABSENT` translates to `required: true`.
Notice that the [documentation for value_presence](https://linkml.io/linkml-model/docs/value_presence/) seems to mix something up here because under Comments it reads "if set to true […]" even though value_presence cannot be set to true. Its range is PresenceEnum.
