### ISSUE TITLE
Validation error for datetime/date data in YAML

### ISSUE THREAD

**Issue by rly** [linkml/linkml#1532]
**Describe the bug**
When I try to validate a YAML file with datetime data against a schema with a datetime or date attribute, I get these errors:
```
✗ datetime.datetime(2007, 3, 1, 13, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=68400))) is not of type 'string' in $.a_datetime
✗ datetime.date(2007, 3, 1) is not of type 'string' in $.a_date
```

I think this is because PyYAML auto-parses datetimes as `datetime.datetime` and `datetime.date` objects. 

Is there a way to use YAML to store datetime data and validate it? 

When YAML is passed to the validator, should it check against `datetime.datetime` and `datetime.date` objects instead of `string`?

See https://stackoverflow.com/questions/34667108/ignore-dates-and-times-while-parsing-yaml for a potential fix.

**To reproduce**
Create `test_datetime.yaml`:
```yaml
id: https://w3id.org/test
name: test
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types

classes:

  FileRoot:
    tree_root: true
    attributes:
      a_datetime:
        range: datetime
      a_date:
        range: date
```

Create `test_datetime_data.yaml`:
```yaml
a_datetime: 2007-03-01T13:00:00-05:00
a_date: 2007-03-01
```

Run: `linkml-validate -s test_datetime.yaml test_datetime_data.yaml`

**About your computer (if applicable, please complete the following information):**
 - OS: macOS
 - Python 3.10

I have these relevant packages installed:
```
linkml                    1.5.6
linkml-dataops            0.1.0
linkml-runtime            1.5.4
PyYAML                    6.0
```
