### ISSUE TITLE
linkml-validate does not check duplicate key

### ISSUE THREAD

**Issue by rly** [linkml/linkml#1542]
**Describe the bug**
How does uniqueness checking work? I think I am missing something, or there is a bug...

Running `linkml-validate` on a YAML schema with a slot with `identifier: true` on YAML data with duplicate values for the identifier slot does not raise an error as I would expect. Same if I use `key: true` or `unique_keys: ...` 

Interestingly, converting the YAML data to JSON does raise a duplicate key error if I use `identifier: true` or `key: true` (correct) but NOT if I use `unique_keys: ...` (incorrect), even though I thought `unique_keys` with one key should act the same as `key: true`.

I know jsonschema doesn't really have native support for uniqueness checking. Is that a factor here?

**To reproduce**
Create `test_identifier.yaml`:
```yaml
id: https://w3id.org/test
name: test
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  Resource:
    slots:
      - id
      - name
    # unique_keys:
    #   main:
    #     unique_key_slots:
    #       - id

  FileRoot:
    tree_root: true
    attributes:
      resources:
        range: Resource
        multivalued: true
        inlined_as_list: true

slots:
  id:
    identifier: true
    # key: true
  name:
```

Create `test_identifier_data.yaml`:
```yaml
resources:
  - id: test
    name: test
  - id: test
    name: test
```

1. Run: `linkml-validate -s test_identifier.yaml test_identifier_data.yaml`
Get unexpected pass: `✓ No problems found`

2. Convert YAML data to JSON: `linkml-convert -t json -s test_identifier.yaml test_identifier_data.yaml`
Get expected error: `ValueError: File "test_identifier_data.yaml", line 4, col 9: test: duplicate key`

3. Comment out `identifier: true` and uncomment `key: true` and run: `linkml-validate -s test_identifier.yaml test_identifier_data.yaml`
Get unexpected pass: `✓ No problems found`

4. Convert YAML data to JSON: `linkml-convert -t json -s test_identifier.yaml test_identifier_data.yaml`
Get expected error: `ValueError: File "test_identifier_data.yaml", line 4, col 9: test: duplicate key`

5. Comment out `identifier: true` and `key: true`. Uncomment `unique_keys: ...` and run: `linkml-validate -s test_identifier.yaml test_identifier_data.yaml`
Get unexpected pass: `✓ No problems found`

6. Convert YAML data to JSON: `linkml-convert -t json -s test_identifier.yaml test_identifier_data.yaml`
Get unexpected pass:
```
{
  "resources": [
    {
      "id": "test",
      "name": "test"
    },
    {
      "id": "test",
      "name": "test"
    }
  ],
  "@type": "FileRoot"
}
```

7. Save the above output as `test_identifier_data.json`. Run `linkml-validate -s nwb-schema/test_identifier.yaml example/test_identifier_data.json` (therefore the issues are also present if the data is JSON)
Get unexpected pass: `✓ No problems found`

**About your computer (if applicable, please complete the following information):**
 - OS: macOS

```
linkml                    1.5.6
linkml-dataops            0.1.0
linkml-runtime            1.5.4
```

**Comment by rly** [comment]
For my case 3, the slots would be:
```yaml
slots:
  id:
    key: true
  name:
```
I think that `key: true` means all objects with this slot in the same outer container must have ids that are unique within the scope of the outer container.

Thanks for the insight into what's going on!
