### ISSUE TITLE
What is the intended behavior for enums when serializing instances as JSON/JSON-LD

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#157]
when I have a model

```yaml
slots:
    state:
    range: model_state_enum

classes:
  model:
    slots:
      - state
enums:
  model_state_enum:
    permissible_values:
      production:
      development:
```

If I create

```python
m = Model(id=id('m1'),
                  title='test title',
                  state=ModelStateEnum.production)
jsonld = dumps(m, cntxt)
print(jsonld)
```

My JSON looks like:

```json
{
  "state": {
    "text": "production"
  }
 ...
```

which creates a blank node. Is this intentional

It's not clear what the behavior *should* be. I can imagine:

 - if meanings are provided, the meaning should be used
 - if no meaning is provided, use a literal

**Comment by hsolbrig** [comment]
It was intentional, but probably needs discussion.  My thinking when I put it together was that, if you HAD a meaning URI, the JSON would come out:
```
"state": {
      "text": "production",
      "meaning": STATESRUS:p,
      "label": "production state"
},
```
And possibly more. 

I realize, however, that when we are defining what JSON looks like, anything besides ```"state": "production"``` is not what I, a user, would expect.  The other stuff above should not actually appear at all in the JSON. 

I would disagree strongly with the "if meanings are provided, the meaning should be used".   The above model says that "production" and "development" are the two possible values of "state".   The intent of the meaning URI is to say that in the RDF context, "production" should be replaced (augmented?) with the accompanying URI.

Maybe this would make it a bit clearer:
```yaml
slots:
    state:
    range: model_state_enum
    slot_uri: STATESRUS:12345

classes:
  model:
    slots:
      - state
enums:
  model_state_enum:
    permissible_values:
      1:
           description: production
           meaning: STATESRUS:19923
      2:
          description: development
          meaning: STATESRUS:19924
```
(I deliberately obfuscated the permissible text values so that we don't confuse the text with the associated intent.

```python
m = Model(id='m1',
                  title='test title',
                  state=ModelStateEnum.1)
jsonld = dumps(m)
print(jsonld)
```
Should come out:
```
{
    "state": "1",
       ...
}
```

The _mapped_ RDF, however, should look something like:
```
:m1 :title "test title";
      STATESRUS:12345 STATESRUS:19923.
```

while the _literal_ RDF would be:
```
:m1 :title "test title;
       :state "1" .
```
Do we need to preserve the "1" in the RDF (ala FHIR)?  If we don't, we fact the (totally legitimate) situation:

```
enums:
  model_state_enum:
    permissible_values:
      1:
           description: production
           meaning: STATESRUS:19923
      2:
          description: development
          meaning: STATESRUS:19924
      3: description: pre-production
          notes: STATESRUS has no notion of pre-production
          meaning: STATESRUS:19923
```
And we go from `"state":"3"` --> `STATESRUS:12345 STATESRUS:19923` -> `"state":"1"`.

**Comment by cmungall** [comment]
V helpful!

Shall I write a test case?

For your last case, can we just prohibit non inverse functional maps to
meaning?

**Comment by cmungall** [comment]
@hsolbrig you say this is legitimate:

```
enums:
  model_state_enum:
    permissible_values:
      1:
         description: production
         meaning: STATESRUS:19923
      2:
         description: development
         meaning: STATESRUS:19924
      3: 
         description: pre-production
         notes: STATESRUS has no notion of pre-production
         meaning: STATESRUS:19923
```

I think that this should at least emit a warning, as it may be unintentional.

But I would have expected it to be an outright error, and the mapping between keys and meanings to be bijective

**Comment by sierra-moxon** [comment]
To fix: need to make an edit to the linkml-runtime/dumers/json-dumper.py

**Comment by cmungall** [comment]
any update on this?

**Comment by hsolbrig** [comment]
Fixed

**Comment by cmungall** [comment]
I'm not convinced this is working, need a test case...

**Comment by cmungall** [comment]
schema:

```yaml
id: http://example.org/sample/sample
name: sample

types:
  yearCount:
    base: int
    uri: xsd:int
  string:
    base: str
    uri: xsd:string

prefixes:
  ORGDATA: http://example.org/sample/sample/data/
  xsd: http://www.w3.org/2001/XMLSchema#
    
classes:

  Sample:
    slots:
      - id
      - name
      - body_site
      - analysis_type
      
  Study:
    slots:
      - samples
      
slots:
  
  id:
    description: Unique identifier of a person
    identifier: true

  name:
    description: human readable name
    range: string

  analysis_type:
    range: analysis_type_enum
    
  samples:
    multivalued: true
    range: Sample
    inlined: true
    inlined_as_list: true
    
  body_site:

enums:
  analysis_type_enum:
    permissible_values:
      genomic:
      metabolomic:
      proteomic:
```

data:

```yaml
samples:
  - id: S1
    name: gut sample 1
    body_site: gut
  - id: S2
    name: gut sample 2
    body_site: gut
  - id: S3
    name: brain sample 1
    body_site: brain
    analysis_type: genomic
```

when I roundtrip the data I get:

```yaml
samples:
- id: S1
  name: gut sample 1
  body_site: gut
- id: S2
  name: gut sample 2
  body_site: gut
- id: S3
  name: brain sample 1
  body_site: brain
  analysis_type:
    text: genomic
```

And when I validate I get:

```
jsonschema.exceptions.ValidationError: {'text': 'genomic'} is not one of ['genomic', 'metabolomic', 'proteomic']

Failed validating 'enum' in schema['properties']['samples']['items']['properties']['analysis_type']:
    {'description': '',
     'enum': ['genomic', 'metabolomic', 'proteomic'],
     'title': 'AnalysisTypeEnum',
     'type': 'string'}

On instance['samples'][2]['analysis_type']:
    {'text': 'genomic'}
```
