### ISSUE TITLE
Question concerning multivalued inlined slots

### ISSUE THREAD

**Issue by capsulecorplab** [linkml/linkml#1574]
Is it possible to define a schema similar to https://linkml.io/linkml/intro/tutorial02.html#nesting-lists-of-objects with container class whose `tree_root` is true and contains a multivalued inlined slot, but without the name of the slot as the parent key in the object?

i.e., instead of a `data.yaml` file that looks like
```
persons:
  - id: ORCID:1234
    full_name: Clark Kent
    age: 32
    phone: 555-555-5555
  - id: ORCID:4567
    full_name: Lois Lane
    age: 33
```
you have

```
- id: ORCID:1234
  full_name: Clark Kent
  age: 32
  phone: 555-555-5555
- id: ORCID:4567
  full_name: Lois Lane
  age: 33
```

If so, would this also be possible for [lining as a dictionary](https://linkml.io/linkml/schemas/inlining.html#inlining-as-a-dictionary)?
