### ISSUE TITLE
how to provide multivalued ifabsent slots

### ISSUE THREAD

**Issue by juliomateoslangerak** [linkml/linkml#1577]
I'm new to linkml and I'm using it for a project and it solves a lot of issues for me. **Big thanks!!**

I had a question about the usage of the ```ifabsent``` slot. I'm trying to define a multivalued slot with a default value and I cannot manage. I tried many different ways but no success. Here is an example giving me a ```ValueError: Incompatible default value: ['a', 'b']```

``` yaml
classes:
  MyClass:
    slots:
      - my_slot

slots:
  my_slot:
    range: string
    multivalued: true
    ifabsent: 
      - a 
      - b
```
Is this intended? Would you have a solution or workaround?
