### ISSUE TITLE
Possible to convert multiple yaml document without using container?

### ISSUE THREAD

**Issue by leonqli** [linkml/linkml#1579]
e.g. 
model:
```
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  biolink: https://w3id.org/biolink/vocab/
imports:
  - linkml:types
  - https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model
default_range: string

classes:
  Person:
    attributes:
      full_name:
      aliases:
      phone:
      age:
        range: integer
```

data:
```
...
full_name: Emily Doe
aliases: Em
phone: 123-456-7890
age: 30
---
full_name: Emily Doe
aliases: Em
phone: 123-456-7890
age: 30
---
full_name: Emily Doe
aliases: Em
phone: 123-456-7890
age: 30
---
full_name: Emily Doe
aliases: Em
phone: 123-456-7890
age: 30
...
```
Convert yaml to ttl:

```bash
linkml-convert -s s.yaml -C Person ss.yaml -o ss.ttl 
```

It raised the following errors:
```
...
    raise ComposerError("expected a single document in the stream",
yaml.composer.ComposerError: expected a single document in the stream

File "ss.yaml", line 1, column 1
but found another document
```

Thanks!
