### ISSUE TITLE
Pydantic generator doesn't resolve rules that switch between multivalued and single valued slots

### ISSUE THREAD

**Issue by sneakers-the-rat** [linkml/linkml#1583]
First of all I want to recognize that dealing with `rules` in generators seems like it would be really hard, so I understand if this is low priority.

**Describe the bug**

Slots that are unions of types (ie. using `any_of` as [here](https://linkml.io/linkml/schemas/advanced.html#unions-as-ranges)) should be able to be multi- or single valued (in general slots that can be single or multiple is not supported by LinkML as far as i know). Maybe I am reading this wrong, but it seems like one should be able to set `slot_conditions` using a `rule` - eg. [here](https://linkml.io/linkml/schemas/advanced.html#rules) the `pattern` is changed for the slot. it seems like that should be possible for any slot property?

So say for example I have some source data like this:
```yaml
object1:
  dtype: "value1"

object2:
  dtype:
    - name: "x"
      dtype: "value1"
    - name: "y"
      dtype: "value2"
```

It seems like this schema should be valid:
```yaml
slots:
  name:
  dtype:
    any_of:
      - range: CompoundDType
      - range: MyEnum

classes:
  CompoundDType:
    slots:
      - name
      - dtype

  MyClass:
    slots:
      - dtype
    rules:
      - preconditions:
          slot_conditions:
            dtype:
              range: CompoundDType
        postconditions:
          slot_conditions:
            dtype:
              multivalued: true

enums:
  MyEnum:
    permissible_values:
      value1:
      value2:
```

Note that it is the "top-level" `dtype` that needs to switch between being singular and multiple, so I can't eg. use `slot_conditions` on the `CompoundDType` to make the "inner" `dtype` multiple. 

The produced Pydantic (v1) code ignores the rule:

```python
class MyClass(ConfiguredBaseModel):
    dtype: Optional[Union[CompoundDType, MyEnum]] = Field(None)
```

and this is also true if i make the default slot `multivalued: true` and try to make it false when matching the single valued case.

```python
class MyClass(ConfiguredBaseModel):
    dtype: Optional[List[Union[CompoundDType, MyEnum]]] = Field(None)
```

**To reproduce**

```
gen-pydantic test_schema.yml --pydantic-version 1 > test_schema.py
```

**Expected behavior**

I would expect the Pydantic type to resolve to this:

```python
class MyClass(ConfiguredBaseModel):
    dtype: Optional[Union[List[CompoundDType], MyEnum]] = Field(None)
```

I'd be happy to contribute a PR to do this, I've read through the  generator code and I think I know how to do that. I wanted to check if this is actually valid to do in LinkML though - Surely someone else has needed to have a property that could be single or multivalued, and potentially they added a "name" key when they did it, but I can't find anything searching the issues and docs. Let me know if i'm just doing this wrong and there's a different way to do mixed cardinality, otherwise I'll draft the PR.

**Additional context**
- linkml 1.5.7
