### ISSUE TITLE
`contributors` annotation is not accepted on a `EnumDefinition`

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1606]
no test yet

`contributors` is listed as a multi-valued uriorcurie slot applicable to `EnumDefinition`
see https://linkml.io/linkml-model/latest/docs/EnumDefinition/#slots

However:

```yaml
enums:
  ResearchInitiativeTypeEnum:
    contributors:
      - "ORCID:0000-0003-2452-6384"
      - "ORCID:0009-0004-8906-5907"
      - "ORCID:0000-0001-9076-6066"
```

> ValueError:  Unknown argument: contributors = ['ORCID:0000-0003-2452-6384', 'ORCID:000
