### ISSUE TITLE
Further constraints on slots: exactly one of

### ISSUE THREAD

**Issue by nruemmele** [linkml/linkml#1607]
**Is your feature request related to a problem? Please describe.**
I am trying to model exactly_one_of constraint for attributes, where I am trying to indicate that exactly one attribute must be present.

For example, I have a Person class with 3 possible different types of phones. Now I want to add a constraint that exactly one phone must be provided.
```
classes:
  Person:
    attributes:
      id:
      full_name:
      mobile_phone:
      work_phone:
      home_phone:
```

**Describe the solution you'd like**
At the moment I could use `union` slot and indicate that its range is exactly_one_of those 3 phone slots. For example, like this:
```
classes:
  Person:
    attributes:
      id:
      full_name:
      phone:
        required: true
        exactly_one_of:
          - range: mobile_phone
          - range: work_phone
          - range: home_phone
```

 but this approach adds an extra slot and there will be one more object when generating JSON schema. I would like to avoid it. Is there another approach?

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by sierra-moxon** [comment]
Hi @nruemmele - Did you happen to see the [advanced "rules" feature of linkml](https://linkml.io/linkml/schemas/advanced.html#rules)?  These rules are turned into ["if/then" statements in the JSONSchema serialization](https://linkml.io/linkml/generators/json-schema.html#rules).  Here's [an example](https://github.com/alliance-genome/agr_curation_schema/blob/96c7951bca3a8895cabb02d545544f8c25c6c3ca/model/schema/expression.yaml#L65) of the syntax. 
 If they are not working for you, I'll log that. :)

**Comment by nruemmele** [comment]
Hi @sierra-moxon , thanks for pointing out further examples how to use the rules feature. You are right I can specify my constraint using empty preconditions and "exactly_one_of" in the postconditions. However, I believe it might be more intuitive if constraints could be modeled separately from rules. In my case, JSON serialization also looks unnecessarily convoluted.

**Comment by cmungall** [comment]
I'm not sure your original example works, since the range of range must be a class/type/enum, and not a slot.

Of course you could choose to model MobilePhone, WorkPhone, etc as classes and have a single slot, and use a type designator, but your intent looks to be have 4 different slots, so let's try and work that in - do you have an example of what a non-convoluted json-schema serialization would look like?

**Comment by nruemmele** [comment]
I guess I haven't used a very good example since those are data properties. In my scenario, I have a domain model based on which I am modeling a Kafka message. In one Kafka message I can send only one object property.

A better example would be:
```
classes:
  Person:
    attributes:
      id:
         identifier: true
         range: string
      is_sibling_of:
         range: Person
         inlined: false
      works_at:
         range: Company
         inlined: false
      lives_in:
         range: City
         inlined: false
```

Now the JSON schema should include the constraint that only one object property can be sent in the message, so I want the JSON schema to look the following way
```json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "oneOf": [
    {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "example": "Person1"
        },
        "is_sibling_of": {
          "type": "string",
          "example": "Person2"
        }
      },
      "required": [
        "id",
        "is_sibling_of"
      ]
    },
    {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "example": "Person1"
        },
        "works_at": {
          "type": "string",
          "example": "Company1"
        }
      },
      "required": [
        "id",
        "works_at"
      ]
    },
    {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "example": "Person1"
        },
        "lives_in": {
          "type": "string",
          "example": "City1"
        }
      },
      "required": [
        "id",
        "lives_in"
      ]
    }
  ]
}
```

For sure, I could have a general relation class and a type designator. But my requirement is to have those different keywords in the JSON message which I struggle to model properly.
