### ISSUE TITLE
Include custom annotations in generated schemas / code

### ISSUE THREAD

**Issue by simontaurus** [linkml/linkml#1618]
**Is your feature request related to a problem? Please describe.**
We are currently working on a link schema repo https://opensemantic.world/ combining json-schema and json-ld (=> https://github.com/OO-LD/schema), compareable to https://github.com/linkml/linkml/issues/474 
On the way we recognized that linkml (great work!) already addresses a lot of problems we have identified, especially the bridges to OWL and SHACL. 
However, since we focus both on programmatical and graphical interfaces would also need some custom annotations 
for custom vocabular e. g. used by https://github.com/json-editor/json-editor to generate html forms.

**Describe the solution you'd like**
Option to transfer 
* a) existing annotations (like `range` even when `inlined_as_list: false`)
* b) custom annotation like `hidden: true` for autogenerated fields in forms
into jsonschema and pydantic classes

```yml
  classes:
  Person:
  Container:
    attributes:
      id:
        option:
          hidden: true
      persons:
        multivalued: true
        inlined_as_list: true
        range: Person
```

```json
{
    "$defs": {
        "Container": {
            "description": "",
            "properties": {
                "id": {
                    "options": {
                        "hidden": "true"
                    },
                    "type": "string"
                "persons": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array",
                    "range": "#/$defs/Person"
                }
            },
            "title": "Container",
            "type": "object"
        },
        "Person": {
        }
    }
}
```

```python
class Person:
    pass

class Container(ConfiguredBaseModel):
    id: str
    persons: Optional[List[str]] = Field(default_factory=list, range=Person, options={'hidden': True})
```
Note: the extra parameter for Field() is also generated by https://github.com/koxudaxi/datamodel-code-generator

Maybe utilizing linkml `annotations` and dump the value as dict in the json-schema property and the pydantic Field if the generator was called with `--include-annotations=True` would be a solution for b)

**How important is this feature?** Select from the options below:
• Important - it's a blocker and can't do work without it (but of course I understand if this is out-of-scope)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Additional context**
Related: 
* https://github.com/json-schema-org/json-schema-vocabularies/issues/55

**Comment by cmungall** [comment]
This is in scope and would be a useful feature. We want to think carefully about how best to do this. I think using `options` in pydantic makes sense. It would be nice if there were an equivalent for dataclasses. @pkalita-lbl does the jsonschema approach above seem reasonable

**Comment by pkalita-lbl** [comment]
I think encoding the extra information in `annotations` along with an optional generator flag like `--inject-annotations` could work well for the JSON Schema generator. We'd just want to make sure we're careful to warn the user about edge cases like if the annotation would overwrite a JSON Schema keyword that was produced by the existing generation logic. Such as:

```yaml
slots:
  age:
    minimum_value: 0  # this will generate `minimum: 0` in JSON Schema
    annotations:
      hidden: true
      minimum: 10  # uh oh!
```

**Comment by cmungall** [comment]
Do we also have to worry about the scenario where a future version of json-schema introduces a keyword `annotations`?

**Comment by simontaurus** [comment]
Following @pkalita-lbl  approach, `annotations` would not collide with json-schema keywords since it's not exported (but the keywords / subobjects below)
So running
```yml
slots:
  age:
    minimum_value: 0  # this will generate `minimum: 0` in JSON Schema
    annotations:
      options: 
        hidden: true
      minimum: 10  # uh oh!
```
with `--inject-annotations` would lead to
```json
{
  "type": "object",
  "properties": {
                "age": {
                    "type": "int",
                    "minimum": 10
                    "options": {
                        "hidden": true
                    }
               }
}
```
with `minimum` overwritten by annotation. I think we can put the responsibility on the user and may introduce in addition  `--inject-annotation-prefix 'x-'`, resulting in
```json
{
  "type": "object",
  "properties": {
                "age": {
                    "type": "int",
                    "minimum": 0
                    "x-options": {
                        "hidden": true
                    },
                    "x-minimum": 10
               }
}
```

or even `--inject-annotation-prefix-on-conflict`, resulting in 
```json
{
  "type": "object",
  "properties": {
                "age": {
                    "type": "int",
                    "minimum": 0
                    "options": {
                        "hidden": true
                    },
                    "x-minimum": 10
               }
}
```

**Comment by pkalita-lbl** [comment]
> I think we can put the responsibility on the user

I agree. I just wanted to flag it as something we should be clear on and communicate to the user (through documentation, runtime warnings, etc) so that no one is surprised.

**Comment by jsheunis** [comment]
I'd like to register my interest in this feature as well, in relation to the automatic generation of user interfaces from schemas (similar to @simontaurus's use case). I'm focusing specifically on SHACL. I've adapted `shaclgen.py` in my local clone, enough to be able to see custom annotations on slots (directly, and slots with custom types as ranges, where the types have annotations) flow through to the exported SHACL. Perhaps my comments provide some more meat for the use case:

1. I am following the design at https://datashapes.org/forms.html quite closely, i.e. using the DASH vocabulary to define constraints for how specific fields are to be edited/viewed.
2. I am hoping this is just a result of my ignorance, but I am not sure how I could coerce the annotations into specific types on the SHACL side. E.g. if I have the following schema:
   ```
   id: https://example.org/test-schema
   name: myschema
   
   prefixes:
     dash: http://datashapes.org/dash#
     myschema: https://example.org/test-schema/
   
   default_prefix: myschema
   
   emit_prefixes:
     - dash
   
   imports: https://w3id.org/linkml/types
   
   slots:
     my_attr:
       range: string
       annotations:
         dash:singleLine: true
   
   classes:
     MyClass:
       abstract: true
       slots:
         - my_attr
   ```
   I want the SHACL to be:
   ```
   @prefix myschema: <https://example.org/test-schema/> .
   @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
   @prefix sh: <http://www.w3.org/ns/shacl#> .
   @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
   
   myschema:MyClass a sh:NodeShape ;
       sh:closed false ;
       sh:ignoredProperties ( rdf:type ) ;
       sh:property [ sh:datatype xsd:string ;
               dash:singleLine true ;
               sh:maxCount 1 ;
               sh:nodeKind sh:Literal ;
               sh:order 0 ;
               sh:path myschema:my_attr ] ;
       sh:targetClass myschema:MyClass .
   ```
   i.e. the annotation tag `dash:singleLine` should be recognized as a CURIE and the annotation value `true` should be recognized as `xsd:boolean`, i.e. not string literals. I don't have ideas yet about how to achieve this.
3. I encountered a scenario where there could be conflicts between annotations of a slot and annotations of a custom type which is used as the range of that same slot. E.g.:
   ```
   types:
     NameString:
       typeof: string
       uri: myschema:NameString
       annotations:
         dash:singleLine: false
   
   slots:
     my_attr:
       range: NameString
       annotations:
         dash:singleLine: true
   ```
   Here, the question is whether the resulting property shape of `my_attr` in SHACL should have `dash:singleLine true ;` or `dash:singleLine false ;`. I thought it's worth mentioning such a scenario and to consider how generator code would deal with this if needed.

If anyone has some more insight to share about these challenges I'm facing, I would love to hear them! I'm happy to create a PR to address shaclgen improvements ito annotations, once the uncertainties are gone.

Disclaimers:
- I have used LinkML for some months now, but I'm almost fully ignorant to the code internals
- I haven't looked into the base `Generators` class that something like `shaclgen` inherits from, so I'm not sure if some of the functionality in my local patches would be general enough to be applied to the base class rather than in shaclgen specifically.

**Comment by sneakers-the-rat** [comment]
saw this when searching for related issues for a PR. this is done for pydanticgen at least via the `metadata_mode` property that can include all schema metadata in generated models, including annotations.

**Comment by nlharris** [comment]
Can this be closed?

**Comment by sneakers-the-rat** [comment]
Original issue requested all metadata included in generated models for pydantic and jsonschemagen, pydantic does, but I dont think jsonschemagen does this yet?

**Comment by pkalita-lbl** [comment]
Correct, not implemented in jsonschemagen yet.

**Comment by sneakers-the-rat** [comment]
If this is blocking anyone - the lifecycle methods being added to jsonschemagen should allow you to dump anything you want in there pending a standard way to include the full linkml schema: https://github.com/linkml/linkml/issues/2339#issuecomment-2468360306

**Comment by simontaurus** [comment]
> @sneakers-the-rat: the lifecycle methods being added to jsonschemagen should allow you to dump anything you want in there

Thanks, this does the job for me as well.

Applying 
<details>
<summary>OOLDSchemaGenerator.py</summary>

```python
from pprint import pprint
from linkml.generators.jsonschemagen import JsonSchemaGenerator, JsonSchema
from linkml.generators.jsonldcontextgen import ContextGenerator 
import jsonasobj2
import json
import yaml

class OOLDSchemaGenerator(JsonSchemaGenerator):
        
    def generate_annotations(self, target):
        annotations = jsonasobj2._jsonobj.as_dict(target.source.annotations)
        schema_annotations = {}
        for key in annotations:
            schema_annotations[annotations[key]['tag']] = annotations[key]['value']
        if len(annotations) > 0:
            target.schema_ = {**target.schema_, **schema_annotations}
        return target
        
    def after_generate_class(self, cls, sv):
        self.generate_annotations(cls)
        return cls
        
    def after_generate_class_slot(self, slot, cls, sv):
        self.generate_annotations(slot)
        return slot

    def generate(self):
        _schema = super().generate()
        _context = json.loads(ContextGenerator(self.schema).serialize())
        oold = JsonSchema({"@context": _context["@context"], **_schema})
        return oold

    def serialize(self, **kwargs) -> str:
        return self.generate().to_json(sort_keys=False, indent=self.indent if self.indent > 0 else None)

if __name__ == "__main__":
    print(yaml.dump(json.loads(OOLDSchemaGenerator('Person.min.linkml.yaml', include_null=False).serialize()), sort_keys=False, indent=2))
```
</details>

on an annotated LinkML schema, e.g.

<details>
<summary>Person.linkml.yaml</summary>

```yaml
id: https://example.org/Person/
name: Person
prefixes:
      linkml: https://w3id.org/linkml/
      schema: http://schema.org/

imports:
      - linkml:types

classes:
    Organization:
      class_uri: schema:Organization
      attributes:
        name:
          slot_uri: schema:name
          range: string
    Address:
      class_uri: schema:PostalAddress
      attributes:
        street:
          range: string
          slot_uri: schema:street
        city:
          range: string
          slot_uri: schema:city
        postal_code:
          range: string
          slot_uri: schema:postalCode
    Person:
      tree_root: true
      class_uri: schema:Person
      attributes:
        name:
          slot_uri: schema:name
          range: string
          description: the name of a person
          required: true
          annotations:
            - tag: options
              value:
                hidden: false
            - template: "{{first_name}} {{last_name}}"
            - tag: watch
              value: 
                first_name: first_name
                last_name: last_name
                  
        first_name:
          range: string
        last_name:
          range: string
        birth_date:
          slot_uri: schema:birthDate
          range: date
          recommended: true
          annotations: 
            title: Birth date
        address:
          slot_uri: schema:address
          range: Address
        employer:
          name: employer
          range: Organization
          inlined: false
          inlined_as_list: false
```

</details>

produces a OO-LD schema (JSON-LD context + JSON-SCHEMA with additional annotation for userinterface generation like, e.g. `options` and `template`)

<details>
<summary>Person.oold.yaml</summary>

```yaml
'@context':
  xsd: http://www.w3.org/2001/XMLSchema#
  Person:
    '@id': schema:Person
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
  '@vocab': https://example.org/Person/
  city:
    '@id': schema:city
  postal_code:
    '@id': schema:postalCode
  street:
    '@id': schema:street
  name:
    '@id': schema:name
  address:
    '@type': '@id'
    '@id': schema:address
  birth_date:
    '@type': xsd:date
    '@id': schema:birthDate
  employer:
    '@type': '@id'
    '@id': employer
  first_name:
    '@id': first_name
  last_name:
    '@id': last_name
  Address:
    '@id': schema:PostalAddress
  Organization:
    '@id': schema:Organization
$schema: https://json-schema.org/draft/2019-09/schema
$id: https://example.org/Person/
metamodel_version: 1.7.0
version: null
title: Person
type: object
additionalProperties: true
$defs:
  Organization:
    type: object
    additionalProperties: false
    description: ''
    properties:
      name:
        type: string
    title: Organization
  Address:
    type: object
    additionalProperties: false
    description: ''
    properties:
      street:
        type: string
      city:
        type: string
      postal_code:
        type: string
    title: Address
  Person:
    type: object
    additionalProperties: false
    description: ''
    properties:
      name:
        type: string
        description: the name of a person
        options:
          hidden: false
        template: '{{first_name}} {{last_name}}'
        watch:
          first_name: first_name
          last_name: last_name
      first_name:
        type: string
      last_name:
        type: string
      birth_date:
        type: string
        format: date
        title: Birth date
      address:
        $ref: '#/$defs/Address'
      employer:
        $ref: '#/$defs/Organization'
    required:
    - name
    title: Person
description: ''
properties:
  name:
    type: string
    description: the name of a person
    options:
      hidden: false
    template: '{{first_name}} {{last_name}}'
    watch:
      first_name: first_name
      last_name: last_name
  first_name:
    type: string
  last_name:
    type: string
  birth_date:
    type: string
    format: date
    title: Birth date
  address:
    $ref: '#/$defs/Address'
  employer:
    $ref: '#/$defs/Organization'
required:
- name
```

</details>

which can be copy-pasted into [OO-LD playground](https://oo-ld.github.io/playground-yaml/?data=N4Ig9gDgLglmB2BnEAuUMDGCA2MBGqIAZglAIYDuApomALZUCsIANOHgFZUZQD62ZAJ5gArlELwwAJzplsrEIgwALKrNSgAAlnhQqAD3FoQ%2BxABNCyqFAgoA9HYpOAdBQDMz6QHM7AJgAM%2FgCMdgAaALIAMgDKKmpkAMQKAApUUrTwGiCaMBYoinGyKKnpCCAAvmy48ADWdPL5VjaI9o5uuZ5SPtV12HYKSqrqjda2DoPxnT4KmgBuYBhkBCPNrQZkdBDYVFN2JRn9bBgwUIJZOXkFQ2Qox6cVbBBgiOTYvFhmVOe5hBNFTy85ABhMCfB6KKBSKhUIxaH75P43F5QmHg%2BAbL7GC6%2FQo3dEMcFkMxmKGIZBY04QTHZH5sbEI3EoIkkmjISogPAwKRQZS8MxkPTnSnU0xmFD8wV0%2BFXeIoTnc5QAEQFX3Zai2YEEaSFgiphGxUsu6uwmu17KIXJevHxmLhlwt6T4NvBAitzqx0tdTox4IAgsTSeS7TjrsVnq9%2FSyyeCAPJdMjwGAALwFcEyHsuiJQca8CeTqbK5XZABJEZZRi0HBwMgBaRG7ElkIhQPzBACcNf8bbsZbYxelTQglbs602212%2BwQhxADHIdFBVDeszSiDThCCzgA7M5%2FApl%2Bk1yh4CJsNg2LAoNtCJPMufddSwJxuOI2MyTmm5MkpJA0rAaKhIREKg%2B0%2BIggxAHM8xTWAymMYVCEfLgeAUN8YPRbAvx%2FbkYH%2FFAiDkRBgJAT4lCkGBoEPEAFAgb8qWw3DQHdUB4IRSEYHgLwKnZC8r3ySDE2gtd2UjQMshY9gkJfEBUI%2FDDaN%2FHDyXw7BCLYEiMDIijYKox55Po8DkWhWEQHE5F2M49k7jOOD71%2BNiOPBAFXneBcxNs1iyIcotzxOXiQBE1lwRvNy9XyRDnxQ4l3wQT89L%2FJSCKI9TNLQwhqLixSsiYkz3IhTzOLUmgNPI1L8h5KgAAIbQqsAiAqsgKrojIFEgNDwOUXJPnTZTCO440VUIYBgAdN0MSLCqhq9a0xvKBQKAFFQshG70CXyZbpoJKoyFG1aQCm51vOIS0VttHLQry8yXW2k6QupMyvLYeUeT5AabPO%2B6CuIaRZCMYiBp8y9qQAIS5HkKolVVXwDQLjGLKEiEIBI7GLUDEDsALozVMdTSkLI4aoBH8iRlGCbR%2Fj81Sw6oQARxELkqDyABtEBnQAXQBvzgsO5KSso9KsPirKfTeu77M%2BnmtPTEzVCqjEarqhqmrKNhWrTdrOqobrEr6sdXpAIb1ptcbJuujaqCLOaFuUJbjrNwhDZ9LadupfafUOh3VuY3KPqu53brs%2FLwSe3kIf9jzLrYEgZAFQhQ454HQeUcGBvZZlRNh%2BHEeR1H0ehzG2GNHG8czons9JuxycEwt2RpumoSZlmfVZ9lEGUMAKF4NJv3SQh2L0KQyB4NdzyGak8DAMAoGRMgIAAFhQjgyH0ACpCAtgamhCBeAQKhat4WY5CAhKVPNthq1gxjhZAAAVGgoAq4LI9t90b7vhRXd2x%2BOUTl7BXySKowGUhEZNKRwTjWR0iAJycgXJgn%2FljDUWpcbGBflxcoQA%3D%3D%3D)

to get an auto-generated userinterface (based on https://github.com/json-editor/json-editor):

![grafik](https://github.com/user-attachments/assets/a83d885c-b345-4676-b3af-8a9a29ebfed3)


Populating `range` in combination with a proper backend allows user to created non-inlined objects on the fly or link (= store the IRI) to existing ones:

![grafik](https://github.com/user-attachments/assets/2e61fb48-b779-4b2d-88f3-c71098a605b5)


![grafik](https://github.com/user-attachments/assets/db298df5-d4f8-4d6c-9ab9-fb7de8314643)



@Duanoc, @nlharris, @LarsVogt: FYI
