### ISSUE TITLE
Unknown Argument: instantiates

### ISSUE THREAD

**Issue by timothy-trinidad-ps** [linkml/linkml#1639]
**Describe the bug**
Good morning! I see the Annotation Validation [in the documentation](https://linkml.io/linkml/schemas/annotations.html), but when I try and use “instantiates” in a class, I get an error with gen-doc that:
```
 ValueError:  Unknown argument: instantiates = [‘TableAnnotations’]
```
I assume that I need to wait for a v1.6 release of https://github.com/linkml/linkml - is that correct?

**To reproduce**
1. Create `personinfo.yaml` with the following contents:
```
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  personinfo: https://w3id.org/linkml/examples/personinfo
imports:
  - linkml:types
default_range: string
default_prefix: personinfo

classes:
  Reviewable:
    attributes:
      id:
      name:
  Person:
    instantiates:
      - Reviewable
    attributes:
      id:
      full_name:
      aliases:
      phone:
      age:
```
2. Run the following command:
```
docker run -v $(PWD):/work -w /work/ --rm -ti linkml/linkml:1.5.7 gen-doc -d . personinfo.yaml
```
Same results with `linkml/linkml:latest` and `linkml/linkml:main`

**Expected behavior**
Docs are generated with `Reviewable` attributes as annotation fields for `Person`

**About your computer (if applicable, please complete the following information):**
- gen-doc version: 1.5.7
