### ISSUE TITLE
How to handle computed properties and conditional assignments

### ISSUE THREAD

**Issue by joylix** [linkml/linkml#1647]
In the tutorial of example , I want to get some more functions, that is, calculated properties and conditional assignment:

```
  Person:
     attributes:
       name:
          required: true     
       weight:
          required: true      
       height:
          required: true      
       BMI:
          computed: true
          formular: weight / (height * height)          
       bodyType:
          oneOf:
              -underWeight      # BMI< 18
              -normal               # BMI >=18 and BMI <=26
              -overWeight        # BMI > 26

- id: bob
  type: Person
  name: Bob
  weight: 67
  height: 1.7

```
When person is instantiated, I want to get Bob.BMI and Bob.bodyType, How should I define the person model correctly and how can I implement this functionality in python?
