### ISSUE TITLE
Exclude or include boundary values of attributes about contraints

### ISSUE THREAD

**Issue by joylix** [linkml/linkml#1648]
```
classes:
  Product:
    attributes:
      id:
        identifier: true     
      name:
        required: true      
      length:                    
        range: decimal       
        minimum_value: 1.5
        maximum_value: 4.7
```
In general constraint expressions, boundary values are not included by default,
In the above example, it means 1.5<product.length<4.7, But many times it is necessary to include the boundary value itself, which is very common especially in engineering,  That is, how to express 1.5 <= length <4.7,  The following solution does not seem ideal：
```
      length:                    
        range: decimal       
        minimum:
             value: 1.5
             exclusive: false
        maximum: 
             value: 4.7
             exclusive: true
```
Is there a better solution?
I strongly hope to add handling of attribute boundary values
