### ISSUE TITLE
pydantic generator does not respect type declarations inheriting classes from imported models

### ISSUE THREAD

**Issue by puja-trivedi** [linkml/linkml#1664]
**Describe the bug**
The pydantic generator does not respect type declarations when you inherit classes from **imported** models. For example, in the code below if `genome annotation` (line 27) inherited from a locally defined class `testclass`; the pydantic generator produces the expected output: `Myclass.referenced_in` is of type `GenomeAnnotation`. However, when we change line 28 from `is_a: testclass` to `is_a: genome` where genome is Biolink:genome, the pydantic behavior changes and `Myclass.referenced_in` is now type `str`.

**To reproduce**
Steps to reproduce the behavior: Run the pydantic generator on the code below. Then look at the output for the `Myclass` class specifically the `referenced_in` attribute. 

```
id: https://identifiers.org/brain-bican/kb-model
name: kb-model
prefixes:
  linkml: https://w3id.org/linkml/
  biolink: https://w3id.org/biolink/
  bican: https://identifiers.org/brain-bican/vocab/
  spdx: http://spdx.org/rdf/terms#
  schema: http://schema.org/
  ncbi: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi
imports:
  - linkml:types
  - biolink:biolink-model
default_range: string
default_prefix: bican

classes:
  testclass:
    attributes: 
      my_attribute:
        range: string

  myclass:
    attributes:
      referenced in:
        range: genome annotation

  genome annotation:
    is_a: genome
    slots:
      - version
```

**Current Pydantic output**
```
class Myclass(ConfiguredBaseModel):
    
    referenced_in: Optional[str] = Field(None)
```

**Expected behavior**
Expected pydantic output: 
```
 class Myclass(ConfiguredBaseModel):
    
    referenced_in: Optional[GenomeAnnotation] = Field(None)
```

**About your computer (if applicable, please complete the following information):**
- This issue occurs with both `--pydantic_version 1` and `--pydantic_version 2`
- linkml version : [1.5.7]

**Comment by puja-trivedi** [comment]
Update: I was able to resolve the issue and get the expected output by using the "inline" slot. I'm not sure if this is the correct approach so any feedback would be appreciated! 

```
id: https://identifiers.org/brain-bican/kb-model
name: kb-model
prefixes:
  linkml: https://w3id.org/linkml/
  biolink: https://w3id.org/biolink/
  bican: https://identifiers.org/brain-bican/vocab/
  spdx: http://spdx.org/rdf/terms#
  schema: http://schema.org/
  ncbi: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi
imports:
  - linkml:types
  - biolink:biolink-model
default_range: string
default_prefix: bican

classes:
  testclass:
    attributes: 
      my_attribute:
        range: string

  myclass:
    attributes:
      referenced in:
        range: genome annotation
        inlined: true

  genome annotation:
    is_a: genome
    slots:
      - version
```
