### ISSUE TITLE
Child of a mixin cannot be used as a mixin

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#1671]
**Describe the bug**
Child of a `mixin` cannot be used as a `mixin`

**To reproduce**
1. Create a schema with a `mixin` class that is the child (`is_a`) of a `mixin`.
2. Generate the corresponding Python dataclass `gen-python schema.yaml > schema.py`
3. Confirm that `HasAliases` inherits the `aliases` attribute from `Interface` over a `is_a` relationship: `python -c 'from schema import * ; getattr(HasAliases, "aliases")`
4. Confirm that `Person1` inherits the `aliases` attribute from `Interface` over a `mixins` relationship: `python -c 'from schema import * ; getattr(Person1, "aliases")`
5. Observe that `Person2` DOES NOT inherits the `aliases` attribute from `HasAliases` over a `mixins` relationship: `python -c 'from schema import * ; getattr(Person2, "aliases")`

Schema example with `mixin` child:
```
id: https://w3id.org/linkml/examples/personinfo
imports:
  - https://w3id.org/linkml/types
default_range: string

classes:
  Person1:
    mixins:
      - Interface

  Person2:
    mixins:
      - HasAliases

  Interface:
    mixin: true
    attributes:
      aliases:

  HasAliases:
    mixin: true
    is_a: Interface
```

**Expected behavior**
I expect `Person2` to have also the `aliases` attributed inherited from `HasAlias` over a `mixin` relationship.

**Additional context**
I expect it to work due to following comment in [this page](https://linkml.io/linkml/schemas/inheritance.html#mixin-classes-and-slots):

> Note that is_a has the characteristics of homeomorphicity: is_a SHOULD only connect either (1) two mixins (2) two non-mixin elements

I don't see any other reason for having a `mixin` with a `is_a` relationship with another `mixin`.
