### ISSUE TITLE
Add additional tooling to support custom metamodeling, in particular for mkdocs generation

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1674]
The LinkML toolchain provides a way to create a mkdocs website for a schema. The results are necessarily generic, and expose the linkml directly.

Groups can customize this. An example being MIxS, also biolink. The customization is via custom Jinja2.

A more flexible way to customize this is to develop your own metamodel, and use [instantiates](https://linkml.io/linkml/schemas/annotations.html#other-uses-of-instantiates). I will use MIxS as an example, but this is broadly applicable.

The MIxS metamodel:

```
classes:
  Term:
      title: term
      is_a: SlotDefinition
      slot_usage:
          label:
            title: structured comment name
          title:
            required: true
            title: label
          slot_uri:
            required: true
      slots: [preferred_unit]
  Extension:
     is_a: ClassDefinition
  Checklist:
     is_a: ClassDefinition
  Combination:
     is_a: ClassDefinition
     slot_usage:
        is_a:
           title: derived from extension
           required: true
        mixins:
          title: derived from checklist
          required: true
  Section:
     is_a: ClassDefinition
```

This could be used like this:

```
slots:
  depth:
    instantiates: [mixs.meta:Term]
    annotations:
       preferred_unit: m
  ...
classes:
  MimsSoil:
    title: MIMS soil combination
    instantiates: [Combination]
    is_a: Soil
    mixins: [Mims]
```

In future there will be additional schema-level validation that will allow for this kind of custom metamodel validation, but it should be stressed this does not yet exist.

The generic linkml docgen framework could then make use of this metamodel reducing the need for custom jinja2

Note this would come at the cost of additional abstraction in the docgen framework.

There is a strong argument for simply using linkml terminology. For example, most generic ontology portals use generic ontology language, users accept this. However, for some scenarios it is useful to present a standard using more bespoke elements preferred by that community
