### ISSUE TITLE
`equals_string_in` meta slot not handled by JSON Schema generator

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1677]
Given this schema:

```yaml
# schema.yaml
id: test
name: test

prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

slots:
  pitches_a:
    equals_string_in:
      - fastball
      - curveball
      - slider
  pitches_b:
    any_of:
      - equals_string: fastball
      - equals_string: curveball
      - equals_string: slider

classes:
  Test:
    slots:
      - pitches_a
      - pitches_b
```

I would expect the JSON Schema generated from it would have roughly similar constructs for both slots. 

However, it appears that the slot using `equals_string_in` does not lead to any constraints at all:

```json
{
    "$defs": {
        "Test": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "pitches_a": {
                    "type": "string"
                },
                "pitches_b": {
                    "anyOf": [
                        {
                            "const": "fastball"
                        },
                        {
                            "const": "curveball"
                        },
                        {
                            "const": "slider"
                        }
                    ],
                    "type": "string"
                }
            },
            "title": "Test",
            "type": "object"
        }
    },
    "$id": "test",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "title": "test",
    "type": "object",
    "version": null
}

```
