### ISSUE TITLE
Incorrect JSON Schema output when using `required` in `rules`

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1678]
Given this schema:

```yaml
# schema.yaml
id: test
name: test

prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

slots:
  drivers_license_number:
  role:

classes:
  CarOccupant:
    slots:
      - role
      - drivers_license_number
    rules:
      - title: drivers need licenses
        preconditions:
          slot_conditions:
            role:
              equals_string: driver
        postconditions:
          slot_conditions:
            drivers_license_number:
              required: true
        elseconditions:
          slot_conditions:
            drivers_license_number:
              required: false
```

I would expect that in JSON Schema generated from it the `else` subschema would essentially be a no-op. But instead I get a `then` and an `else` subschema that assert that the `drivers_license_number` property is required:

```json
{
    "$defs": {
        "CarOccupant": {
            "additionalProperties": false,
            "description": "",
            "else": {
                "properties": {
                    "drivers_license_number": {}
                },
                "required": [
                    "drivers_license_number"
                ]
            },
            "if": {
                "properties": {
                    "role": {
                        "const": "driver"
                    }
                },
                "required": [
                    "role"
                ]
            },
            "properties": {
                "drivers_license_number": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            },
            "then": {
                "properties": {
                    "drivers_license_number": {}
                },
                "required": [
                    "drivers_license_number"
                ]
            },
            "title": "CarOccupant",
            "type": "object"
        }
    },
    "$id": "test",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "title": "test",
    "type": "object",
    "version": null
}
```

I think what's happening here is that the `open_world` metaslot on the rule definition is overriding what the `elsecondition` asserts.
