### ISSUE TITLE
JSON Schema generator output is unsatisfiable when type designator slot is also multivalued

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1681]
Given a schema like this:

```yaml
id: test
name: test
imports:
  - http://w3id.org/linkml/types
default_range: string

slots:
  whatsit:
    designates_type: true
    multivalued: true

classes:
  Test:
    tree_root: true
    slots:
      - whatsit
```

This is admittedly an odd schema. Conceptually, it probably doesn't _really_ make sense to have both `designates_type: true` and `multivalued: true` on a slot. Nevertheless, the JSON Schema produced by `gen-json-schema` in this case is actually unsatisfiable:

```
➜ gen-json-schema schema.yaml
INFO:root:Using SchemaView with im=None
INFO:root:Importing http://w3id.org/linkml/types as http://w3id.org/linkml/types from source schema.yaml; base_dir=
{
    "$defs": {
        "Test": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "whatsit": {
                    "enum": [
                        "Test"
                    ],
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "title": "Test",
            "type": "object"
        }
    },
    "$id": "test",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "description": "",
    "metamodel_version": "1.7.0",
    "properties": {
        "whatsit": {
            "enum": [
                "Test"
            ],
            "items": {
                "type": "string"
            },
            "type": "array"
        }
    },
    "title": "test",
    "type": "object",
    "version": null
}
```

If you say `{"whatsit": "Test"}` in order to satisfy the `enum` constraint, you'll fail the `type` constraint because you gave a string not an array. If you say `{"type": ["Test"]}` in order to satisfy the `type` constraint, you fail the `enum` constraint because you gave an array containing the string `"Test"`, not the string `"Test"` itself.

Even though this a vaguely pathological case, we should at least generate something satisfiable. I think if we see a slot declare `designates_type: true` that should fully control the JSON Schema output and other metaslots that normally influence the JSON Schema output (like `multivalued`, `pattern`, etc) should be disregarded.

**Comment by cmungall** [comment]
The simplest thing is to explicitly forbid TD+MV at the same time.

I suppose a multivalued type designator might make sense if there is always a single most specific class in the set of classes. E.g. 

 * `MSC(CodingGene,Gene,Thing) = {CodingGene}` --> OK
 * `MSC(CodingGene,NonCodingGene,Thing) = {CodingGene,NonCodingGene}` --> error
 * 
That is forcing quite a bit of logic into the validators and other generators… it is of course all possible with SchemaView, but it increases overall complexity. At best, MV + DT should be considered unsupported now, and at risk in future

**Comment by gouttegd** [comment]
> At best, MV + DT should be considered unsupported now, and at risk in future

If so, the documentation should be amended to reflect that, because for now, it clearly states that “MV + DT” is perfectly legitimate:

> **Type designators can also be assigned to multivalued slots**. In this case the same rules apply for each value of the slot. When performing inference, the most specific class is chosen. _(Emphasis mine)_

Of note, the validator is not the only component of LinkML that does not support multivalued type designators. The runtime loader does not support them either:

If I amend the schema provided in the original ticket to add a subclass to `Test`:

```
id: https://example.org/test
name: test
imports:
  - http://w3id.org/linkml/types
default_range: string

slots:
  whatsit:
    designates_type: true
    multivalued: true

classes:
  Test:
    tree_root: true
    slots:
      - whatsit

  SubTest:
    is_a: Test
```

(this is needed because, without a subclass, `linkml generate python` does not even generate the code to recognise the type designator – I guess it assumes that, since there is only one possible class that can be designated, there is no need to do anything.)

and then generate the code with `linkml generate python` and try to load the following file:

```yaml
whatsit:
  - Test
```

(which _should_ be a valid instance according to the schema), this fails:

```python
>>> yaml_loader.load("test.yaml", Test)
ValueError: Wrong type designator value: class Test has no subclass with ['class_name']='['Test']'
```

**Comment by gouttegd** [comment]
For what it’s worth, I had in mind a (potential) use case for multivalued type designators.

Let’s say I have a schema that defines the following class hierarchy:

```yaml
classes:
  Base:
    attributes:
      type:
        designates_type: true

  Foo:
    is_a: Base

  Bar:
    is_a: Base
```

where `Base` has a type designator slot.

Now let’s say that a third party _extends_ this schema by adding a new subclass to `Bar`:

```yaml
classes:
  Baz:
    is_a: Bar
```

The following instance is then valid according to the extended schema:

```
type: Baz
```

but it cannot be recognised by an application that is only aware of the base schema, because the `Baz` class is unknown in that schema.

I think it would be nice if an application that is only aware of the base schema could still be made to transparently accept (possible as an optional behaviour) data that is conforming to an unknown extension of the schema, and I was thinking that one way to do that would be to build upon multivalued type designators.

If we make the type designator slot in `Base` multivalued, then the instance data could become:

```
type:
  - Bar
  - Baz
```

For an application that is aware of the extended schema, this would not change anything: it would apply the rule (stated in the documentation) that “when performing inference, the most specific class is chosen”, and would therefore infer the instance to be an instance of `Baz` (since it knows about that class).

For an application that is only aware of the original schema, it would still of course be ignorant of the `Baz` class, but it could still recognise it as an instance of the parent `Bar` class.

Combined maybe with `extra_slots.allowed = True`, this could **allow an old application to transparently manipulate the data even though it makes use of an extended schema that the application is not (yet?) aware of**.
