### ISSUE TITLE
Enum inheritance not working in gen-sqlddl and others

### ISSUE THREAD

**Issue by kappe-c** [linkml/linkml#1685]
**Describe the bug**

Several tools (all but linkml-validate?) do not implement enum inheritance. If I made no mistake.  
E.g., when running  
`linkml-sqldb dump -s schema.yaml -D schema.db -C MyClass data.yaml`  
I get the error  
`ValueError: Unknown MyEnumB enumeration code: B`

schema:
```yaml
id: https://example.org/inheriting-enum
name: inheritingenum

imports: https://w3id.org/linkml/types

enums:
  MyEnumA:
    permissible_values:
      A:
  MyEnumB:
    inherits:
      - MyEnumA
    include:
      - permissible_values:
          B:

classes:
  MyClass:
    attributes:
      my_attr:
        # range: MyEnumA # simple enum works
        range: MyEnumB
```

Data: 
```yaml
# my_attr: A
my_attr: B # neither permissable values included in MyEnumA nor inherited from MyEnumB are recognized
```

I know it is said that "tooling support for dynamic enums is maturing" but also that "default behavior will be too permissive" [1]; while here it is not permissive at all.

Reluctantly (because installing OAK seemed overkill) I also tried the given suggestion
```sh
vskit expand -s schema.yaml -o schema_expanded.yaml
```
This has no effect (except for changing the indention a little)!

I also found that, e.g, gen-doc does not know what to do with *inherits* and *includes*.

**To reproduce**

1. Create the two files
2. Run the command(s)

**Expected behavior**

There are no complaints about A or B as a value for range *MyEnumB*.

To me this seems like the simplest case of a "dynamic enum". Just like the set of slots is extended from a parent to a child class, I would expect the set of permissible values to be extended in the enum example given above (actually the first thing I tried was using *is_a*). In particular I think it should not be a problem for database tools to materialize/expand such enums.

**About your computer (if applicable, please complete the following information):**
 - OS: openSUSE  Leap 15.5
 - linkml: 1.5.7

[1]: https://linkml.io/linkml/schemas/enums.html#tooling-to-support-dynamic-enums
