### ISSUE TITLE
Add documentation on value set expansion with a custom ontology

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#1690]
It's not very obvious how to do this at the moment. It's additionally confusing because vskit expansion is in OAK (this was intentional to avoid too many dependencies in linkml; however, it may be worth revisiting, or having a new repo/pypi like linkml-value-set-tools).

Here's an example of how this is done. Let's start with an example ontology, e.g. hsapdv for stages:

```
wget http://purl.obolibrary.org/obo/hsapdv.owl -O stages.owl
```

Of course, normally there is no need to do this as we could specify `obo:hsapdv`, but let's assume we can't do this or want to use a static local version etc

Here is our dynamic enum:

```yaml
id: https://w3id.org/linkml/examples/enums
title: Local Dynamic Enums Example
name: dynamicenums-example
description: This demonstrates the use of dynamic enums with a local file
license: https://creativecommons.org/publicdomain/zero/1.0/

prefixes:
  linkml: https://w3id.org/linkml/
  ex: https://w3id.org/linkml/examples/enums/
  HsapDV: http://purl.obolibrary.org/obo/HsapDV_
  my_ontologies: http://example.org/my_ontologies/
  
default_prefix: ex
default_range: string

imports:
  - linkml:types

classes:
  HumanSample:
    slots:
      - name
      - age

enums:
  Stage:
    reachable_from:
      include_self: true
      source_ontology: "my_ontologies:stages"
      relationship_types:
        - rdfs:subClassOf
      source_nodes:
        - HsapDv:0000000 ## life cycle stage

```

Here we are using a CURIE `my_ontologies:stages` to denote our ontology. *It doesn't matter that this doesn't resolve*. This is just a logical name for the ontology.

We can bind the logical name to a concrete product using a conf file:

```yaml
resource_resolvers:
  "my_ontologies:stages":
    shorthand: stages.owl
```

here we are using `./stages.owl` which we just downloaded. This could be any OAK shorthand, it could be an obo file, a sqlite file, .... see OAK docs for details

Then if we run

`poetry run vskit expand -s tests/input/value_set_url_example.yaml -c tests/input/value_set_url_example_conf.yaml Stage -o test.yaml`

We get:

```yaml
enums:
  Stage:
    reachable_from:
      include_self: true
      source_ontology: my_ontologies:stages
      relationship_types:
      - rdfs:subClassOf
      source_nodes:
      - HsapDv:0000000   ## life cycle stage
    permissible_values:
      HsapDv:0000123:
        text: HsapDv:0000123
        description: 29-year-old stage
        meaning: HsapDv:0000123
      HsapDv:0000156:
        text: HsapDv:0000156
        description: 62-year-old stage
        meaning: HsapDv:0000156
      HsapDv:0000099:
        text: HsapDv:0000099
        description: 5-year-old stage
        meaning: HsapDv:0000099
...
```
