### ISSUE TITLE
LinkML 1.6.2 breaks local imports

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#1694]
**Describe the bug**
Validation using local imports doesn't work is not run from directory of importing schema

**To reproduce**
1. Create a schema importing another local schema
2. Run `linkml-validate` from another directory than that of the importing schema
4. See error reporting `FileNotFoundError: [Errno 2] No such file or directory: <imported-schema>`

**Expected behavior**
Full-path resolution is relative to the path of the importing schema and not relative to the current working directory.

**About your computer (if applicable, please complete the following information):**
 - Version 1.6.2

**Comment by Silvanoc** [comment]
I've bisected the issue. This is the culprit commit: 36ab7c512321d864191c011db4d9ff7b04c666c1

**Comment by Silvanoc** [comment]
Assigning to @pkalita-lbl as author of the commit introducing the issue.

**Comment by Silvanoc** [comment]
Just for easy reproduction:

_base.yaml_
```
id: http://example.org/base
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  AClass:
    attributes:
      an_attribute:
```

_importing.yaml_
```
id: http://example.org/local-import
prefixes:
  linkml: https://w3id.org/linkml/
default_range: string
imports:
  - base
```

_data.yaml_
```
an_attribute: something
```

Validation command: `poetry run linkml-validate -s <path to importing schema> <path to data>`

Bisecting:
```
git bisect start
git bisect good v1.6.1
git bisect bad v1.6.2
git bisect run bash -c 'poetry run linkml-validate -s <path to importing schema> <path to data>'
```
