### ISSUE TITLE
Strange behavior of linkml-sqldb with slot_usage

### ISSUE THREAD

**Issue by kappe-c** [linkml/linkml#1702]
**Describe the bug**
Sometimes linkml-sqldb seems to ignore slot_usage of a child class. E.g. "overriding" integer with float works, string or an enum do not.

**To reproduce**

schema.yaml:
```yaml
id: https://example.org/slot-usage
name: slotusage

imports: https://w3id.org/linkml/types

enums:
  EnumA:
    permissible_values:
      A:

slots:
  originally_int:
    range: integer

classes:
  ClassA:
    slots:
      - originally_int
  ClassB:
    is_a: ClassA
    slot_usage:
      originally_int:
        range: float # works
        # range: string # ValueError: invalid literal for int() with base 10: 'foo'
        # range: EnumA # TypeError: int() argument must be a string, a bytes-like object or a real number, not 'EnumA'
```

data.yaml:
```yaml
# ClassB
originally_int: 1.2
# originally_int: foo
# originally_int: A
```

`linkml-sqldb dump -s schema.yaml -D slot-usage.db -C ClassB data.yaml`

**Expected behavior**
The slot range is taken from the slot_usage.

**About your computer (if applicable, please complete the following information):**
 - OS: openSUSE Leap 15.5
 - LinkML: 1.6.1

**Additional context**
I am aware that I have reported quite a few annoying issues lately. I hope this is not seen as destructive behavior or anything. I actually invested several hours trying to fix this bug myself. Because linkml-validate does work, I suspect the buggy code must be in https://github.com/linkml/linkml/blob/main/linkml/transformers/relmodel_transformer.py which is used by https://github.com/linkml/linkml/blob/main/linkml/generators/sqltablegen.py
In particular I analyzed the function *transform* in relmodel_transformer but it actually seems correct. Because `source_sv.class_induced_slots(cn)` is used to copy the slots from the source (yaml) class to the target (sql) class, the correctly materialized slots are taken (also considering any slot usage). That must be why e.g. float in the subclass works; but what is different for, e.g. string or enum, I cannot see.
