### ISSUE TITLE
JSON-LD generation for ENUM is wrong

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#173]
The `ENUM_CONTEXT` in the JSON-LD context generator is incorrect.  To remove the `@vocab` setting, you need to use `null`, not `@null`.  (Line 23)

**Comment by cmungall** [comment]
is this fixed?

**Comment by cmungall** [comment]
I don't understand the original comment but it seems that enums aren't supported by jsonld contexts

E.g. if I have

```yaml

prefixes:
  ...
  famrel: https://example.org/FamilialRelations#

enums:
  FamilialRelationshipType:
    permissible_values:
      SIBLING_OF:
        meaning: famrel:01
      PARENT_OF:
        meaning: famrel:02
      CHILD_OF:
        meaning: famrel:01
```

there is nothing for the enums in the jsonld context

see the personinfo schema in the examples folder
