### ISSUE TITLE
Multiline text in enumerations are not properly commented in gen-pydantic

### ISSUE THREAD

**Issue by nicholsn** [linkml/linkml#1746]
**Describe the bug**

`gen-pydantic` converts the `description` field for `permissible_values` into a line comment; however, when the `description` field includes multiple lines only the first line is commented out. This leads to errors like the following when running tests or otherwise importing the generated python module.

```python
  File "/Users/nnichols/Code/altos-labs-ontology/tests/test_data.py", line 7, in <module>
    from alo.datamodel.alo import Database
  File "/Users/nnichols/Code/altos-labs-ontology/src/alo/datamodel/alo.py", line 83157
    By isolating the protein, the RNA will also be isolated as it is bound to the protein. The purified RNA-protein complexes can be separated by performing an RNA extraction and the identity of the RNA can be determined by cDNA sequencing or RT-PCR.
       ^^^^^^^^^
SyntaxError: invalid syntax
```

**To reproduce**
1. Create an enum with multiple lines
```yaml
enums:
  AssayEnum:
    description: >-
      AssayEnum is an enumeration of the different types of assays that can be performed
      on a sample.
    permissible_values:
      RIP:
        text: RIP
        description: |-
          RNA Immunoprecipitation (RIP) is an experimental process used to investigate the interaction between proteins and RNA in the cell via the immunoprecipitation with an antibody that targets the protein of interest.
          By isolating the protein, the RNA will also be isolated as it is bound to the protein. The purified RNA-protein complexes can be separated by performing an RNA extraction and the identity of the RNA can be determined by cDNA sequencing or RT-PCR.
        meaning: EFO:0005033
        title: RIP
```
2. Use `gen-pydantic` to create the following (abbreviated) class as `enum.py`
```python
class AssayEnum(str, Enum):
    """
    AssayEnum is an enumeration of the different types of assays that can be performed on a sample.
    """
    # RNA Immunoprecipitation (RIP) is an experimental process used to investigate the interaction between proteins and RNA in the cell via the immunoprecipitation with an antibody that targets the protein of interest.
By isolating the protein, the RNA will also be isolated as it is bound to the protein. The purified RNA-protein complexes can be separated by performing an RNA extraction and the identity of the RNA can be determined by cDNA sequencing or RT-PCR.
    RIP = "RIP"
```
4. Try importing the module to see the error
```python
import enums
Traceback (most recent call last):

  File ~/Library/Caches/pypoetry/virtualenvs/alo-xdIJTcGn-py3.11/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3508 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[1], line 1
    import enums

  File ~/Code/altos-labs-ontology/enums.py:560
    By isolating the protein, the RNA will also be isolated as it is bound to the protein. The purified RNA-protein complexes can be separated by performing an RNA extraction and the identity of the RNA can be determined by cDNA sequencing or RT-PCR.
       ^
SyntaxError: invalid syntax
```

**Expected behavior**
The module should import w/o error

**About your computer (if applicable, please complete the following information):**
 - OS: OSX 12.6.5
 - Browser: chrome
 - Version: linkml-runtime 1.6.2

**Additional context**

This was discovered while using dynamic enums and extracting definitions from EFO where multiline comments are used.
