### ISSUE TITLE
Error when generating JSON Schema from schema with inlined (not as list), multivalued slot and --include-range-class-descendants

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1757]
With this schema:
```yaml
# schema.yaml
id: http://example.org/schema
name: schema

slots:
  id:
    range: string
    identifier: true
  name:
    range: string
    required: true
  hair_length:
    range: string
  breed:
    range: string
  pets:
    range: Pet
    multivalued: true
    inlined: true

classes:
  Pet:
    slots:
      - id
      - name
  Cat:
    is_a: Pet
    slots:
      - hair_length
  Dog:
    is_a: Pet
    slots:
      - breed
  PetCollection:
    tree_root: true
    slots:
      - pets
```

If I run:

```shell
gen-json-schema --include-range-class-descendants schema.yaml 
```

I get the following error:

```text
AttributeError: 'list' object has no attribute 'strip'
```

If I change the schema so that the `pets` slot is also `inlined_as_list: true`, then the command runs successfully.
