### ISSUE TITLE
linkml:pattern could handle capitalization rules of a field, but could LinkML have named patterns?

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#176]
We occasionally need string content to adhere to capitalization rules like lowercase, uppercase, and title case.  Could we somehow name regular expression patterns and reuse them in linkml:pattern strings (or values) so that the regular expression was substituted in before being applied?

**Comment by cmungall** [comment]
Some of this may be better served by a more general expression language

**Comment by ddooley** [comment]
A latest thought is to utilize the linkml:string_specification field to contain expressions like "{decimal} {unit}" or "{email}" where each specification that utilizes string_specification would also have a dictionary of what these elements transform to as regular expression tests or as you say a more general expression language.

**Comment by cmungall** [comment]
the semantics of string serialization are such that the things in `{...}` should be slots or slot paths. See https://github.com/linkml/linkml-runtime/pull/111

so you could have

```yaml
  verbatim:
    string_serialization: "{magnitude} {unit}" or "{email}"
  magnitude:
    range: decimal
  unit:
     range: string
     string_serialization: "^[c|cm|...]$"
  email:
    range: string
    string_serialization: "^...\\@...$"
```

where you are at least pushing things to reusable components. But I think this is not quite right for your use case

So I think what we want here is a new metaslot (we can't overload string_serialization, the things in braces MUST be slots or paths, and these must be slots of the containing class, so this is no good for literal/type slots)

open to names, but something like:


```yaml
id: http://...my-schema
prefixes:
   ...
constants:
    decimal: "^[0-9]+[\\.[0-9]+]" 
    email: ".^*@.*\\..*$"
    unit: "^[m|cm|...]"
...    

slots:
  measurement:
    range: string
    abstract_pattern: "{decimal} {unit}"
  email:
    range: string
    abstract_pattern: "{unit}"
```

apologies for the brevity... is this on the right lines?

**Comment by cmungall** [comment]
Just a ping @ddooley to see if the above approach makes sense

**Comment by ddooley** [comment]
In first example above, for unit and email above you still allow string_serializations that are regular expressions? e.g. "^[c|cm|...]$"  ... while "verbatim" has the kind of named slot entity/string substitution thing going on.  I understand how "verbatim" might support a notion of slots or slot path reference, but don't the other two examples break it?  Or the two types of string_serialization strings are both accepted, but are detected quietly?

But yes, "constants", or more to the point "named_patterns", could be a good way of naming patterns, and introducing "abstract_pattern" property could separate out the regular expression matching functionality clearly from the string_serialization functionality.  Does "abstract_pattern" become the only place to express regular expressions?  And we drop regular expressions from "string_serialization"?

**Comment by cmungall** [comment]
> In first example above, for unit and email above you still allow string_serializations that are regular expressions?

oops, sorry, I mis-typed. Should have been:


```yaml
class:
  sample:
    slots:
      - ...
      - depth
  QuantityValue:
    slots:
      - verbatim
      - magnitude
      - unit 
  
slots:
  depth:
     range: QuantityValue
  verbatim:
    string_serialization: "{magnitude} {unit}"
  magnitude:
    range: decimal
    pattern: "^\\d+(\\.\\d+)?$"
  unit:
     range: string
     pattern: "^[c|cm|...]$"
```

i.e. string_serialization must be something that can be generated. So the string for verbatim can be generated if the values for unit and magnitude are known. And string_serializations can be used for parsing, if the regex part of the grammar is restricted to patterns.

> But yes, "constants", or more to the point "named_patterns", could be a good way of naming patterns, and introducing "abstract_pattern" property could separate out the regular expression matching functionality clearly from the string_serialization functionality. 

Exactly

> Does "abstract_pattern" become the only place to express regular expressions?

We would retain `pattern` for backwards compatibility and just for simplicity.

here is a more complete example:

```yaml
# constant/parameter settings
settings:
  float: "\\d+[\\.\\d+]"
  unit: "\\S+"
  unit.length: "(centimeter|meter|inch)"
  unit.weight: "(kg|g|lbs|stone)"
  email: "\\S+@\\S+{\\.\\w}+"
  
#==================================
# Classes                         #
#==================================

classes:
  PersonInfo:
    slots:
      - id
      - name
      - height
      - email

#==================================
# Slots                           #
#==================================

slots:
  id:
    identifier: true
    range: string
    pattern: "^P\\d{7}"    ## simple pattern. Note {}s are NOT interpolated
  name:
    range: string
  email:
    range: EmailString
  height:
    range: string
    structured_pattern:
      pattern: "{float} {unit.length}"
      interpolated: true   ## all {...}s are replaced using settings
      partial_match: false
  weight:
    range: string
    structured_pattern:
      pattern: "{float} {unit.weight}"
      interpolated: true
      partial_match: false  ## implicit ^...$

#==================================
# Types
#==================================

types:
  EmailString:
    typeof: string
    structured_pattern:
      pattern: "{email}"
      interpolated: true
      partial_match: false  ## implicit ^...$
```

> And we drop regular expressions from "string_serialization"?

Yep, that was just my typo in my previous comment, should have been `pattern`, sorry for the confusion!
