### ISSUE TITLE
Inherited rules do not appear in JSON Schema generator output

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1802]
With this schema:

```yaml
# schema.yaml
id: https://example.org/test
name: test

prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types

default_range: integer

classes:
  MyClass:
    attributes:
      a:
      b:
    rules:
      - description: if a is big then b is small
        preconditions:
          slot_conditions:
            a:
              minimum_value: 100
        postconditions:
          slot_conditions:
            b:
              maximum_value: 10
  MySubClass:
    is_a: MyClass
    attributes:
      c:
```

And this data instance:

```yaml
# data.yaml
a: 1000
b: 1000
```

I would expect that data to fail validation because of the rule on `MyClass`. Indeed `linkml-validate` correctly reports the problem when validating against `MyClass`:

```text
➜ linkml-validate -s schema.yaml --target-class MyClass data.yaml   
[ERROR] [data.yaml/0] 1000 is greater than the maximum of 10 in /b
```

I would expect to see the same problem reported when validating against `MySubClass`. However, no problem is reported:

```text
➜ linkml-validate -s schema.yaml --target-class MySubClass data.yaml
No issues found
```

When looking at the output of `gen-json-schema` is appears that the `rules` are only being translated for `MyClass` and not `MySubClass`:

```json
{
    "$defs": {
        "MyClass": {
            "additionalProperties": false,
            "description": "",
            "if": {
                "properties": {
                    "a": {
                        "minimum": 100
                    }
                },
                "required": [
                    "a"
                ]
            },
            "properties": {
                "a": {
                    "type": "integer"
                },
                "b": {
                    "type": "integer"
                }
            },
            "then": {
                "properties": {
                    "b": {
                        "maximum": 10
                    }
                },
                "required": [
                    "b"
                ]
            },
            "title": "MyClass",
            "type": "object"
        },
        "MySubClass": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "a": {
                    "type": "integer"
                },
                "b": {
                    "type": "integer"
                },
                "c": {
                    "type": "integer"
                }
            },
            "title": "MySubClass",
            "type": "object"
        }
    },
    "$id": "https://example.org/test",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "title": "test",
    "type": "object",
    "version": null
}
```
