### ISSUE TITLE
JSON Schema generator does not handle case where a rule changes a slot from required to not required

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#1803]
With this schema:

```yaml
id: https://example.org/test
name: test

imports:
  - https://w3id.org/linkml/types

slots:
  age:
    range: integer
    required: true
  name:
    range: string
    required: true

classes:
  Person:
    tree_root: true
    slots:
      - age
      - name
    rules:
      - description: Babies don't need a name right away
        preconditions:
          slot_conditions:
            age:
              equals_integer: 0
        postconditions:
          slot_conditions:
            name:
              required: false
```

With LinkML 1.6.6, the following JSON Schema is generated by `gen-json-schema` (abridged for clarity):

```json
{
    "$defs": { ... },
    "$id": "https://example.org/test",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "description": "",
    "if": {
        "properties": {
            "age": {
                "const": 0
            }
        },
        "required": [
            "age"
        ]
    },
    "metamodel_version": "1.7.0",
    "properties": {
        "age": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        }
    },
    "required": [
        "age",
        "name"
    ],
    "then": {
        "properties": {
            "name": {}
        },
        "required": [
            "name"
        ]
    },
    "title": "test",
    "type": "object",
    "version": null
}
```

The `"required": [ "name" ]` in the `then` subschema is obviously a bug, but even without it that JSON Schema would not correctly validate an instance like `{ "age": 0 }`. This is because once `name` is included in the top-level `required` keyword, there is nothing that a `then` or `else` subschema can do to override that.

I think the only way to express this in JSON Schema would look something like this instead:

```json
{
  "$id": "https://example.org/test",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": true,
  "description": "",
  "if": {
    "not": {
      "properties": {
        "age": {
          "const": 0
        }
      },
      "required": [
        "age"
      ]
    }
  },
  "metamodel_version": "1.7.0",
  "properties": {
    "age": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    }
  },
  "required": [
    "age",
  ],
  "then": {
    "required": ["name"]
  },
  "title": "test",
  "type": "object",
  "version": null
}
```

The changes are that `name` is **not** included in the top-level `required` keyword, the entire `if` subschema has been negated, and `name` has been included in a `required` keyword in the `then` subschema. We've basically logically inverted the rule in order to work around JSON Schema's inability to override the top-level `required` keyword.
