### ISSUE TITLE
Invalid URI error on creating nested instances with python dataclass

### ISSUE THREAD

**Issue by cmdoret** [linkml/linkml#1804]
**Describe the bug**

Thank you for this great framework!

When trying to instantiate a nested structure using the autogenerated python dataclasses, linkml complains about invalid URIs.

I did not find an example of using dataclasses with composed structures in the documentation. Maybe this is the expected behaviour, in which case the bug report can be ignored.

**To reproduce**

1. use linkml cookiecutter and setup
3. edit demo schema to following yaml

<details>
<summary>demo_schema.yaml</summary>

```yaml
---
id: https://w3id.org/foo/demo-schema
name: demo-schema
title: demo-schema
description: |-
  bad
license: MIT
see_also:
  - https://foo.github.io/demo-schema

prefixes:
  demo_schema: https://w3id.org/foo/demo-schema/
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
  PATO: http://purl.obolibrary.org/obo/PATO_
default_prefix: demo_schema
default_range: string

imports:
  - linkml:types

classes:

  NamedThing:
    description: >-
      A generic grouping for any identifiable entity
    slots:
      - id
      - name
      - description
    class_uri: schema:Thing

  Person:
    is_a: NamedThing
    slots:
      - pet
      - vital_status
  Pet:
    is_a: NamedThing
    slots:
      - vital_status

  PersonCollection:
    tree_root: true
    description: >-
      A holder for Person objects
    attributes:
      entries:
        range: Person
        multivalued: true
        inlined: true

slots:
  id:
    identifier: true
    slot_uri: schema:identifier
    range: uriorcurie
    description: A unique identifier for a thing
  name:
    slot_uri: schema:name
    description: A human-readable name for a thing
  description:
    slot_uri: schema:description
    description: A human-readable description for a thing
  vital_status:
    range: VitalStatus
    description: living or dead status
  pet:
    range: Pet
    description: Having a pet

enums:
  VitalStatus:
    permissible_values:
      ALIVE:
        description: is living
        meaning: PATO:0001421
      DEAD:
        description: is deceased
        meaning: PATO:0001422
      UNKNOWN:
        description: is not known
        todos:
          - map this to an ontology
```
</details>

5. `make all`
6. open python
7. Run the following

```py
from demo_schema.datamodel import Person, Pet, VitalStatus

pet = Pet('https://example.org/dog1')
Person('https://example.org/person1', pet=pet)
```

This raises the following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 Person('https://example.org/person1', pet=pet)

File <string>:8, in __init__(self, id, name, description, pet, vital_status, **_kwargs)

File /tmp/demo-schema/src/demo_schema/datamodel/demo_schema.py:107, in Person.__post_init__(self, *_, **kwargs)
    104     self.id = PersonId(self.id)
    106 if self.pet is not None and not isinstance(self.pet, PetId):
--> 107     self.pet = PetId(self.pet)
    109 if self.vital_status is not None and not isinstance(self.vital_status, VitalStatus):
    110     self.vital_status = VitalStatus(self.vital_status)

File ~/.local/share/mambaforge/envs/py310/lib/python3.10/site-packages/linkml_runtime/utils/metamodelcore.py:104, in URIorCURIE.__init__(self, v)
    102 def __init__(self, v: Union[str, URIRef, "Curie", "URIorCURIE"]) -> None:
    103     if is_strict() and not URIorCURIE.is_valid(v):
--> 104         raise ValueError(f"{v} is not a valid URI or CURIE")
    105     super().__init__(v)

ValueError: Pet(id='https://example.org/dog1', name=None, description=None, vital_status=None) is not a valid URI or CURIE

```

In case this is useful, the autogenerated code is provided below.
<details>
<summary>demo_schema.py</summary>

```py
# Auto generated from demo_schema.yaml by pythongen.py version: 0.0.1
# Generation date: 2023-12-22T15:43:06
# Schema: demo-schema
#
# id: https://w3id.org/foo/demo-schema
# description: bad
# license: MIT

import dataclasses
import re
from jsonasobj2 import JsonObj, as_dict
from typing import Optional, List, Union, Dict, ClassVar, Any
from dataclasses import dataclass
from linkml_runtime.linkml_model.meta import EnumDefinition, PermissibleValue, PvFormulaOptions

from linkml_runtime.utils.slot import Slot
from linkml_runtime.utils.metamodelcore import empty_list, empty_dict, bnode
from linkml_runtime.utils.yamlutils import YAMLRoot, extended_str, extended_float, extended_int
from linkml_runtime.utils.dataclass_extensions_376 import dataclasses_init_fn_with_kwargs
from linkml_runtime.utils.formatutils import camelcase, underscore, sfx
from linkml_runtime.utils.enumerations import EnumDefinitionImpl
from rdflib import Namespace, URIRef
from linkml_runtime.utils.curienamespace import CurieNamespace
from linkml_runtime.linkml_model.types import String, Uriorcurie
from linkml_runtime.utils.metamodelcore import URIorCURIE

metamodel_version = "1.7.0"
version = None

# Overwrite dataclasses _init_fn to add **kwargs in __init__
dataclasses._init_fn = dataclasses_init_fn_with_kwargs

# Namespaces
PATO = CurieNamespace('PATO', 'http://purl.obolibrary.org/obo/PATO_')
DEMO_SCHEMA = CurieNamespace('demo_schema', 'https://w3id.org/foo/demo-schema/')
LINKML = CurieNamespace('linkml', 'https://w3id.org/linkml/')
SCHEMA = CurieNamespace('schema', 'http://schema.org/')
DEFAULT_ = DEMO_SCHEMA


# Types

# Class references
class NamedThingId(URIorCURIE):
    pass


class PersonId(NamedThingId):
    pass


class PetId(NamedThingId):
    pass


@dataclass
class NamedThing(YAMLRoot):
    """
    A generic grouping for any identifiable entity
    """
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = SCHEMA["Thing"]
    class_class_curie: ClassVar[str] = "schema:Thing"
    class_name: ClassVar[str] = "NamedThing"
    class_model_uri: ClassVar[URIRef] = DEMO_SCHEMA.NamedThing

    id: Union[str, NamedThingId] = None
    name: Optional[str] = None
    description: Optional[str] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self._is_empty(self.id):
            self.MissingRequiredField("id")
        if not isinstance(self.id, NamedThingId):
            self.id = NamedThingId(self.id)

        if self.name is not None and not isinstance(self.name, str):
            self.name = str(self.name)

        if self.description is not None and not isinstance(self.description, str):
            self.description = str(self.description)

        super().__post_init__(**kwargs)


@dataclass
class Person(NamedThing):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = DEMO_SCHEMA["Person"]
    class_class_curie: ClassVar[str] = "demo_schema:Person"
    class_name: ClassVar[str] = "Person"
    class_model_uri: ClassVar[URIRef] = DEMO_SCHEMA.Person

    id: Union[str, PersonId] = None
    pet: Optional[Union[str, PetId]] = None
    vital_status: Optional[Union[str, "VitalStatus"]] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self._is_empty(self.id):
            self.MissingRequiredField("id")
        if not isinstance(self.id, PersonId):
            self.id = PersonId(self.id)

        if self.pet is not None and not isinstance(self.pet, PetId):
            self.pet = PetId(self.pet)

        if self.vital_status is not None and not isinstance(self.vital_status, VitalStatus):
            self.vital_status = VitalStatus(self.vital_status)

        super().__post_init__(**kwargs)


@dataclass
class Pet(NamedThing):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = DEMO_SCHEMA["Pet"]
    class_class_curie: ClassVar[str] = "demo_schema:Pet"
    class_name: ClassVar[str] = "Pet"
    class_model_uri: ClassVar[URIRef] = DEMO_SCHEMA.Pet

    id: Union[str, PetId] = None
    vital_status: Optional[Union[str, "VitalStatus"]] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self._is_empty(self.id):
            self.MissingRequiredField("id")
        if not isinstance(self.id, PetId):
            self.id = PetId(self.id)

        if self.vital_status is not None and not isinstance(self.vital_status, VitalStatus):
            self.vital_status = VitalStatus(self.vital_status)

        super().__post_init__(**kwargs)


@dataclass
class PersonCollection(YAMLRoot):
    """
    A holder for Person objects
    """
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = DEMO_SCHEMA["PersonCollection"]
    class_class_curie: ClassVar[str] = "demo_schema:PersonCollection"
    class_name: ClassVar[str] = "PersonCollection"
    class_model_uri: ClassVar[URIRef] = DEMO_SCHEMA.PersonCollection

    entries: Optional[Union[Dict[Union[str, PersonId], Union[dict, Person]], List[Union[dict, Person]]]] = empty_dict()

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        self._normalize_inlined_as_dict(slot_name="entries", slot_type=Person, key_name="id", keyed=True)

        super().__post_init__(**kwargs)


# Enumerations
class VitalStatus(EnumDefinitionImpl):

    ALIVE = PermissibleValue(
        text="ALIVE",
        description="is living",
        meaning=PATO["0001421"])
    DEAD = PermissibleValue(
        text="DEAD",
        description="is deceased",
        meaning=PATO["0001422"])
    UNKNOWN = PermissibleValue(
        text="UNKNOWN",
        description="is not known")

    _defn = EnumDefinition(
        name="VitalStatus",
    )

# Slots
class slots:
    pass

slots.id = Slot(uri=SCHEMA.identifier, name="id", curie=SCHEMA.curie('identifier'),
                   model_uri=DEMO_SCHEMA.id, domain=None, range=URIRef)

slots.name = Slot(uri=SCHEMA.name, name="name", curie=SCHEMA.curie('name'),
                   model_uri=DEMO_SCHEMA.name, domain=None, range=Optional[str])

slots.description = Slot(uri=SCHEMA.description, name="description", curie=SCHEMA.curie('description'),
                   model_uri=DEMO_SCHEMA.description, domain=None, range=Optional[str])

slots.vital_status = Slot(uri=DEMO_SCHEMA.vital_status, name="vital_status", curie=DEMO_SCHEMA.curie('vital_status'),
                   model_uri=DEMO_SCHEMA.vital_status, domain=None, range=Optional[Union[str, "VitalStatus"]])

slots.pet = Slot(uri=DEMO_SCHEMA.pet, name="pet", curie=DEMO_SCHEMA.curie('pet'),
                   model_uri=DEMO_SCHEMA.pet, domain=None, range=Optional[Union[str, PetId]])

slots.personCollection__entries = Slot(uri=DEMO_SCHEMA.entries, name="personCollection__entries", curie=DEMO_SCHEMA.curie('entries'),
                   model_uri=DEMO_SCHEMA.personCollection__entries, domain=None, range=Optional[Union[Dict[Union[str, PersonId], Union[dict, Person]], List[Union[dict, Person]]]])
```

</details>

**Expected behavior**
A person is instantiated with the nested `Pet` attached.

**About your computer (if applicable, please complete the following information):**
 - OS: ubuntu 22.04
 - linkml-runtime: 1.6.3
 
 **Additional context**
