### ISSUE TITLE
`linkml-jsonschema-validate` fails to hande/recognize `datetime` 

### ISSUE THREAD

**Issue by mih** [linkml/linkml#1806]
I get `datetime.datetime(2023, ... tzinfo=datetime...) is not of type 'string'` from `linkml-jsonschema-validate`, and I believe I should not.

Here is a reproducer schema and data:

`miniprov.yaml`
```yaml
id: https://example.com/miniprov
name: miniprov
prefixes:
  mp: https://example.com/miniprov/
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_prefix: mp

slots:
  ended_at:
    range: datetime

classes:
  Activity:
    slots:
      - ended_at
```

`miniprov_activity.yaml`
```yaml
ended_at: 2023-12-23T22:26:04+01:00
```

Produce the error:

```
❯ linkml-jsonschema-validate -s miniprov.yaml miniprov_activity.yaml -C Activity
✗ datetime.datetime(2023, 12, 23, 22, 26, 4, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600))) is not of type 'string' in $.ended_at
```

At the same time

```
❯ linkml-convert -t rdf --validate -s miniprov.yaml miniprov_activity.yaml
@prefix mp: <https://example.com/miniprov/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

[] a mp:Activity ;
    mp:ended_at "2023-12-23T22:26:04+01:00"^^xsd:dateTime .

❯ linkml-convert -t json --validate -s miniprov.yaml miniprov_activity.yaml
{
  "ended_at": "2023-12-23T22:26:04+01:00",
  "@type": "Activity"
}
```

I would expect JSON schema based validation to pass on this data file.

```
❯ linkml-jsonschema-validate -V
linkml-jsonschema-validate, version 1.6.7
```
