### ISSUE TITLE
In autogenerated enumeration documentation, the hierarchy of permissible values is absent

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#1816]
In linkml_runtime.schemaview, it would be nice to have a method like `sv.class_hierarchy_as_tuples()` for permissible values in an enumeration so that I can generate a hierarchy view of permissible values on enumeration pages like this one: 
https://biolink.github.io/biolink-model/ChemicalOrGeneOrGeneProductFormOrVariantEnum/

```
permissible_values:
  genetic_variant_form:
    text: genetic_variant_form
    is_a: modified_form
  modified_form:
    text: modified_form
  loss_of_function_variant_form:
    text: loss_of_function_variant_form
    is_a: genetic_variant_form
  gain_of_function_variant_form:
    text: gain_of_function_variant_form
    is_a: genetic_variant_form
  polymorphic_form:
    text: polymorphic_form
    is_a: genetic_variant_form
  snp_form:
    text: snp_form
    is_a: polymorphic_form
  analog_form:
    text: analog_form
    is_a: modified_form
```

• Medium - can do work without it, but it's important (e.g. to save time or for convenience)
