### ISSUE TITLE
a mixin class with no is_a parent and no slots nor attributes should not have slot_usage

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#1817]
given this mixin class definition:

```
name: model to disease association mixin
description: This mixin is used for any association class for which the subject (source
  node) plays the role of a 'model', in that it recapitulates some features of the
  disease in a way that is useful for studying the disease outside a patient carrying
  the disease
from_schema: https://w3id.org/biolink/biolink-model
mixin: true
slot_usage:
  subject:
    name: subject
    description: The entity that serves as the model of the disease. This may be an
      organism, a strain of organism, a genotype or variant that exhibits similar
      features, or a gene that when mutated exhibits features of the disease
  predicate:
    name: predicate
    description: The relationship to the disease
    domain_of:
    - predicate mapping
    - association
    subproperty_of: model of
```

Expected: 
```
validation error: subject not in `slots`, nor `attributes`, nor inherited from any class or mixin ancestors.
```
Actual: 
```
SMoxon@SMoxon-M82 biolink-model % poetry run linkml-validate -s biolink-model.yaml
No issues found
```

The linter does find this issue:
```
SMoxon@SMoxon-M82 biolink-model % poetry run linkml-lint biolink-model.yaml
  error    Slot 'subject' not found on class 'model to disease association mixin'  (no_invalid_slot_usage)
```
