### ISSUE TITLE
Can't create class when same-named class existed in imported schema

### ISSUE THREAD

**Issue by sneakers-the-rat** [linkml/linkml#1825]
**Describe the bug**
When there exists some class in an imported schema, one cannot make a class with the same name in the current schema.

Eg. 

`imported.yaml`
```yaml
classes:
  Object:
    slot:
     - slot1
     - slot2
     # ...
```

`current.yaml`
```yaml
imports:
- imported

classes:
  Object:
    slot:
      - slot1
      - slot2
      - slot3
      # ...
```

The resulting generated code and schema classes will just by the original `imported.yaml` definition, even when the `current.yaml` definition doesn't specify that it is a subclass.

This seems to be inconsistent across generators, as I am able to generate a json-ld context, but can't make a graphql schema, which fails because `slot1` and `slot2` are not defined in the `current.yaml` schema (though they are in `imported.yaml`). 

**Expected behavior**

Between this and some prior issues (eg. https://github.com/linkml/linkml/issues/1228#issuecomment-1712390959 ) I suspect some information leakage in the schemaview class - the expected behavior here is basically that the imported class would be fully "compiled" and then passed into the current schema's context, which then updates any received values. Each imported schema's "compilation" process should be fully independent from each others, merely receiving imported schemas as prepopulated class/slot/etc. definitions. That this doesn't happen makes me suspect that information is leaking between each schema's "compilation", or else the update logic is incorrect. Haven't read myself yet.

 - `linkml_runtime`: 1.6.3

**Additional context**
Seems related to:
- https://github.com/linkml/linkml/issues/1730
- https://github.com/linkml/linkml/issues/1349
- https://github.com/linkml/linkml/issues/584
