### ISSUE TITLE
Protobuf generator generates dubious output

### ISSUE THREAD

**Issue by ielis** [linkml/linkml#1832]
**Describe the bug**

LinkML generates Protocol Buffers with `proto3` syntax. The syntax prescribes that field numbers must be [unique](https://protobuf.dev/programming-guides/proto3/#assigning) among all fields of that message. However, the LinkML output sets all field numbers to `0`.

**To reproduce**

Start with the person info example:
```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:                                 
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
  personinfo: https://w3id.org/linkml/examples/personinfo/
  ORCID: https://orcid.org/
imports:
  - linkml:types
default_range: string
  
classes:
  Person:
    class_uri: schema:Person             
    slots:   ## specified as a list
     - id
     - full_name
     - aliases
     - phone
     - age
    id_prefixes:
      - ORCID
  Container:
    attributes:
      persons:
        multivalued: true
        inlined_as_list: true
        range: Person

# slots are first-class entities in the metamodel
# declaring them here allows them to be reused elsewhere
slots:
  id:
    identifier: true
  full_name:
    required: true
    description:
      name of the person
    slot_uri: schema:name
  aliases:
    multivalued: true
    description:
      other names for the person
  phone:
    pattern: "^[\\d\\(\\)\\-]+$"
    slot_uri: schema:telephone 
  age:
    range: integer
    minimum_value: 0
    maximum_value: 200

```

Next, generate the proto files:
```shell
gen-proto personinfo.yaml | less
```

which produces the following output:
```
syntax="proto3";
 package
// metamodel_version: 1.7.0
message Container
 {
 repeated  person persons = 0
 }
message Person
 {
  string id = 0
  string fullName = 0
 repeated  string aliases = 0
  string phone = 0
  integer age = 0
 }
```

**Expected behavior**
The fields should be set with unique numbers.
