### ISSUE TITLE
Self-describing datasets - a Container class that adheres to a schema

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#1833]
**Is your feature request related to a problem? Please describe.**
Not a problem, rather an "intelligent" feature.

The Person+Organization [tutorial](https://github.com/linkml/linkml/blob/main/examples/PersonSchema/data/example_personinfo_data.yaml) shows how to set up a Container class to store corresponding data as a json file containing a json object with two keys. Below I show a schema with a Container having GRDI_Samples and AMR_Tests as array of rows of such objects.  The question is, how best within this file to add a reference to the schema (& version) that this file adheres to?  Via a “schema: …” and “version: …” attributes?  Or has someone already defined what a self-identifying data package adhering to a schema should look like visa vis the Container class?

The general use-case is that DataHarmonizer will be able to know what schema to load when confronted with a file containing Container data conforming to that schema.

**How important is this feature?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**

Example schema showing data for two classes to be stored in a json data file as array of rows (like Person, Organization) combo:

```
id: https://example.com/GRDI
name: GRDI
description: ''
version: 8.9.8
imports:
- linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
  GENEPIO: http://purl.obolibrary.org/obo/GENEPIO_
classes:
  GRDI_Sample:
    description: Specification for GRDI virus biosample data gathering
    …

  AMR_Test:
      description: Antimicrobial test result
      …

  Container:
      tree_root: true
      attributes:
        schema: 
          range: uri
        version: 
          range: string
        GRDI_Samples:
          range: GRDI_Sample
          multivalued: true
          inlined_as_list: true
        AMR_Tests:
          range: AMR_Test
          multivalued: true
          inlined_as_list: true
```

Data file would look something like:

```
{
  schema: https://example.com/GRDI
  version: 8.9.8
  “GRDI_Samples”: [
    {“Sample_ID”:1, … },
    {“Sample_ID”:2, … },
  ],
  “AMR_Tests”: [
    {“Sample_ID”:1, “antimicrobial_resistance_test_drug”:“ampicillin”, … },
    {“Sample_ID”:1, “antimicrobial_resistance_test_drug”:“cefoxitin”, … },
  ],
}

```
