### ISSUE TITLE
gen-owl warns about `equals_string` from rules

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#1855]
> `WARNING:root:ignoring equals_string=pass as unable to tell if literal`

**Comment by pkalita-lbl** [comment]
Hi @turbomam can you provide steps to reproduce this warning and let us know why you think the warning was issued incorrectly?

**Comment by Angatar** [comment]
Same for equals_string_in ... example from the test file [linkml]https://raw.githubusercontent.com/linkml/linkml/2fdf8b38b9049e3fa2ca726d1596a3c53d5e9c5f/tests/test_generators/input/kitchen_sink.yaml

```YAML
  EqualsStringIn:
    attributes:
      attribute6:
        equals_string_in:
          - "foo"
          - "bar"
```
gen-owl is ignoring the equals_string_in with the warning:
```
WARNING:linkml.generators.owlgen:ignoring equals_string=['foo', 'bar'] as unable to tell if literal
```
