### ISSUE TITLE
gen-python generates classes in wrong order in some cases

### ISSUE THREAD

**Issue by kervel** [linkml/linkml#1857]
**Describe the bug**

When there are multiple schema's refering to each other, it is possible to generate syntactically incorrect python. For instance:

**To reproduce**

machine.yaml:

```yaml
id: https://w3id.org/a
name: m
title: m

prefixes:
  mdm: https://a/mdm/
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
default_prefix: mdm
default_range: string

imports:
  - linkml:types
  - ./equipment


classes:
    Machine:
      is_a: Equipment


    Container:
        tree_root: true
        attributes:
            machines:
                multivalued: true
                inlined_as_list: true
                range: Machine
```

equipment.yaml

```yaml
id: b
name: b
title: b

prefixes:
  mm: https://b/
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
default_prefix: mm
default_range: string

imports:
  - linkml:types

classes:
  Equipment:
    description:
      An individually identifiable piece of equipment
```

now `gen-python machine.yaml` generates python that is not correct. The reason is that the type hints in the `Container` class refer to a `Machine` which is only defined later. The fix is simple (quoting the type hints).

**Expected behavior**

The generated python compiles

**About your computer (if applicable, please complete the following information):**
 - OS: Linux ubuntu 22.04
 - Version Linkml 1.6.10

cc @vdwpsmt
