### ISSUE TITLE
specifying `default_prefix:` prevents `gen-jsonld-context` from emitting classes

### ISSUE THREAD

**Issue by tgbugs** [linkml/linkml#1881]
**Describe the bug**
specifying `default_prefix:` prevents `gen-jsonld-context` from emitting classes

**To reproduce**
``` yaml
id: https://sparc.olympiangods.org/sparcur/schemas/1/sparc
title: sparc export schema
name: sparc-linkml
imports:
  - linkml:types

default_prefix: sparc  # uncomment this line to get default behavior

prefixes:
  linkml: https://w3id.org/linkml/
  sparc: http://uri.interlex.org/tgbugs/uris/readable/sparc/

classes:
  Thing:

slots:
  # manual
  id:
  label:
    slot_uri: rdfs:label

```
run `gen-jsonld-context` and `Thing` will not be included.

**Expected behavior**
Should generate jsonld context with `Thing`
