### ISSUE TITLE
Unexpected behaviour involving JSON-Schema generation, importing another LinkML file and the `default_range` slot.

### ISSUE THREAD

**Issue by paulmillar** [linkml/linkml#1896]
To be honest, I'm not sure whether or not this is a bug.  In any case, the behaviour was a surprise to me.

**Describe the bug**

LinkML supports the `default_range` top-level slot that provides the `range` value for attributes that do not define this slot explicitly.

LinkML also supports the `imports` top-level slot as a way to compose definitions from different files.

What was a surprise is that, if the imported file has attributes defined without `range` slot (so taking the `default_range`) then the resolution takes place _after_ the import; i.e., within the context of the LinkML file that doing the importing.

**To reproduce**

Consider this file, called `example-class.yaml`:

```yaml
id: https://example.org/metadata1
name: example1
title: "Target class"
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  ExampleClass:
    description: An illustration of a problem
    attributes:
      foo:
        description: Measuring the foo
```

Note that this file defines the attribute `foo` that does not define a `range`.  Therefore, this attribute will use the `default_range` value of `string`.

The `gen-json-schema` command, when targeting `example-class.yaml`,  provides the following JSON-Schema:

```json
{
    "$defs": {
        "ExampleClass": {
            "additionalProperties": false,
            "description": "An illustration of a problem",
            "properties": {
                "foo": {
                    "description": "Measuring the foo",
                    "type": "string"
                }
            },
            "title": "ExampleClass",
            "type": "object"
        }
    },
    "$id": "https://example.org/metadata1",
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "title": "example1",
    "type": "object",
    "version": null
}
```

Note that the `"type": "string"` declaration within the `foo` property description.

Consider the LinkML definition file `example-container-1.yaml` with the following contents:

```yaml
id: https://example.org/metadata2
name: example2
title: "Example importer"
imports:
  - example-class
```

Running the `gen-json-schema` command, targeting `example-container-1.yaml`, will produce the following JSON-Schema:

```json
{
    "$defs": {
        "ExampleClass": {
            "additionalProperties": false,
            "description": "An illustration of a problem",
            "properties": {
                "foo": {
                    "description": "Measuring the foo"
                }
            },
            "title": "ExampleClass",
            "type": "object"
        }
    },
    "$id": "https://example.org/metadata2",
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "title": "example2",
    "type": "object",
    "version": null
}
```

Note that the JSON-Schema now defines the `foo` property without the `"type": "string"` declaration.

This is valid JSON-Schema, but it means the value is unconstrained -- which is not the anticipated result.

The behaviour is different if the importing file contains a `default_range` top-level slot.  Consider the `example-container-2.yaml` file with the following contents.

```yaml
id: https://example.org/metadata2
name: example2
title: "Example importer"
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
  - example-class
default_range: string
```

The `example-container-2.yaml` is almost the same as `example-container-1.yaml`.  The difference is that `example-container-2.yaml`  defines the `default_range` top-level slot.

The `gen-json-schema` command, targeting `example-container-2.yaml` provides the desired JSON-Schema:

```json
{
    "$defs": {
        "ExampleClass": {
            "additionalProperties": false,
            "description": "An illustration of a problem",
            "properties": {
                "foo": {
                    "description": "Measuring the foo",
                    "type": "string"
                }
            },
            "title": "ExampleClass",
            "type": "object"
        }
    },
    "$id": "https://example.org/metadata2",
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "title": "example2",
    "type": "object",
    "version": null
}
```

**Expected behavior**

I had expected the process of identifying an attribute's range (i.e., using the `default_range` top-level slot) to take place within the context of the file within which that attribute is defined.

Put another way, `example-container-1.yaml` and `example-container-2.yaml` both define no attributes.  Therefore, I would have expected the presence or absence of `default_range` top-level slot to have no effect: gen-json-schema should produce the same output when targeting either of these files.
