### ISSUE TITLE
gen-sqlddl generates tables for abstract classes

### ISSUE THREAD

**Issue by bendichter** [linkml/linkml#1902]
**Describe the bug**

Currently, `gen-sqlddl` outputs abstract classes to the DDL as tables that can be written to. For example, `gen-sqlddl slot-usage-example.yaml` for the yaml file (taken from the tutorial):

```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:                                 
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string
  
classes:
  NamedThing:
    slots: 
     - id
     - full_name
  Person:
    is_a: NamedThing
    attributes:
      has_familial_relationships:
        multivalued: true
        range: FamilialRelationship
        inlined_as_list: true
      has_organizational_relationships:
        multivalued: true
        range: OrganizationalRelationship
        inlined_as_list: true
    
  Organization:
    is_a: NamedThing

  Relationship:
    abstract: true
    attributes:
      duration:
        range: integer
      related_to:
        range: NamedThing
      relationship_type:

  FamilialRelationship:
    is_a: Relationship
    slot_usage:
      related_to:
        range: Person
        required: true
      relationship_type:
        range: FamilialRelationshipType
      

  OrganizationalRelationship:
    is_a: Relationship
    slot_usage:
      related_to:
        range: Organization
        required: true
      relationship_type:
        range: OrganizationalRelationshipType

  Container:
    attributes:
      persons:
        multivalued: true
        inlined_as_list: true
        range: Person
      organizations:
        multivalued: true
        inlined_as_list: true
        range: Organization

slots:
  id:
    identifier: true
  full_name:
  related_to:
  relationship_type:

enums:
  FamilialRelationshipType:
    permissible_values:
      SIBLING_OF:
      PARENT_OF:
      CHILD_OF:
  OrganizationalRelationshipType:
    permissible_values:
      EMPLOYED_BY:
      FOUNDED_BY:
      LEADER_OF:
      MEMBER_OF:
```

generates 

```
$ gen-sqlddl slot-usage-example.yaml 
-- # Class: "NamedThing" Description: ""
--     * Slot: id Description: 
--     * Slot: full_name Description: 
-- # Class: "Person" Description: ""
--     * Slot: id Description: 
--     * Slot: full_name Description: 
--     * Slot: Container_id Description: Autocreated FK slot
-- # Class: "Organization" Description: ""
--     * Slot: id Description: 
--     * Slot: full_name Description: 
--     * Slot: Container_id Description: Autocreated FK slot
-- # Class: "Relationship" Description: ""
--     * Slot: id Description: 
--     * Slot: duration Description: 
--     * Slot: related_to Description: 
--     * Slot: relationship_type Description: 
-- # Class: "FamilialRelationship" Description: ""
--     * Slot: id Description: 
--     * Slot: duration Description: 
--     * Slot: related_to Description: 
--     * Slot: relationship_type Description: 
--     * Slot: Person_id Description: Autocreated FK slot
-- # Class: "OrganizationalRelationship" Description: ""
--     * Slot: id Description: 
--     * Slot: duration Description: 
--     * Slot: related_to Description: 
--     * Slot: relationship_type Description: 
--     * Slot: Person_id Description: Autocreated FK slot
-- # Class: "Container" Description: ""
--     * Slot: id Description: 

CREATE TABLE "NamedThing" (
	id TEXT NOT NULL, 
	full_name TEXT, 
	PRIMARY KEY (id)
);
CREATE TABLE "Container" (
	id INTEGER NOT NULL, 
	PRIMARY KEY (id)
);
CREATE TABLE "Person" (
	id TEXT NOT NULL, 
	full_name TEXT, 
	"Container_id" TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY("Container_id") REFERENCES "Container" (id)
);
CREATE TABLE "Organization" (
	id TEXT NOT NULL, 
	full_name TEXT, 
	"Container_id" TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY("Container_id") REFERENCES "Container" (id)
);
CREATE TABLE "Relationship" (
	id INTEGER NOT NULL, 
	duration INTEGER, 
	related_to TEXT, 
	relationship_type TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(related_to) REFERENCES "NamedThing" (id)
);
CREATE TABLE "FamilialRelationship" (
	id INTEGER NOT NULL, 
	duration INTEGER, 
	related_to TEXT NOT NULL, 
	relationship_type VARCHAR(10), 
	"Person_id" TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(related_to) REFERENCES "Person" (id), 
	FOREIGN KEY("Person_id") REFERENCES "Person" (id)
);
CREATE TABLE "OrganizationalRelationship" (
	id INTEGER NOT NULL, 
	duration INTEGER, 
	related_to TEXT NOT NULL, 
	relationship_type VARCHAR(11), 
	"Person_id" TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(related_to) REFERENCES "Organization" (id), 
	FOREIGN KEY("Person_id") REFERENCES "Person" (id)
);
```
which creates a Relationship table despite the fact that the "Relationship" class is abstract. I think a more correct behavior would be to skip the creation of tables that correspond to abstract classes. 

This has come up as an issue in #1901
