### ISSUE TITLE
Possibility for deterministic order of multivalue slots in RDF output?

### ISSUE THREAD

**Issue by mih** [linkml/linkml#1943]
I have a schema that defines a class with this component:

```
   slot_usage:
      qualified_part:
        inlined: true
        inlined_as_list: true
        multivalued: true
   ...
```

A corresponding data items has

```
    qualified_part:
      - at_location: subdir/README.txt
        relation: gitsha:56094a33cf330fef5b375aa813fc4dc07147729f
      - at_location: subdir/data.bin
        relation: gitsha:b94ef1797f7bfc1ac979be122e1b538bbb0d1d58
```

When I convert this data from YAML to JSON, the output is deterministic. When I convert to RDF, the order of the `qualified_part` declarations is random.

This leads to noise, and is particularly problematic when version-controlling the output, due to the random changes that are introduced, even when there is no relevant change.

I understand that the order here is insignificant from a modeling/validation/content perspective. However, from a technical angle it matters (to me).

----

I now verified that the order of call to `Graph.add()` in `linkml_runtime/dumpers/rdflib_dumper.py:inject_triples()` is indeed deterministic, while the actual dump is in random order. It appears this is either an RDFlib limitation, or a problem in how RDFlib is being used by linkml.
