### ISSUE TITLE
Allow representation of denormalized classes and derived slots

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#195]
consider the following normalized schema:

```yaml
classes:
  gene:
    slots:
      - id
      - name
      - category
  phenotype:
    slots:
      - id
      - name
      - category
  gene to phenotype association:
    slots:
      - gene ## range: Gene
      - phenotype ## range: Phenotype
```

slot definitions omitted for brevity but you can see the basic idea, we have two entities and a linking class

Now consider a different schema with a denormalized representation:

```yaml
classes:
  flat gene to phenotype association:
    slots:
      - gene_id
      - gene_name
      - gene_category
      - phenotype_id
      - phenotype_name
      - phenotype_category
```

This denormalized representation is useful for many purposes:

 - formalizing the headers in an excel file or google sheet
 - loading into a store such as solr
 - optimized for read SQL storage
 - use with data science tools and formats, pandas/scikit-learn/bigtable/...
 - end user presentation

I would like to be able to formally represent the connection between the two. This supports a range of use cases, including:

 - autogeneration of normalize/denormalize SQL transforms
 - supporting intelligent grouping of columns on denormalized form for visual presentation
 - autogeneration of property chains in OWL
 - autogeneration of rules
 - intelligent transforms in python runtime

The simplest way to do this may be to have a dedicated slot for representing how to derive a denormalized representation:

```yaml
classes:
  flat gene to phenotype association:
    inference:
      denormalized_from_of: gene to phenotype association
      derivations:
        - derived: gene_id
           follows: gene
           base_slot: id
        - derived: gene_name
           follows: gene
           base_slot: name
        ...
        - derived: phenotype_id
           follows: phenotype
           base_slot: id
        - derived: phenotype_name
           follows: phenotype
           base_slot: name
```

(we can imagine tooling that could auto-derived denormalized schemas based on a configuration...)

this could serve as the basis for deriving SQL commands or VIEW definitions, e.g.

```sql
INSERT INTO GeneToPhenotypeAssociationFlat 
SELECT (gene.id AS gene_id, gene.name AS gene.name, ..., phenotype.id AS phenotype_id, ...)
FROM gene JOIN GeneToPhenotypeAssociation JOIN phenotype WHERE
 (gene.id = GeneToPhenotypeAssociation.gene) AND
 (phenotype.id = GeneToPhenotypeAssociation.phenotype)
```

also RDF rules such as:

```turtle
[ a GeneToPhenotypeAssociation ;
     gene ?gene_id ;
     phenotype ?phenotype_id  ] .
[?gene_id name ?gene_name ;
                  category ?gene_category ] .
[?phenotype_id name ?phenotype_name ;
                  category ?phenotype_category ] 
->
[ a FlatGeneToPhenotypeAssociation ;
     gene_id ?gene_id ;
     gene_name ?gene_name ;
     phenotype_id ?phenotype_id ;
    ...
 ] .
```

I don't think this would autogenerate additional python; instead the python runtime could support operations such as

```python
g2p = GeneToPhenotypeAssocation(...)
flat_g2p = linkml.inference.derive_denormalized_instance(g2p, FlatGeneToPhenotypeAssociation)
```

This would also support the use case where there is no separate denormalized table, but denormalized fields are incorporated into a table, e.g

```
classes:
  employee:
    slots: ['id', 'name', 'employer', 'employer_name']
    inference:
      derivations:
         employer_name:
           follows: employer
           base_slot: name
```

Some things that would not be supported:

 - nesting; but intermediate denormalizations can always be named
 - arbitrary transformations, e.g. `len = end-start`

Some of these may be in scope for a linkml rule language, but the basic denormalization use case is so common it would be useful to have in the language.
