### ISSUE TITLE
External Namespace Support

### ISSUE THREAD

**Issue by vincentkelleher** [linkml/linkml#1950]
Hi 👋 

## Our case

We are using LinkML to describe our Gaia-X ontology to then generate Shacl shapes, Json-LD contexts, OWL files and others to come.

As many concepts already exist in other ontology namespaces, we are planning on reusing existing elements. For example, we have a `gx:Address` which describes a physical location's address, this is planned to be a child (inheritance wise) of a [VCard Address](http://www.w3.org/2006/vcard/ns#) (http://www.w3.org/2006/vcard/ns#Address) with an extra `gx:countryCode` attribute representing an ISO-3166-1 country code.

LinkML provides the [`is_a:` directive](https://linkml.io/linkml/schemas/inheritance.html#mixin-classes-and-slots) which corresponds perfectly to our needs but this causes the following error message to appear when using generators.

> ValueError: File "address.yaml", line 16, col 11 Class: "Address" - unknown is_a reference: vcard:Address

## LinkML Sample

The following example should illustrate how we plan to use external namespace inheritance. This example is simplified to avoid unnecessary complexity.

```yaml
id: https://w3id.org/gaia-x/development/address
name: address
prefixes:
  gx: https://w3id.org/gaia-x/development/
  linkml: https://w3id.org/linkml/
  vcard: http://www.w3.org/2006/vcard/ns#
  xsd: http://www.w3.org/2001/XMLSchema#
  schema: http://schema.org/
imports:
  - linkml:types

classes:
  Address:
    is_a: vcard:Address
    description: Full address of the entity.
    attributes:
      countryCode:
        description: Country code in ISO 3166-1 alpha2 format.
        required: true
        range: string
```

## Shacl Shape Definition

To add some context to this improvement, we are looking to generate a Shacl shape that would be close to the following.

```turtle
gx:Address a <http://www.w3.org/2006/vcard/ns#Address> ;
    sh:description "Full address of the entity." ;
    sh:property [ sh:datatype xsd:string ;
            sh:description "Country code in ISO 3166-1 alpha2 format." ;
            sh:maxCount 1 ;
            sh:minCount 1 ;
            sh:order 0 ;
            sh:path gx:countryCode ] ;
    sh:targetClass gx:Address .
```

## Feature Relevance

This feature is a blocker in our case as we can't generate our ontology and it is relevant at this time.

I'm aware of the maintenance cost of an Open Source project as it's my full-time job right now and I'm willing to help the LinkML project to evolve as it is used in the [Gaia-X Service Characteristics Working Group](https://gitlab.com/gaia-x/technical-committee/service-characteristics). I raised this issue to make sure that my request was feasible and relevant, not only an isolated case.

I think that being able to reuse existing ontologies is an important feature 😃
