### ISSUE TITLE
Add support for multivalue tree_root classes

### ISSUE THREAD

**Issue by paulmillar** [linkml/linkml#1960]
**Is your feature request related to a problem? Please describe.**

I am trying to model data that simply a collection of items.  Here is a mock-up of the kind of structure:

```json
{
  "ID1": {
    "field1": "value1-1",
    "field2": [
      "list-item-1-1",
      "list-item-1-2"
    ]
  },
  "ID2": {
    "field1": "value2-1",
    "field2": [
      "list-item-2-1",
      "list-item-2-2"
    ]
  }
}
```

My first thought was to follow the example [from the tutorial](https://linkml.io/linkml/intro/tutorial02.html), describing each item with a class, identifying some ID slot as the identifier (`identifier: true`).  The problem comes with trying to define the container class, as (seemingly) there isn't one.

More generally, it seems that the LinkML metamodel requires that statements like `multivalued: true` and `inlined_as_list: false` apply only to slots and not to classes.  However, there doesn't seem to be any way to refer to the document root as a slot.

I'm not sure if this is helpful but, just for comparison, XPath [defines](https://www.w3.org/TR/1999/REC-xpath-19991116/#location-paths) `/` to be the document root, with a parent-child relationship with the first element in the XML infoset; for example, `/foo` is the XPath expression targeting the first element in the XML:
```xml
<?xml version="1.0" encoding="utf-8"?>
<foo>
    <bar/>
</foo>
```

**Describe the solution you'd like**

I'm new to LinkML, so it's possible that I've simply missed how to model data with repeated items.

If not, I suspect the LinkML metamodel would need to be extended to support this use-case.

One possible solution would be to introduce the concept of a slot (of some "document root" class, perhaps) that allows for slot-level attributes to describe the `tree_root` class.

Another would be to loosen the definition of `multivalue` (and related slots) to allow them to apply to the `tree_root` class.

There are probably other solutions.

I don't have any preference for any one solution over the others.

**How important is this feature?** Select from the options below:

I would say **Medium**.

For this particular use-case, the problem is awkward, but I can probably implement some kind of work-around.  The work-around would require a certain investment of time, though, and I'm not sure how much.

**When will use cases depending on this become relevant?** Select from the options below:
Short-term.

**Comment by paulmillar** [comment]
Just a quick update.

I've decided to restructure the data, so the list of items are now a field (a slot) within some new class, with this new class being the `tree_root`.

With this new structure, the data now fairly closely follows [the example](https://linkml.io/linkml/intro/tutorial02.html) shown in the tutorial.  The concepts and ideas described in the tutorial now work fine for data.

Therefore, the issue described here is no longer important for my specific use of LinkML.

Nevertheless, I believe this points to a valid use-case that (it looks like) LinkML currently doesn't support, so I would suggest leaving this issue open.

**Comment by cmungall** [comment]
I see, if I understand "ID1" and "ID2" are keys decided at runtime rather than slots.

 I think the original use case can be supported if we allow `tree_root` to apply to a slot, and also extend some of the tooling such that slots can be passed as tree_root.

This could also support the use case where a JSON file is a list at the top level, or even an atom

**Comment by sneakers-the-rat** [comment]
I'm sort of surprised that the loaders don't already handle this - i would assume that if one had data like in the OP, and the class had an `identifier` field, that it would be able to infer that the `ID1`, etc. field was that field?

**Comment by paulmillar** [comment]
Hi @sneakers-the-rat ,

I'm new to LinkML, so it's entirely possible I'm missing something.

That said, I tried to implement a model, trying to follow your comments.  Here is the result (`model.yaml`)

```yaml
id: https://example.org/linkml/issue-1960
name: issue1960
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  Item:
    description: An item
    tree_root: true
    attributes:
      id:
        description: unique identifier
        identifier: true
      field1:
        description: first field
      field2:
        description: second field
        multivalued: true
```

Taking the above data as `data.json`:

```json
{
  "ID1": {
    "field1": "value1-1",
    "field2": [
      "list-item-1-1",
      "list-item-1-2"
    ]
  },
  "ID2": {
    "field1": "value2-1",
    "field2": [
      "list-item-2-1",
      "list-item-2-2"
    ]
  }
}
```

Unfortunately, when I try to validate the data using the model, I see errors:

```console
(linkml) paul@monkeywrench:~/LinkML-1960$ linkml-validate -s model.yaml data.json 
[ERROR] [data.json/0] Additional properties are not allowed ('ID1', 'ID2' were unexpected) in /
[ERROR] [data.json/0] 'id' is a required property in /
(linkml) paul@monkeywrench:~/LinkML-1960$ 
```

**Comment by sneakers-the-rat** [comment]
right, ya the loader doesn't know to swap the field in there, and is also trying to pass that whole dict into the object instead each of the entries. Trying to see if i can make a hacky version of this work to see how hard it would be.

Here's a pair of commits in `linkml` and `linkml-runtime` that can load the [above example](https://github.com/linkml/linkml/issues/1960#issuecomment-1992538673)

- linkml: https://github.com/sneakers-the-rat/linkml/commit/34d50598f67a1eb1e43a9b3281ee83c605a80119
- linkml-runtime: https://github.com/sneakers-the-rat/linkml-runtime/commit/dfc6e342e2ea635981b494357976053b6c2c3574

So

```
linkml-convert -t csv -s ./model.yaml -C "Item"  --no-validate ./data.json
```

does

```csv
id,field1,field2,@type
ID1,value1-1,[list-item-1-1|list-item-1-2],Item
ID2,value2-1,[list-item-2-1|list-item-2-2],Item
```

This seems like behavior worth supporting, since we do have the `identifier` property, and needing to make a container class seems like a bit of a hack? This would be for instances where the target class is specified explicitly (as above) or when it can be inferred from something like `designates_type`, but then when an unambiguous container can't be identified we throw the same error.

The above commits are explicitly a hack, and the logic would need to be unified (eg. that was in `converter` but i'm not sure where else data is loaded, ideally we would have a single data loading routine to handle that, since the logic is split between the `converter` cli function and the loaders/dumpers). would be happy to PR with some guidance on where that would need to happen, since it seems like some refactoring is due anyway.

**Comment by rly** [comment]
@paulmillar Is it necessary to have the identifier as the key in your data JSON? An alternative approach would be to move the identifier into the dict and have a list of `Item` objects instead of a dict of `Item` objects. Then add a container class `ItemCollection` that has `tree_root: True` to contain those `Item` objects. (analogous to https://linkml.io/linkml/intro/tutorial02.html#nesting-lists-of-objects). For example:

```yaml
id: https://example.org/linkml/issue-1960
name: issue1960
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  Item:
    description: An item
    attributes:
      id:
        description: unique identifier
        identifier: true
      field1:
        description: first field
      field2:
        description: second field
        multivalued: true
  ItemCollection:
    tree_root: true
    attributes:
      items:
        range: Item
        multivalued: true
        inlined_as_list: true
```

data:
```json
{
    "items": [
        {
            "id": "ID1",
            "field1": "value1-1",
            "field2": [
                "list-item-1-1",
                "list-item-1-2"
            ]
        },
        {
            "id": "ID2",
            "field1": "value2-1",
            "field2": [
                "list-item-2-1",
                "list-item-2-2"
            ]
        }
    ]
}
```

Note: the `identifier: true` field is supposed to signal that the keys are unique, but the validator does not yet check for that (see https://github.com/linkml/linkml/issues/1542). 

re: @sneakers-the-rat 's idea in the last comment
> This seems like behavior worth supporting, since we do have the identifier property, and needing to make a container class seems like a bit of a hack?

I agree. It would be nice to not have to define the `ItemCollection` class and say that the tree root is a collection of `Item` objects, whether defined using identifier as dict key or within the dict.
