### ISSUE TITLE
skos:example is unexpectedly used in rdf translation of annotation extension tags and values

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#198]
Example:

```yaml
id: http://example.org/interval

default_curi_maps:
  - semweb_context

prefixes:
  ex: http://example.org/
  schema: http://schema.org/
  linkml: https://w3id.org/linkml/

imports:
  - linkml:types

default_prefix: ex

classes:

  c:
    annotations:
      - extension_tag: my_tag1
        extension_value: my_value1
      - extension_tag: my_tag2
        extension_value: my_value2
```

gen-rdf generates:

```turtle
<http://example.org/C> a linkml:ClassDefinition ;
    skos:inScheme <http://example.org/interval> ;
    linkml:annotations [ a linkml:Annotation ;
            skos:example "my_tag1" ;
            linkml:tag <http://example.org/extension_tag> ],
        [ a linkml:Annotation ;
            skos:example "my_value2" ;
            linkml:tag <http://example.org/extension_value> ],
        [ a linkml:Annotation ;
            skos:example "my_value1" ;
            linkml:tag <http://example.org/extension_value> ],
        [ a linkml:Annotation ;
            skos:example "my_tag2" ;
            linkml:tag <http://example.org/extension_tag> ] ;
    linkml:class_uri <http://example.org/C> ;
    linkml:definition_uri <http://example.org/C> .
```

is this intentional? Why skos:example?

Note also this generates **four** instances of Annotation, not two as expected. The associations between specific keys and specific values is lost
