### ISSUE TITLE
using "name" slot in in slot_usage

### ISSUE THREAD

**Issue by djarecka** [linkml/linkml#1988]
When working with schemasheet I noticed that I can't really use "name" slot in `slot_usage` (e.g. to add more specific  `description`). I believe this is removed in [schema_as_dict](https://github.com/linkml/linkml-runtime/blob/54036129f827f03ad28120f9bdffdfb4aac1d21d/linkml_runtime/utils/schema_as_dict.py#L70).

Is it really something wrong about using "name" in `slot_usage`?

**Comment by turbomam** [comment]
Interesting!

Can you give an example of when it would be beneficial to change the name of something (like the slot) in `slot_usage`?

In LinkML, `name`s function like primary keys. If you change the name, aren't you essentially creating a  new slot?

**Comment by rly** [comment]
I am also curious about this issue as per our recent meeting @djarecka .

I thought `alias` might help because it seemed like `alias` was supposed to be used as the attribute name after resolving `slot_usage` and so you can customize the name of a general property slot, but that doesn't seem to work (maybe that's a bug?). 

Given the contrived example schema:
```yaml
classes:
  LivingThing:
    slots:
      - age
  Person:
    is_a: LivingThing
    slot_usage:
      age:
        alias: age_in_y
        unit:
          ucum_code: a
        range: float
        description: age in years since birth
slots:
  age:
    minimum_value: 0
```

After running `gen-linkml linkml_alias_schema.yaml`, which should resolve induced slots and materialize attributes, I get this `Person` class definition:
```json
"Person": {
  "name": "Person",
  "from_schema": "https://w3id.org/slot-alias-test/",
  "is_a": "LivingThing",
  "slot_usage": {
    "age": {
      "name": "age",
      "description": "age in years since birth",
      "alias": "age_in_y",
      "domain_of": [
        "LivingThing"
      ],
      "range": "float",
      "unit": {
        "ucum_code": "a"
      }
    }
  },
  "attributes": {
    "age": {
      "name": "age",
      "description": "age in years since birth",
      "from_schema": "https://w3id.org/slot-alias-test/",
      "alias": "age_in_y",
      "owner": "Person",
      "domain_of": [
        "LivingThing"
      ],
      "range": "float",
      "minimum_value": 0,
      "unit": {
        "ucum_code": "a"
      }
    }
  }
}
```

The name of the attribute is still "age" as opposed to "age_in_y". 

And running `gen-python linkml_alias_schema.yaml`
results in: `ValueError:  Class: "Person" - alias not permitted in slot_usage slot: age_in_y`

maybe related: https://github.com/linkml/linkml/issues/1109
