### ISSUE TITLE
SQL schema generation fails for "complex" unique_key_slots

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2006]
**Describe the bug**
SQL schema generation fails on linkml v1.7.5 and v1.7.6 if the range of a "unique_key_slot" is an array or an object.

**To reproduce**
1. Create a schema with a slot which range is an array and enter that slot into `unique_key_slots`.
2. Run `gen-sqltable` or `gen-sqlddl` on the schema.
3. See error `sqlalchemy.exc.ConstraintColumnNotFoundError: Can't create UniqueConstraint on table 'MyClass': no column named 'my_slot' is present.`

**Expected behavior**
Successful SQL schema generation.

**Additional context**

According a `git bisect` the issue appeared on commit c5b908fe931cbd81ba4e7b7e08d11599f92921b3.

Error can be reproduced with following schema:
```
id: https://examples.org/my-schema
prefixes:
  linkml: https://w3id.org/linkml/
  myschema: https://examples.org/my-schema
imports:
  - linkml:types
default_prefix: myschema
default_range: string

classes:
  MyClass:
    slots:
      - my_slot
    unique_keys:
      identifier:
        unique_key_slots:
          - my_slot

slots:
  my_slot:
    multivalued: true
    range: string
```
