### ISSUE TITLE
problem generating enum in json schema

### ISSUE THREAD

**Issue by smrgeoinfo** [linkml/linkml#201]
I'm trying to have an enumerated list of terms as the value range for a property (slot) in my JSON schema. I must be missing something in my yaml schema description.

here's what's in in the yaml:

```
enums:
  materialtype:
    description: categories for kinds of material that constitute the sample 
    permissible_values:
      anyanthropogenicmaterial:
        text: anyanthropogenicmaterial
      anthropogenicmetal:
        text: anthropogenicmetal
      otheranthropogenicmaterial:
        text: otheranthropogenicmaterial
```
...
```
slots:		
  hasMaterialCategory:
    range: materialtype
    domain: PhysicalSampleRecord
    description: specify the kind of material that constitutes the sample
    multivalued: true		
```
....

The generated JSON schema:
		
```
            "hasMaterialCategory": {
               "description": "specify the kind of material that constitutes the sample",
               "items": {
                  "type": "string"
               },
               "type": "array"
            },
```
			
			
I expected 
... 
```
"items": {
                  "type": "string"
				  "enum": [
					"anyanthropogenicmaterial",
					"anthropogenicmetal",
					"otheranthropogenicmaterial"
				  ]
               },
```
