### ISSUE TITLE
Add tests and documentation on extending the metamodel

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#2015]
In some cases it may be desirable to extend the metamodel; for example, to make a subset of LinkML that is more restrictive (e.g. forces every class to have a description, adds new slots to schemas...).

One way to do this is to import the metamodel and add a `DerivedSchema` class, and possibly other derived elements (`slot_usage` can be used to e.g say that every class listed under `DerivedSchema` is a `DerivedClass`).

This approach my have limitations - the runtime comes with a baked version of meta.py that is used throughout (if this were in lisp we could do all kinds of runtime manipulations). However many parts of the toolchain such as validators operate generically over any model including an extended metamodel, so if the use cases is more restricted validation then this should work.

From slack, @Silvanoc reports this may be failing to validate as expected

```yaml
id: https://w3id.org/my-org/derived-schema-model
name: derived-schema-model

prefixes:
  derived_schema_model: https://example.org/derived-schema-model/
  linkml: https://w3id.org/linkml/
default_prefix: derived_schema_model
default_range: string

imports:
  - linkml:types
  - linkml:model

classes:
  DerivedSchema:
    is_a: SchemaDefinition
    slots:
      - base_schema_version

slots:
  base_schema_version:
    required: True
    range: string
    pattern: "^v\d+\.\d+$"
```
