### ISSUE TITLE
problem with Decimal data type

### ISSUE THREAD

**Issue by smrgeoinfo** [linkml/linkml#202]
I want the type in the JSON schema to be 'number', so in the YAML I've got

```
types:
  decimal:
    base: Decimal
    uri: xsd:decimal
```
slots:
```
  latitude:
    range: decimal
    domain: GeospatialDDCoordLocation
    description: angular coordinate measured positive north from the equator.
```

but in the JSON schema, the type for the property is coming up 

```
"latitude": {
               "description": "angular coordinate measured positive north from the equator.",
               "type": "string"
            },
```

Any suggestions on how to fix? thanks
