### ISSUE TITLE
Best practices validator

### ISSUE THREAD

**Issue by rly** [linkml/linkml#2025]
**Is your feature request related to a problem? Please describe.**
In LinkML there are sometimes multiple equivalent ways of specifying a schema, e.g., due to syntactic sugar. While I think LinkML should allow users to express schema however they want within the language, I think it would be nice to have an additional layer of standardization of schema that follows an opinionated set of best practices, and a validator that checks for that.

For example, the [Simple Implicit Scalar Pattern](https://linkml.io/linkml/howtos/model-measurements.html#variant-simple-implicit-scalar-pattern) for modeling quantities and units of measurement is marked as an anti-pattern and could be flagged in a best practices validator. 

This is inspired by some of our work on linkml arrays: https://github.com/linkml/linkml/pull/1887#discussion_r1518639867
Here:
```yaml
array:
  minimum_number_dimensions: 3
  maximum_number_dimensions: False
  dimensions:
    - alias: time
```
is equivalent to:
```yaml
array:
  minimum_number_dimensions: 3
  maximum_number_dimensions: False
  dimensions:
    - alias: time
    - {}
    - {}
```
but the second example more explicitly shows that the second and third required dimensions are left unspecified.

```yaml
array:
  minimum_number_dimensions: 3
  maximum_number_dimensions: 3
```
is equivalent to:
```yaml
array:
  exact_number_dimensions: 3
```
but I prefer the second example because even though min/max is more explicit, it suggests a range. Perhaps that is a controversial example, but I am sure there are other examples of good patterns / best practices to follow. 

Related: 
- checking for semantic versioning of schema https://github.com/linkml/linkml/issues/1262

**How important is this feature?**
• Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?**
• Long-term - 6 months - 1 year
