### ISSUE TITLE
Add support for list comprehensions / loops in expression language

### ISSUE THREAD

**Issue by rly** [linkml/linkml#2067]
**Is your feature request related to a problem? Please describe.**
The [LinkML expression language](https://linkml.io/linkml/schemas/expression-language.html) has a lot of useful features, but it does not support for loops and list comprehensions. This would be useful when generating lists and arrays.

I would also like `range` to be supported.

**Describe the solution you'd like**
For example, I want to define a class for a list of timestamps with a regular interval. It has an array attribute `values_in_s` that is defined by a starting time, sampling rate, and length. In Python, this would look like 
`timestamp_values = [1 / sampling_rate + start_time for i in range(length)]`

Here is a more concrete example

```yaml
  RegularlySampledTimestampSeries:
    description: >-
      A 1D array of timestamps, represented efficiently using a sampling rate, starting time,
      and number of elements (length).
    attributes:
      sampling_rate_in_Hz:
        range: float
        required: true
        unit:
          ucum_code: Hz
      starting_time_in_s:
        range: float
        required: true
        unit:
          ucum_code: s
      length:
        range: integer
        required: true
        implements:
          - linkml:length
      values_in_s:
        range: float
        required: true
        unit:
          ucum_code: s
        array:
          exact_number_dimensions: 1
        # I would like to do the following:
        equals_expression: "[i / {sampling_rate_in_Hz} + {starting_time_in_s} for i in range({length})]"
```

This is important for adoption by the NWB team and for any other array cases where you don't want to store a million timestamps that can be simply computed by an equation. 

**How important is this feature?**
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?**
• Long-term - 6 months - 1 year
