### ISSUE TITLE
Allow options of mapping permissible values to non classes in OWL

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#2090]
Currently gen-owl translates PVs to classes. This is very convenient because we can take advantage of constructs like like UnionOf to represent an enumeration. It is also the default case since often PVs are classes taken from ontologies

But this is not always the case.

- authors may want to follow the [Rector partition model](https://www.w3.org/2001/sw/BestPractices/OEP/SpecifiedValues-20050405/) e.g. for LOW MEDIUM HIGH
- the PVs may represent actual individuals. E.g an enum `HomePlanet` with PVs for `{Earth, Venus, ...}`
- the PVs may be other OWL constructs like ObjectProperty, Datatype, even Ontology
- the author may prefer to be non-committal

IF the user decides that ALL the members of a PV are individuals then we can take advantage of the OWL `AnyOf` construct

IF the PV is a mix of classes AND inviduals, it's impossible to have a single OWL definition of the enum in OWL-DL, unless we pun. But punning creates a lot of confusion.

Of course some users may not care about having an enum definition. It may be sufficient to simply use annotation properties to link an enum to PVs, as we do for `gen-rdf`

This PR is to gather feedback from the community on preferred mappings for PVs in OWL translations

**Comment by cmungall** [comment]
Proposed solution:

We make use of [linkml:instantiates](https://w3id.org/linkml/instantiates) to allow each PV specification to be an instance of an OWL *metaclass*

E.g.

```yaml
HomePlanet:
 permissible_values:
   Jupiter:
       instantiates:
          - owl:NamedIndividual
   Earth:
       instantiates:
         - owl:NamedIndividual
```

or as a convenience, this can be at the Enum level

```yaml
HomePlanet:
 instantiates:
   - owl:NamedIndividual
 permissible_values:
   Jupiter:
   Earth:
```

* if all PVs are NamedIndividuals, use `ObjectOneOf` to define the enum
* if all PVs are literals, use `DataOneOf` to define the enum
* if all PVs are Classes, use `UnionOf` to define the enum
* otherwise use an annotation assertion

Note that until LinkML 1.8, PVs don't have the `instantiates` metaslot, so annotations will be used instead
