### ISSUE TITLE
The `exact_cardinality` metamodel slot doesn't seem to have any effect when used in a `SlotDefinition`

### ISSUE THREAD

**Issue by candleindark** [linkml/linkml#2104]
**Describe the bug**
The `exact_cardinality` metamodel slot doesn't seem to have any effect when used in a `SlotDefinition`

**To reproduce**
1. Given the following files
`personinfo.yaml`
```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  personinfo: https://w3id.org/linkml/examples/personinfo
imports:
  - linkml:types
default_range: string
default_prefix: personinfo

classes:
  Person:
    attributes:
      id:
      full_name:
      aliases:
        multivalued: true
        exact_cardinality: 3
      phone:
      age:
      occupation:
      employed_by:
```
and `data.yaml`
```yaml
id: ORCID:1234
full_name: Clark Kent
age: "32"
occupation: reporter
employed_by: Daily Planet
phone: 555-555-5555
aliases:
  - Superman
  - Kal-El
```
2. Run `linkml-validate -s personinfo.yaml data.yaml`
3. The output of the above command is `No issues found`.

**Expected behavior**
The validation command should have failed with an error message.

**About your computer (if applicable, please complete the following information):**
 - OS: MacOS 14.4.1 on M1
 - Python version 3.11.7
 - LinkML version 1.7.9

**Comment by candleindark** [comment]
I have changed `personinfo.yaml` have the slots defined in the metadata model `slots` in the "global" level (as illustrated below), and the result is the same.

```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  personinfo: https://w3id.org/linkml/examples/personinfo
imports:
  - linkml:types
default_range: string
default_prefix: personinfo

classes:
  Person:
    slots:
      - id
      - full_name
      - aliases
      - phone
      - age
      - occupation
      - employed_by


slots:
  id:
  full_name:
  aliases:
    multivalued: true
    exact_cardinality: 3
  phone:
  age:
  occupation:
  employed_by:
```
