### ISSUE TITLE
Cardinality slots are not reflected in pydantic models for `multivalued` fields, but they work in arrays

### ISSUE THREAD

**Issue by manulera** [linkml/linkml#2109]
Following a slack conversation with @cmungall

Using linkml 1.7.8

Cardinality slots are not reflected in pydantic models for `multivalued` fields, but they work in arrays. I don't know if this is only an error of the pydantic generator, or it also affects other things.

For instance:

```yaml
slot_usage:
  input:
    multivalued: true
    maximum_cardinality: 3
    minimum_cardinality: 1
```
Translates into this in pydantic:
```python
input: Optional[List[int]] = Field(
        default_factory=list,
        description=...)
```

Whereas this:

```yaml
    slot_usage:
      input:
        array:
          dimensions:
            - alias: max_card
              maximum_cardinality: 3
              minimum_cardinality: 1
```

Gives the wanted result in pydantic:

```python
input: Optional[conlist(min_length=1, max_length=3, item_type=int)] = Field(
        default_factory=list,
        description=...,
    )
```
