### ISSUE TITLE
Missing definitions

### ISSUE THREAD

**Issue by ialarmedalien** [linkml/linkml#2133]
The following terms in the transformer syntax under `SlotDerivation` need definitions:
```yaml
      type_designator:
        range: boolean
      cast_collection_as:
        range: CollectionType
```

The following definition is not very clear:
```yaml
      hide:
        range: boolean
        description: True if this is suppressed
```

Does this mean that if `hide` is set to true, this slot does not appear in the target object? How does this differ from completely omitting the slot from the mapping?
