### ISSUE TITLE
Unable to generate valid YAML for `PermissibleValue` with `text` containing a colon

### ISSUE THREAD

**Issue by candleindark** [linkml/linkml#2138]
**Describe the bug**

```py
from linkml_runtime.linkml_model import (
    EnumDefinition,
    PermissibleValue,
)

from linkml_runtime.dumpers import yaml_dumper

E = EnumDefinition(
    "Choice",
    permissible_values=[
        PermissibleValue(text="a:b", meaning="c:d"),
    ],
)

yml = yaml_dumper.dumps(E)

print(yml)
```

The above code produces the following output

```yaml
name: Choice
permissible_values:
  a:b:
    text: a:b
    meaning: c:d
```

which is invalid YAML since the `a:b` key needs to be quoted to because of the `:`.

**Expected behavior**
The expected output is 
```yaml
name: Choice
permissible_values:
  "a:b":
    text: a:b
    meaning: c:d
```

or

```yaml
name: Choice
permissible_values:
  "a:b":
    text: "a:b"
    meaning: c:d
```

**About your computer (if applicable, please complete the following information):**
 - OS: MacOS 14.5
 - Version: Linkml 1.7.10

**Comment by cmungall** [comment]
See also #104

**Comment by candleindark** [comment]
My original claim is a mistake. Actually,

```yaml
name: Choice
permissible_values:
  a:b:
    text: a:b
    meaning: c:d
```

is valid YAML. Particularly `:` followed by a non-space character is just a literal character within a plain scalar. I.e., `a:b` is a valid key of type string in YAML, without the need of quotes.

You can confirm this by running the following script

```py
import yaml

yaml_str = """
name: Choice
permissible_values:
  a:b:
    text: a:b
    meaning: c:d
"""

data = yaml.safe_load(yaml_str)
print(data)
"""
{'name': 'Choice', 'permissible_values': {'a:b': {'text': 'a:b', 'meaning': 'c:d'}}}
"""
```

Documentation evidence is also available at https://yaml.org/spec/1.1/#id907281 for YAML 1.1 and https://yaml.org/spec/1.2.2/#rule-ns-plain-safe for YAML 1.2.

@cmungall I think we can close this issue.
