### ISSUE TITLE
incorrect linkml-validation error message

### ISSUE THREAD

**Issue by aclum** [linkml/linkml#2146]
**Describe the bug**
The error message describes an issue with the incorrect slot.

**To reproduce**
poetry run linkml-validate -s ../../../project/nmdc_materialized_patterns.yaml Database-Extraction-extraction_method-slot-retired.yaml

where the materialized pattern version of the schema comes from https://github.com/microbiomedata/berkeley-schema-fy24/tree/2046-Database-slot-updates and Database-Extraction-extraction_method-slot-retired.yaml is 

```yaml
material_processing_set:
  - id: nmdc:extrp-99-abcdef
    type: nmdc:Extraction
    name: DNA extraction of NEON sample WREF_072-O-20190618-COMP
    description: DNA extraction of NEON sample WREF_072-O-20190618-COMP using SOP BMI_dnaExtractionSOP_v7
    has_input:
      - nmdc:bsm-11-24vb2d
    has_output:
      - nmdc:procsm-11-sdt3
    processing_institution: Battelle
    protocol_link:
      type: nmdc:Protocol
      name: BMI_dnaExtractionSOP_v7
      url: https://data.neonscience.org/documents/10179/2431540/BMI_dnaExtractionSOP_v7/61204962-bb01-a0b9-3354-ccdaab5132c3
    start_date: "2019-11-08"
    end_date: "2019-11-08"
    qc_status: pass
    extraction_method: phenol/chloroform extraction # not allowed anymore
    extraction_target: DNA
```

The test fails but for the wrong reason, it complains about the length of has_input 
**Expected behavior**
The error should say 'extraction_method' doesn't exist or a generic error instead of saying a valid slot is invalid.

**Screenshots**

**About your computer (if applicable, please complete the following information):**

**Additional context**
 cc @turbomam
