### ISSUE TITLE
Inconsistent nullability in generated Pydantic model

### ISSUE THREAD

**Issue by candleindark** [linkml/linkml#2155]
**Describe the bug**
The nullability of a field in the generated Pydantic model corresponding to a LinkML class is inconsistent with the nullability of the the corresponding slot in the class.

**To reproduce**
1. Given the following LinkML schema
    `personinfo.yaml`
    ```yaml
    id: https://w3id.org/linkml/examples/personinfo
    name: personinfo
    prefixes:
      linkml: https://w3id.org/linkml/
      personinfo: https://w3id.org/linkml/examples/personinfo
    imports:
      - linkml:types
    default_range: string
    default_prefix: personinfo
    
    classes:
      Person:
        attributes:
          name:
    ```
2. and the following data instance
    `data.yaml`
    ```yaml
    name: null
    ```
3. Produces the following outcome when running `linkml-validate`
    ```sh
    ❯ linkml-validate -s personinfo.yaml data.yaml
    [ERROR] [data.yaml/0] None is not of type 'string' in /name
    ```
    The `name` slot is not nullable.
4. However, running `gen-pydantic` to generate a Pydantic model to represent `Person`.
    ```sh
    gen-pydantic --pydantic-version 2 personinfo.yaml > model.py
    ```
    We have the following outcome.
    `model.py`
    ```python
    from __future__ import annotations 
    from datetime import (
        datetime,
        date
    )
    from decimal import Decimal 
    from enum import Enum 
    import re
    import sys
    from typing import (
        Any,
        List,
        Literal,
        Dict,
        Optional,
        Union
    )
    from pydantic.version import VERSION  as PYDANTIC_VERSION 
    if int(PYDANTIC_VERSION[0])>=2:
        from pydantic import (
            BaseModel,
            ConfigDict,
            Field,
            field_validator
        )
    else:
        from pydantic import (
            BaseModel,
            Field,
            validator
        )
    
    metamodel_version = "None"
    version = "None"
    
    
    class ConfiguredBaseModel(BaseModel):
        model_config = ConfigDict(
            validate_assignment = True,
            validate_default = True,
            extra = "forbid",
            arbitrary_types_allowed = True,
            use_enum_values = True,
            strict = False,
        )
        pass
    
    
    class Person(ConfiguredBaseModel):
        name: Optional[str] = Field(None)
    
    
    # Model rebuild
    # see https://pydantic-docs.helpmanual.io/usage/models/#rebuilding-a-model
    Person.model_rebuild()
    ```
    The `name` field is nullable.

**Expected behavior**
The nullability of the corresponding field in the corresponding Pydantic model is the same as the slot's nullability.

**About your computer (if applicable, please complete the following information):**
 - OS: MacOS 14.5
 - Version: linkml version 1.7.9
