### ISSUE TITLE
How should a slot with a multivalued enum range look in tsv data file?

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#2162]
We have a tsv data file with several slots (columns) holding multivalued enumeration selections. I assumed a comma or some other delimited list would be parsed by linkml-validate, but it seems that was naive, since linkml-validate is erroring out when just one element is mentioned, e.g. for value "Swab", I get error "'Swab' is not of type 'array' in /collection_device"  Do I need to signal a delimiter attribute on the slot somehow, or is "inlined_as_list" called for?  There is probably a straightforward example of this I haven't seen?

Our schema for example "collection device" slot:
```
  collection device:
    name: collection device
    title: collection device
    description: The instrument or container used to collect the sample e.g. swab.
    comments: Provide a descriptor if a device was used for sampling. Use the picklist
      provided in the template. If a desired term is missing from the picklist, contact
      emma_griffiths@sfu.ca. If not applicable, do not leave blank. Choose a null
      value.
    slot_uri: GENEPIO:0001234
    any_of:
    - range: collection device menu
    - range: null value menu
    multivalued: true
    required: true
    examples:
    - value: Swab
    exact_mappings:
    - GISAID:Specimen%20source
    - CNPHI:Specimen%20Collection%20Matrix
    - NML_LIMS:PH_SPECIMEN_TYPE_ORIG
    - BIOSAMPLE:isolation_source
    - BIOSAMPLE:collection_device
    - VirusSeq_Portal:collection%20device
```
And menu:
```
  collection device menu:
    name: collection device menu
    permissible_values:
      Air filter:
        text: Air filter
        meaning: ENVO:00003968
      Blood Collection Tube:
        text: Blood Collection Tube
        meaning: OBI:0002859
      Bronchoscope:
        text: Bronchoscope
        meaning: OBI:0002826
        ...
```
p.s. I see one reference: "multivalued slots are serialized using a | separator" on this [https://linkml.io/linkml/data/csvs.html](https://linkml.io/linkml/data/csvs.html) page.  Meanwhile the serialization/deserialization [json-flattener](https://github.com/cmungall/json-flattener/) example shows an array represented in tsv as  e.g. "[fantasy]".  But changing tsv field value to "[Swab]" yields error: '[Swab]' is not of type 'array'.
