### ISSUE TITLE
LinkML validators do not take into account capitalisation in model?

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#2164]
**Describe the bug**

I have this enum:

```
enums:
  predicate_modifier_enum:
    permissible_values:
      Not: Negating the mapping predicate. The meaning of the triple becomes subject_id is not a predicate_id match to object_id.
```

Trying to validate a row with `Not` as a value fails with:

```
ERROR:root:(text='Not', description='Negating the mapping predicate. The meaning of the triple becomes subject_id is not a predicate_id match to object_id.') is not of type 'string' in /mappings/2/predicate_modifier
ERROR:root:(text='Not', description='Negating the mapping predicate. The meaning of the triple becomes subject_id is not a predicate_id match to object_id.') is not one of ['Not'] in /mappings/2/predicate_modifier
```

Example:

```
d:something	YYYYY	owl:equivalentClass	Not	a:something	yyyyyy	semapv:LexicalMatching	d:example	a:example	rdf_matcher	0.82	rdfs:label	rdfs:label	biolink:AnatomicalEntity	biolink:AnatomicalEntity	xxxxx	mock data
```

**Note:** If I change the capitalisation to `not`, it works (lower case `n`).

**To reproduce**

1. Checkout https://github.com/mapping-commons/sssom-py/pull/532
2. Run `poetry run tox`

**Expected behavior**

The use of `Not` with a capital N, should validate, while `not` should not.

**About your computer (if applicable, please complete the following information):**

- OS: Mac OS
- linkml                    1.7.11rc1
- linkml-dataops            0.1.0
- linkml-runtime            1.7.7

**Comment by pkalita-lbl** [comment]
Hi @matentzn I tried checking out https://github.com/mapping-commons/sssom-py/pull/532 to reproduce this issue. I saw the test `TestValidate.test_validate_nando` failing which validates against a data file called `mondo-nando.sssom.tsv`. That file doesn't appear to have a `not` or `Not` in it, so I'm a bit confused. I think digging in deeper into your repo is a bit more than I can take on. Can you please send more focused steps to reproduce this problem, ideally outside of your repo?

For example, here's what I also tried. I made this schema:

```yaml
# schema.yaml
id: https://example.org/my-schema
name: my-schema
imports:
  - https://w3id.org/linkml/types

enums:
  predicate_modifier_enum:
    permissible_values:
      Not: Negating the mapping predicate.

classes:
  Test:
    attributes:
      id:
        range: string
      predicate_modifier:
        range: predicate_modifier_enum
```

And I made this data file (`data.csv`):

```csv
id,predicate_modifier
id:1,
id:2,Not
```

When I validated using `linkml-validate` I saw no issues, as expected:

```
$ linkml-validate --version
linkml-validate, version 1.7.10

$ linkml-validate -s schema.yaml data.csv
No issues found
```

Can you come up with a simple example like that which _does_ show the issue?

**Comment by matentzn** [comment]
Sorry I left the branch in the wrong state, now the error is thrown as I describe here. 

Unfortunately I dont really know where to look for debugging this further - you can check out the branch again and run `poetry run tox` to see it - it is possible that this is not specifically about linkml validator, but has to do with the way the enums are represented by the data classes:

<details><summary>A dump of how the mapping set data class represents the `Not` enum which I am try to pass to the validator</summary>

```
  predicate_modifier: !!python/object:sssom_schema.datamodel.sssom_schema.PredicateModifierEnum
    _code: !!python/object:linkml_runtime.linkml_model.meta.PermissibleValue
      text: !!python/object/new:linkml_runtime.linkml_model.meta.PermissibleValueText
        args:
        - Not
        state:
          _s: null
          _len: null
      description: Negating the mapping predicate. The meaning of the triple becomes
        subject_id is not a predicate_id match to object_id.
      meaning: null
      unit: null
      is_a: null
      mixins: []
      extensions: {}
      annotations: {}
      alt_descriptions: {}
      title: null
      deprecated: null
      todos: []
      notes: []
      comments: []
      examples: []
      in_subset: []
      from_schema: null
      imported_from: null
      source: null
      in_language: null
      see_also: []
      deprecated_element_has_exact_replacement: null
      deprecated_element_has_possible_replacement: null
      aliases: []
      structured_aliases: {}
      mappings: []
      exact_mappings: []
      close_mappings: []
      related_mappings: []
      narrow_mappings: []
      broad_mappings: []
      created_by: null
      contributors: []
      created_on: null
      last_updated_on: null
      modified_by: null
      status: null
      rank: null
      categories: []
      keywords: []
```

</details>

See here for the context of this:

https://github.com/mapping-commons/sssom-py/pull/532/files#r1644087641

Much appreciated for you taking a look - I am suspecting the data class YAML is actually not the right now, and I am missing some step
