### ISSUE TITLE
Accepting null values or a specific type of variable (e.g., string)

### ISSUE THREAD

**Issue by daniel-ji** [linkml/linkml#2171]
Hi, this is maybe less of a bug, but a question that is related to some other issues existing (particularly #2155).

Is there any way to accept both null values and also perform validation on non-null values? For example, if in some yaml data files, there exists:

```
name: null
```

and in another file:

```
name: Daniel
```

and in another file:

```
name: 123
```

With a linkml.yaml file as folows:

```
name: dataset_config
id: placeholder

imports:
  - linkml:types
  
classes:
  Container:
    tree_root: true
    attributes:
      name: 
        range: string
        required: false
``` 

I'm hoping that the linkml file can accept both files where there is a null / unset name attribute, as well as any set name attributes that are strings. (So `name: null`, `name:`, and `name: Daniel` should pass, where `name: 123` shouldn't). 

As per the #1975 discussion, 
```
name: null
```

should act the same as

```
name:
```

which should act the same as 
```
(empty file)
```

However, 
when trying to run  `linkml-validate` on either `name: null` or `name:`, I get the error:

[ERROR] [test.yaml/0] None is not of type 'string' in /name

Is there any way to go about this? Thank you!

LinkML version: v1.7.10
