### ISSUE TITLE
`multivalued` meta slot doesn't work within `any_of` meta slot elements

### ISSUE THREAD

**Issue by candleindark** [linkml/linkml#2190]
**Describe the bug**
The move of `multivalued` meta slot to `SlotExpression` from `SlotDefinition` per https://github.com/linkml/linkml-model/pull/197 is not working as intended.

**To reproduce**
Give the following schema as `personinfo.yaml`

```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  personinfo: https://w3id.org/linkml/examples/personinfo
imports:
  - linkml:types
default_range: string
default_prefix: personinfo

classes:

  Any:
    class_uri: linkml:Any

  Person:
    attributes:
      id:
      full_name:
      aliases:
      phone:
        range: Any
        any_of:
          - range: string
            multivalued: true
          - range: integer
      age:
```

and the following data instance as `data.yaml`

```yaml
id: ORCID:1234
full_name: Clark Kent
age: "32"
phone: ["42"]
```

Running `linkml-validate -s personinfo.yaml data.yaml` produced the following output

```
[ERROR] [data.yaml/0] ['42'] is not of type 'null', 'boolean', 'object', 'number', 'string' in /phone
```

**Expected behavior**
The above data instance should be consider a valid by the validator.

**About your computer (if applicable, please complete the following information):**
 - OS: MacOS 14.5
 - LinkML related packages
 ```
linkml                    1.8.0
linkml-dataops            0.1.0
linkml-runtime            1.8.0
```
