### ISSUE TITLE
Document edge case: CompactDicts with lists as values

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#2191]
LinkML allows for compact serialization of objects that follow a key-value pattern (one slot is key, the other is value, no other slots).

One such example of this is annotations in the metamodel.

We can create annotations like

```python
Annotation(key="my_key", value="my_value")
```

The full ExpandedDict serialization of an annotation might be:

```yaml
  MyClass:
    ...
    annotations:
      my_key:
         tag: my_key
         value: my_value
```

But by default a CompactDict is chosen:

```yaml
  MyClass:
    ...
    annotations:
      my_key: my_value
```

The value of the annotation does not have to be a string; this is valid:

```python
Annotation(key="my_key", value=[1, 2])
```

However, if we attempt to serialize this in compact form:

```yaml
  MyClass:
    ...
    annotations:
      my_key: [1, 2]
```

The dataclass instantiation of the metamodel will get confused and reject this. The reasons for this is that the dataclass generator is *Postelian* by default, it proactively tries to coerce objects that don't conform and the rules for doing this become ambiguous when Any is used with a simple dictionary.

There is an easy if slightly annoying workaround:

```yaml
```yaml
  MyClass:
    ...
    annotations:
      my_key: 
         value: [1, 2]
```

This is highly non-obvious. The need for this should go away when we start using pydantic for the metamodel, but for now there should be a FAQ entry on this
