### ISSUE TITLE
`gen-doc` error message for slot with no range is uninformative

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#2200]
```yaml
name: assumption_schema
id: http://example.com/assumption_schema

imports:
  - linkml:types

prefixes:
  linkml: https://w3id.org/linkml/

classes:
  Assumption:
    slots:
      - assumes

slots:
  assumes: {}
```

```shell
gen-doc -d docs assumption_schema.yaml
```

>AttributeError: type object 'NoneType' has no attribute 'class_name'
