### ISSUE TITLE
`equals_string_in` meta slot has no affect in validation

### ISSUE THREAD

**Issue by candleindark** [linkml/linkml#2206]
**Describe the bug**
`equals_string_in` meta slot has no affect in validation. This bug could be related to https://github.com/linkml/linkml/issues/1677 since JSON validator is used, by default, in LinkML validation.

**To reproduce**
1. ` personinfo.yaml` as the schema
```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  personinfo: https://w3id.org/linkml/examples/personinfo
imports:
  - linkml:types
default_range: string
default_prefix: personinfo

classes:
  Person:
    attributes:
      id:
      full_name:
      aliases:
      phone:
      age:
      sex:
        equals_string_in: [male, female]
```

2. Given `data.yaml` as the data instance
```yaml
id: ORCID:1234
full_name: Clark Kent
age: "32"
phone: 555-555-5555
sex: man
```

3. Running `linkml-validate -s personinfo.yaml data.yaml` produces
```
No issues found
```

**Expected behavior**
The `linkml-validate -s personinfo.yaml data.yaml` command produces an error message complaining that the value for `sex` is neither `male` nor `female`.

**About your computer (if applicable, please complete the following information):**
 - OS: MacOS 14.5
 - Version: LinkML 1.8.1, linkml-runtime  1.8.0
