### ISSUE TITLE
Allow other collection types beyond List and Dict

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#221]
If multivalued = True, then the corresponding python class uses a List or Dict, depending on inlined

conversely, in JSON-LD/RDF this will be treated as if it were a set

I propose adding a slot field

```yaml
  collection_type:
     range: <enum of Set|List>
     required: false
     description: >-
       what type of collection, applicable to multivalued only, when not inlined as dict
       this field is optional
          None: pygen makes lists, JSON-LD serialized as list but with set semantics in RDF (ie current default)
          Set: pygen makes sets, JSON-LD/RDF as current default
          List: pygen makes lists, JSON-LD/RDF makes rdf:Lists. Warning. Only use if ordering is absolutely essential, as rdf:Lists mean lots of blank nodes
```
