### ISSUE TITLE
LinkML JSON Schema Generator - Incorrect Type Conversion

### ISSUE THREAD

**Issue by mahdanoura** [linkml/linkml#2211]
**Describe the bug**
The LinkML JSON Schema generator translates `custom data types` such as `rdf:langString` and specific URI-related types (`uri, uriorcurie`) always to `"type": "string"` types in the generated JSON schema.
For instance, the following LinkML schema, 
```
classes:
  supportContact:
    description: >-
      Provides information about the TD maintainer as URI scheme.
    range: uriorcurie
    from_schema: schema:contactPoint
```
generates the following JSON Schema snippet

```
"supportContact": {
                    "description": "Provides information about the TD maintainer as URI scheme",
                    "type": "string"
                }
```

The same is true when I try to define `customised data types`, for instance:
```
types:
  languageString:
    base: rdf:langString
    uri: rdf:langString
    structured_pattern:
      syntax: "{text}@{tag}"
slots:
  title:
    description: >-
      Provides a human-readable title (e.g., display a text for UI representation) based on a default language.
    range: languageString
    required: true
    slot_uri: td:title
```

In this case, the generated JSON Schema is also, 
```
"title": {
      "description": "Provides a human-readable title (e.g., display a text for UI representation) based on a default language.",
        "type": "string"
                }
```

**To Reproduce**
My environment is follows:
python = "^3.11"
linkml-runtime = "^1.8.0rc2"
linkml = "^1.8.0rc2"

I use the the following code snippet for generating the JSON Schema from the LinkML schema:
```
from linkml.generators.jsonschemagen import JsonSchemaGenerator

json_schema_generator = JsonSchemaGenerator(YAML_SCHEMA_PATH, mergeimports=True)
(output_dir / 'jsonschema.json').write_text(json_schema_generator.serialize())
```

**Expected behavior**
The JSON Schema generator should for instance consider the format in JSON Schema `"type":"string", "format":"uri"`

**Comment by Silvanoc** [comment]
I forgot that CURIEs are in fact valid URIs (that's the reason why the use of [SafeCURIEs is recommended to avoid ambiguities](https://www.w3.org/TR/curie/#sec_2.2.). So probably following is valid for all three (URI, CURIE, URIorCURIE):
```json
{
  "supportContact": {
    "type": "string",
    "format": "uri"
  }
}
```

**Comment by Silvanoc** [comment]
You can see that I've tried to improve it (look for `curie` among [these contributions](https://github.com/linkml/linkml-runtime/commits/main/?author=Silvanoc)), but I don't have the feeling that it's covering all corner-cases. So we need to take care on whatever changes we introduce and to make sure that we have enough test coverage to avoid regressions.

**Comment by Silvanoc** [comment]
BTW @mahdanoura your example is not a valid LinkML schema.

Did you mean something like this? If so, please edit your first comment accordingly.
```
classes:
  supportContact:
    description: >-
      Provides information about the TD maintainer as URI scheme.
    from_schema: schema:contactPoint
    attributes:
      id:
        range: uriorcurie
```
