### ISSUE TITLE
No validation for range `uri` beyond validation for range `string`

### ISSUE THREAD

**Issue by candleindark** [linkml/linkml#2215]
**Describe the bug**
The validation for a slot of range `uri` seems no different than the validation for a slot of range `string`.

**To reproduce**
1. Given `personinfo.yaml`
```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  personinfo: https://w3id.org/linkml/examples/personinfo
imports:
  - linkml:types
default_range: string
default_prefix: personinfo

classes:
  Person:
    attributes:
      id:
      full_name:
      aliases:
      phone:
      age:
      webpage:
        range: uri
```

2. And given `data.yaml`
```yaml
id: ORCID:1234
full_name: Clark Kent
age: "32"
phone: 555-555-5555
webpage: "Hello world"
```

3. Running `linkml-validate -s personinfo.yaml data.yaml` produces
```
No issues found
```

**Expected behavior**
An error message specifying `"Hello world"` is an invalid URI.

**About your computer (if applicable, please complete the following information):**
 - OS: MacOS 14.5
 - linkml: 1.8.1, linkml-runtime:  1.8.0
