### ISSUE TITLE
some (multivalued?) slot definition metaslot values are lost after `SchemaView.induced_class()`

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#2224]
For discussion in 2024-07-26 LinkML developer's meeting

No example/tests yet, but see

- https://github.com/GenomicsStandardsConsortium/mixs/pull/812

**Comment by sneakers-the-rat** [comment]
this looks like it's related to:
- https://github.com/linkml/linkml/issues/2219
- https://github.com/linkml/linkml-runtime/pull/332

I see you're missing `examples` - when inducing a slot, we...
first get the value of the metaslot, say `examples`:
https://github.com/linkml/linkml-runtime/blob/984e4b2657f681dfa50e4cbd692bdb946ea56976/linkml_runtime/utils/schemaview.py#L1355

iterate from furthest to most proximal ancestor, and get any matching value for `slot_usage` in that class for the slot and metaslot in question:
https://github.com/linkml/linkml-runtime/blob/984e4b2657f681dfa50e4cbd692bdb946ea56976/linkml_runtime/utils/schemaview.py#L1364

and in one of three ways replace the old value `v` with the new value `v2` if `v2` is not None:
https://github.com/linkml/linkml-runtime/blob/984e4b2657f681dfa50e4cbd692bdb946ea56976/linkml_runtime/utils/schemaview.py#L1372-L1373

The problem is that `slot_usage` is a `Dict[str, SlotDefinition]`, and the default value of `SlotDefinition.examples` is `[]` -- not `None` . so even if `examples` is not overridden by `slot_usage`, because there is `slot_usage` declared for that slot, all non-scalar values will always be overridden. 

I've started drafting a PR that refactors `induced_slot` because i kept running into problems like this with inheritance, `slot_usage`, and mutating values after they were retrieved from `SchemaView`: https://github.com/linkml/linkml-runtime/pull/332

**Comment by sneakers-the-rat** [comment]
MWE

```yaml
id: myschema
name: myschema
title: myschema
imports:
- linkml:types
classes:
  MyClass:
    slots:
    - my_slot
    slot_usage:
      my_slot:
        range: integer
slots:
  my_slot:
    examples:
    - value: hey what up
    range: string
```

```python
>>> from linkml_runtime import SchemaView
>>> sv = SchemaView(schema)
>>> cls = sv.induced_class('MyClass')
>>> cls.attributes['my_slot'].examples
[]
```
