### ISSUE TITLE
Add more docs and tests for logical model transformer

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#2234]
LogicalModelTransformer provides a formal and rigorous way to do logical schema rewrites, including finding the simplest disjunctive (any_of) expression. 

E.g a slot

```
has_pet:
  range: Animal
```

classes:

```
Renter:
  slots: [has_pet]
  slot_usage:
    has_pet:
      any_of:
        - range: HouseCat
        - range: Dog
```

LinkML is monotonic, so combining these gives

```
has_pet:
  range: Animal
  any_of:
        - range: HouseCat
        - range: Dog
```

Assuming a standard `is_a` hierarchy with animal types, we can rewrite this to an equivalent simpler form:

```
has_pet:
  any_of:
        - range: HouseCat
        - range: Dog
```

Assume also we have a mixin

```
FelineFan:
  mixin: true
  slots: [has_pet]
  slot_usage:
    has_pet:
      range: Feline
```

making a compositional class

```
FileFanRenter:
  is_a: Renter
  mixins: [FelineFan]
```

The entailed has_pet attribute for this class would be:

```
has_pet:
  range: HouseCat
```

We should improve the docs for this, and it's explore it's use in various scenarios:

- schema logical validation; e.g. max and mix range for a slot should intersect with mins and maxes for ancestors
- most languages have a type system that is effectively a disjunction of atoms, e.g. `Union[Dog,Cat]` so this could be used as a preprocessing step for module generation
- for schemaview type intersection, we may often want to get a slot range as a disjunctive expression
