### ISSUE TITLE
JSON Schema "additionalProperties" default value not set correctly

### ISSUE THREAD

**Issue by mahdanoura** [linkml/linkml#2238]
**Describe the bug**
In the context of LinkML schema, currently (to the best of my knowledge) we cannot set a boolean value for `additionalProperties`. 
By default, the LinkML JSON Schema generator assigns ```json"additionalProperties": false``` for object type schemas. 

However, according to the [JSON Schema Specification Draft 00 ](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#page-10):

`If "additionalProperties" is absent, it may be considered present with an empty schema as a value.`

This means to conform to the spec, by default `additionalProperties` should be set to `{}` for object type schemas and not to `false`.

**To reproduce**
The following LinkML 
```
classes:
  ExpectedResponse:
    attributes:
      contentType:
        required: true
```
produces the JSON Schema: 

```json
"ExpectedResponse": {
            "additionalProperties": false,
            "properties": {
                "contentType": {
                    "type": "string"
                }
            },
            "required": [
                "contentType"
            ],
            "title": "ExpectedResponse",
            "type": "object"
        }
```

**Expected behavior**
I would expect the default value of `"additionalProperties"` is `true` when it cannot be even specified.
```json
"ExpectedResponse": {
            "additionalProperties": true,
            "properties": {
                "contentType": {
                    "type": "string"
                }
            },
            "required": [
                "contentType"
            ],
            "title": "ExpectedResponse",
            "type": "object"
        }
```

We could introduce a new term to the LinkML vocabulary on the `class` level called `"additionalProperties"` of type `boolean` to customise the default behaviour. For instance, 
```
classes:
  ExpectedResponse:
    attributes:
      contentType:
        additionalProperties: false
        required: true
```
