### ISSUE TITLE
[proposal] `extra` metaslot to define behavior of extra values in classes.

### ISSUE THREAD

**Issue by sneakers-the-rat** [linkml/linkml#2241]
**Is your feature request related to a problem? Please describe.**

Weirdly, this just came up in another issue:
- https://github.com/linkml/linkml/issues/2238
and previously related to:
- https://github.com/linkml/linkml/issues/1404

Currently linkml schemas are formally closed - things that are not declared are not allowed. That's a good default I think, and previous discussions highlight how 'open' schemas are often a hack around some insufficiency in discoverability/api/etc. where instead of allowing arbitrary extra properties it should be easier for users to create new schemas, etc. 

I think there's a distinction between "not a recommended data modeling practice" and "shouldn't be expressible at all," as we have been through in the arrays process :). 

Consider this example from NWB (abbreviated from [https://github.com/hdmf-dev/hdmf-common-schema/blob/5b4cbb31dbafcff51ca70bf218f464b186568151/common/table.yaml#L96C1-L139C18):

```yaml
- data_type_def: DynamicTable
  data_type_inc: Container
  datasets:
  - name: id
    data_type_inc: ElementIdentifiers
    dtype: int
    dims:
    - num_rows
    shape:
    - null
    doc: Array of unique identifiers for the rows of this dynamic table.
  - data_type_inc: VectorData
    doc: Vector columns, including index columns, of this dynamic table.
    quantity: '*'
```

This notation means, in linkml parlance that "`DynamicTable` can allow any number of additional slots/attributes of type `VectorData`"

There is an ambiguity here (in both NWB and in general) between whether the `extra` here refers to additional slots *in the schema* vs *in the data*.

It would be desirable to handle both, because it is intuitively useful for me to be able to declare some parent container model that allows additional slots as long as they have a particular range, say strings for a simple example:

```yaml
classes:
  Parent:
    extra:
      range: string
    attributes:
      first_attr:
        range: string

  # valid child class
  ValidChild:
    is_a: Parent
    attributes:
      second_attr:
        range: string

  # invalid child class
  InvalidChild:
    is_a: Parent
    attributes:
      second_attr:
        range: integer
```

But it would also be useful to declare how extra values *in the data* should be handled - returning to the NWB `DynamicTable` example, pydantic allows one to declare a `__pydantic_extra__` property to validate any additional values passed to the model. 

```python
from pydantic import BaseModel, ConfigDict

class MyModel(BaseModel):
    model_config = ConfigDict(extra="allow")
    __pydantic_extra__: list[str]

    first_attr: str

# fine
>>> a = MyModel(first_attr='hey', second_attr=['a','b'])
# validation error
>>> b = MyModel(first_attr='hey', second_attr='whats up')
```

This is also coming up in https://github.com/linkml/linkml/issues/2238 where it would be useful to declare how to handle the `additionalProperties` field in JSON Schema, so it seems like there should be some in-universe way of declaring how to handle extra values both in the schema and in the data.

## Examples from other schema langs

JSON Schema allows `additionalProperties` to be
- `false` - no extra values allowed
- `true` - any extra values allowed
- `object` - extra values that validate against that schema

Pydantic allows `ConfigDict(allow=)` to be
- `forbid` - raise a validation error on additional values
- `ignore` - silently drop extra values
- `allow` - default allow any extra values, optionally validating against `__pydantic_extra__` if present

I am not entirely sure how OWL deals with it, but from what i understand class definitions are default open, where class membership is either just flatly declared or inferred by satisfying a restriction class like a class having `allValuesFrom` a given class definition, so idk how relevant this would be there.

## Proposal

Make an `extra` metamodel slot like...

```yaml
classes:
  ClassDefinition:
    slots:
      # ...
      - extra

  ExtraExpression:
    attributes:
      schema:
        ifabsent: true
        description: Control of extra slots by inheriting classes in linkml schemas
        any_of:
          - range: boolean
          - range: anonymous_slot_expression
      data:
        ifabsent: false
        description: Control of extra slots in data/instantiations of the class
        any_of:
          - range: boolean
          - range: anonymous_slot_expression

slots:
  extra:
    any_of:
      - range: boolean
      - range: ExtraExpression
```

This makes it so that one can have control over extra values both in the schema and data level. The naming and structure aren't all that important, eg. i imagine having two slots like `extra_slots` or `extra_data` would be more in line with linkml naming style, but in general I like to group related functionality for discoverability and concision in naming, though ofc i'm not really dogmatic about that.

Some examples..

```yaml
extra:
```
Unset value would default to the defaults in `ExtraExpression` (i'm not sure if there's a formal way to specify that in the metamodel, ExtraExpression's attributes all have defaults so it's possible to instantiate without parameterization) - allow all additional slots in inheriting classes, forbid additional slots in data

```yaml
extra: true
# or
extra: false
```
At a top-level, set both values at once - allow all additional values in schema and all additional values in data, or forbid both.

```yaml
extra:
  schema: true
```
default behavior, allow any additional slots in inheriting classes

```yaml
extra:
  schema: false
```
forbid any additional slots in inheriting classes, *sort of* like python's [Final](https://docs.python.org/3/library/typing.html#typing.Final), but would still allow for `slot_usage` etc. and any `is_a` relationship that doesn't add new slots

```yaml
extra:
  schema:
    range: string
    
# or
extra:
  schema:
    any_of:
    - range: string
    - range: integer
```
allow any additional slots that validate against the SlotExpression. so here any additional slots that are strings (or either strings or integers in the second example)

```yaml
extra:
  data: false
```
forbid any additional slots provided when instantiating/in the data - current behavior

```yaml
extra:
  data: true
```
allow any additional slots provided when instantiating/any additional slots in the data - this collapses the two cases for `additionalProperties: true` / `additionalProperties: {}` which as far as i can tell are equivalent? 

```yaml
extra:
  data:
    range: string
```
same as above, allow any additional slots in data that match the slot expression.

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

I'm monkeypatching my way around this rn so i'll be fine, but would be p useful to have i think.

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months
