### ISSUE TITLE
Provide more informative error messages when an input schema has incorrect indentation

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#2249]
The following schema has incorrect indentation:

```yaml
id: https://example.org
name: test

classes:
  A:
    attributes:
      s:
      multivalued: true
```

Running any LinkML tooling over this produces `TypeError: 'bool' object is not subscriptable`, which is not informative.

It's not possible to fully diagnose all errors (in this case the `multivalued` needs to be indented further), but we could provide more informative error messages.

Contrast the above with

```yaml
classes:
  A:
    attributes:
      s:
        multivalued: xyz
```

==> `ValueError: xyz: Must be a boolean value`

which is more informative

A different case:

```yaml
classes:
  A:
    attributes:
      s:
        multivalued: True
  A:
```

==>`ValueError: Duplicate key: "A"`

In some cases line numbers are provided:

```yaml
id: https://example.org
name: abc def

classes:
  A:
    attributes:
      s:
        multivalued: True
```

===> `ValueError: File "s.yaml", line 2, col 7: abc def: Not a valid NCName`

which provides the line number
