### ISSUE TITLE
Are multiple schemadefinitions per LinkML file needed?

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml#225]
The current LinkML schema processor is designed to handle multiple schema definitions per YAML input file.  As an example:
```yaml
schema1:
   id: http://examples.org/test#schema1
   ...

schema2:
   is: http://examples.org/test#schema2
   ...
```

Does anyone:
1) Use this feature today?
2) Anticipate needing it in the near future?
