### ISSUE TITLE
Usage of a non-existent enum does not trigger linting error 

### ISSUE THREAD

**Issue by jat255** [linkml/linkml#2254]
**Describe the bug**
If a LinkML schema tries to use an Enum that is not defined, it does not trigger a warning/error when running `linkml-lint`

**To reproduce**
Use the following schema:

```yaml
# enum_bug.yaml
name: enum_bug
id: enum_bug_example
classes:
  ExampleMixin:
    description: the mixin example
    attributes:
      valid_attribute:
        description: this has a valid enum as its range
        range: EnumOne
      invalid_attribute:
        # EnumTwo is never defined anywhere, so I would expect this to raise an error
        description: this does NOT have a valid enum as its range
        range: EnumTwo

enums:
  EnumOne:
    description: a test enum
    permissible_values:
      one:
      two:
      three:
```

Attempt to lint:
```shell
$ linkml-lint enum_bug.yaml
✓ No problems found
```

**Expected behavior**
I would expect that this would cause an error, since `EnumTwo` is not defined anywhere

**Additional context**
This issue was first discussed in the #linkml-community Slack channel: https://obo-communitygroup.slack.com/archives/C04EU7JL1NF/p1722520842250019
