### ISSUE TITLE
Add OWL dumpers and loaders to runtime

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#226]
These would be distinct from RDF dumpers/loaders.

A common pattern is to use linkml to model TBox metaclasses. See for example

  - https://cmungall.github.io/chem-schema/
  - https://github.com/monarch-initiative/monochrom (@jiaola is working on this)

If a linkml instance corresponds to an OWL class, then we frequently want links to be translates as restrictions. E.g.

```yaml
 taxon:
    range: TaxonIdentifier
    required: false
    slot_uri: RO:0002162
 exact_synonyms:
    multivalued: true
    slot_uri: OIO:hasExactSynonym
 cell_location:
    range: LocationType
    slot_uri: BFO:0000050
    description: >-
      which organelle the chromosome is associated with. For eukaryotes this is mitochondrion
      or nucleus. For prokaryotes the distinction does not make sense
```

in the above from monochrom we want to treat taxon and location as SVFs, and OIO properties as annotations. 

currently my strategy is to use the awesome funowl and to hardcode thekinds of owl mappings:

https://github.com/monarch-initiative/monochrom/blob/482105eee6af65b927e86a7a2e02bd8916c6f8c4/monochrom/monochrom.py#L25-L69

it would be good if the boilerplate moved to the runtime

[more later]
