### ISSUE TITLE
IfAbsentProcessor too strict with matching type with custom types.

### ISSUE THREAD

**Issue by sneakers-the-rat** [linkml/linkml#2279]
**Describe the bug**

The beloved new IfAbsentProcessor makes a series of checks using `<T>.type_name`: https://github.com/linkml/linkml/blob/2127636dbe178f13f314455d04a8aa5b93f77b4e/linkml/generators/common/ifabsent_processor.py#L64

the intent of the tests is to match against linkml base types. however when one is using custom types it fails because the type no longer has the matching type_name, for obvious reasons. 

MWE:

```yaml
id: name
imports:
- linkml:types
types:
  text:
    name: text
    typeof: string

classes:
  MyClass:
    attributes:
      value:
        range: text
        ifabsent: string(hey)
```

```shell
$ linkml generate pydantic test.yml                                                              
ValueError: The ifabsent value `string(hey)` of the `value` slot could not be processed
```

we are looking for something like

```python
typ = sv.induced_type(type_name)
typ.repr == 'str' or 'string' in sv.type_ancestors(type_name)
```

**Version of LinkML you are using**

`1.8.1.post78.dev0+be8dbf21` (but true in current `main` branch too)
