### ISSUE TITLE
`ifabsent` allowable values documentation is incorrect/inconsistent

### ISSUE THREAD

**Issue by sneakers-the-rat** [linkml/linkml#2280]
**Describe the bug**

[metamodel says](https://github.com/linkml/linkml-model/blob/76bc3279981f00f9f6590caf7fbe5a1f15520f85/linkml_model/model/schema/meta.yaml#L1507-L1519)

```
      function that provides a default value for the slot.
        * [Tt]rue -- boolean True
        * [Ff]alse -- boolean False
        * bnode -- blank node identifier
        * class_curie -- CURIE for the containing class
        * class_uri -- URI for the containing class
        * default_ns -- schema default namespace
        * default_range -- schema default range
        * int(value) -- integer value
        * slot_uri -- URI for the slot
        * slot_curie -- CURIE for the slot
        * string(value) -- string value
        * EnumName(PermissibleValue) -- enum value
```

but [docs say](https://linkml.io/linkml/schemas/slots.html#default-values):

```yaml
slots:
  my_string_slot:
    range: string
    ifabsent: string(default value)
  my_int_slot:
    range: integer
    ifabsent: int(42)
  my_float_slot:
    range: float
    ifabsent: float(0.5)
  my_bool_slot:
    range: boolean
    ifabsent: True
  my_date_slot:
    range: date
    ifabsent: date("2020-01-31")
  my_datetime_slot:
    range: datetime
    ifabsent: datetime("2020-01-31T12:00:00Z")
  my_enum_slot:
    range: FamilialRelationshipType
    ifabsent: FamilialRelationshipType(PARENT_OF)
```

and `IfAbsentProcessor` tests seem to indicate yet more allowable values.

not sure what the source of truth is here but we should probably have one :)
