### ISSUE TITLE
Validation fails on "ifabsent" for enumeration

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2284]
**Describe the bug**

Validation of a schema with an [enumeration permissible value](https://linkml.io/linkml-model/latest/docs/PermissibleValue/) as default ([`ifabsent`](https://linkml.io/linkml-model/latest/docs/ifabsent/)) fails.

I run the validation as part of the Python generation: `gen-python --validate <schema-path>`.

The error that I get is consistently the same:
```shell
ERROR:root:Error compiling generated python code: name '<EnumClass>' is not defined
NameError: name '<EnumClass>' is not defined. Did you mean: 'PermissibleValue'?
```

The generated Python code looks fine.

**Version of LinkML you are using** v1.8.3

**Please provide a schema (and if applicable, a data file) that replicates the issue**

Reproduced with
* one of the test schemas: [kitchen_sink_ifabsent.yaml](https://github.com/linkml/linkml/blob/main/tests/test_generators/input/kitchen_sink_ifabsent.yaml)
* following very simple schema:
```yaml
id: https://example.org/test-ifabsent
name: Test-ifabsent
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  MyClass:
    attributes:
      my_slot:
        range: PossibleValues
        ifabsent: PossibleValues(first_option)

enums:
  PossibleValues:
    permissible_values:
      first_option:
      second_option:
```
