### ISSUE TITLE
gen-graphql does not generate enumerations

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2301]
**Describe the bug**
The generation of GraphQL types out of a schema mit gen-graphql does not include the [enumerations](https://linkml.io/linkml-model/latest/docs/EnumDefinition/) of the schema.

**Version of LinkML you are using** 1.8.2

**Please provide a schema (and if applicable, a data file) that replicates the issue**
``` yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  personinfo: https://w3id.org/linkml/examples/personinfo
imports:
  - linkml:types
default_range: string
default_prefix: personinfo

classes:
  Person:
    attributes:
      id:
      full_name:
      civil_status:
          range: CivilStatus

enums:
  CivilStatus:
    permissible_values:
        married:
        single:
        divorced:
```

Gets following GraphQL types:
``` graphql
# metamodel_version: 1.7.0
type Person
  {
    id: String
    fullName: String
    civilStatus: CivilStatus
  }
```

Where the enumeration `CivilStatus` is obviously missing.
