### ISSUE TITLE
gen-graphql not generating equivalent scalar for types

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2302]
**Describe the bug**
Generation of the GraphQL types out of a schema is not resolving types into the corresponding [GraphQL scalar types](https://graphql.org/learn/schema/#scalar-types).

I would expect [LinkML types](https://linkml.io/linkml-model/latest/docs/#types) to be converted to the corresponding GraphQL scalar types, but no conversion happens. Only those types that (by chance) have exactly the same name (like `String`) will work, for all others GraphQL tools will raise an error because they are unknown.

Using the `repr` slot (`base` if `repr` is missing) of a LinkML type it should be easy to generate the corresponding GraphQL scalar type. Only `Int` would need to be renamed to `Integer` and an explicit conversion of `Decimal` into GraphQL `Float` would be needed.

**Version of LinkML you are using** 1.8.2

**Please provide a schema (and if applicable, a data file) that replicates the issue**

The conversion of following schema into GraphQL
``` yaml
id: https://w3id.org/linkml/examples/alltypes
name: alltypes
prefixes:
  linkml: https://w3id.org/linkml/
  alltypes: https://w3id.org/linkml/examples/alltypes
imports:
  - linkml:types
default_range: string
default_prefix: alltypes

classes:
  AllTypes:
    attributes:
      string:
        range:
          string
      integer:
        range:
          integer
      boolean:
        range:
          boolean
      float:
        range:
          float
      double:
        range:
          double
      decimal:
        range:
          decimal
      time:
        range:
          time
      date:
        range:
          date
      datetime:
        range:
          datetime
      dateOrDatetime:
        range:
          date_or_datetime
      uriorcurie:
        range:
          uriorcurie
      curie:
        range:
          curie
      uri:
        range:
          uri
      ncname:
        range:
          ncname
      objectidentifier:
        range:
          objectidentifier
      nodeidentifier:
        range:
          nodeidentifier
      jsonpointer:
        range:
          jsonpointer
      jsonpath:
        range:
          jsonpath
      sparqlpath:
        range:
          sparqlpath
```

Results in following GraphQL schema

``` graphql
# metamodel_version: 1.7.0
type AllTypes
  {
    string: String
    integer: Integer
    boolean: Boolean
    float: Float
    double: Double
    decimal: Decimal
    time: Time
    date: Date
    datetime: Datetime
    dateordatetime: Dateordatetime
    uriorcurie: Uriorcurie
    curie: Curie
    uri: Uri
    ncname: Ncname
    objectidentifier: Objectidentifier
    nodeidentifier: Nodeidentifier
    jsonpointer: Jsonpointer
    jsonpath: Jsonpath
    sparqlpath: Sparqlpath
  }
```

Running a validation with the package `gql` like this `python3 -c 'from gql import Client ; Client(schema=open("<path to GraphQL schema>").read())'` yields following errors:
```
Unknown type 'Integer'.
Unknown type 'Double'.
Unknown type 'Decimal'.
Unknown type 'Time'.
Unknown type 'Date'.
Unknown type 'Datetime'.
Unkwnon type 'Dateordatetime'.
Unknown type 'Uriorcurie'.
Unknown type 'Curie'.
Unknown type 'Uri'.
Unknown type 'Ncname'.
Unknown type 'Objectidentifier'.
Unknown type 'Nodeidentifier'.
Unknown type 'Jsonpointer'.
Unknown type 'Jsonpath'.
Unknown type 'Sparqlpath'.
```

Notice that `String` and `Float` are not failing, because they have the same name in both. But the LinkML type `Int` is called `Integer` in GraphQL and therefore it is failing.
