### ISSUE TITLE
Pydantic: Use Python type aliases for custom LinkML types

### ISSUE THREAD

**Issue by bartkl** [linkml/linkml#2307]
**What is your feature request?**
Suppose I have a custom type like which is used as the range of some class attribute:

```yaml
classes:
  Person:
    attributes:
      name:
        range: Name
types:
  Name:
    uri: xsd:string
    base: string
    description: Name.
```

When generating Pydantic code, this yields:

```py
class Person(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'http://example.o
rg/test-schema'})

    name: Optional[str] = Field(None, json_schema_extra = { "linkml_meta": {'alias':
 'name', 'domain_of': ['Person']} })
```

**Suggestion**: why not utilize Python's [type aliases](https://docs.python.org/3/library/typing.html#type-aliases) for this and generate sometihng like:

```py

type Name = str

class Person(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'from_schema': 'http://example.o
rg/test-schema'})

    name: Optional[Name] = Field(None, json_schema_extra = { "linkml_meta": {'alias':
 'name', 'domain_of': ['Person']} })
```

This way it's no longer a comment, but actually part of the Python model.

**How important is this feature to you?** Select from the options below:
*Low/Medium*.

It can really make the model more clear for developers.
