### ISSUE TITLE
range doesn’t support multiple values with any_of

### ISSUE THREAD

**Issue by rajavishah** [linkml/linkml#2319]
`range` doesn’t support `multiple-values`

- LinkML_Version: 1.8.3

In my project I want to allow 1+ types of `range` for a particular `slot`. 

Below is my `schema_file_snippet`: [Link-to-code](https://github.com/rajavishah/linkml-learn/blob/main/src/linkml_learning/schema/linkml_learning.yaml#L150-L163)

```
label:
    description: "Label of the object"
    required: true
    any_of:
      - range: string
      - range: integer
      - range: boolean
  value:
    description: "Value of the object"
    required: true
    any_of:
      - range: string
      - range: integer
      - range: boolean
```
And `test.yaml` file to validate - Here is the [link-to-code](https://github.com/rajavishah/linkml-learn/blob/main/src/data/examples/test.yaml#L94-L111) 
Note: As of now, files would work without error, since `value's` are enclosed in `string` 
```
- name: chan2
    type: radio
    label: "Chan2"
    description: "Nuclear Channel, if cyto then optional"
    options: 
      - label: "None"  
        value: 0
      - label: "RED"
        value: 1
      - label: "GREEN"
        value: 2
      - label: "BLUE"
        value: 3
    default: "0"
    cli_tag: "--chan2"
    optional: True
    section_id: "input-args"
    mode: "advanced"
```

And tries to validate my schema with this command 
```poetry run linkml-validate \
 --schema src/linkml_learning/schema/linkml_learning.yaml \
 --target-class Container \
 src/data/examples/test.yaml
``` 
It throws the below error:
```
[ERROR] [src/data/examples/test.yaml/0] 0 is not of type 'string' in /parameters/8/options/0/value
[ERROR] [src/data/examples/test.yaml/0] 1 is not of type 'string' in /parameters/8/options/1/value
[ERROR] [src/data/examples/test.yaml/0] 2 is not of type 'string' in /parameters/8/options/2/value
[ERROR] [src/data/examples/test.yaml/0] 3 is not of type 'string' in /parameters/8/options/3/value
``` 
[Link-to-my-whole-test-repo](https://github.com/rajavishah/linkml-learn/)

**Comment by amc-corey-cox** [comment]
I'm not certain this is the problem. But in the example here:
https://linkml.io/linkml/schemas/advanced.html 

There is first a range value of any, like this.
```
label:
    description: "Label of the object"
    required: true
    range: Any
    any_of:
      - range: string
      - range: integer
      - range: boolean
  value:
    description: "Value of the object"
    required: true
    range: Any
    any_of:
      - range: string
      - range: integer
      - range: boolean
```
You will also have to define the Any class.

```
classes:

  Any:
    class_uri: linkml:Any
```
I hope that helps!
