### ISSUE TITLE
erdiagram export: identifier rendered as optional relation

### ISSUE THREAD

**Issue by stanleyj-edsn** [linkml/linkml#2328]
**Describe the bug**

when an identifier attribute's range is Any, it is drawn as an optional relation, despite identifier=true implying required=true

Example:
```yaml
classes:
  Any:
    class_uri: linkml:Any

MyClass:
   attributes:
      my_attribute:
        identifier: true
        range: Any
        any_of:
          - range: integer
          - range: MyEnum


enums:
  MyEnum:
    permissible_values:
      A:
      B:
      C:
```

version: 1.8.3
