### ISSUE TITLE
Additional keys for UI schema definitions

### ISSUE THREAD

**Issue by Duanoc** [linkml/linkml#2339]
**What is your feature request?**
I am currently testing linkml to define the forms for our electronic lab notebook (ELN) to collect structured metadata.
To generate the forms in the ELN a json schema could be used directly in some cases. But to use the fully functionality additional parameters for the form definition are recommended.
To describe the forms a configuration file is needed and my intention was to exend the json schema with additional configurational propoerties like in json forms (https://jsonforms.io/).
They are needed to describe e.g. the input type in the form, additional handling for displaying within a template, etc.
How can I add additional key value pairs in the json schema? 

One workaround is to miss use the description key and define a json object as value.
I need the additional keys on class and on slot level.
The key 'notes' or 'comments' are not exported by 'gen-json-schema'.
Better would be using annotations. Within annotations I can use any key value pairs.

Another workaround would be to write a script which extracts the annotations and extends the json schema (e.g. using patchjson) or write a matching UI schema file. Theoretically the annotation keys can be validated. But following the example written in the [documentation](https://linkml.io/linkml/schemas/annotations.html#annotations) I could not create a annotation key validation, any key was accepted, when running `gen-json-schema Annotation_test.yaml`. Can you provide a working example?

<details>
  <summary>Annotation_test.yaml</summary>
  
  ```yaml
id: https://example.org/Annotation_test/
name: Annotation_test
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types

classes:
  Person:
    instantiates:
      - mymetamodel:Reviewable
    annotations:
      review: A very useful class that is well defined
      input_type: combobox
    attributes:
      name:
        description: the name of a person
        instantiates: Reviewable
        annotations:
          review3: A very useful attribute that is well defined
  Reviewable:
    class_uri: mymetamodel:Reviewable
    attributes:
      review:
        description: an expert review of a schema element
        range: string
  ```
</details>

What is your suggestion how to solve my task if it is possible with linkml?
Or should a new generator be implemented to create a ui-schema.json file?

**How important is this feature to you?** Select from the options below:
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**Additional context**
jsonforms.io is just one example. There might be other standards to describe the ui schema.
