### ISSUE TITLE
SchemaView.induced_enum does not induce permissible values from `reachable_from`

### ISSUE THREAD

**Issue by sneakers-the-rat** [linkml/linkml#2343]
**Describe the bug**
from discussion in https://github.com/linkml/linkml/pull/2303
related to, but seems distinct from: https://github.com/linkml/linkml/issues/1690

this is described in the docs as being possible to do, but as far as i can tell it only happens once in the biolink ontology:

```yaml
enums:
  AnatomicalContextQualifierEnum:
    reachable_from:
      source_ontology: bioregistry:uberon
      source_nodes:
        - UBERON:0001062
      is_direct: false
      relationship_types:
        - rdfs:subClassOf
```

but schemaview doesn't actually do that, and i'm not sure if the logic to actually compute a reachability query exists anywhere within linkml? i'd actually really like to see it because the description in the metamodel sounds cool.

The docs mention this package (which i also haven't seen before and also looks cool): https://github.com/INCATools/ontology-access-kit and `vskit` seems to be this? https://github.com/INCATools/ontology-access-kit/blob/main/src/oaklib/utilities/subsets/value_set_expander.py

but i can't start on an impl for linkml because the enum in the biolink model lists `source_ontology` as `bioregistry:uberon` and i can't find the `bioregistry` prefix.

However I can create an expanded schema with vskit, and that yields an enum with 16,121 possible values (!!!!! i understand why this feature was needed !!!!!).

So it seems like the ability to expand a schema needs to be ported over from `oaklib`, but it has ~30 top-level dependencies so we probably don't want to have `linkml-runtime` depend on it. That, or we can emit a warning that someone needs to expand the schema before generating from it when `reachable_from` is encountered in a schema. 

idk i don't really have strong feelings about what needs to happen here, i just wanted to raise the issue as a partial "sorry here i'll do some work to pay back how much of your time i took up in the graphql pr" and stop hounding it lol.

**Version of LinkML you are using**

`HEAD@main`

**Please provide a schema (and if applicable, a data file) that replicates the issue**
(biolink schema in repo)
