### ISSUE TITLE
Incorrect multiplicity and (bidirectional) relationship representation in generated diagrams

### ISSUE THREAD

**Issue by stanleyj-edsn** [linkml/linkml#2350]
Consider the following scenario:

- A **Tourist** optionally stays at a **Hotel**.
- We store the information about which hotel the tourist stays in a field called `stays at`.

The minimum LinkML representation is as follows:

```yaml
id: tourist
default_prefix: https://www.example.com/tourist/

classes:
  Tourist:
    attributes:
      stays at:
        range: Hotel
  Hotel:
```

## Issue: mermaid output

When rendering this using `erdiagram`, the output is:

```mermaid
erDiagram
  Tourist ||--o| Hotel : "stays at"
```

**Problem:**
The generated diagram implies that a **Hotel** has exactly one **Tourist**. This is incorrect because the model does not specify the multiplicity on the **Tourist** side. 

**Proposed Solution:**
The Mermaid generator should not imply any multiplicity information if it cannot determine it from the model.

## Issue: PlantUML output

When rendering with `plantuml`, the output is:

![UML](https://www.plantuml.com/plantuml/svg/PSwz2i9040JWVfzYsL98I5eBIMbbPHTIhBa53-_dkDqK8UJT5KGjx0Q-6PX1ZQijCO0-V2fSEMBAJbGAzXtSlHESVPs3lBF4OYj6YJUf2dDWLQHhNgfN8np7xPAJxDE46y3-yNCs2V_wsnsQveJKjMrFt_OHIOrNHJQ2GP9xdNm2)

**Problem:**
The diagram suggests a composition relationship, indicating that a **Hotel** belongs to a **Tourist**, which is incorrect. The model does not specify any composition relationship.

**Proposed Solution:**
The PlantUML generator should not imply a composition relationship unless explicitly defined in the LinkML model.

## Desired Outcome

I would like to define a **bidirectional relationship** between **Tourist** and **Hotel**:
- From **Tourist** to **Hotel**, the relation is called `stays at`.
- From **Hotel** to **Tourist**, the relation is called `guests`, and it is **multivalued** (i.e., a hotel can have multiple guests).

LinkML provides the [`inverse`](https://linkml.io/linkml-model/latest/docs/inverse/) field to handle bidirectional relationships. Can the `inverse` option resolve the issue of setting the multiplicity of a bidirectional relation?
Using the `inverse` option, the diagram should look like this:

```mermaid
erDiagram
  Tourist }o--o| Hotel : ""
```

This properly represents the relationship:
- A **Tourist** can optionally stay at a **Hotel** (zero-to-one from **Tourist**'s perspective).
- A **Hotel** can have multiple **Tourist** guests (zero-to-many from **Hotel**'s perspective).

### Request

Can the diagram generators be updated to:
- Not imply specific multiplicity or composition relationships if they cannot be determined from the model.
- Correctly represent bidirectional relationships, perhaps using the `inverse` option, ensuring that both sides of the relationship are accurately depicted in diagrams.

**Comment by sierra-moxon** [comment]
Thank you for the thoughtful and well-written ticket @stanleyj-edsn!

**Comment by sierra-moxon** [comment]
from dev call:
- schemaview should be used to infer cardinality on the tail of the diagram.

**Comment by nlharris** [comment]
Wow, that may be the most labels I've seen on a single issue! 😅

**Comment by sneakers-the-rat** [comment]
When would the tail on the graph not be zero-or-many?

**Comment by stanleyj-edsn** [comment]
> When would the tail on the graph not be zero-or-many?

There is no reason or logic to assume this is logically true.

I can come up with examples if needed, but implementing such an assumption would result in new bug reports similar to this one (false implications).

**Comment by sneakers-the-rat** [comment]
it was a question, so please do post any examples for each of the cases in the mermaid ER diagram domain so we can fix the generator :)

**Comment by stanleyj-edsn** [comment]
This is a simplified example based on a real case:
```mermaid
erDiagram
  Device ||--o{ Usage : "usages"
  Usage |o--|| Location : "at"
```

Device is composed of zero or more Usages (composition cannot be visualised using mermaid ER), but in LinkML I would mark it as an `inlined`
A Usage always refers to a Location, but a Location does not necessarly have a Device. The **at** relation is an attribute defined at Usage. 
In LinkML, Usage may have `represents_relationship: true`

**Comment by sneakers-the-rat** [comment]
great! didn't know we had reification/rdf-star-like constructs in linkml.

so for a concrete example [following the docs](https://github.com/linkml/linkml/blob/c4379e5a121732b6adda21284bb34dde590743b1/docs/faq/modeling.md?plain=1#L479-L511) and being super explicit, to specify a zero-or-one to exactly-one relationship (like `usage |o--|| location` in mermaid) between usage and location we would do something like

```yaml
enums:
  predicate_enum:
    permissible_values:
      used_at:

classes:
  Device:
  Location:
  Usage:
    slots:
    - subject
    - object
    - predicate
    slot_usage:
      subject:
        multivalued: false
        required: false
        range: Device
      predicate:
        equals_string: used_at
      object:
        multivalued: false
        required: true
        range: Location
 
slots:
  predicate: 
    range: predicate_enum
    relational_role: PREDICATE
  subject:
    relational_role: SUBJECT
  object:
    relational_role: OBJECT
    
```

( i'm not sure about my `equals_string` there, please correct me if there's a different way of specifying a fixed value for a slot within a class from an enum )

is `represents_relationship: true` the only way to declare the cardinality on the `subject` side? (again just trying to scope out what the fix should be for a PR, please tell me if there are more mechanisms)
