### ISSUE TITLE
Declaring a slot with `range: string`, `multivalued: true` and `inlined: true` results in the error `KeyError: string`

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2356]
**Describe the bug**

Declaring a slot with `range: string`, `multivalued: true` and `inlined: true` results in the error `KeyError: string`. 

Such a slot declaration does not make much sense (since inlining is only for objects), but the reported error provides so scarce information, that it very difficult to find the error in the schema.

**Version of LinkML you are using**

v1.8.4

**Please provide a schema (and if applicable, a data file) that replicates the issue**

The issue can be reproduced with this very simple schema:
``` yaml
id: https://example.org/test-inlined-string
name: Test-inlined-string
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  MyClass:
    attributes:
      my_slot:
        range: string
        multivalued: true
        inlined: true
```
