### ISSUE TITLE
feature request: custom subset generation

### ISSUE THREAD

**Issue by ramonawalls** [linkml/linkml#238]
It would be nice to be able to generate custom subset of a schema, like we do when we generate import modules from ontologies. This would be particularly helpful for large schemas like Biolink.

**Comment by cmungall** [comment]
I can think of two broad approaches

 1. selective imports, as is common for most programming languages
     - e.g. the equivalent of `from biolink import Gene, Disease, `
 2. analog of robot extract

I prefer 1. 

Note that another reuse pattern is to define your own classes and reuse the class_uri. This is not very obo-esque, but it can avoid some of the brittleness that we see with obo.

**Comment by cmungall** [comment]
something like:

```yaml
imports:
  "linkml:types": 
    - string
  biolink:
     - Gene
     - Protein
     - Disease
```
