### ISSUE TITLE
SHACL generation ignores `all_of`, `none_of`, and `exactly_one_of`

### ISSUE THREAD

**Issue by elichad** [linkml/linkml#2400]
**Describe the bug**
@floWetzels, @dnlbauer and I are developing a LinkML schema and converting to SHACL. When we use `any_of`, this is converted to a `sh:or` statement in the SHACL, as expected.
LinkML:
```
slots:
  main_entity:
    required: true
    slot_uri: schema:mainEntity
    description: Check if the Main Workflow is specified through a `mainEntity` property in the root data entity
    annotations:
      sh:message: The Main Workflow must be specified through a `mainEntity` property in the root data entity
    any_of:
      - range: Person
      - range: ComputationalWorkflow
      - range: Workflow
```
Result:
```ro-crate:RootDataEntity a sh:NodeShape ;
    sh:closed false ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:description "Check if the Main Workflow is specified through a `mainEntity` property in the root data entity" ;
            sh:maxCount 1 ;
            sh:minCount 1 ;
            sh:or ( [ sh:class schema1:Person ] [ sh:class bioschemas:ComputationalWorkflow ] [ sh:class schema1:CreativeWork ] ) ;
            sh:order 0 ;
            sh:path schema1:mainEntity ] ;
    sh:targetClass ro-crate:RootDataEntity .
```

However, when we use `all_of` with the same constraints, this is **not** represented in the SHACL, and the default `sh:datatype xsd:string` is used. We expected to see a `sh:and` statement, but there is nothing like this present. The same is true when using `none_of` and `exactly_one_of`.
```
slots:
  main_entity:
    required: true
    slot_uri: schema:mainEntity
    description: Check if the Main Workflow is specified through a `mainEntity` property in the root data entity
    annotations:
      sh:message: The Main Workflow must be specified through a `mainEntity` property in the root data entity
    all_of:
      - range: Person
      - range: ComputationalWorkflow
      - range: Workflow
```
SHACL:
```
ro-crate:RootDataEntity a sh:NodeShape ;
    sh:closed false ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:datatype xsd:string ;
            sh:description "Check if the Main Workflow is specified through a `mainEntity` property in the root data entity" ;
            sh:maxCount 1 ;
            sh:message "The Main Workflow must be specified through a `mainEntity` property in the root data entity"^^xsd:string ;
            sh:minCount 1 ;
            sh:nodeKind sh:Literal ;
            sh:order 0 ;
            sh:path schema1:mainEntity ] ;
    sh:targetClass ro-crate:RootDataEntity .
```

**Version of LinkML you are using**
1.8.4

**Please provide a schema (and if applicable, a data file) that replicates the issue**
You can include this in th issue if small, or provide a link e.g. to github.
Ideally a minimal example that replicates the problem is ideal, but only if this is easy for you.

Here's our current working schema. We did also try including `range: Any` as seen in [this example](https://linkml.io/linkml/schemas/advanced.html#unions-as-ranges) but it didn't make any real difference.
```
id: https://github.com/crs4/rocrate-validator/profiles/workflow-ro-crate/linkml
name: workflow_ro_crate
prefixes:
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
  ORCID: https://orcid.org/
  bioschemas: https://bioschemas.org/
  roterms: http://purl.org/ro/roterms#
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  sh: http://www.w3.org/ns/shacl#
  ro-crate: https://github.com/crs4/rocrate-validator/profiles/ro-crate/
  workflow-ro-crate: https://github.com/crs4/rocrate-validator/profiles/workflow-ro-crate/
imports:
  - linkml:types
default_range: string

classes:
  # basic classes, no validation performed?
  WorkflowROCrateRootDataEntity:
    class_uri: ro-crate:RootDataEntity
    mixins:
      - MainEntityPropertyMustExist

  # validation classes
  MainEntityPropertyMustExist:
    mixin: true
    title: Main Workflow entity existence
    description: >-
      The Main Workflow must be specified through a `mainEntity` property in the root data entity
    slots:
      - main_entity 

  Workflow:
    class_uri: schema:CreativeWork
  ComputationalWorkflow:
    class_uri: bioschemas:ComputationalWorkflow
  Person:
    class_uri: schema:Person
  Any:
    class_uri: linkml:Any
  
slots:
  main_entity:
    required: true
    slot_uri: schema:mainEntity
    description: Check if the Main Workflow is specified through a `mainEntity` property in the root data entity
    annotations:
      sh:message: The Main Workflow must be specified through a `mainEntity` property in the root data entity
    # range: Any
    all_of:
      - range: Person
      - range: ComputationalWorkflow
      - range: Workflow
```
