### ISSUE TITLE
Ambiguous attributes should not be accepted ?

### ISSUE THREAD

**Issue by vincentkelleher** [linkml/linkml#2403]
**Describe the bug**

In a case where a schema has ambiguous class attributes, the `SchemaView.get_slot(...)` method should throw an exception rather than returning the first attribute it can find with less details about it.

Here is the test case I used to reproduce the issue :

```yaml
id: https://examples.org/get-slot-with-attribute#
name: get-slot-with-attribute

prefixes:
  test: https://examples.org/get-slot-with-attribute#

default_prefix: test
default_range: string

classes:
  ClassWithAttributes:
    attributes:
      randomAttribute:
        description: "A random attribute for testing purposes"
        range: integer
        minimum_value: 0
        maximum_value: 999

  ImportantSecondClass:
    description: "Important class to reproduce the error I got as the class loop needs to have at least a 
              second iteration"
    attributes:
      randomAttribute:
        description: "Now you see the ambiguity intensifying ?"
        range: integer
        minimum_value: 0
        maximum_value: 111
```

In my case, the unexpected behaviour comes from [this part of the code base](https://github.com/linkml/linkml-runtime/blob/main/linkml_runtime/utils/schemaview.py#L634) which returns a `SlotDefinition` with its name only.

I would imagine that attributes are made to bring ease of use but in the case above the user should be *forced* to define a slot instead through an exception.

What do you think ?

**Comment by sierra-moxon** [comment]
+1 from me

**Comment by sneakers-the-rat** [comment]
Totally agree. I don't think that we should *ever* return an attribute there, but returning an empty SlotDefinition that just has the name is just confusing.

I think that method should have `attributes` and `strict` removed from the signature and only ever return slots. attributes are only meaningful within the context of a class, and it is unclear to me when someone would want to get any attribute defined within any class by a specific name rather than with something like `class_slots`

if we wanted to preserve that behavior it seems like it should go be in a `get_attribute` method that similarly does not return slots.

**Comment by vincentkelleher** [comment]
@sneakers-the-rat I always got the impression that attributes were introduced to ease OOP developers into the LinkML/ontology paradigm as getting your head around the fact that a slot is a unique property that can be assigned to any class is complicated at first for us (OOP developers). Meaning that I imagined that attributes were transformed into slots but it's not exactly the case.

I find it hard to justify separating attributes and slots, can someone clarify why attributes exist so we can be on the same page ? 😊

**Comment by sneakers-the-rat** [comment]
for me personally as someone who is an outside observer and was not part of 99.999% of the metamodel's creation, i think attributes make both semantic and syntactic sense - bridging OOP and other paradigms that might be more slot-forward is a genuine achievement and needs some glue between the impedance mismatches somewhere, and attributes are a pretty intuitive compromise among possible universes i think. 

Semantically, things exist, and things sometimes have properties that are private/unique to them. It makes sense to differentiate between "things that could be true of anything" and "things that can only apply to this thing." I think this is especially true when thinking about the practicalities of linked data, where being able to to incremental refinement is a pretty natural modeling desire, but without a shorthand for "refinement of this thing within the context of this other thing" we would be left in RDF-soup land having to parse a million gradations of a slot disembodied from context. In the world where i was dictator of linkml, i would make it canonical for all slots and attributes used within a class to have implicit uris of `base_prefix:Classname.{Slot|Attribute}Name` alongside the URI for the slot used outside of the class `base_prefix:SlotName` with a `owl:equivalentProperty` for attributes/slots with no changes from e.g. attribute overrides, rules, slot_usage, etc. and `rdfs:subClassOf` for attributes/slots with changes. 

Syntactically i think it also makes sense to differentiate between the two cases above^ (unchanged/vs. changed) as well as from an authorship POV: I myself often switch between defining everything as slots and wanting to define things within the context of a class. I think it can be easy to underrate the lowered cognitive barriers for researchers/data-havers generally who aren't used to the cognitive inversion of "predicates first" in RDF universe, and having a syntactic olive branch back to OOP thinking that has a smooth transition into predicate-land is especially easy to underrate.

Also syntactically, I have a known difference of preference between nominal/structural typing, where linkml is very much a nominally-typed system but i often want to edge towards structural typing (and am often wrong, as i am seeing while implementing rustgen how nice it is to not have to worry about structural type inference). So to me getting rid of the *metamodel slot named `attributes`* is different than getting rid of the *abstract notion of attributes* - i wouldn't mind a declaration like this

```yaml
classes:
  MyClass:
    slots:
      pure_slot:
      pure_slot_2:
      attribute_or_modified_slot:
        description: "idk i changed it somehow"
        max_cardinality: 5 # always a good idea
```

or equivalently

```
classes:
  MyClass:
    slots:
    - pure_slot
    - pure_slot_2
    - name: attribute_or_modified_slot
      description: idk i changed it somehow
      max_cardinality: 5
```

anyway, getting back to the issue at hand - i can be reductive sometimes in thinking that "schemaview is all that matters" as the thing that materializes schema, but i think here it would definitely be good to make schemaview be a bit of a semantic guide, differentiating between `slots` as *always referring to the schema-level slot-definitions* and `attributes` as *always referring to slots-or-attributes when used within the context of a class*
