### ISSUE TITLE
missing keys for required, multivalued, annotations during linkml-map transformation for in slots

### ISSUE THREAD

**Issue by Duanoc** [linkml/linkml#2411]
**Describe the bug**
I tried to convert a schema like below into a new schema using linkml-map basically renaming the attributes.
In the resulting yaml file the tags `required`, `multivalued` and `annotations` are incomplete. `Multivalued` and `required` are copied for the `tree_root`/`Class1` class but not for the `Class2`. Where as `annotations` are copied for the classes but not for the slots. It this the correct behavior or a bug?

**Version of LinkML you are using**
linkml_map-0.3.8

**Please provide a schema (and if applicable, a data file) that replicates the issue**

```yaml
classes:
  Class1:
    tree_root: true
    annotations:
      key: value
    attributes:
      att1:
        required: true
        multivalued: true
        annotations:
          key: value
      att2:
        range: Class2
        required: true

  Class2:
    attributes:
      att3:
        required: true
        multivalued: true
        annotations:
          key: value
      att4:
        range: Class2
        required: true
```
