### ISSUE TITLE
SHACL annotations are skipped on slots/properties where `any_of` is used

### ISSUE THREAD

**Issue by elichad** [linkml/linkml#2417]
**Describe the bug**
 I have a slot called `license` as follows (the specific details aren't important):
```
license:
    required: true
    slot_uri: schema:license
    title: Crate license
    description: The Crate must specify a license
    annotations:
      sh:message: The Crate (Root Data Entity) must specify a license, which should be a URL but can also be a string
    any_of:
      - range: CreativeWork
      - range: string
```
When this is converted to SHACL (with `--include-annotations`), the relevant output is:
```
sh:property [ sh:description "The Crate must specify a license" ;
            sh:maxCount 1 ;
            sh:minCount 1 ;
            sh:name "Crate license" ;
            sh:or ( [ sh:class schema1:CreativeWork ] [ sh:datatype xsd:string ;
                        sh:nodeKind sh:Literal ] ) ;
            sh:order 1 ;
            sh:path schema1:license ],
```
Note that the `sh:message` annotation is missing.
When I _remove_ the `any_of` statement and use simply `range: string` instead, the output becomes:
```
sh:property [ sh:datatype xsd:string ;
            sh:description "The Crate must specify a license" ;
            sh:maxCount 1 ;
            sh:message "The Crate (Root Data Entity) must specify a license, which should be a URL but can also be a string"^^xsd:string ;
            sh:minCount 1 ;
            sh:name "Crate license" ;
            sh:nodeKind sh:Literal ;
            sh:order 1 ;
            sh:path schema1:license ],
```
`sh:message` has now been included.

I have other slots in the same schema which also use annotations with `sh:message` - only the slot using `any_of` is affected.
This omission of `sh:message` does _not_ occur when I use `all_of` instead of `any_of` - but I think that is because that doesn't get converted to SHACL at all, see #2400.

**Version of LinkML you are using**
1.8.4

**Please provide a schema (and if applicable, a data file) that replicates the issue**
You can include this in th issue if small, or provide a link e.g. to github.
Ideally a minimal example that replicates the problem is ideal, but only if this is easy for you.

```
id: https://github.com/crs4/rocrate-validator/profiles/workflow-ro-crate/linkml
name: workflow_ro_crate
prefixes:
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
  ORCID: https://orcid.org/
  bioschemas: https://bioschemas.org/
  roterms: http://purl.org/ro/roterms#
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  sh: http://www.w3.org/ns/shacl#
  ro-crate: https://github.com/crs4/rocrate-validator/profiles/ro-crate/
  workflow-ro-crate: https://github.com/crs4/rocrate-validator/profiles/workflow-ro-crate/
imports:
  - linkml:types
default_range: string

classes:
  # validation class
  WorkflowROCrateRootDataEntity:
    title: WROC Root Data Entity Required Properties
    description: Root Data Entity properties defined as MUST
    class_uri: ro-crate:RootDataEntity
    slots:
      - main_entity
      - license

  # schema.org wrappers
  Workflow:
    class_uri: schema:CreativeWork
  CreativeWork:
    class_uri: schema:CreativeWork

# individual property requirements
slots:
  main_entity:
    required: true
    slot_uri: schema:mainEntity
    range: Workflow
    title: Main Workflow entity existence
    description: Check if the Main Workflow is specified through a `mainEntity` property in the root data entity
    annotations:
      sh:message: The Main Workflow must be specified through a `mainEntity` property in the root data entity
  license:
    required: true
    slot_uri: schema:license
    title: Crate license
    description: The Crate must specify a license
    annotations:
      sh:message: The Crate (Root Data Entity) must specify a license, which should be a URL but can also be a string
    any_of:
      - range: CreativeWork
      - range: string
```
