### ISSUE TITLE
run-examples fails on inlining as simple dictionary

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2423]
**Describe the bug**

Running `linkml examples` fails when [inlining as simple dictionary](https://linkml.io/linkml/schemas/inlining.html#inlining-as-simple-dictionaries) being used. More details to reproduce it below.

The error being reported is (being `prop1` a key of the simple dictionary):
```
ValueError: Example valid-examples/Thing-001.yaml failed validation:
No such slot prop1 as an attribute of Property ancestors or as a slot definition in the schema
```

[Validation](https://github.com/linkml/linkml/blob/da294e6f3bf5c36c7d7333c7e7312ad70b45941b/linkml/workspaces/example_runner.py#L185) is fine, the issue appears when [trying to load the object](https://github.com/linkml/linkml/blob/da294e6f3bf5c36c7d7333c7e7312ad70b45941b/linkml/workspaces/example_runner.py#L249) from a [previously created dictionary](https://github.com/linkml/linkml/blob/da294e6f3bf5c36c7d7333c7e7312ad70b45941b/linkml/workspaces/example_runner.py#L177) loading the example. At that point the key of the simple dictionary is being interpreted as a slot of an object, therefore it fails. As of now, I cannot tell if the issue is how the dictionary is being created or how the object is being loaded from the dictionary, but I suspect that it is the second.

**Version of LinkML you are using** v1.8.5

**Please provide a schema (and if applicable, a data file) that replicates the issue**

Simple schema to reproduce the issue:
```yaml
# schema.yaml
id: https://example.org/
name: example
prefixes:
  example: https://example.org/
  linkml: https://w3id.org/linkml/
default_prefix: example
default_range: string
imports:
  - linkml:types
classes:
  Thing:
    attributes:
      properties:
        range: Property
        multivalued: true
        inlined: true
        inlined_as_list: false
  Property:
    attributes:
      name:
        identifier: true
      value:
        required: true
```

Simple valid example:
```yaml
# valid-examples/Thing-001.yaml
properties:
  prop1: "something"
  prop2: "some other thing"
```

Command line to reproduce the issue: `linkml examples -s schema.yaml -e valid-examples -d output`.
