### ISSUE TITLE
 run-examples fails on inlining as dictionary

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2425]
**Describe the bug**

The generic form of #2423. The same issue appears on inlined dictionaries.

**Version of LinkML you are using** v1.8.5

**Please provide a schema (and if applicable, a data file) that replicates the issue**

```yaml
# schema.yaml
id: https://example.org/
name: example
prefixes:
  example: https://example.org/
  linkml: https://w3id.org/linkml/
default_prefix: example
default_range: string
imports:
  - linkml:types
classes:
  Thing:
    attributes:
      parameters:
        range: Parameter
        multivalued: true
        inlined: true
        inlined_as_list: false
  Parameter:
    attributes:
      name:
        identifier: true
      value1:
        required: true
      value2:
        required: true
```

```yaml
# valid-examples/Thing-001.yaml
parameters:
  parm1:
    value1: "a value"
    value2: "another value"
  parm2:
    value1: "yet another value"
    value2: "a value"
```
