### ISSUE TITLE
feature: adding actions to the LinkML model for modelling dataprocessing and lab workflows

### ISSUE THREAD

**Issue by markdoerr** [linkml/linkml#2431]
**What is your feature request?**

Currently LinkML is very well designed to model data (hierarchies of data / classes / subclasses).
In the future, it might be very powerful to add the ability to add **actions** to the data (similar to a function/method call).

This can be used to, e.g. generate "real" classes with associated method interfaces.
One use case could be to model laboratory or data processing workflows, specifying the data and the operations, which could be done with the data. The ability to specify target methods/actions  is missing in LinkML for this purpose.

One way, one could model this could be by adding an **actions** section next to **slots** sections:
```
classes:
  Labworkflow:
    actions:
      - aspirate
      - dispense
      - mix

actions:
  aspirate:
   - slots:
     - volume
     - volume_change_velocity
  dispense:
   - slots:
     - volume
     - volume_change_velocity
  [...]
  
slots:
  volume:
    range: float
    unit: litre # IRI to unit
  volume_change_velocity:
    description: volume change per second

```

**How important is this feature to you?** Select from the options below:
• Medium - it would open up a huge field of applications to LinkML, e.g. all work flows in laboratory could be then modeled with LinkML, or the combination of lab operations and data that is collected during these operations - think, e.g. of a spectroscopic measurement: one could model the data the is generated by the spectrometer, but also the procedures / actions that have been performed to achieve the measurement). These workflow models could then be used to generate interfaces / blueprints for workflow engines.

**Additional context**
One target could be, e.g., generating prototype code for the [prefect workflow execution engine](https://github.com/PrefectHQ/prefect).
