### ISSUE TITLE
`gen-linkml` complains about schemas with `contexts` values in `StructuredAlias`es

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#2434]
```yaml
name: test_schema
id: https://w3id.org/nmdc/test_schema
enums:
  SomeEnum:
    permissible_values:
      some_pv:
        structured_aliases:
          some_alias:
            literal_form: some_alias
            predicate: NARROW_SYNONYM
            contexts:
              - https://example.com/
```

```shell
gen-linkml --format yaml test_schema.yaml 
```

> ValueError:  Unknown argument: contexts = ['https://example.com/']
