### ISSUE TITLE
Windows: 

### ISSUE THREAD

**Issue by melonora** [linkml/linkml#2437]
**Describe the bug**
using the command `gen_pydantic` on a schema doing an import of `linkml:types` the following warning is given:
```
WARNING:rdflib.term:C:\ProgramData\miniforge3\envs\spatialdata_new\Lib\site-packages\linkml_runtime\linkml_model\model\schema\types does not look like a valid URI, trying to serialize this will break.
```

**Version of LinkML you are using**
LinkML 1.8.5.

**Please provide a schema (and if applicable, a data file) that replicates the issue**
```
id: cell_type_summary_schema
name: CellTypeSummarySchema
description: A schema for summarizing cell type annotation information from an AnnData table.
prefixes:
  linkml: https://w3id.org/linkml/
  example: http://www.example.org/rdf#
  EFO: http://www.ebi.ac.uk/efo/EFO_
default_prefix: example
default_range: string
imports:
  - linkml:types

classes:
  CellTypeAnnotationSummary:
    description: Represents the summarized information extracted from a table.
    attributes:
      cell_type_statistics:
        description: Summary statistics for each cell type.
        range: string
   ```
