### ISSUE TITLE
Generated JSON-Schema allows "null" on identifiers

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2448]
**Describe the bug**
Generated JSON-Schema allows "null" on identifiers (slots with the attribute `identifier: true`) if a `range` is specified and `required` is not explicitly specified.

The `range` can be explicitly declared in the slot or over `default_range: [...]`.

**Version of LinkML you are using** Any from v1.8.2 upwards

**Please provide a schema (and if applicable, a data file) that replicates the issue**

Git history bisected to identify commit 2bd1c19892201b2d2030a8708cf4801fe276ea9a as the one introducing the bug.

Schema to reproduce the issue:
```yaml
id: https://example.org/nullable-id
name: nullable-id
prefixes:
  linkml: https://w3id.org/linkml/
  ni: https://example.org/nullable-id/
imports:
  - linkml:types
default_range: string
classes:
  MyClass:
id: https://example.org/nullable-id
name: nullable-id
prefixes:
  linkml: https://w3id.org/linkml/
  ni: https://example.org/nullable-id/
imports:
  - linkml:types
default_range: string
  MyClass:
    attributes:
      id:
        identifier: true
      needed:
        required: true
      name:
```

Resulted in following JSON-Schema extract in version v1.8.2:
```json
{
  "id": {
    "type": [
      "string",
      "null"
    ]
  },
  "name": {
    "type": [
      "string",
      "null"
    ]
  },
  "needed": {
    "type": "string"
  }
}
```
