### ISSUE TITLE
Rules seem to only have access to some metamodel functions

### ISSUE THREAD

**Issue by timalamenciak** [linkml/linkml#2455]
**Describe the bug**
Emerged from #2452 

When specifying a rule, it does not allow direct use of the `range` class. This code works to restrict the colour slot to a particular enum:

```
        postconditions:
          slot_conditions:
            colour:
              any_of:
                - range: BluePink
```

But this code does not properly detect invalid entries:
```
postconditions:
          slot_conditions:
            colour:
              range: BluePink
```

**Version of LinkML you are using** 1.8.1

**Please provide a schema (and if applicable, a data file) that replicates the issue**

Full schema (toy example):

```
classes:
  Toys:
    attributes:
      species:
        range: SpeciesRng
      colour:
    rules:
      - preconditions:
          slot_conditions:
            species:
              equals_string: horse
        postconditions:
          slot_conditions:
            colour:
              any_of:
                - range: RedGreen
      - preconditions:
          slot_conditions:
            species:
              equals_string: frog
        postconditions:
          slot_conditions:
            colour:
              any_of:
                - range: BluePink

enums:
  SpeciesRng:
    permissible_values: 
      horse:
      frog:
  BluePink:
    permissible_values:
      blue:
      pink:
  RedGreen:
    permissible_values:
      red:
      green:
```

You can include this in th issue if small, or provide a link e.g. to github.
Ideally a minimal example that replicates the problem is ideal, but only if this is easy for you.
