### ISSUE TITLE
Use `multivalued` expression in the Pydantic generator 

### ISSUE THREAD

**Issue by multimeric** [linkml/linkml#2459]
**What is your feature request?**
If I understand https://github.com/linkml/linkml-model/pull/197 correctly, it's designed to allow a schema such as this:

```yml
slots:
    oneOrMoreStrings:
        range: string
        one_of:
            - multivalued: true
            - multivalued: false
```
Which should correspond to `oneOrMoreStrings = str | list[str]` in Python. However, using the codegen on such a schema ignores this and just gives you `oneOrMoreStrings: str`.

**How important is this feature to you?** Select from the options below:
Medium

**Comment by dalito** [comment]
I see a similar problem for:
```
slots:
  value:
    exactly_one_of:
      - range: string
      - range: ResourceInfo
      - range: LogRecord

```
`ResourceInfo` and `LogRecord` are classes. The schema has `default_range: string`.

In my case the pydantic generator produces also code that only accepts `str` but not the other allowed types:
```
    value: Optional[str] = Field(...)
```
