### ISSUE TITLE
SHACL generator: `has_member` is ignored

### ISSUE THREAD

**Issue by elichad** [linkml/linkml#2465]
**Describe the bug**
If `has_member` is used on a slot, it is ignored by the SHACL generator.

**Without** `has_member`:
```
slots:
  test_slot:
    slot_uri: schema:hasPart
    range: string
    equals_string: "abc"
```
Output:
```
sh:property [ sh:datatype xsd:string ;
            sh:in ( "abc" ) ;
            sh:maxCount 1 ;
            sh:nodeKind sh:Literal ;
            sh:order 0 ;
            sh:path schema1:hasPart ] ;
```

**With** `has_member`:
```
slots:
  test_slot:
    slot_uri: schema:hasPart
    range: string
    has_member:
      equals_string: "abc"
```
Output:
```
sh:property [ sh:datatype xsd:string ;
            sh:maxCount 1 ;
            sh:nodeKind sh:Literal ;
            sh:order 0 ;
            sh:path schema1:hasPart ] ;
```
The `sh:in` is now missing and there is no conditional present.

**Proposed solution**
The SHACL feature `sh:qualifiedValueShape` seems most appropriate here, as this uses a sub-shape that should be able to support anything nested under `has_member`. [SHACL spec reference](https://www.w3.org/TR/shacl/#QualifiedValueShapeConstraintComponent), [textbook reference](https://book.validatingrdf.com/bookHtml011.html#sec164)

**Version of LinkML you are using**
1.8.5

**Please provide a schema (and if applicable, a data file) that replicates the issue**
You can include this in th issue if small, or provide a link e.g. to github.
Ideally a minimal example that replicates the problem is ideal, but only if this is easy for you.
```
id: https://example.org
name: test_schema
prefixes:
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
imports:
  - linkml:types
default_range: string

classes:
  TestClass:
    class_uri: schema:Thing
    title: test class
    slots:
      - test_slot

slots:
  test_slot:
    slot_uri: schema:hasPart
    range: string
    has_member:
      equals_string: "abc"
```
