### ISSUE TITLE
`linkml lint` does not complain about multiple classes with `tree_root: true`

### ISSUE THREAD

**Issue by roblinksdata** [linkml/linkml#2466]
**Describe the bug**
Having multiple classes with `tree_root: true` does not represent a valid schema in my opinion. 

The linter does not pick this issue up, and claims that the schema is completely valid. 

Further, generators such as the json-schema generator seem to arbitrarily choose one of the classes with `tree_root: true` to be the winner. This isn't clearly defined behaviour (if it turns out that it is valid to have multiple classes with `tree_root: true`).

**Version of LinkML you are using**
linkml, version 1.8.5

**Please provide a schema (and if applicable, a data file) that replicates the issue**

```yaml
id: http://example.com/something/schema
name: something
prefixes: 
  linkml: https://w3id.org/linkml/
  some: http://example.com/something/
imports:
  - linkml:types

classes:
  Something:
    tree_root: true
    class_uri: some:Something
    description: A thing, something.
    attributes:
      id: 
        required: true
        identifier: true
        slot_uri: some:id
        description: An identifier.
        range: integer
      name: 
        required: true
        slot_uri: some:name
        description: A name.
        range: string

  Container:
    tree_root: true
    attributes:
      values:
        multivalued: true
        inlined_as_list: true
        range: Something
```

The behaviour of the linter:

```bash
$ linkml lint something-else.yaml 
.../something-else.yaml
  warning  Class 'Container' does not have recommended slot 'description'  (recommended)
  warning  Slot 'values' does not have recommended slot 'description'  (recommended)

✖ Found 2 problems in 1 schema
```
