### ISSUE TITLE
Difficulties with yes/no and boolean values.

### ISSUE THREAD

**Issue by timalamenciak** [linkml/linkml#2474]
**Describe the bug**
I have a slot called "refdata" in my dataset that is an answer to the question: "Was reference data provided?" It has two values: yes or no. I have approached this a number of ways. The first is using an enum:

```
refdata:
    range: RefDataRng
    description: Was reference data provided?
...
enums:
  RefDataRng:
    permissible_values:
      Yes:
      No:
```  
When I try to validate the data, it appears to automatically change "Yes" to "True" and "No" to "False" in the template and tries to validate my data against that:
```
[ERROR] [Project.csv/189] 'No' is not one of ['True', 'False'] in /refdata
[ERROR] [Project.csv/186] 'Yes' is not one of ['True', 'False'] in /refdata
```

If I change the values to "True" and "False" in Excel, it automatically uppercases them. If I them change the enum to "TRUE" and "FALSE," it still tries to validate them as "True" and "False."

If I make the slot `range: boolean`, it doesn't seem happy with either "TRUE" or "1"/"FALSE" or "0" as the values in that slot. 

If I change the enum to use different words, it validates fine:
```
  RefDataRng:
    permissible_values:
      Yay:
      Nay:
```
Erroneous input for verification purposes:
```
[ERROR] [Project.csv/97] 'Yaaaay' is not one of ['Yay', 'Nay'] in /refdata
```

So my guess is that the YAML parser has some kind of function to change "Yes:" and "No:" to "True:" and "False:" which causes problems.

**Version of LinkML you are using**
linkml-validate 1.8.1

**Please provide a schema (and if applicable, a data file) that replicates the issue**
The above snippets should reproduce the problem.

**Comment by rly** [comment]
LinkML uses `pyyaml` for parsing yaml (according to conversation with @cmungall), and `pyyaml` follows the YAML 1.1 spec, which interprets "Yes" as True and "No" as False, even when these strings are keys.

I *think* if you wrap the "Yes" and "No" keys with quotes, linkml will not interpret them as True/False.

```
refdata:
    range: RefDataRng
    description: Was reference data provided?
...
enums:
  RefDataRng:
    permissible_values:
      "Yes":
      "No":
```

Related: https://github.com/linkml/linkml/issues/1883
