### ISSUE TITLE
Type inheritance doesn't inherit `base` 

### ISSUE THREAD

**Issue by multimeric** [linkml/linkml#2485]
**Describe the bug**
If I have a schema that defines a subclass of `string`, it's base (ie Python) data type doesn't get inherited.

This causes downstream tooling like generators to break, because they rely on `base` existing.

**Version of LinkML you are using**
1.8.5

**Please provide a schema (and if applicable, a data file) that replicates the issue**

```yaml
name: example
id: http://example.org/example
imports:
- https://w3id.org/linkml/types
types:
  MyString:
    typeof: string
```

If I then load that schema, I'm not able to get the base type of `MyString`, even though it should be `str`. The inheritance relationship is clearly there, as is the link between `string` and `str`:

```python
>>> from linkml_runtime import SchemaView
>>> sv = SchemaView("/path/to/schema")
>>> sv.get_type("MyString").base
None
>>> sv.get_type("MyString").typeof
'string'
>>> sv.get_type("string").base
'str'
```
