### ISSUE TITLE
Import system: prefixed references in an imported file are broken

### ISSUE THREAD

**Issue by roblinksdata** [linkml/linkml#2494]
**Describe the bug**

Example configuration: 

```yaml
id: http://example.com/thing
name: Thing
prefixes: 
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
```

when I run `linkml generate yaml --mergeimports thing.yaml > merged.yaml` which essentially should just bring the contents of `linkml:types` into the current document, I get the following which contains now **broken `schema` prefixed imports`**.

N.B. [linkml:types](https://w3id.org/linkml/types.yaml) correctly references schema as a prefix `schema: http://schema.org/`.

**Also note that this appears to break a wide variety of tooling which relies upon the correct functioning of the import system.**

```yaml
name: Thing
id: http://example.com/thing
imports:
- linkml:types
license: https://creativecommons.org/publicdomain/zero/1.0/
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/
default_prefix: http://example.com/thing/
default_range: string
types:
  string:
    name: string
    definition_uri: https://w3id.org/linkml/String
    description: A character string
    notes:
    - In RDF serializations, a slot with range of string is treated as a literal or
      type xsd:string.   If you are authoring schemas in LinkML YAML, the type is
      referenced with the lower case "string".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    exact_mappings:
    - schema:Text
    base: str
    uri: xsd:string
  integer:
    name: integer
    definition_uri: https://w3id.org/linkml/Integer
    description: An integer
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "integer".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    exact_mappings:
    - schema:Integer
    base: int
    uri: xsd:integer
  boolean:
    name: boolean
    definition_uri: https://w3id.org/linkml/Boolean
    description: A binary (true or false) value
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "boolean".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    exact_mappings:
    - schema:Boolean
    base: Bool
    uri: xsd:boolean
    repr: bool
  float:
    name: float
    definition_uri: https://w3id.org/linkml/Float
    description: A real number that conforms to the xsd:float specification
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "float".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    exact_mappings:
    - schema:Float
    base: float
    uri: xsd:float
  double:
    name: double
    definition_uri: https://w3id.org/linkml/Double
    description: A real number that conforms to the xsd:double specification
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "double".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    close_mappings:
    - schema:Float
    base: float
    uri: xsd:double
  decimal:
    name: decimal
    definition_uri: https://w3id.org/linkml/Decimal
    description: A real number with arbitrary precision that conforms to the xsd:decimal
      specification
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "decimal".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    broad_mappings:
    - schema:Number
    base: Decimal
    uri: xsd:decimal
  time:
    name: time
    definition_uri: https://w3id.org/linkml/Time
    description: A time object represents a (local) time of day, independent of any
      particular day
    notes:
    - URI is dateTime because OWL reasoners do not work with straight date or time
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "time".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    exact_mappings:
    - schema:Time
    base: XSDTime
    uri: xsd:time
    repr: str
  date:
    name: date
    definition_uri: https://w3id.org/linkml/Date
    description: a date (year, month and day) in an idealized calendar
    notes:
    - URI is dateTime because OWL reasoners don't work with straight date or time
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "date".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    exact_mappings:
    - schema:Date
    base: XSDDate
    uri: xsd:date
    repr: str
  datetime:
    name: datetime
    definition_uri: https://w3id.org/linkml/Datetime
    description: The combination of a date and time
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "datetime".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    exact_mappings:
    - schema:DateTime
    base: XSDDateTime
    uri: xsd:dateTime
    repr: str
  date_or_datetime:
    name: date_or_datetime
    definition_uri: https://w3id.org/linkml/DateOrDatetime
    description: Either a date or a datetime
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "date_or_datetime".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    base: str
    uri: linkml:DateOrDatetime
    repr: str
  uriorcurie:
    name: uriorcurie
    definition_uri: https://w3id.org/linkml/Uriorcurie
    description: a URI or a CURIE
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "uriorcurie".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    base: URIorCURIE
    uri: xsd:anyURI
    repr: str
  curie:
    name: curie
    definition_uri: https://w3id.org/linkml/Curie
    conforms_to: https://www.w3.org/TR/curie/
    description: a compact URI
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "curie".
    comments:
    - in RDF serializations this MUST be expanded to a URI
    - in non-RDF serializations MAY be serialized as the compact representation
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    base: Curie
    uri: xsd:string
    repr: str
  uri:
    name: uri
    definition_uri: https://w3id.org/linkml/Uri
    conforms_to: https://www.ietf.org/rfc/rfc3987.txt
    description: a complete URI
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "uri".
    comments:
    - in RDF serializations a slot with range of uri is treated as a literal or type
      xsd:anyURI unless it is an identifier or a reference to an identifier, in which
      case it is translated directly to a node
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    close_mappings:
    - schema:URL
    base: URI
    uri: xsd:anyURI
    repr: str
  ncname:
    name: ncname
    definition_uri: https://w3id.org/linkml/Ncname
    description: Prefix part of CURIE
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "ncname".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    base: NCName
    uri: xsd:string
    repr: str
  objectidentifier:
    name: objectidentifier
    definition_uri: https://w3id.org/linkml/Objectidentifier
    description: A URI or CURIE that represents an object in the model.
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "objectidentifier".
    comments:
    - Used for inheritance and type checking
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    base: ElementIdentifier
    uri: shex:iri
    repr: str
  nodeidentifier:
    name: nodeidentifier
    definition_uri: https://w3id.org/linkml/Nodeidentifier
    description: A URI, CURIE or BNODE that represents a node in a model.
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "nodeidentifier".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    base: NodeIdentifier
    uri: shex:nonLiteral
    repr: str
  jsonpointer:
    name: jsonpointer
    definition_uri: https://w3id.org/linkml/Jsonpointer
    conforms_to: https://datatracker.ietf.org/doc/html/rfc6901
    description: A string encoding a JSON Pointer. The value of the string MUST conform
      to JSON Point syntax and SHOULD dereference to a valid object within the current
      instance document when encoded in tree form.
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "jsonpointer".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    base: str
    uri: xsd:string
    repr: str
  jsonpath:
    name: jsonpath
    definition_uri: https://w3id.org/linkml/Jsonpath
    conforms_to: https://www.ietf.org/archive/id/draft-goessner-dispatch-jsonpath-00.html
    description: A string encoding a JSON Path. The value of the string MUST conform
      to JSON Point syntax and SHOULD dereference to zero or more valid objects within
      the current instance document when encoded in tree form.
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "jsonpath".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    base: str
    uri: xsd:string
    repr: str
  sparqlpath:
    name: sparqlpath
    definition_uri: https://w3id.org/linkml/Sparqlpath
    conforms_to: https://www.w3.org/TR/sparql11-query/#propertypaths
    description: A string encoding a SPARQL Property Path. The value of the string
      MUST conform to SPARQL syntax and SHOULD dereference to zero or more valid objects
      within the current instance document when encoded as RDF.
    notes:
    - If you are authoring schemas in LinkML YAML, the type is referenced with the
      lower case "sparqlpath".
    from_schema: https://w3id.org/linkml/types
    imported_from: linkml:types
    base: str
    uri: xsd:string
    repr: str
metamodel_version: 1.7.0
source_file: thing.yaml
source_file_date: '2025-01-13T16:51:54'
source_file_size: 144
generation_date: '2025-01-13T16:53:29'
```

Note that `linkml lint merged.yaml` also erroneously returns the following:

```
✓ No problems found
```

**Version of LinkML you are using**

linkml, version 1.8.5

**Comment by roblinksdata** [comment]
Interestingly enough, running something similar appears to yield the correctly imported 

`linkml generate linkml --format yaml thing.yaml > thing.mat.yaml`

```yaml
name: Thing
id: http://example.com/thing
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/
  xsd:
    prefix_prefix: xsd
    prefix_reference: http://www.w3.org/2001/XMLSchema#
  shex:
    prefix_prefix: shex
    prefix_reference: http://www.w3.org/ns/shex#
  schema:
    prefix_prefix: schema
    prefix_reference: http://schema.org/
default_prefix: http://example.com/thing/
...
```
