### ISSUE TITLE
Make it possible to map a URI to an RDF Node

### ISSUE THREAD

**Issue by roblinksdata** [linkml/linkml#2495]
**What is your feature request?**

According to [Direct Translation of instance graphs to RDF](https://linkml.io/linkml-model/latest/docs/specification/06mapping/#direct-translation-of-instance-graphs-to-rdf) it does not seem that it is possible to design a model in which the use specifies a URI and that URI is then referenced as a **graph node** when the data is translated to RDF.

It appears that it is only possible to express URIs as a **literal** as in the following example:

```ttl
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://example.com/some-identifier> a schema:Dataset ;
    schema:isBasedOn "http://example.com/some-previous-dataset"^^xsd:anyURI.
```

This information could better be represented in the following way, where the URI points at a node in the graph:

```ttl
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://example.com/some-identifier> a schema:Dataset ;
    schema:isBasedOn <http://example.com/some-previous-dataset>.
```

Given that RDF is so deeply integrated into the linkml metamodel, this seems like a key feature that is missing. It's clear that the ability exists when `identifier` is set to `true` on a given slot, however there are plenty of predicates which don't identify an instance of a class, but nonetheless provide deep links into the web of linked data.

*How important is this feature to you?** 
• Important - it's a blocker and can't do work without it

**Comment by roblinksdata** [comment]
It seems it's possible to trick linkml in to serialising a URI as a reference to a node in the graph:

```yaml
...

prefixes: 
  schema: http://schema.org/
...

classes:

  UriasNode:
    description: Use this only in the `range` field of a slot to make a URI point at a node in an RDF graph.
    attributes:
      id: 
        description: You probably don't want to actually populate this field of the class, it's just here to support a reference.
        identifier: True
        required: True
        range: uriorcurie
...

slots:
  source_dataset_identifier:
    required: False
    multivalued: True
    slot_uri: schema:isBasedOn
    range: UriasNode
```

This can be used to generate RDF translations of the form

```ttl
@prefix schema: <http://schema.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<https://example.com/some-identifier> a schema:Dataset ;
    schema:isBasedOn <http://example.com/some-previous-dataset>.
```

Make sure that you **don't** set [inlined](https://linkml.io/linkml/schemas/inlining.html#) to `true` on the slot, else you'll end up with some undesirable artifacts of the form:

```ttl
<http://example.com/some-previous-dataset> a <http://example.com/dataset/:UriasNode> .
```

**Comment by roblinksdata** [comment]
I found the [secret documentation](https://github.com/linkml/linkml/issues/450#issuecomment-960356068) of how to do this!

Now sadly I've found a bug in the generation of the corresponding SHACL constraints. Example schema:

```yaml
# linkml generate json-schema --top-class Dataset dataset.yaml > dataset.schema.json 
id: http://example.com/marco-bolo/dataset
name: Dataset
prefixes: 
  rdfs: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
imports:
  - linkml:types


types:

  UriOrCurieAsNode:
    typeof: uriorcurie
    description: Use this only in the `range` field of a slot to make a URI point at a node in an RDF graph.
    base: str
    uri: rdfs:Resource


classes:

  Dataset:
    tree_root: True
    class_uri: schema:Dataset
    description: The MBO implementation of a schema:Dataset
    slots:
      - dataset_identifier
      - source_dataset_identifier

slots:

  dataset_identifier:
    identifier: True
    required: True
    description: An internal ID for the dataset.@en
    comments:
    - The identifier property represents any kind of identifier for any kind of <a
      class=\"localLink\" href=\"/Thing\">Thing</a>, such as ISBNs, GTIN codes, UUIDs
      etc. Schema.org provides dedicated properties for representing many of these,
      either as textual strings or as URL (URI) links. See <a href=\"/docs/datamodel.html#identifierBg\">background
      notes</a> for more details.@en
    slot_uri: schema:identifier
    range: uriorcurie
  
  source_dataset_identifier:
    required: False
    multivalued: True
    slot_uri: schema:isBasedOn
    range: UriOrCurieAsNode
```

Generates the following SHACL:

```ttl
@prefix rdfs1: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix schema1: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

schema1:Dataset a sh:NodeShape ;
    sh:closed true ;
    sh:description "The MBO implementation of a schema:Dataset" ;
    sh:ignoredProperties ( rdfs1:type ) ;
    sh:property [ sh:datatype xsd:anyURI ;
            sh:description "An internal ID for the dataset.@en" ;
            sh:maxCount 1 ;
            sh:minCount 1 ;
            sh:nodeKind sh:Literal ;
            sh:order 0 ;
            sh:path schema1:identifier ],
        [ sh:datatype rdfs1:Resource ;
            sh:nodeKind sh:Literal ;
            sh:order 1 ;
            sh:path schema1:isBasedOn ] ;
    sh:targetClass schema1:Dataset .
```

The `sh:nodeKind` should be an `sh:IRI`, not `sh:Literal` for the `source_dataset_identifier` slot. I'm also not entirely sure that `sh:dataType` is completely valid for such slots either - it isn't clear in the SHACL docs, but it only seems to make sense when used in conjunction with primitive/literal types.
