### ISSUE TITLE
Enums not serialised to JSON-LD as anticipated

### ISSUE THREAD

**Issue by roblinksdata** [linkml/linkml#2497]
**Describe the bug**

Given the following linkml schema:

```yaml
id: http://example.com/broken-enum-jsonld
name: Broken-Enum-JSON-LD

prefixes:
  stuff: http://example.com/stuff/

enums:
  SomeEnum:
    description: Some Enum
    permissible_values:
      some_value:
        meaning: stuff:SomeValue
      some_other_value:
        meaning: stuff:SomeOtherValue

classes:
  SomeClass:
    tree_root: True
    class_uri: stuff:SomeClass
    description: Some Class
    attributes:
      some_slot:
        multivalued: True
        slot_uri: stuff:someSlot
        description: Some Slot
        range: SomeEnum
```

When I convert the following JSON representation (which is validated as correct by linkml) into JSON-LD using linkml,

```json
{
    "some_slot": [
        "some_value",
        "some_other_value"
    ]
}
```

I end up with the following JSON-LD representation which **does not correctly represent the meaning `SomeEnum` as I would expect it to in RDF**:

```json
{
  "some_slot": [
    "some_value",
    "some_other_value"
  ],
  "@type": "SomeClass",
  "@context": {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "Broken-Enum-JSON-LD": "http://example.com/broken-enum-jsonld/",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "stuff": "http://example.com/stuff/",
    "@vocab": "http://example.com/broken-enum-jsonld/",
    "some_slot": {
      "@context": {
        "text": "skos:notation",
        "description": "skos:prefLabel",
        "meaning": "@id"
      },
      "@id": "stuff:someSlot"
    },
    "SomeClass": {
      "@id": "stuff:SomeClass"
    }
  }
}
``` 

Note that the URIs representing the `meaning` of the enum are not present anywhere in the document, that `some_slot` holds only the text values, but that the `@context` suggests that it should hold an object with `text`/`description`/`meaning` values.

Further, when I convert the JSON example to rdf/ttl I get the following output which aligns better with what I would expect in an RDF representation:

```ttl
@prefix stuff: <http://example.com/stuff/> .

[] a stuff:SomeClass ;
    stuff:someSlot stuff:SomeOtherValue,
        stuff:SomeValue .
```

**Version of LinkML you are using**

linkml, version 1.8.6
