### ISSUE TITLE
`structured_pattern` regex on Slot definition not expressed in JSON Schema (ignored in data validation too)

### ISSUE THREAD

**Issue by roblinksdata** [linkml/linkml#2499]
**Describe the bug**

When I define a regex `pattern` against a slot and generate a JSON schema, I get a valid JSON schema which correctly enforces the regular expression, however when I make use of a `structured_pattern` instead, it does not express the constraint in JSON schema, and **does not warn** that it has failed to do so.

Due to the default `linkml validate` approach being to write a JSON Schema and then to use that for validation, this bug has the effect of more-or-less completely (and **silently**) ignoring any `structured_pattern` regular expression in the linkml model.

## Using `pattern` works

```yaml
id: http://example.com/dataset
name: Dataset
prefixes: 
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
imports:
  - linkml:types

classes:
  Thing:
    tree_root: True
    slots:
      - identifier

slots:
  identifier:
    identifier: True
    required: True
    title: URI Identifier
    slot_uri: schema:identifier
    range: uriorcurie
    pattern: '(https?://|(mailto|tel):)\w+'
```

generates the following JSON schema:

```json
{
    "$defs": {
        "Thing": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "identifier": {
                    "pattern": "(https?://|(mailto|tel):)\\w+",
                    "type": "string"
                }
            },
            "required": [
                "identifier"
            ],
            "title": "Thing",
            "type": "object"
        }
    },
    "$id": "http://example.com/dataset",
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "additionalProperties": true,
    "description": "",
    "metamodel_version": "1.7.0",
    "properties": {
        "identifier": {
            "pattern": "(https?://|(mailto|tel):)\\w+",
            "type": "string"
        }
    },
    "required": [
        "identifier"
    ],
    "title": "Dataset",
    "type": "object",
    "version": null
}
```

**This correctly applies the regular expression.**

## Using `structured_pattern` doesn't work

```yaml
id: http://example.com/dataset
name: Dataset
prefixes: 
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
imports:
  - linkml:types

classes:
  Thing:
    tree_root: True
    slots:
      - identifier

slots:
  identifier:
    identifier: True
    required: True
    title: URI Identifier
    slot_uri: schema:identifier
    range: uriorcurie
    structured_pattern: 
      syntax: '(https?://|(mailto|tel):)\w+'
```

generates the following JSON schema:

```json
{
    "$defs": {
        "Thing": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "identifier": {
                    "type": "string"
                }
            },
            "required": [
                "identifier"
            ],
            "title": "Thing",
            "type": "object"
        }
    },
    "$id": "http://example.com/dataset",
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "additionalProperties": true,
    "description": "",
    "metamodel_version": "1.7.0",
    "properties": {
        "identifier": {
            "type": "string"
        }
    },
    "required": [
        "identifier"
    ],
    "title": "Dataset",
    "type": "object",
    "version": null
}
```

**This does not apply the regular expression.**

**Version of LinkML you are using**

linkml, version 1.8.6
