### ISSUE TITLE
Insufficient type_designator slot setup to allows for YAML->RDF->YAML roundtrip

### ISSUE THREAD

**Issue by mih** [linkml/linkml#2506]
I need to convert some schema-compliant data to RDF and back into YAML/JSON. This works in general, but not with a type designator slot. Here is a minimal schema, and data record:

<details>
<summary>schema.yaml</summary>

```yaml
id: demo
name: demo
prefixes:
  things: https://example.com/s/things/
  linkml: https://w3id.org/linkml/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  exthisns: https://example.org/ns/

default_prefix: things

imports:
  - linkml:types

types:

slots:
  id:
    identifier: true
    range: uriorcurie

  schema_type:
    slot_uri: rdf:type
    designates_type: true
    description: Type designator.
    range: uriorcurie


classes:
  Thing:
    class_uri: things:Thing
    description: >-
      The most basic, identifiable item.
    slots:
      - id
      - schema_type

```
</details>

<details>
<summary>Thing-01-minimal.yaml (data record)</summary>

```yaml
id: exthisns:mything
```
</details>

Converted to RDF, this gives

```
> linkml-convert -s typedesdemo.yaml -C Thing -t ttl Thing-01-minimal.yaml | tee dummy.ttl
@prefix exthisns: <https://example.org/ns/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

exthisns:mything a "things:Thing"^^xsd:anyURI .
```

The type is encoded as a literal. This causes an issues when converting this back to YAML

```
❯ linkml-convert -s typedesdemo.yaml -C Thing -t yaml dummy.ttl
Traceback (most recent call last):
...
linkml_runtime.DataNotFoundError: Got 0 of type <class 'test.Thing'> from source, expected exactly 1
```

No graph node is recognized to have the target class type.

Following https://linkml.io/linkml/schemas/type-designators.html, `uriorcurie` should be a valid choice for the type designator slot.

Looking around the issues, I found https://github.com/linkml/linkml/issues/2495, and in particular https://github.com/linkml/linkml/issues/2495#issuecomment-2589594856 by @roblinksdata

When I apply this solution to the problem here, I end up with the following minimally modified schema:

<details>
<summary>schema_improved.yaml</summary>

```yaml
id: demo
name: demo
prefixes:
  things: https://example.com/s/things/
  linkml: https://w3id.org/linkml/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  exthisns: https://example.org/ns/

default_prefix: things

imports:
  - linkml:types

types:

  UriOrCurieAsNode:
    typeof: uriorcurie
    description: Use this only in the `range` field of a slot to make a URI point at a node in an RDF graph.
    base: str
    uri: rdfs:Resource

slots:
  id:
    identifier: true
    range: uriorcurie

  schema_type:
    slot_uri: rdf:type
    designates_type: true
    description: Type designator.
    range: UriOrCurieAsNode


classes:
  Thing:
    class_uri: things:Thing
    description: >-
      The most basic, identifiable item.
    slots:
      - id
      - schema_type
```
</details>

And with this change, it is possible to do rountrip-conversion:

```
❯ linkml-convert -s typedesdemo.yaml -C Thing -t ttl Thing-01-minimal.yaml | tee dummy.ttl
@prefix exthisns: <https://example.org/ns/> .
@prefix things: <https://example.com/s/things/> .

exthisns:mything a things:Thing .
```

```
❯ linkml-convert -s typedesdemo.yaml -C Thing -t yaml dummy.ttl | tee dummy.yaml
id: exthisns:mything
schema_type: things:Thing
```

I think something on this topic should be added to the documentation on type-designator slots.
