### ISSUE TITLE
add exclude-types configuration to recommended linter rule

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#2523]
As a corollary to this, from `linkml/linter/config/datamodel/config.yaml`

```yaml
  RecommendedRuleConfig:
    description: >-
      Additional configuration options for the `recommended` rule
    is_a: RuleConfig
    attributes:
      exclude:
        range: string
        multivalued: true
        description: >-
          Default: []
          All elements except the ones with names specified in this list will be checked
```

which must be converted to python with this Makefile target

```make
linkml/linter/config/datamodel/config.py: linkml/linter/config/datamodel/config.yaml
	$(RUN) gen-python $< > $@.tmp && mv $@.tmp $@
```
