### ISSUE TITLE
Entity relational mermaid diagram generator fails with any_of/union ranges

### ISSUE THREAD

**Issue by roblinksdata** [linkml/linkml#2527]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**

Given a class using `any_of` in conjunction with `range` on a slot, when I generate an ER diagram, the resulting model silently chooses to represent the range as `string` instead of the correct unioned range.

**Version of LinkML you are using**
linkml, version 1.8.6

```yaml
id: http://example.com/something/schema
name: something
prefixes: 
  linkml: https://w3id.org/linkml/
  some: http://example.com/something/
imports:
  - linkml:types

classes:
  Something:
    class_uri: some:Something
    description: A thing, something.
    attributes:
      another_thing: 
        required: true
        slot_uri: some:otherthing
        description: An identifier.
        any_of:
          - range: OtherThingTypeA
          - range: OtherThingTypeB

  OtherThingTypeA:
    class_uri: SomeTypeA
    description: Type A
    attributes:
      id:
        required: true
        slot_uri: some:id
        range: integer

  OtherThingTypeB:
    class_uri: SomeTypeB
    description: Type B
    attributes:
      id:
        required: true
        slot_uri: some:id
        range: integer
```

when I run the above through `linkml generate erdiagram --format mermaid broken-any-of.yaml` I get the following:

```mermaid
erDiagram
Something {
    string another_thing  
}
OtherThingTypeA {
    integer id  
}
OtherThingTypeB {
    integer id  
}
```
