### ISSUE TITLE
document the order or precedence when reconciling the attributes of slots that are inherited from an is_a parent and a mixin

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#2528]
If `ClassC` from this schema is induced

```yaml
name: composition_precedence_schema
id: https://example.com/composition_precedence_schema.yaml

imports:
  - linkml:types
prefixes:
  linkml: https://w3id.org/linkml/

classes:
  ClassP:
    slots:
      - slot_s
    slot_usage:
      slot_s:
        minimum_value: 2
  ClassM:
    mixin: true
    slots:
      - slot_s
    slot_usage:
      slot_s:
        minimum_value: 3
  ClassC:
    is_a: ClassP
    mixins:
      - ClassM
slots:
  slot_s:
    range: integer
    minimum_value: 1
```

like this

```python
from linkml_runtime.utils.schemaview import SchemaView
from linkml_runtime.dumpers import yaml_dumper

schema_file = "composition_precedence_schema.yaml"

schema_view = SchemaView(schema_file)

class_c_induced = schema_view.induced_class("ClassC")

print(yaml_dumper.dumps(class_c_induced))
```

the result is

```yaml
name: ClassC
from_schema: https://example.com/composition_precedence_schema.yaml
is_a: ClassP
mixins:
- ClassM
attributes:
  slot_s:
    name: slot_s
    from_schema: https://example.com/composition_precedence_schema.yaml
    alias: slot_s
    owner: ClassC
    domain_of:
    - ClassP
    - ClassM
    range: integer
    minimum_value: 3
```

That `ClassC.attributes.slot_s.minimum_value` of 3 isn't shocking, but why? How am I supposed to know what to expect. Did we arrive at this result because
- 3 is the maximum of the `minimum_value`s
- `ClassM` is alphabetically first
- `ClassM` was visited first (or last) for some other reason?
