### ISSUE TITLE
Tutorial 01's JSON Schema Output does not match generator output

### ISSUE THREAD

**Issue by joestrouth1** [linkml/linkml#2530]
**Describe the bug**
Documentation only.
Part 1 of the tutorial describes generating a JSON schema. When running the same commands locally, a slightly different JSON schema is generated than shown.

Because the attributes are not marked as required, the JSON schema types them as `["string", "null"]` - related: #2252 

Happy to update the [example](https://github.com/linkml/linkml/blob/main/examples/tutorial/tutorial01/personinfo.json) but am opening this first as I am unsure whether those files are used elsewhere (e.g. tests)

**Version of LinkML you are using**: 1.8.6

### Schema
```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  personinfo: https://w3id.org/linkml/examples/personinfo
imports:
  - linkml:types
default_range: string
default_prefix: personinfo

classes:
  Person:
    attributes:
      id:
      full_name:
      aliases:
      phone:
      age:
```

### Documented output
```json
{
    "$defs": {
        "Person": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "age": {
                    "type": "string"
                },
                "aliases": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            },
            "title": "Person",
            "type": "object"
        }
    },
    "$id": "https://w3id.org/linkml/examples/personinfo",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "title": "personinfo",
    "type": "object",
    "version": null
}
```

### Actual output
```json
{
    "$defs": {
        "Person": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "age": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "aliases": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "full_name": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "id": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "phone": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "title": "Person",
            "type": "object"
        }
    },
    "$id": "https://w3id.org/linkml/examples/personinfo",
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "title": "personinfo",
    "type": "object",
    "version": null
}
```
