### ISSUE TITLE
Error in enum Python class generation

### ISSUE THREAD

**Issue by gaurav** [linkml/linkml#254]
There's an error in enum Python class generation that I've found while trying to get PR #239 to work. An existing test (the "kitchen_sink" generator test) catches this.

Given the following schema:
```
enums:
  FamilialRelationshipType:
    permissible_values:
      SIBLING_OF:
      PARENT_OF:
      CHILD_OF:
```

I can generate the Python data class for this. However, I find that:

```
print(kitchen_module.FamilialRelationshipType('SIBLING_OF')) # Produces: 'SIBLING_OF: '
```

I'm not sure why the extraneous `: ` is being added, but this is what is causing PR #239 to fail: https://github.com/linkml/linkml/pull/239/checks?check_run_id=2968179446#step:6:410
