### ISSUE TITLE
namespaces for LinkML classes (esp. for imports)

### ISSUE THREAD

**Issue by markdoerr** [linkml/linkml#2546]
---
name: Feature request
about: **namespaces in LinkML**
title: '**namespaces** for LinkML classes (esp. for imports)'
labels: feature
assignees: ''

---

**What is your feature request?**
It should be possible to add a **namespace** to imported classes, otherwise undesired overwrites could happen.
**Namespaces** would also make extending of imported classes more transparent.

**How important is this feature to you?** Select from the options below:
• Important - it's a blocker and can't do work without it: we are building data-model hierarchies, trying to extend an imported class without   changing its name (e.g. as an application profile), this is currently not working. 

**Additional context**
**Example:**

```
id: https://example.com/extended-dataset
name: extended-dataset
namespace: ext-dataset

imports:
  - dataset
    as: dataset-imported 

classes:
  Dataset:
    is_a: dataset-imported:Dataset
```
