### ISSUE TITLE
classification_rules does not work as expected

### ISSUE THREAD

**Issue by rly** [linkml/linkml#2551]
**Describe the bug**
Following advice from @cmungall , I am trying to use `classification_rules` to say if cond1 is met, validate an object as class C1 and if cond2 is met, validate an object as class C2. I cannot get this pattern to work. Please see the schema and data below.

**Version of LinkML you are using**
1.8.6

**Please provide a schema (and if applicable, a data file) that replicates the issue**
Schema:
```yaml
id: https://w3id.org/example
name: example

imports:
  - linkml:types

classes:
  Container:
    tree_root: true
    attributes:
      objs:
        range: BaseObject
        multivalued: true
        required: true

  BaseObject:
    abstract: true
    attributes:
      attr1:
        range: string
        required: true

  B:
    is_a: BaseObject
    classification_rules:
      - is_a: BaseObject
        slot_conditions:
          attr1:
            equals_string: "a"
    attributes:
      attr2:
        range: string
        required: true

  C:
    is_a: BaseObject
    classification_rules:
      - is_a: BaseObject
        slot_conditions:
          attr1:
            equals_string: "not a"
    attributes:
      attr3:
        range: integer
        required: true
```

Data:
```
objs:
  - attr1: "a"
    attr2: "attr2"
  - attr1: "not a"
    attr3: 2
```
