### ISSUE TITLE
No validation error when range class is not defined

### ISSUE THREAD

**Issue by rly** [linkml/linkml#2552]
It seems if I have a slot with `range: X` and class `X` is not defined, LinkML does not raise an error.

Schema:
```yaml
id: https://w3id.org/example
name: example

imports:
  - linkml:types

classes:
  Container:
    tree_root: true
    attributes:
      objs:
        range: A
        multivalued: true
        required: true

  A:
    attributes:
      attr2:
        range: NotAClass
        required: true
```

data:
```yaml
objs:
  - attr2: "attr2"
  - attr2: 2
  - attr2: 
      - something: 3
```

I can put anything for `attr2` and it will validate: `linkml validate` says `No issues found`.

Leaving out `attr2` result in error. It would be nice to raise an error here.

The schema:
```yaml
classes:
  Container:
    tree_root: true
    attributes:
      objs:
        range: NotAClass
        multivalued: true
        required: true
```
results in the same lack of error.

LinkML Version 1.8.6
