### ISSUE TITLE
SQL DDL generator: omit abstract classes

### ISSUE THREAD

**Issue by ialarmedalien** [linkml/linkml#2554]
When generating an SQL DDL from linkml, all classes are instantiated.

Whilst that makes sense for object-oriented representations, it is less useful for SQL DDLs (and possibly other output formats, such as DBML or mermaid).

Are there use cases for keeping the abstract classes in the generated schema? It would be useful to be able to disable abstract class instantiation via a command line switch.

**Comment by VictoriaSavageNNL** [comment]
This is related to Issue #2414 but you did a better job explaining it than I did.

**Comment by dalito** [comment]
Is this closed by #2614 or is there still more to do?

**Comment by FlorianK13** [comment]
@dalito @sagehrke This is solved in #2614

# Current behaviour

One can get abstract classes in the DDL by running
```bash
linkml generate sqltables test.yaml > tables-with-abstract-classes.sql
```
Or you can get the sql without abstract classes by using this:
```bash
linkml generate sqltables --generate_abstract_class_ddl False test.yaml > tables-without-abstract-classes.sql
```





## Files for reference:
<details><summary>test.yaml</summary>
<p>

```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string

classes:
  NamedThing:
    abstract: true
    attributes:
      - id


  Person:
    is_a: NamedThing
    attributes:
      - primary_email
      - birth_date
```
</p>
</details> 

<details><summary>tables-without-abstract-classes.sql
</summary>
<p>

```sql
-- # Abstract Class: NamedThing
--     * Slot: uid
--     * Slot: id
-- # Class: Person
--     * Slot: uid
--     * Slot: primary_email
--     * Slot: birth_date
--     * Slot: id

CREATE TABLE "Person" (
	uid INTEGER NOT NULL,
	primary_email TEXT,
	birth_date TEXT,
	id TEXT,
	PRIMARY KEY (uid)
);
CREATE INDEX "ix_Person_uid" ON "Person" (uid);

```
</p>
</details> 

<details><summary>tables-with-abstract-classes.sql
</summary>
<p>

```sql
-- # Abstract Class: NamedThing
--     * Slot: uid
--     * Slot: id
-- # Class: Person
--     * Slot: uid
--     * Slot: primary_email
--     * Slot: birth_date
--     * Slot: id

CREATE TABLE "NamedThing" (
	uid INTEGER NOT NULL,
	id TEXT,
	PRIMARY KEY (uid)
);
CREATE INDEX "ix_NamedThing_uid" ON "NamedThing" (uid);

CREATE TABLE "Person" (
	uid INTEGER NOT NULL,
	primary_email TEXT,
	birth_date TEXT,
	id TEXT,
	PRIMARY KEY (uid)
);
CREATE INDEX "ix_Person_uid" ON "Person" (uid);


```
</p>
</details>
