### ISSUE TITLE
`ifabsent` not included in JSON Schema

### ISSUE THREAD

**Issue by sbliven** [linkml/linkml#2556]
**Describe the bug**
Linkml includes the [`ifabsent`](https://linkml.io/linkml/schemas/slots.html#default-values) keyword to provide default values for slots. This seems to correspond well to JSON Schema's [`default` keyword](https://json-schema.org/draft/2019-09/draft-handrews-json-schema-validation-02#rfc.section.9.2). Although `default` is ignored during validation, it can be used downstream (eg by our frontend form generator, which is based on the JSON schema output). Could `default` be included by the `JsonSchemaGenerator`?

**Version of LinkML you are using**
1.8.6

**Please provide a schema (and if applicable, a data file) that replicates the issue**
You can include this in th issue if small, or provide a link e.g. to github.
Ideally a minimal example that replicates the problem is ideal, but only if this is easy for you.

```yaml
name: test-schema
id: http://example.org/test-schema
imports:
- linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
  test_schema: http://example.org/test-schema/
default_prefix: test_schema
default_range: string
slots:
  withdefault:
    ifabsent: string(default value)
    range: string
    required: false
classes:
  Test:
    slots:
    - withdefault
```

This generates the following json schema:

```json
{
    "$defs": {
        "Test": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "withdefault": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "title": "Test",
            "type": "object"
        }
    },
    "$id": "http://example.org/test-schema",
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "title": "test-schema",
    "type": "object",
    "version": null
}
```
