### ISSUE TITLE
Working with linked csv's

### ISSUE THREAD

**Issue by redst4r** [linkml/linkml#2558]
Hi,

I'm quite new to LinkML and after going through the docs I thought I'd try to model some very simple spreadsheet/csv data we're using in some projects.
It's basically two spreadsheets/tables with information about patients, and biosamples collected from those patients (one patient can have mutiple samples). Adding a LinkML schema would help me enforce constrains on the entries and catch some errors early.

A minimal example:
```
patients.csv
------------
id, name, age
p1, John Doe, 34
p2, Jane Doe, 65

samples.csv
------------
id, patient
s1, p1
s2, p2
s3, p2
```
In this case, John Doe has one sample (s1), Jane Doe has two samples (s2,s3).

My attempt in LinkML
```yaml
classes:
  Sample:
    attributes:
      id:
        identifier: true
      patient:
        range: Patient
        inlined: false

  Patient:
    attributes:
      id:
        identifier: true
      name:
        required: true
      age:
        range: integer
```

Now to validate the data against the schema
```
linkml-validate -s patient_schema.yaml -C Patient patients.csv
linkml-validate -s patient_schema.yaml -C Sample samples.csv
```
works fine wrt catching type errors (e.g. age not being an int).

However, **is it possible to check if the tables are properly "linked"**, i.e. ensure that  `Sample.patient` (p1,p2) in `samples.csv` ("foreign key") is indeed present in the `patients.csv` (as a primary key). For example to catch the following typo:
```
patients.csv
-----------
id, name, age
p1, John Doe, 34
p2, Jane Doe, 65

samples.csv
-----------
id, patient
s1, p1
s2, p2
s3, p22  <--- p22 doesnt exist!
```

### yaml
I couldn't figure it out in yaml either (using a container in addition):
```yaml
classes:
  Sample:
    attributes:
      id:
        identifier: true
      patient:
        range: Patient
        inlined: false

  Patient:
    attributes:
      id:
        identifier: true
      name:
        required: true
      age:
        range: integer
  
  Container:
    tree_root: true
    attributes:
      patients:
        range: Patient
        multivalued: true
        inlined_as_list: true
      samples:
        range: Sample
        multivalued: true
        inlined_as_list: true
```
and the data as
```yaml
patients:
  - id: p1
    name: John Doe
    age: 34
  - id: p2
    name: Jane 
    age: 56

samples:
- id: s1
  patient: p1
- id: s2
  patient: p2
- id: s3
  patient: p22 #  <--- p22 doesnt exist!
```
will happily validate via `linkml-validate -s patient_schema.yaml data.yaml`
It only seems to enforce that the type of `Sample.patient` matches the type of `Patient.id`, but won't check if the foreign key `p22` actually exists.

The only way I see (in yaml) is to `inline` the `Sample.patient` attribute in the schema and either type out each `Sample.patient` slot or use references. However that won't work with csvs.

I'm aware that csvs are not the best way to approach this, but the ease-of-use is a big factor here (clinicians are filling out those sheets). 
We could of course just add a little script downstream to check if the two tables join "properly", but it would be much nicer/cleaner if it would be part of the validator! 

I hope someone can point me in the right direction!
