### ISSUE TITLE
generate-jsonld-context and generate-json-schema incompatible with range: Any

### ISSUE THREAD

**Issue by dnlbauer** [linkml/linkml#2570]
---
name: Bug report
about: Create a report to help us improve
title: 'generate-jsonld-context and generate-json-schema incompatible with range: Any'
labels: bug
assignees: ''

---

**Describe the bug**
I am attempting to define a LinkML model where a slot can reference one of two possible classes. Here's a minimal reproducible example:

```yaml
id: http://example.com
name: Example
imports:
  - linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
  example: http://example.com/

default_range: string
default_prefix: example

classes:
  Author:
    slots:
      - author

  Person:
    slots:
      - name

  LargeLanguageModel:
    slots:
      - name

slots:
  name:
  author:
    range: Any
    any_of:
      - range: Person
      - range: LargeLanguageModel

```

When I try to generate a JSON-LD context from this schema, I get the following error:

```bash
❯ linkml generate jsonld-context test.yaml
ValueError: File "test.yaml", line 28, col 12 slot: author - unrecognized range (Any)
```

If I remove the `range: Any` line, the JSON-LD context generation works, but then generating a JSON Schema produces incorrect output where the `author` field is typed as `string` instead of the expected `type: object`:

```bash
❯ linkml generate json-schema test.yaml
```
```json
(...)
"author": {
    "anyOf": [
        {
            "$ref": "#/$defs/Person"
        },
        {
            "$ref": "#/$defs/LargeLanguageModel"
        },
        {
            "type": "null"
        }
    ],
    "type": "string"
}
(...)
```

It seems like there's an inconsistency here:

generate-jsonld-context does not accept range: Any.
Removing range: Any affects generate-json-schema, resulting in an incorrect type assignment.

Expected behaviour would be that generate-jsonld-context would work with range: Any, because to my knowledge this works with other generators as well.

**Version of LinkML you are using**
1.8.7
