### ISSUE TITLE
String default values (ifabsent) with parentheses not working correctly

### ISSUE THREAD

**Issue by leitte** [linkml/linkml#2571]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**
I want to specify default values for units of measurements that contain parentheses. Example: "J/(kg K)" in the ifabsent attribute. 

When I convert the schema to python with `gen-python`, everything starting from the first parenthesis is missing.

"J/(kg K)" --> "J/"

The same holds for functions, e.g. "ln(...)" --> "ln"

**Version of LinkML you are using**
linkml, version 1.8.5 + 1.8.7
gen-python, version 1.8.5 + 1.8.7

**Please provide a schema (and if applicable, a data file) that replicates the issue**

```
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  personinfo: https://w3id.org/linkml/examples/personinfo
imports:
  - linkml:types
default_range: string
default_prefix: personinfo

classes:
  Person:
    attributes:
      id:
      full_name:
        ifabsent: hello(you)
      aliases:
      phone:
      age:
```

I tried the following variants to escape the parentheses:
- `"hello(you)"`
- `string("hello(you)")`
- `string("hello\\(you\\)")`

None of them seems to work.

Thanks for LinkML and your support ❤
