### ISSUE TITLE
add a FAQ entry for "punning" in LinkML

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#2572]
Punning in OWL is defined as: one entity interpreted as two different types of thing—a class and an individual—depending on its syntactic context.

In LinkML, we don't have a way to "share" an "entity" between classes and slots collections, but we can sort of reproduce this strategy by specifying a class and slot separately with the same name.

This is already somewhat addressed in: https://linkml.io/linkml/generators/owl.html but needs to be expanded with examples and more detail.  (it only addresses controlling punning in the context of a schema that isn't intentionally trying to pun, I believe, but I am not an OWL expert). 

An example with output is below.

```
:Author rdf:type owl:Class .
:author rdf:type owl:ObjectProperty .
```

where I am using the concept of "Author" as a class (probably with person-like attributes) and "author" as a property to link a book to its author.
in linkml, something like:

```
classes:
   author:
     slots:
        - id
        - name
   Book:
     slots:
       - author
slots:
   author:
     range: uriorcurie  # the id of the Author class
   id:
     identifier: true
   name:
```

or

```
classes:
   author:
     slots:
        - id
        - name
   Book:
     slots:
       - author
slots:
   author:
     range: author  # (not inlined, use the id as a reference here) 
   id:
     identifier: true
   name:
```

Many of the generators will warn you that this is not considered best practice for a linkml model, e.g.:
```
WARNING:linkml.utils.generator:Overlapping slot and class names: author
```

nevertheless, the owl serialization does make an object property and a class, nonetheless, with the same name:
```
test:author a owl:ObjectProperty ;
    rdfs:label "author" ;
    rdfs:range test:author ;
    skos:inScheme <https://w3id.org/test/test-model> .

test:author a owl:Class ;
    rdfs:label "author" ;
```

YMMV - I know at one point we had a bug on specific operating systems where casing didn't get picked up correctly in specific generators when all that was different was the casing between two linkml entities.
I think that is fixed now.

TODO:
- [ ] explain why LinkML generates the warning (we can do this by looking through the code, writing some tests or examples to test)
- [ ] explain the generators that support punning and those that don't (if any).  (we can do this by running through the tests we write above and producing snippets of content for the FAQ here, showing how the serializations look under a punning scheme). 
- [ ] check on the support for case-sensitive, same-name entities in LinkML and fix if still not working.
