### ISSUE TITLE
[owl]: erroneous ':' in generated URIs if no `default_prefix`

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2578]
**Describe the bug**

Element URIs contained in generated OWL contain erroneous `:`. For example: `https://example.org/my-schema/:MySubclass` for the below provided schema. The issue **appears only** if no `default_prefix` is explicitly declared.

**Version of LinkML you are using**

v1.8.7

**Please provide a schema (and if applicable, a data file) that replicates the issue**

```yaml
id: https://example.org/my-schema
prefixes:
  linkml: https://w3id.org/linkml/
  rdl: https://rds.posccaesar.org/ontology/lis14/rdl/
imports:
  - linkml:types
default_range: string

classes:
  MySubclass:
    is_a: FunctionalObject
  FunctionalObject:
    class_uri: rdl:FunctionalObject
```
