### ISSUE TITLE
Cannot use derived class as `range` for a `key` slot

### ISSUE THREAD

**Issue by mih** [linkml/linkml#2600]
I am trying to do something similar to `linkml` annotations:

```yaml
  Annotation:
    description: >-
      A tag/value pair with the semantics of OWL Annotation.
    slots:
      - annotation_tag
      - annotation_value
    slot_usage:
      annotation_tag:
        key: true
```

things are fine when `annotation_tag` is something like this

```yaml
  annotation_tag:
    description: A tag identifying an annotation.
    range: uriorcurie
```

things are also fine, when the `range` of `annotation_tag` is a class with an `identifier:true` slot.

things are no longer fine, when `range` is a subclass of such a class. In other words. The following `AnnotationTag` class is not acceptable, whenever its base class `Thing` is.

```yaml
  AnnotationTag:
    is_a: Thing
```

The error I am getting from `gen-python` is

```
Traceback (most recent call last):
  File "<stdin>", line 179, in <module>
NameError: name 'AnnotationTagPid' is not defined
```
