### ISSUE TITLE
mkdocs doesn't display multiple annotations

### ISSUE THREAD

**Issue by wdduncan** [linkml/linkml#2609]
---
name: Bug report
about: Create a report to help us improve
title: 'mkdocs doesn't display multiple annotations'
labels: bug
assignees: ''

---

**Describe the bug**
When multiple annotations are added to an element, `mkdocs serve` only displays the first annotations. Is this an issue with `mkdocs` or the markdown produced by `gen-doc`?

**Version of LinkML you are using**
version 1.8.7

**Please provide a schema (and if applicable, a data file) that replicates the issue**
I have a simple schema with a `Foo` class defined as:
```
classes:
  Foo:
    annotations:
      one: "value one"
      two: "value two"
```
After running the command `gen-doc test-schema.yml -d docs`, the corresponding markdown file contains both annotations.
```
### Annotations

| property | value |
| --- | --- |
| one | value one || two | value two |
```
But the webpage only shows one annotation.

<img width="228" alt="Image" src="https://github.com/user-attachments/assets/5a5b1958-fb62-4dd6-9611-840e3d98b757" />

Not sure if this a problem with `mkdocs` or the markdown produced by `gen-doc`.

**Comment by sujaypatil96** [comment]
[annotations](https://linkml.io/linkml-model/latest/docs/annotations/) is a multivalued metaslot. What do you see when you change the schema syntax to the following?

```yaml
classes:
  Foo:
    annotations:
      - one: "value one"
      - two: "value two"
```

_Change_: adding a hyphen (`-`) to the `annotations`
