### ISSUE TITLE
JsonSchemaGenerator includes invalid `version` and `metamodel_version` properties

### ISSUE THREAD

**Issue by sbliven** [linkml/linkml#2610]
---
name: Bug report
about: Create a report to help us improve
title: 'JsonSchemaGenerator includes invalid `version` and `metamodel_version` properties'
labels: bug
assignees: ''

---

**Describe the bug**
The `JsonSchemaGenerator` output claims to conform to the `https://json-schema.org/draft/2019-09/schema` metaschema. However it includes two properties, `version` and `metamodel_version`, which are not accepted by the [2019 schema](https://json-schema.org/draft/2019-09/draft-handrews-json-schema-02).

The extra properties are problematic because they cause validators to fail when using the generated json schema. For example, Ajv throws the error `Uncaught Error Error: strict mode: unknown keyword: "metamodel_version". While it is possible to work around this in some cases (eg by disabling strict schema validation), linkml should aim for compliance with the standard.

**Version of LinkML you are using**
1.8.6 / main

**Please provide a schema (and if applicable, a data file) that replicates the issue**

```yaml
id: https://example.org/minimal_schema
name: MinimalSchema
version: 1.0.0

prefixes:
  linkml: https://w3id.org/linkml/

imports:
  - linkml:types

classes:
  Person:
    attributes:
      - name:
          range: string
          required: true
```
    poetry run gen-json-schema minimal_schema.yaml -t Person
```json
{
    "$defs": {
        "Person": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ],
            "title": "Person",
            "type": "object"
        }
    },
    "$id": "https://example.org/minimal_schema",
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "additionalProperties": true,
    "description": "",
    "metamodel_version": "1.7.0",
    "properties": {
        "name": {
            "type": "string"
        }
    },
    "required": [
        "name"
    ],
    "title": "MinimalSchema",
    "type": "object",
    "version": "1.0.0"
}

```

[Demo of Ajv failing to validate](https://codesandbox.io/p/devbox/z4sr4s)
