### ISSUE TITLE
Differences in context between jsonldgen.py and jsonldcontextgen.py

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2626]
**Describe the bug**

Generating the JSON-LD context of a LinkML schema with `linkml generate jsonld-context` should result in the same context contained in the full-blown JSON-LD document generated with `linkml generate jsonld`. At least when the context generation options (`model`, `prefixes`,...) are set to the same values.

See the example at the bottom of this issue report.

Notice the differences in the context between the context contained in the JSON-LD document generated with `linkml generate jsonld` and `linkml generate jsonld-context`:
| **Json-LD** Generator | Json-LD **Context** Generator |
|-|-|
| [context of the metamodel](https://github.com/linkml/linkml/blob/335502ce8ee794ab3349062a887dc84d3d91cff0/linkml/generators/jsonldgen.py#L167) | |
| what the [`ContextGenerator` returns](https://github.com/linkml/linkml/blob/335502ce8ee794ab3349062a887dc84d3d91cff0/linkml/generators/jsonldgen.py#L165) | what the [`ContextGenerator` returns](https://github.com/linkml/linkml/blob/335502ce8ee794ab3349062a887dc84d3d91cff0/linkml/generators/jsonldgen.py#L165) |
| [contexts corresponding the imports](https://github.com/linkml/linkml/blob/335502ce8ee794ab3349062a887dc84d3d91cff0/linkml/generators/jsonldgen.py#L172) | |

I don't see a reason why the `ContextGenerator` should return a different JSON-LD context from that returned by the `JSONLDGenerator`.

My expectation is so-to-say: `linkml generate jsonld | jq '."@context"'` == `linkml generate jsonld-context | jq '."@context"'`.

**Version of LinkML you are using**

v1.8.7

---

**Please provide a schema (and if applicable, a data file) that replicates the issue**

As a reference I'm generating the context of [simple_uri_test.yaml](https://github.com/linkml/linkml/blob/main/tests/test_scripts/input/simple_uri_test.yaml):
```yaml
id: https://raw.githubusercontent.com/linkml/linkml/main/tests/test_scripts/input/simple_uri_test
name: simple_uri_test

description: A test of various forms of jsonld context generation

imports:
  - linkml:extensions
  - simple_slots
  - includes/simple_types

prefixes:
  linkml: https://w3id.org/linkml/
  foo: http://samples.r.us/foo#
  bar: http://samples.r.us/bar_


classes:
  model:
    class_uri: foo:model
    slots:
      - state
    exact_mappings:
      - bar:whaoo
```

`poetry run linkml generate jsonld tests/test_scripts/input/simple_uri_test.yaml|jq -r '."@context"'` yields

```json
[
  "https://w3id.org/linkml/meta.context.jsonld",
  {
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "https://w3id.org/linkml/extensions.context.jsonld",
  "simple_slots.context.jsonld",
  "includes/simple_types.context.jsonld",
  "https://w3id.org/linkml/types.context.jsonld"
]
```

Whereas `poetry run linkml generate jsonld-context --no-model --no-prefixes tests/test_scripts/input/simple_uri_test.yaml|jq -r '."@context"'` (`--no-model --no-prefixes` needed to have the equivalent context to the previous generation) yields

```json
{
  "xsd": "http://www.w3.org/2001/XMLSchema#"
}
```
