### ISSUE TITLE
pythongen emits erroneous code for non-multivalued inlined slots

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#265]
given:

 ```yaml
classes:

  Person:
    slots:
      - has birth event
  BirthEvent:
    slots:
      - started at time
 
slots:
  has birth event:
    range: BirthEvent
```

note there is no PK for event which forces inlining; I believe we get the same result if we explicitly ask for inlining

this generates:

```python
@dataclass
class Person(YAMLRoot):
...
   def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
 ...
       if self.has_birth_event is not None and not isinstance(self.has_birth_event, BirthEvent):
            self.has_birth_event = BirthEvent(**self.has_birth_event)
```

if I use json_loader to instantiate using:

```json
{"id": "P:2",
 "has_birth_event": {"started_at_time": "1981-01-01"}}
```

I get:

```
  File "test", line 141, in __post_init__
TypeError: test.BirthEvent() argument after ** must be a mapping, not JsonObj
```
