### ISSUE TITLE
add FAQ entry: What is a good/best way to handle default values in the schema?

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#2655]
For example, suppose I have field in my data named body_mass. I learn from the investigators that the unit is always in kilograms. I can do apply some of the patterns described [here](https://linkml.io/linkml/howtos/model-measurements.html) (e.g., have a body_mass_kg field). Of those patterns, I find the [Generic Quantity Type Pattern](https://linkml.io/linkml/howtos/model-measurements.html#generic-quantity-type-pattern) appealing:
```
classes:
  Subject:
    attributes:
      id:
        identifier: true
      measurements:
        range: Measurement
        multivalued: true
  Measurement:
    attributes:
      quantity_kind:
        range: uriorcurie
      quantity_value:
        range: decimal
      quantity_unit:
However, does this pattern always require that the quantity_unit be given in the input data? E..g.,:
- id: P001
  measurements:
    - quantity_kind: body mass
      quantity_value: 70
      quantity_unit: kg
```
Since the data is already known to be in kg , can I define the Measurement class so that unit specified as kg (which is important for documentation purposes), but not have to input the unit when validating data?

Philip Stromert:
I think https://linkml.io/linkml/schemas/slots.html#default-values has the answers you are looking for. So if I understand you correctly and the quantity_unit slot of your Measurement class should always be "kg", if not overridden by the user input, you could do:
```
Measurement:
    attributes:
      quantity_kind:
        range: uriorcurie
      quantity_value:
        range: decimal
      quantity_unit:
        range: string
        ifabsent: string(kg)
```

Bill Duncan:
Just curious. Why not do this?
```
quantity_value:
    range: decimal
    unit:
      ucum_code: kg
```
