### ISSUE TITLE
JSON Schema generator wrongly selects `string` for all indirect types

### ISSUE THREAD

**Issue by vcschapp** [linkml/linkml#2666]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

# Bug description

**Describe the bug**

The output of `$ linkml generate json-schema` incorrectly selects the JSON Schema type `string` for any slot whose type is a user-defined type based on another user-defined type.

# LinkML version

**Version of LinkML you are using**

1.9.1

# Reproduction steps

**Please provide a schema (and if applicable, a data file) that replicates the issue**
You can include this in the issue if small, or provide a link e.g. to github.
Ideally a minimal example that replicates the problem is ideal, but only if this is easy for you.

## Example schema

```yaml
id: https://github.com/linkml/linkml/issues/1234
name: indirect_type_bug

prefixes:
  example: https://example.org/linkml

classes:
  example:
    attributes:
      foo:
        range: foo
      bar:
        range: bar

types:
  foo:
    uri: example:foo
    base: float
    minimum_value: 0.0
  bar:
    uri: example:bar
    base: foo
```

## Output JSON schema

This is the output of `$ linkml generate json-schema known_bugs/indirect_type.yaml`.

Notice how the type of the `bar` property is `["string", "null"]` and has no `minimum` constraint, whereas the the type of the `foo` property is correctly `["number", "null"]` and it has the `minimum` constraint.

```json
{
    "$defs": {
        "Example": {
            "additionalProperties": false,
            "description": "",
            "properties": {
                "bar": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "foo": {
                    "minimum": 0.0,
                    "type": [
                        "number",
                        "null"
                    ]
                }
            },
            "title": "Example",
            "type": "object"
        }
    },
    "$id": "https://github.com/linkml/linkml/issues/1234",
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "additionalProperties": true,
    "metamodel_version": "1.7.0",
    "title": "indirect_type_bug",
    "type": "object",
    "version": null
}

```
