### ISSUE TITLE
`class_uri` and `slot_uri` being ignored on RDF URI generation

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2677]
**Describe the bug**
Specified [`class_uri`](https://linkml.io/linkml-model/latest/docs/class_uri/) or [`slot_uri`](https://linkml.io/linkml-model/latest/docs/slot_uri/) not being used as element identifier on generated RDF or JSON-LD.

Those classes or slots declaring their own URIs are still getting the URIs that are typically generated derived from the schema prefixes.

**Version of LinkML you are using** v1.9.1

**Please provide a schema (and if applicable, a data file) that replicates the issue**

The issue can be reproduced with one of the schemas being provided for testing ([jsonld_context_class_uri_prefix.yaml](https://github.com/linkml/linkml/blob/main/tests/test_generators/input/jsonld_context_class_uri_prefix.yaml)):

```yaml
id: https://sparc.olympiangods.org/sparcur/schemas/1/sparc
title: sparc export schema
name: sparc-linkml
imports:
  - linkml:types

prefixes:
  linkml: https://w3id.org/linkml/
  sparc: http://uri.interlex.org/tgbugs/uris/readable/sparc/
  rdfs: http://www.w3.org/2000/01/rdf-schema#

default_prefix: sparc

classes:
  Thing:
    class_uri: rdfs:Resource

slots:
  id:
    slot_uri: sparc:id
  label:
    slot_uri: rdfs:label
```

Running `linkml generate rdf tests/test_generators/input/jsonld_context_class_uri_prefix.yaml` generates the Turtle code that will be attached as a file (extension `.txt` added to get GitHub to accept it) to this issue.

This is the generated Turtle code for the class `Thing`:
```turtle
<http://uri.interlex.org/tgbugs/uris/readable/sparc/Thing> a linkml:ClassDefinition ;
    skos:inScheme <https://sparc.olympiangods.org/sparcur/schemas/1/sparc> ;
    skos:mappingRelation rdfs:Resource ;
    linkml:class_uri rdfs:Resource ;
    linkml:definition_uri <http://uri.interlex.org/tgbugs/uris/readable/sparc/Thing> ;
    linkml:slot_usage [ ] .
```
Notice that the subject's URI is `http://uri.interlex.org/tgbugs/uris/readable/sparc/Thing` instead of `http://www.w3.org/2000/01/rdf-schema#Resource` (as I'd expect it to be).

The same happens with the slot `label`:
```turtle
<http://uri.interlex.org/tgbugs/uris/readable/sparc/label> a linkml:SlotDefinition ;
    skos:inScheme <https://sparc.olympiangods.org/sparcur/schemas/1/sparc> ;
    skos:mappingRelation rdfs:label ;
    linkml:definition_uri <http://uri.interlex.org/tgbugs/uris/readable/sparc/label> ;
    linkml:range <http://uri.interlex.org/tgbugs/uris/readable/sparc/string> ;
    linkml:slot_uri rdfs:label .
```
Notice that the subject's URI is `http://uri.interlex.org/tgbugs/uris/readable/sparc/label` instead of `http://www.w3.org/2000/01/rdf-schema#label` (as I'd expect it to be).

[jsonld_context_class_uri_prefix.ttl](https://github.com/user-attachments/files/20162607/jsonld_context_class_uri_prefix.ttl.txt)
