### ISSUE TITLE
RDF generation creating unexpected URIs

### ISSUE THREAD

**Issue by Silvanoc** [linkml/linkml#2679]
**Describe the bug**
RDF generation is creating element URIs that do not seem to correspond the URIs that can be expected.

**Version of LinkML you are using** v1.9.1

**Please provide a schema (and if applicable, a data file) that replicates the issue**

The issue can be reproduced with one of the schemas being provided for testing ([jsonld_context_inlined_external_types.yaml](https://github.com/linkml/linkml/blob/main/tests/test_generators/input/jsonld_context_inlined_external_types.yaml)):

```yaml
id: https://example.org/external_type
prefixes:
  linkml: https://w3id.org/linkml/
  ex: https://example.org/external_type#
  cred: https://www.w3.org/2018/credentials#

imports:
  - linkml:types

default_prefix: ex
default_range: string

slots:
  id:
    identifier: true
    range: string

  digestSRI:
    title: "Digest SRI"
    description: "Subresource Integrity hash ensuring it has won't be modified."
    range: SriString
    slot_uri: cred:digestSRI
    required: true

  credential:
    title: "Credential"
    description: "Some credential"
    range: VerifiableCredential
    inlined: true
    required: true

classes:
  SriString:
    class_uri: cred:sriString

  VerifiableCredential:
    class_uri: cred:VerifiableCredential
    slots:
      - id
```

Running `linkml generate rdf tests/test_generators/input/jsonld_context_inlined_external_types.yaml` generates the Turtle code that will be attached as a file (extension .txt added to get GitHub to accept it) to this issue.

Notice, for example, how the class `SriString` is getting the URI `https://example.org/SriString` instead of the expected `https://www.w3.org/2018/credentials#sriString` (result of applying the prefix `cred: https://www.w3.org/2018/credentials#`.

```turtle
<https://example.org/SriString> a linkml:ClassDefinition ;
    skos:inScheme <https://example.org/external_type> ;
    skos:mappingRelation <cred:sriString> ;
    linkml:class_uri <https://www.w3.org/2018/credentials#sriString> ;
    linkml:definition_uri <https://example.org/external_type#SriString> ;
    linkml:slot_usage [ ] .
```

[jsonld_context_no_default_namespace_prefix.ttl.txt](https://github.com/user-attachments/files/20164242/jsonld_context_no_default_namespace_prefix.ttl.txt)
