### ISSUE TITLE
Add info on how to extend the metadata of a schema to the FAQ

### ISSUE THREAD

**Issue by amc-corey-cox** [linkml/linkml#2691]
---
title: Add info on how to extend the metadata of a schema to the FAQ
assignees: @amc-corey-cox @joshmoore 

---

**What is your feature request?**
@joshmoore asked a great question about how to add extend the metadata of a schema. We should add this to the FAQ

**Additional context**
@gouttegd shared the “metamodel extensions” in this link https://linkml.io/linkml/schemas/annotations.html for some details.

Here is some additional info from the Slack chat:

> annotation can be on any element. As the docs pointed at say, instantiates is the way to declare conformance with an extension. The disappointing thing is that this is not enforced, but the encouraging thing is that this should not be hard…
> 
> The instantiates slot is defined in the Element class, and the SchemaDefinition class (which represents the “top-level”) inherits from it, so the intention seems clear that it should be usable at the top-level. Whether the tooling supports it or not, no idea – I have only used metamodel extensions on slots.
> 
> Gotcha. I was pleasantly surprised that annotations worked for the schema definition and so it makes sense for instantiates as well. I can pass this along and we can at least make use of it, even if we might need to then build our own validators (temporarily).
> for the top level the simplest thing is just to look at the list here: [linkml:SchemaDefinition](https://w3id.org/linkml/SchemaDefinition)

Some text removed for brevity.

**Comment by strambc** [comment]
Thank you @amc-corey-cox for opening this issue.

Just to introduce myself, I am a member of the BioImaging community and would like to promote the use of LinkML to author BioImage Metadata schemas that would implement the REMBI recommendations (https://github.com/NL-BioImaging/ISA-REMBI-Metadata-Modules/blob/main/REMBI-BioSample/REMBI_Biosample_LightMicroscopy_CStrambio-JLacoste_v1-2-0.yaml). Other projects are also in the pipeline such as converting the [NBO-Q Microscopy Schema from xsd ](https://github.com/WU-BIMAC/NBOMicroscopyMetadataSpecs/blob/master/Model/in%20progress/v02-10/NBO_MicroscopyMetadataSpecifications_ALL.xsd)to LinkML

The use case I am currently working on concerns creating model-level custom meta model slots describing the schema authorship, date of creation, scope etc.

I am not sure if this is all in scope here as an example of what the FAQ might have to address...
In case it has to be moved somewhere else, let me know.

------------------

After some guidance from @cmungall I have done the following:

```
id: https://example.org/schemas/rembi_biosample
name: REMBI_Biosample
description: Schema for REMBI Biosample metadata template
conforms_to: REMBI
created_on: 2025-04-25
last_updated_on: 2025-05-13
created_by: C. Strambio-De-Castillia -BINA & J. Lacoste -CBI
version: v1.2.0
metamodel_version: v1.0.0
license: https://creativecommons.org/publicdomain/zero/1.0/
imports:
  - linkml:types
default_range: string

instantiates: 
    - module_schema:model_level_metadata
    
annotations:    
      module_scope: Light Microscopy
      module_scope_term_accession: http://edamontology.org/topic_3385
      created_by_affiliation: UMass Chan Medical School, MIACellavie

classes:
...
```
and then created a separate yaml schema containing the metaschema for the annotations as follows:

```
id: https://example.org/schemas/Module
name: module_schema
description: Model-level metadata for generic REMBI or ISA module schema
version: v1.0.0
license: https://creativecommons.org/publicdomain/zero/1.0/
imports:
  - linkml:types
default_range: string

classes:

    model_level_metadata:
      slots:
        - module_scope
        - module_scope_term_accession
        - created_by_affiliation
...
```

Does this look OK?
 if I want some of the top-level fields to be mandatory for the schema to be valid, can I mark them as required somehow?

I have noticed the "required" property for slots.
can I specify that in the schemaDefinition under slots even for model-level metadata?
