### ISSUE TITLE
add FAQ entry: how do I represent ontology individuals in LinkML

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#2694]
I am trying to model port Pokemon OWL ontology to LinkML,  mostly to be used as a teaching tool.  One struggle I have is to how to treat OWL Ontology Individuals?
For example this one:
```
# https://pokemonkg.org/ontology#Habitat_Cave
:Habitat_Cave a owl:NamedIndividual,
                       :Habitat ;
              rdfs:label "Cave"@en .
```
Does LinkML has a concept of individual?  Or should these just be converted to a regular objects?
Pokemon might look as a silly example,  but many ontologies that were presented at ISWC over the years contain quite a large number of individuals

In LinkML terms, what about using an enumeration to constrain the values of the habitat slot of a Pokemon class?

```
classes:
  Pokemon:
    attributes:
      habitat:
        range: HabitatEnum

enums:
  HabitatEnum:
    permissible_values:
      Cave:
        meaning: https://pokemonkg.org/ontology#Habitat_Cave
      Forest:
        meaning: https://pokemonkg.org/ontology#Habitat_Forest
      Ocean:
        meaning: https://pokemonkg.org/ontology#Habitat_Ocean
```
@turbomam  any alternatives or additional examples you could provide here?
