### ISSUE TITLE
[pydanticgen] implement string_serialization

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#2701]
depends on:
- [ ] merging https://github.com/linkml/linkml/pull/2036
  
  this PR builds on #2036, see the [diff between branches](https://github.com/sneakers-the-rat/linkml/compare/pydanticgen-metadata..pydanticgen-string-template) for what is unique to this PR

---

> *i have implemented*
> *the `string_serialization`*
> *that was in*
> *the metamodel*
> 
> *and which*
> *you were probably*
> *hoping*
> *i wouldnt*
> 
> *Forgive me*
> *the metaprogramming potential*
> *so fucked up*
> *and so good*

couldn't sleep, saw this earlier while doing https://github.com/linkml/linkml/pull/2052 and had a whacky idea

so like

```yaml
classes:
  MyClass:
    attributes:
      attr:
    annotations:
      meta:
        value: my special metadata annotation
    aliases:
    - alias1
    - alias2
    string_serialization: |
      ---
      annotations: {annotations[meta][value]}
      aliases: {aliases}
      attr: {attr}
``` 

becomes

```python
class MyModel(ConfiguredBaseModel):
    linkml_meta: ClassVar[LinkMLMeta] = LinkMLMeta({'aliases': ['alias1', 'alias2'],
         'annotations': {'meta': {'tag': 'meta',
                                  'value': 'a string value set as a linkml '
                                           'classdefinition metadata value'}},
         'from_schema': 'pydantic'})

    attr: Optional[str] = Field(None, json_schema_extra = { "linkml_meta": {'alias': 'attr', 'domain_of': ['StringSerialization']} })
    
    def __str__(self) -> str:
        if self.linkml_meta is not None:
            kwargs = self.linkml_meta
        else:
            kwargs = {}

        kwargs.update(self.model_dump())
        return '''
---
annotations: {annotations[meta][value]}
aliases: {aliases}
attr: {attr}
'''.format(**kwargs)

```

which of course works like

```python
>>> instance = MyModel(attr=attr_str_value)
>>> print(str(instance))

---
annotations: a string value set as a linkml classdefinition metadata value
aliases: ['alias1', 'alias2']
attr: a string value set as a class attribute
```

so one could imagine the metaprogramming possibilities that could be had if one were to eval (after, perhaps, safely escaping) a string that looked like another model or format and so on. 

also this is just a demonstration of 𝓉𝒽𝑒 𝒻𝓊𝓃𝓏𝒾𝑒𝓈 𝓉𝑜 𝒷𝑒 𝒽𝒶𝒹 with the pydanticgen templating system :)

@cmungall i also added a little sketch of a pytest-fixture based complement to the compliance framework - the teeniest, tiniest hookable version. obvs it doesn't implement all the semantics of the existing compliance framework, but i'm thinking about how it would be nice to be able to surface some of what happens in the `helper` module, and allow for both 'proper' compliance tests alongside the ability to allow tests that might not fit well there to declare that a certain test implements a part of the metamodel. just a quick idea :)
