### ISSUE TITLE
define CURIEs for permissible values

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#272]
given a schema with an enum e, in a schema s, we would like to make CURIEs for each permissible value

Proposed: S:e.UUENCODE(pv)

**Comment by cmungall** [comment]
See https://github.com/mapping-commons/SSSOM/issues/81

**Comment by cmungall** [comment]
This is already defined by rdf generation

in:

```yaml
id: https://w3id.org/linkml/tests/enum
name: enum_test
prefixes:
  linkml: https://w3id.org/linkml/
  enum_test: https://w3id.org/linkml/tests/kitchen_sink/
  x: https://example.org/x/
default_prefix: enum_test

enums:
  TestEnum:
    permissible_values:
      A B:
        meaning: x:001
      A B+C:
        meaning: x:002
      A B C:
        meaning: x:003
```

translates to 

```turtle
@prefix : <https://w3id.org/linkml/> .
@prefix linkml: <https://w3id.org/linkml/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

...

<https://w3id.org/linkml/tests/kitchen_sink/A%20B> linkml:meaning <x:001> .

<https://w3id.org/linkml/tests/kitchen_sink/A%20B%20C> linkml:meaning <x:003> .

<https://w3id.org/linkml/tests/kitchen_sink/A%20B%2BC> linkml:meaning <x:002> .

<https://w3id.org/linkml/tests/kitchen_sink/TestEnum> skos:inScheme <https://w3id.org/linkml/tests/enum> ;
    linkml:definition_uri <https://w3id.org/linkml/tests/kitchen_sink/TestEnum> ;
    linkml:permissible_values <https://w3id.org/linkml/tests/kitchen_sink/A%20B>,
        <https://w3id.org/linkml/tests/kitchen_sink/A%20B%20C>,
        <https://w3id.org/linkml/tests/kitchen_sink/A%20B%2BC> .

```
