### ISSUE TITLE
Definition for `Uri` type should clarify what values are acceptable

### ISSUE THREAD

**Issue by gouttegd** [linkml/linkml#2726]
The [linkml:Uri](https://linkml.io/linkml-model/latest/docs/Uri/) type is currently defined as follows:

```yaml
uri:
    uri: xsd:anyURI
    base: URI
    repr: str
    description: a complete URI
    comments:
      - >-
        in RDF serializations a slot with range of uri is treated as a literal or type xsd:anyURI unless it is an identifier or
        a reference to an identifier, in which case it is translated directly to a node
    notes: >-
      If you are authoring schemas in LinkML YAML, the type is referenced with the lower case "uri".
    close_mappings:
      - schema:URL
    conforms_to: https://www.ietf.org/rfc/rfc3987.txt
```

There are several issues with that definition, making it difficult to figure out what are the allowed values for that type.

1) What is the base `URI` type?

Unless I am mistaken, `URI` is _not_ a built-in Python type, so what does the `base: URI` refers to?

2) Are _relative URIs_ supposed to be acceptable for that type?

The description says that the type represents “a complete URI”. I initially thought that “complete”, in this context, was merely intended to mark the contrast with the `Curie` type, which is defined as “a compact URI”.

The specification for the `xsd:anyURI` type, to which this LinkML type is mapped, [clearly says](https://www.w3.org/TR/xmlschema-2/#anyURI) that “an anyURI value can be absolute or relative”, and further clarifies that when the value is a relative URI, it does not have to be “absolutizable”.

But people have interpreted the word “complete” in the LinkML description as meaning that the field is only intended for _absolute_ URIs ([example in SSSOM](https://github.com/mapping-commons/sssom/issues/448)).

So, is the `linkml:Uri` type intended to refer to any type of URI (absolute or relative), or only absolute URIs?

3) Conflicting references to other standards

The mapped `xsd:anyURI` type is defined as expecting values conformant with RFCs 2732 and 2396 (since then replaced by RFC 3986), the standard reference for URIs. But the LinkML model explicitly references (`conforms_to`) the RFC 3987 instead, the standard reference for **IRIs**. But the two standards are not interchangeable: any valid URI is necessarily also a valid IRI but not all valid IRIs are valid URIs.
