### ISSUE TITLE
SHACL export of class with re-annotated properties overwrites parent annotations

### ISSUE THREAD

**Issue by jsheunis** [linkml/linkml#2731]
---
Mac
Python version
LinkML version: 1.8.5
---

I am working with an application that renders UI from SHACL. The SHACL is exported from a LinkML schem, which imports other local and remote linkml schemas. I have some base classes where I add basic annotations to common slots, with the expectation that all inheriting classes will retain those annotations for the same properties.

Here's an illustrative example (`test.yaml`):

```yaml
id: https://concepts.datalad.org/s/things/test
name: things-schema
title: Generic schema for an arbitrarily detailed description of "things"

prefixes:
  dash: http://datashapes.org/dash#
  dlthings: https://concepts.datalad.org/s/things/v1/
  linkml: https://w3id.org/linkml/
  sh: http://www.w3.org/ns/shacl#

default_prefix: dlthings

imports:
  - linkml:types

slots:
  description:
    slot_uri: dlthings:description
    title: Description
    description: A free-text account of the subject.
    range: string
    annotations:
      dash:singleLine: false

  pid:
    slot_uri: dlthings:pid
    identifier: true
    title: Persistent identifier
    description: >-
      Persistent and globally unique identifier of a `Thing`.
    range: uriorcurie

classes:
  BaseClass:
    slots:
      - description
  
  ThingFromClass:
    class_uri: dlthings:ThingFromClass
    is_a: BaseClass
    description: >-
      The most basic, identifiable item.
    slots:
      - pid
    slot_usage:
      pid:
        annotations:
          sh:order: 1
      description:
        annotations:
          sh:order: 2
```

The `description` slot has annotation `dash:singleLine: false`. This slot is included as is into the `BaseClass` class. Another class `ThingFromClass` has `BaseClass` as parent, and it uses `slot_usage` to add another annotation `sh:order: 2` for the `description` slot.

When I then generate shacl from this (`gen-shacl --include-annotations test.yaml`), I get:

```ttl
@prefix dash: <http://datashapes.org/dash#> .
@prefix dlthings: <https://concepts.datalad.org/s/things/v1/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

dlthings:BaseClass a sh:NodeShape ;
    sh:closed true ;
    sh:ignoredProperties ( dlthings:pid rdf:type ) ;
    sh:property [ dash:singleLine false ;
            sh:datatype xsd:string ;
            sh:description "A free-text account of the subject." ;
            sh:maxCount 1 ;
            sh:name "Description" ;
            sh:nodeKind sh:Literal ;
            sh:path dlthings:description ] ;
    sh:targetClass dlthings:BaseClass .

dlthings:ThingFromClass a sh:NodeShape ;
    sh:closed true ;
    sh:description "The most basic, identifiable item." ;
    sh:ignoredProperties ( rdf:type ) ;
    sh:property [ sh:datatype xsd:anyURI ;
            sh:description "Persistent and globally unique identifier of a `Thing`." ;
            sh:maxCount 1 ;
            sh:name "Persistent identifier" ;
            sh:nodeKind sh:Literal ;
            sh:order 1 ;
            sh:path dlthings:pid ],
        [ sh:datatype xsd:string ;
            sh:description "A free-text account of the subject." ;
            sh:maxCount 1 ;
            sh:name "Description" ;
            sh:nodeKind sh:Literal ;
            sh:order 2 ;
            sh:path dlthings:description ] ;
    sh:targetClass dlthings:ThingFromClass .

```

The `dash:singleLine false ;` is present in the property shape for `sh:path dlthings:description` of the  `dlthings:BaseClass` node shape, but it is absent for `dlthings:ThingFromClass`. If I change the original schema by removing the re-annotation lines and then generate the SHACL again, the `dash:singleLine false ;` is present in both node shapes, as expected.

Notes:
- I'm guessing the re-annotation overwrites inherited annotations, which should not happen.
- IIRC I introduced the code for the `--include-annotations` flag for `shacl_gen.py` originally, so I will start by searching that to see if the error originates there
- I originally noticed this problem in the context of `sh:order` being different for a mixin-derived class compared to the mixin itself, and I mistakenly thought the issue was related to classes derived from other classes vs from mixins. But I tested this with the above schema, and it seems the problem persists irrespective of the particular inheritance.
- From a cursory read of https://github.com/linkml/linkml/issues/2219 I had the impression that this issue could be related, but I am not sure yet. Will update my opinion once I have tested the annotation code in `shacl_gen.py`.
