### ISSUE TITLE
Inlined Classes: Misinterpretation of the JSON-LD standard in PR #2461

### ISSUE THREAD

**Issue by hadjian** [linkml/linkml#2772]
---
name: Inlined Classes generate wrong JSON-LD context
title: ''Misinterpretation of the JSON-LD standard in PR #2461"
labels: bug

---

**Describe the bug**
I think PR #2461 misinterpreted the JSON-LD standard, which resulted in using the class IRI specified in the range of a slot as the ```@type``` in the JSON-LD context. 

**Version of LinkML you are using**

1.9.2

**Please provide a schema (and if applicable, a data file) that replicates the issue**

I added the ```spouse``` slot to the personinfo example:
```
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
  personinfo: https://w3id.org/linkml/examples/personinfo#
imports:
  - linkml:types
default_range: string
default_prefix: personinfo

classes:
  Person:
    attributes:
      id:
      full_name:
      aliases:
      phone:
      age:
    slots:
      - spouse

slots:
  spouse:
    range: Person
    inlined: true
```
The generated context below (the ```spouse``` term has an ```@type``` of ```personinfo:Person``` ):
```
{
   "@context": {
      "xsd": "http://www.w3.org/2001/XMLSchema#",
      "linkml": "https://w3id.org/linkml/",
      "personinfo": "https://w3id.org/linkml/examples/personinfo#",
      "@vocab": "https://w3id.org/linkml/examples/personinfo#",
      "age": {
         "@id": "age"
      },
      "aliases": {
         "@id": "aliases"
      },
      "full_name": {
         "@id": "full_name"
      },
      "id": {
         "@id": "id"
      },
      "phone": {
         "@id": "phone"
      },
      "spouse": {
         "@type": "personinfo:Person",
         "@id": "spouse"
      },
      "Person": {
         "@id": "Person"
      }
   }
}
```
**Replicate the Bug**

Using the generated context, I prepared an example on the JSON-LD playground: https://tinyurl.com/5n75yjwc

If you inspect the "n-quads" tab, you will see that the object of the spouse triple reads:

```
"personinfo:f1922f1d-409f-402d-b44b-9248633ac9f6"^^<https://w3id.org/linkml/examples/personinfo#Person>
```

This is a typed string and should be an IRI. IMHO, this is the confusion between [typing node objects][0] and [typing value objects][1] in the JSON-LD standard. Both use the keyword ```@type```, but one designates the type of a resource as in RDF:

```
:john rdf:type :Person
```
While the other designates datatypes for strings to enable the mapping of JSON strings to RDF literals, as in:

```
"3"^^^xsd:integer
"ISBN 978-3-8668-0192-9"^^^schema:isbn
```
As IRIs in RDF are identified in lexical space, they would not appear as quoted strings, but with angle brackets:

```
<http://www.example.com>
```
You can also observe in the JSON-LD playground that the spouse is not embedded anymore, because the information that it is an IRI is lost. 

To rectify the example, switch to the "framed" tab in the playground example and change in the context the ```@type``` in the ```spouse``` term to ```@id``` again, but both in the input document and in the frame document or open this link, where I applied the change: https://tinyurl.com/2p7hjvxc

Now you can see that the spouse object is embedded and the "n-quads" tab shows the ID of John correctly as an IRI literal.

Also mind the note in the standard:

---
**Note**
The use of @type to define a type for both [node objects](https://www.w3.org/TR/json-ld11/#dfn-node-object) and [value objects](https://www.w3.org/TR/json-ld11/#dfn-value-object) addresses the basic need to type data, be it a literal value or a more complicated resource. Experts may find the overloaded use of the @type keyword for both purposes concerning, but should note that Web developer usage of this feature over multiple years has not resulted in its misuse due to the far less frequent use of @type to express typed literal values.
---

I strongly disagree with this observation ;-)

@vincentkelleher 

[0]: https://www.w3.org/TR/json-ld11/#node-objects 
[1]: https://www.w3.org/TR/json-ld11/#value-objects
