### ISSUE TITLE
Method resolution with multiple inheritance

### ISSUE THREAD

**Issue by kshefchek** [linkml/linkml#290]
I'm wondering if LinkML should provide some guidance (or validation) on potential method resolution errors with multiple inheritance with base classes and mixins.  Take the following example in the biolink model schema:

```yaml
  behavior:
    is_a: biological process
    mixins:
      - ontology class
      - activity and behavior
 
  activity and behavior:
    is_a: occurrent
  
  biological process:
    is_a: biological process or activity
    mixins:
      - occurrent
      - ontology class
  
  occurrent:
    is_a: physical essence or occurrent
    
  physical essence or occurrent:
    # physical essence or occurrent is a base class
  
  biological process or activity:
    is_a: biological entity
  
  biological entity:
    is_a: named thing
 
  named thing:
    is_a: entity
  
  ontology class:
    # ontology class is a root class

```

When converting to python classes, one might order the classes from (left to right), ParentClass, Mixin1, Mixin2, ...

However this returns a TypeError for Behavior:
Given class Behavior(BiologicalProcess, OntologyClass, ActivityAndBehavior):
```TypeError: Cannot create a consistent method resolution order (MRO) for bases Occurrent, OntologyClass, ActivityAndBehavior```

My question is - should LinkML have some validation of multiple inheritance ordering and potential problems with method resolution order?  Do we want to prevent diamond inheritance all together (I'm guessing no)?

 Here is an example with python classes to test the behavior
 
 ```python3
# MRO resolution TypeError example
class Entity:
    pass

class OntologyClass:
    pass

class PhysicalEssenceOrOccurrent:
    pass

class NamedThing(Entity):
    pass

class BiologicalEntity(NamedThing):
    pass

class BiologicalProcessOrActivity(BiologicalEntity):
    pass

class Occurrent(PhysicalEssenceOrOccurrent):
    pass

class ActivityAndBehavior(Occurrent):
    pass

class BiologicalProcess(BiologicalProcessOrActivity, Occurrent, OntologyClass):
    pass

# TypeError: Cannot create a consistent method resolution order (MRO) for bases Occurrent, OntologyClass, ActivityAndBehavior
#class Behavior(BiologicalProcess, OntologyClass, ActivityAndBehavior):
#    pass

# This fails as well
# class Behavior(OntologyClass, BiologicalProcess, ActivityAndBehavior):
#    pass

# This order compiles
class Behavior(ActivityAndBehavior, BiologicalProcess, OntologyClass):
    pass

# This compiles as well
class Behavior(BiologicalProcess, ActivityAndBehavior, OntologyClass):
    pass
```
