### ISSUE TITLE
annotations schema does not support multiple values for an annotation key: need an Any type?

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#296]
extension values are not multivalued:

```yaml
  extension_value:
    description: the actual annotation
    domain: extension
    alias: value
    required: true
```

additionally, these are inlined as dicts. This means there is no way to have multiple values for an annotation key

I have tried all the following:

```yaml
slots:
  foo:
    annotations:
      - tag: "ks:a1"
        value: [1,2,3]
      - tag: "ks:a2"
        value: ["v1", "v2", "v3"]
      - tag: "ks:a3"
        value: 'a3.1'
      - tag: "ks:a3"
        value: 'v3.2'
```

The resulting structure is:

```
{'ks:a1': Annotation(tag='ks:a1', value='[1, 2, 3]', extensions={}, annotations={}), 'ks:a2': Annotation(tag='ks:a2', value="['v1', 'v2', 'v3']", extensions={}, annotations={}), 'ks:a3': Annotation(tag='ks:a3', value='v3.2', extensions={}, annotations={})}
```

i.e. for the first two, lists are coerced into strings

I have also tried:

```yaml
annotations:
      "ks:mv": [1,2,3]
```

but this throws an error

A related issue is that even for single valued entries, everything is coerced into a string.

to solve the multivalued use case, we can extend the metamodel in extensions.yaml:

```yaml
  extension_value:
    description: the actual annotation
    domain: extension
    alias: value
    required: true
  extension_values:
    description: the actual annotation (multivalued)
    multivalued: true
    domain: extension
    alias: values
    required: true
```

but this doesn't solve the issue with needing annotations whose values are ints, bools, floats (or lists of these). Perhaps we need an Any type?
