### ISSUE TITLE
Add reversible to_str meta-property

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#30]
Use case: lat-long coordinates can be represented in both structured/normalized and flattened/denormalized form. E.g

```yaml
  geolocation value:
    is_a: attribute value
    description: >-
      A normalized value for a location on the earth's surface
    slots:
      - latitude
      - longitude
      - as string value
    slot_usage:
      as string value:
        to_str: "{latitude} {longitude}"
```

The semantics of SLOT.to_str would be:

 - the range of SLOT must be string
 - the value of SLOT must be equal to to_str, expanding all `{x}` expressions with SLOT.parent.x

Implementations are not dictated but for python way to generate code for _as_str.

This could be used to drive validators and bidirectional converters (e.g. given a flat string, auto-parse into normalized object)
