### ISSUE TITLE
undefined behavior when string used as key value for top level 

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#313]
given the following contrived schema, in which top level schema slots' dictionaries' have values which are strings rather than objects:

```yaml
id: foo
prefixes:
  foo: http://x.org/
default_prefix: foo
default_range: string

types:
  string:
    base: str
    uri: xsd:string
  t2:
    t2val

classes:
  c1:
    c1val
  c2:
    slot_usage:
      c2s:
        c2sval
    
slots:
  s1:
    s1val

enums:
  e1:
    permissible_values:
      v1: v1val

  e2:
    e2val
```

I would expect either:

 1. an error to be thrown as this doesn't match the metamodel schema
 2. OR consistent useful default behavior

It seems we get useful default behavior for e1, but in other cases the string is unexpectedly treated as a length-1 id_prefixes array:

```bash
pipenv run gen-yaml --raw --no-metadata testschema.yaml 
```

```yaml
name: foo
id: foo
prefixes:
  foo:
    prefix_prefix: foo
    prefix_reference: http://x.org/
default_prefix: foo
default_range: string
types:
  string:
    name: string
    definition_uri: http://x.org/String
    from_schema: foo
    base: str
    uri: xsd:string
  t2:
    name: t2
    id_prefixes:
    - t2val
    definition_uri: http://x.org/T2
    from_schema: foo
enums:
  e1:
    name: e1
    definition_uri: http://x.org/E1
    from_schema: foo
    permissible_values:
      v1:
        text: v1
        description: v1val
  e2:
    name: e2
    id_prefixes:
    - e2val
    definition_uri: http://x.org/E2
    from_schema: foo
slots:
  s1:
    name: s1
    id_prefixes:
    - s1val
    definition_uri: http://x.org/s1
    from_schema: foo
classes:
  c1:
    name: c1
    id_prefixes:
    - c1val
    definition_uri: http://x.org/C1
    from_schema: foo
  c2:
    name: c2
    definition_uri: http://x.org/C2
    from_schema: foo
    slot_usage:
      c2s:
        name: c2s
        id_prefixes:
        - c2sval
metamodel_version: 1.7.0
source_file: /Users/cjm/repos/linkml-model-enrichment/testschema.yaml
source_file_date: Mon Aug 30 22:36:48 2021
source_file_size: 327
generation_date: 2021-08-30 22:36
```

**Comment by cmungall** [comment]
in:
https://github.com/linkml/linkml-runtime/blob/444c6a8d1ed70d012d92671f6e3cbd0797a39a03/linkml_runtime/utils/yamlutils.py#L102

`order_up` is called passing the key-value tuple (e.g c1, c1val):

https://github.com/linkml/linkml-runtime/blob/444c6a8d1ed70d012d92671f6e3cbd0797a39a03/linkml_runtime/utils/yamlutils.py#L202

This is like calling `ClassDefinition(c1, c1val)`

the 2nd arg for all elements is `id_prefixes`

```yaml
element:
    description: a named element in the model
    abstract: true
    mixins:
      - extensible
      - annotatable
      - common_metadata
    slots:
      - name
      - id_prefixes
      - definition_uri
      - aliases
      - local_names
      - mappings
      - exact mappings
      - close mappings
      - related mappings
      - narrow mappings
      - broad mappings
    see_also:
      - https://en.wikipedia.org/wiki/Data_element
```

which explains the slightly odd behavior

for permissible value the order is text, description

```yaml
permissible_value:
    description: a permissible value, accompanied by intended text and an optional mapping to a concept URI
    mixins:
      - extensible
      - annotatable
      - common_metadata
    slot_usage:
      is_a:
        range: permissible_value
      mixins:
        range: permissible_value
    slots:
      - text
      - description
      - meaning
```

thus 
```
permissible_values:
      v1: v1val
```

is like calling PermissibleValue(v1,v1val)

it seems that relying on this behavior may be fragile - e.g. there is no guarantee that mixin slots are ordered after the direct class slots. It would be better to control this behavior through some explicit default field
