### ISSUE TITLE
Document how to model json objects with arbitrary keys and atomic values

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#315]
If we have json/yaml like:

```
translations:
  hand: manus
  foot: pes
  bone: os
```

where the keys are arbitrary the values are strings, it may not be obvious how this can be modeled in linkml, should be documented, see also #313.
