### ISSUE TITLE
Add enums and label->id mappings

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#37]
We have

```
  values_from:
    domain: definition
    multivalued: true
    range: uriorcurie
    description: >-
      the identifier of a "value set" -- a set of identifiers that form the possible values for the range of a slot
```

(aside: this is declared at the definition level, should be a slot property)

We should have the equiv for string values, i.e an enum.

e.g

```
slots:
  evidence code:
    enum:
      - IEA
      - ISS
...
```

it would be good to specify mappings for each of these, perhaps:

```
slots:
  evidence code:
    enum:
      IEA: ECO:nnnn
      ISS: ECO:nnn
...
```

or perhaps a more expressive:

```
slots:
  evidence code:
    enum:
      IEA:
        id: ECO:nnnn
        description: ...
      ISS: 
         id: ECO:nnn
         description: ...
...
```

mapping to a json-ld context should be obvious
