### ISSUE TITLE
Consider enum for metaslot "status"

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#440]
We have status in the linkml metamodel, mapped to pav:status, the range is string

Should we have the range of this be an enum? Closed or open?

There is a semweb vocab:

https://www.w3.org/2003/06/sw-vocab-status/note.html

<rdf:Property rdf:about="#term_status">
  <rdfs:label>term status</rdfs:label>
  <rdfs:comment>the status of a vocabulary term, expressed as a short symbolic string; known values include 'unstable','testing', 'stable' and 'archaic'</rdfs:comment>
  <vs:term_status>unstable</vs:term_status>
  <rdfs:isDefinedBy rdf:resource="http://www.w3.org/2003/06/sw-vocab-status/ns#"/>      
</rdf:Property>

should we at least have a convention about which strings are used in the metamodel? It is useful to include new features but mark them in some way as subject to change

**Comment by sierra-moxon** [comment]
It looks like `status` is constrained only as a 'uriorcurie' data type, not with an enumeration of possible values.  Do we still want that?  Right now we mostly just leave it out or it is set to 'testing'? 

```
  status:
    aliases:
      - workflow status
    domain: element
    range: uriorcurie
    description: status of the element
    slot_uri: bibo:status
    examples:
      - value: "bibo:draft"
    see_also:
      - https://www.hl7.org/fhir/valueset-publication-status.html  ## Draft, Active, Retired, Unknown
      - https://www.hl7.org/fhir/versions.html#std-process  ## Draft, Trial Use, Normative, Informative, Deprecated
    in_subset:
      - BasicSubset
```

**Comment by sierra-moxon** [comment]
It looks like the enum could be as simple as:
```
StatusEnum:
  permissible_values:
    unstable:
    testing:
    stable:
    archaic:
```
