### ISSUE TITLE
Clarify behavior of uriorcurie in rdf dumpers

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#450]
Recall that these are distinct triples in rdf:

LITERAL:

```turtle
:foo :pred "http://example.org"^^xsd:anyURI .
```

NODE:

```turtle
:foo :pred <http://example.org> .
```

The mapping from linkml instances to rdf is simple:

 1. instances of linkml classes are treated as nodes
 2. Instances of linkml types (including [linkml:Uriorcurie](https://w3id.org/linkml/Uriorcurie)) are treated as literals, with the type determined by `uri`. E.g

[linkml:Uriorcurie](https://w3id.org/linkml/Uriorcurie) is defined as:

```
 uriorcurie:
    uri: xsd:anyURI
    base: URIorCURIE
    repr: str
    description: a URI or a CURIE
```

This means if one wants to serialize using the NODE representation above, they need to model the range of :pred as a linkml **class**

First of all we need to make this very clear in the docs

Second, do we want a way to make it possible for people to model a range as a uriorcurie type, but to have this expanded to a node? This makes it easier for people who want to have a "flat" schema for TSVs with a single class (e.g. SSSOM)

I am not convinced it is a great idea to allow this, but if we do, I am leaning towards an implementation that first does a dynamic transform of the schema, rather than complexifying the dumper code with conditional logic.

Something like a utility class `nodeify_range(schemaview, slot_names) -> schema`. But this would only work for rdflib_dumper, rdf_dumper using the json-ld strategy is driven purely by the generated python code... See #424

**Comment by cmungall** [comment]
See https://github.com/linkml/linkml-runtime/releases/tag/v1.1.6

To model the range of a slot as a rdfs:Resource rather than rdfs:Literal **without** the overhead of creating a class

 1. Create a new type
 2. declare the uri to be rdfs:Resource

E.g.

given

```yaml
types:

  CrossReference:
    typeof: uriorcurie
    description: A string URI or CURIE representation of an external identifier, modeled as a Resource in RDF
    base: str
    uri: rdfs:Resource

  ImageURL:
    typeof: uri
    base: str
    uri: xsd:anyURI
```

and class

```yaml
 Concept:
    is_a: NamedThing
    attributes:
      code system:
        range: code system
      mappings:
        slot_uri: skos:exactMatch
        multivalued: true
        range: CrossReference
```


and data

```yaml
          id: CODE:D0001
          name: headache
          code_system: CODE:D
          mappings:
            - HP:0002315
            - http://purl.obolibrary.org/obo/SYMP_0000504
            - http://www.wikidata.org/entity/Q86
```

We get

```turtle
CODE:D0001 a ns1:DiagnosisConcept ;
    ns3:name "headache" ;
    ns2:exactMatch <http://purl.obolibrary.org/obo/HP_0002315>,
        <http://purl.obolibrary.org/obo/SYMP_0000504>,
        <http://www.wikidata.org/entity/Q86> ;
    ns1:code_system CODE:D .

```

In contrast, to force representation as a URI:

```yaml
depicted_by:
    range: ImageURL
```

yields:

```yaml
P:001 a ns3:Person ;
    ns3:email "fred.bloggs@example.com" ;
    ns3:gender <http://purl.obolibrary.org/obo/GSSO_000371> ;
    ns3:name "fred bloggs" ;
    ns1:age_in_years 33 ;
    ns1:depicted_by "https://example.org/pictures/fred.jpg"^^xsd:anyURI .
```

note the builtin type uriorcurie is modeled as xsd:anyURI, so any slot that takes this as a range will model as a anyURI literal
