### ISSUE TITLE
add more specific kinds of aliases

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#472]
I think in some of the models I work on, we conflate "mappings" with "aliases."  

For example, in biolink-model, we make a prefix declaration for 'CTD' and then use 'CTD:enables' as an exact_mapping for the biolink predicate 'enables.' (this is just an example, I've cleaned this one up, but there are many more like it).  Since `CTD:enables` isn't actually a curie that is resolvable, it leaves a fair bit of confusion for users that try to look up these "identifiers" to understand CTD's definition of this predicate (which sort of exists, but not officially, and not in a resolvable way).   

It seems like we're trying to solve two use cases with this kind of 'mapping':

1. we need users to see that `CTD enables` is equivalent to `biolink:enables` -- we want to capture the work the modelers have already done to research and understand `CTD enables` in relation to `biolink:enables.`   And we want users coming from a CTD perspective, to have an easy time of finding the biolink equivalent objects.  

Sometimes these "mappings" are syntactically equivalent to the biolink component, but other times they are different.  In either case, a modeler has already done the work to declare how close/narrow/broad/exact the "mappings" are to biolink.

2. we want to document that an external data source has mappings to the model components.  Said another way, we want to attribute this 'mapping' to an external data source.  (the prefix on the 'mapping' does this for us, but in a non-obvious way). 

Perhaps we need more granular alias types in the meta model?
eg: 
exact_alias
narrow_alias
broad_alias

Sometimes we don't actually want to say that all aliases are created equal either - depending on implementation use cases, a broader concept/alias might map to a narrower class or slot.  A generic "alias" takes this granularity away and makes it non-obvious to use as a meta-model component.  

eg, the CTD narrow mappings here, might be more like narrow_aliases rather than just aliases? 
```
  affects molecular modification of:
    description: >-
      holds between two chemical or gene/gene product entities  where the action or effect of one leads changes in the molecular
      modification(s) of the other (e.g. via post-translational modifications of proteins such as the addition of
      phosphoryl group, or via redox reaction that adds or subtracts electrons)
    is_a: affects
    in_subset:
      - translator_minimal
    domain: chemical entity or gene or gene product
    range: chemical entity or gene or gene product
    annotations:
      tag: biolink:canonical_predicate
      value: true
    narrow_mappings:
      - CTD:affects_acetylation
      - CTD:affects_acylation
```
And, perhaps these should be lists of alias objects so that we can store both the alias string 'enables' and the source of the alias 'CTD' instead of trying to use a curie that doesn't resolve to capture both the alias string and the source of the alias.

• Long-term - 6 months - 1 year

**Comment by sierra-moxon** [comment]
another use case here might be: how to represent a "use this model slot instead of these non-curied terms"

(see below, the NCIT narrow mappings should fit into this use case category). 

```

  has attribute:
    description: >-
      connects any entity to an attribute
    domain: entity
    range: attribute
    multivalued: true
    in_subset:
      - samples
    close_mappings:
      # RTX term meaning 'specifies value of' tagged as inverse of 'biolink:has attribute'
      - OBI:0001927
    exact_mappings:
      - SIO:000008
    narrow_mappings:
      - NCIT:eo_disease_has_property_or_attribute
      - NCIT:has_data_element
      - NCIT:has_pharmaceutical_administration_method
      - NCIT:has_pharmaceutical_basic_dose_form
      - NCIT:has_pharmaceutical_intended_site
      - NCIT:has_pharmaceutical_release_characteristics
      - NCIT:has_pharmaceutical_state_of_matter
      - NCIT:has_pharmaceutical_transformation
      - NCIT:is_qualified_by
      - NCIT:qualifier_applies_to
      - NCIT:role_has_domain
      - NCIT:role_has_range
```
