### ISSUE TITLE
Add a JsonLdSchema generator

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#474]
json-ld-schema combines both json-schema and json-ld contexts into a single semantic schema (this is also one of the value propositions of linkml):

Project here:
https://github.com/mulesoft-labs/json-ld-schema

here is an example, with my annotations as `##`:

```json
{
  ## Analogous to the LinkML prefixes block
  "@context": {
    "sorg": "http://schema.org/"
  },
  ## Analogous to LinkML class
  "@type": "sorg:Person",
  "type": "object",

  ## Class slots
  "properties": {
    "sorg:givenName": {
      "type": "string"
    },
    "sorg:gender": {
      "type": "string",
      "pattern": "male|female"
    }
  },
  "required": [ "sorg:name", "sorg:gender"]
}
```

The analogous LinkML is:

```yaml
prefixes:
  sorg: http://schema.org/
default_prefix: sorg
default_range: string
classes:
  Person:
    attributes:
      givenName:
        required: true
      gender:
        pattern: "male|female" 
        required: true
```

(if we have a mixed set of vocabularies we can explicitly declare URIs using [class_uri](https://w3id.org/linkml/class_uri) and [slot_uri](https://w3id.org/linkml/slot_uri)

Note that just like json-ld-shema, the linkml schema can be used to validate rdf data regardless of whether it has been normalized to a specific json form

If we decide to implement a generator, we could either:

 * subclass JsonSchemaGenerator and use ContextGenerator to inject a context
 * use composition instead - i.e. build both a json schema and a context and then merge them

We could also implement the reverse transform, currently the importers live in a separate repo (linkml-model-enrichment)

I would say both are relatively low as we don't gain anything that we don't get already by our existing validation routes

We should also have an entry in the FAQ about json-ld-schema
