### ISSUE TITLE
SchemaView not retrieving induced slot description

### ISSUE THREAD

**Issue by wdduncan** [linkml/linkml#479]
I have put together a small test to for retrieving an induced slots description.

Schema:
```
id: https://example.com/test-induced
name: test-induced
title: test induced

description: >-
    test schema view's finding of induced slot information.

classes:
    class1:
        slots:
            - slot1
        slot_usage:
            slot2:
                 description: induced slot2
slots:
    slot1:
        description: non-induced slot1
    slot2:
        description: non-induced slot2
```
When I run tests, this passes:
```
s1 = view.get_slot('slot1')
assert s1.description == "non-induced slot1"
```
But, this fails:
```
s2_induced = view.induced_slot("slot2", "class1")
assert s2_induced.description == "induced slot2"
```
Is this expected behavior?

I am attaching my test file, which I can turn into a unit test if need be.
[induced-slot-test.py.txt](https://github.com/linkml/linkml-runtime/files/7565520/induced-slot-test.py.txt)
