### ISSUE TITLE
Make framework robust to network errors (caching, alternate download paths, etc)

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#502]
Currently there is a network dependency if a schema imports another schema via URL - this is most commonly done via imports of types from linkml-model

This morning a number of us have seen intermittent issues with w3id, specifically for https://w3id.org/linkml/types.yaml. If w3id network resolution fails, then most test suites of both linkml itself and libs that use linkml will failm due to the need to import types.yaml over the network

e.g. linkml-runtime fail earlier today:

https://github.com/linkml/linkml-runtime/runs/4461013582?check_suite_focus=true#step:5:238

![image](https://user-images.githubusercontent.com/50745/145267408-577afefc-27d9-43a7-a0f6-2667fd819911.png)

Reported here: https://github.com/perma-id/w3id.org/issues/2434

They suggest:

> I'd also consider adding a fallback to local cached resources if possible rather than depending on networked resources to always be available.

I think we should implement this

**Comment by cmungall** [comment]
Two orthogonal approaches:

 1. a global configuration that includes a CURIE to location map, analogous to catalog-v001.xml in OWL
 2. a caching mechanism

For 1, could be

```yaml
download_map:
    "linkml:types":
       alternate_paths:             ## in priority order
         - https://raw.github./.....
         - /path/to/my/folder/types.yaml
```

For 2, one challenge is refreshes. Separate from this, it would be good to able to state the equivalent of [version specifiers](https://packaging.python.org/en/latest/glossary/#term-Requirement-Specifier) on imports, so that tooling can cache on a per-version basis. But this would require something like a repository for schemas...

**Comment by joeflack4** [comment]
Wouldn't `/path/to/my/folder/types.yaml` in (1) indeed be a locally cached file? That would seem to me to entail (2).

The way (1) is set up looks fine. As it's setup, I imagine that `alternate_paths` would have 1+ URLs at the top of the list, and 1 (would you ever need more than 1?) path to a locally cached file.

I don't see any harm in making this structure more explicit, as well as adding versioning, e.g.:

```yml
download_map:
    "linkml:types":
        latest:
            online:
                - https://raw.github.somerepo1/.....
                - https://raw.github.somerepo2/.....
            cache:
                - /path/to/my/folder/types_yaml/latest/types.yaml
        1.0.1:
            online:
                - https://raw.github.somerepo1/.....
                - https://raw.github.somerepo2/.....
            cache:
                - /path/to/my/folder/types_yaml/1.0.1/types.yaml
```

I think this is pretty self explanatory, but basically, we store this structure. Then linkml attempts to fetch from 'online' for the given version, else loads from cache.
