### ISSUE TITLE
Add slots to SchemaDefinition in metamodel to document how to contribute and local best practice modeling

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#503]
```yaml
id: my_model
examples:
counter_examples:
contributing:
  repo: ...
  code_of_conduct: ...
  mail_list: ...
  pull_requests: ...
  tests: ...
  best_practices:
    - element: id
       title: all elements must have identifiers
       description: ...
```

this could be used to generate markdown that is added alongside index.md, allowing a consistent look across model repos, while allowing customization.

It also provides an alternative to template-based generation of standard files in the repo such as CONTRIBUTING.md, CODE_OF_CONDUCT, ...
