### ISSUE TITLE
extension_tag should be declared a key in extensions.yaml

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#548]
extensions tag should be declared a key

```yaml
 extension_tag:
    description: a tag associated with an extension
    domain: extension
    range: uriorcurie
    alias: tag
    required: true
```

Such that it's valid to have schemas

```
classes:
  my_class:
    ...
    annotations:
       my_tag: my_value
```

in fact it's treated as if it has a key due to this bug:

 * https://github.com/linkml/linkml/issues/463
