### ISSUE TITLE
Provide a compact way to export a schema eliminating fields that duplicate keys

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#553]
See #100 

when roundtripping

```yaml
prefixes:
  ex: http://example.org/
  biolinkml: https://w3id.org/biolink/biolinkml/
```

this is generated:

```yaml
prefixes:
  ex:
    prefix_prefix: ex
    prefix_reference: http://example.org/
  biolinkml:
    prefix_prefix: biolinkml
    prefix_reference: https://w3id.org/biolink/biolinkml/
```

also duplicative name fields are added for anything inlined as a dict

```yaml
classes:
  person:
    slot_usage:
      id:
        identifier: true
        required: true
      name:
        required: true
      aliases:
        multivalued: true
```

becomes

```yaml
classes:
  person:
    name: person
    definition_uri: http://example.org/Person
    from_schema: http://example.org/sample/sql
    slots:
    - person_id
    - person_name
    - person_aliases
    slot_usage:
      id:
        name: id
        from_schema: http://example.org/sample/sql
        range: string
        slot_uri: ex:id
        required: true
        identifier: true
      name:
        name: name
        from_schema: http://example.org/sample/sql
        range: string
        slot_uri: ex:name
        required: true
      aliases:
        name: aliases
        from_schema: http://example.org/sample/sql
        range: string
        slot_uri: ex:aliases
        multivalued: true
    class_uri: ex:Person
```

Although this is correct there is redundancy that can be removed.
