### ISSUE TITLE
pydanticgen fails if the enum permissible value includes unsafe characters

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#554]
in kitchen sink yaml, 

```yaml
  other codes:
    permissible_values:
      a b:
      #1+2:
```

uncommenting the last line causes pydanticgen to generate nonparseable python
