### ISSUE TITLE
Loaders should allow lists as inputs/outputs

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#564]
A common pattern is to store data im yaml/json as lists:

E.g

```yaml
- id: P1
  name: dr doctor
- id: P2
  name: dr octopus
- ...
```

currently the yaml/json loader and dumper framework doesn't work with
this. This necessitates creating *container* classes and slots in a
schema, e.g

```yaml
persons:
- id: P1
  name: dr doctor
- id: P2
  name: dr octopus
- ...
```

This becomes awkard if the schema has heterogenous classes,
necessitating a container for each class

It would be better if the loader framework allowed loading of lists
directly

I think load/loads could be generalized but this would required
generalizing the return type using a Union. While this would not
affect the logic of existing code, it could make existing code violate
mypy typing.

I think therefore it would be better to have parallel functions `multiload(s)`

We may also want this for dump(s) too.

Another thing that would be convenient for heterogeneous classes is the ability to specify a type_designator at the top level, or using `@type`, to be able to specify lists of mixed classes.
