### ISSUE TITLE
default_prefix should work against imported prefixes as well as prefixcommons prefixes

### ISSUE THREAD

**Issue by jiaola** [linkml/linkml#57]

**Comment by hsolbrig** [comment]
The following reproduces this problem:

test.yaml:
```
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
  - stuff
default_range: string
default_prefix: ex

classes:
  Person:
    class_uri: ex:Foo
```
stuff.yaml:
```
id: https://w3id.org/linkml/examples/stuff
name: stuff
prefixes:
  ex: https://examples.org/
```
If you comment out the `default_prefix:` line, the imported "ex" prefix works correctly.  The error message is:

`ValueError: File "<file>", line 9, col 17 Default prefix: ex is not defined`

Note also that:
1) this error message follows a stack trace.  We've got an issue for that bit
2) "<file>" should actually be "test.yaml".  We've got an issue for that as well
