### ISSUE TITLE
define behavior for converting non-CURIE identifiers in data to RDF

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#576]
given a schema:

```yaml
id: https://example.org/
name: example

prefixes:
  ex: https://example.org/
  linkml: https://w3id.org/linkml/

default_prefix: ex
default_range: string

imports:
  - linkml:types

classes:
  Container:
    tree_root: true
    slots:
      - things
  Thing:
    slots:
      - name
      - description

slots:
  name:
    identifier: true
    range: string
  description:
    range: string
  things:
    multivalued: true
    range: Thing
    inlined: true
```

and data:

```yaml
things:
  thing1:
    description: foo
```

what is the expected behavior of converting to RDF? Specifically the URI for thing1

Currently we get:

```
ValueError: : Unknown CURIE prefix: @base
```

which, while not user-friendly, is actually reasonable since we are using a non-CURIE as an identifier.

However, we should define the intended behavior precisely, which could be one of:

 1. explicitly disallow non-CURIE identifiers, and have a more friendly error message
 2. use default_prefix as `@base`
 3. allow addition of `@base` into the list of prefixes
      - variant: allow passing of base on command line

I think 2 is a bad choice, as typically schema namespaces and data namespaces are different

implementing 3 could be challenging. As expected, if we try this:

```yaml
prefixes:
  ex: https://example.org/
  linkml: https://w3id.org/linkml/
  "@base": https://example.org/data/
```

we get:

```
ValueError: @base: Not a valid NCName
```

so if we want to allow option 3, passing of a base prefix via the schema, then we must either

 - a. relax the constraint on prefix.prefix_prefix to be any string, or either NCName or `@base`
 - b. have another NCName that stands for `@base`. The challenge here is to avoid clashes. I may want to use `base` for my ontology prefix
 - c. have a new schema level slot such as `base_prefix_for_data`
 - d. force passing on command line or a separate prefix map
 - e. have some mechanism for including in the data. I don't think this is desirable as the data should reflect the actual data
 - f. have a hardcoded base used by all. this is obviously not ideal
