### ISSUE TITLE
generated jsonschema should support unconstrained ranges

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#579]
if a class is mapped to linkml:Any, and this is used in a range, then any object can go here. See #54 and also these docs: https://github.com/linkml/linkml/blob/main/sphinx/schemas/experimental.md

currently the generated jsonschema ignores this

we want to allow

```yaml

classes:
  AnyObject:
    class_uri: linkml:Any

slots:
 ...
 metadata:
    range: AnyObject
    description: Example of a slot that has an unconstrained range
```

and have data:

```yaml
       metadata:
          anything:
            goes:
              here:
```

validate

the generated json schema should be

```json
            "metadata": {
               "$ref": "#/$defs/AnyObject",
               "description": "Example of a slot that has an unconstrained range"
            },

...

      "AnyObject": {
         "additionalProperties": true,
         "description": "",
         "properties": {},
         "required": [],
         "title": "AnyObject",
         "type": "object"
      },
```
