### ISSUE TITLE
provide override/extension system

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#584]
we may frequently wish to reuse an existing schema, but override some fields. For example, override descriptions with our own.

linkml provides is_a to extend something, but sometimes we don't want a new element, we just want a locally modified version of one element

It is relatively easy to do this on an ad-hoc basis - e.g. a script that takes a yaml schema and a tsv of overrides and applies them. But this can lead to complexity and be hard to manage.

It would be good to have standard practice for this. Some approaches:

 - a TSV serialization data conforming of the linkml-dataops datamodel, similar to NMDC changesheets
 - a metamodel extension, where I can say "import E from S, modifying E.x to value v"
 - a standard core script that takes simple TSV and applies it
 - ...?

**Comment by cmungall** [comment]
See https://github.com/linkml/linkml-runtime/pull/114

**Comment by goodb** [comment]
@cmungall this would be helpful for adoption of biolink.  I'd like to use it, but I need to be able to make some extensions to core classes - e.g. additional slots on Gene.  I can do this via isa but I would prefer a method to override certain aspects of the schema for a given class.

**Comment by sneakers-the-rat** [comment]
+1 having this problem now, trying to make a version of the activitypub schema, which inherits from activitystreams and extends the Object model. when I try this:

```yaml
classes:
  Object:
    is_a: Object # inherited from an imported activitystreams schema
    slots:
      - source # additional slot not present in base schema

slots:
  source:
    slot_uri: ap:source
    # ...
```

the resulting models are just the original imported `Object` without any modifications made by the importing class. This would still be a monotonic class extension (cf https://github.com/linkml/linkml/issues/1730 ), it seems to be the inherited class having the same name that is the issue.
