### ISSUE TITLE
extend loaders/dumpers to instantiate from a list

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#589]
Sometimes we want to be able to load from a JSON or YAML file that has no container and is just a list of objects, e.g

```yaml
  - id: P:001
    name: fred bloggs
    primary_email: fred.bloggs@example.com
    age_in_years: 33
    depicted_by: https://example.org/pictures/fred.jpg
  - id: P:002
    name: joe schmoe
    primary_email: joe.schmoe@example.com
    has_employment_history:
      - employed_at: ROR:1
        started_at_time: 2019-01-01
        is_current: true
    has_familial_relationships:
      - related_to: P:001
        type: SIBLING_OF
    has_medical_history:
      - started_at_time: 2019-01-01
        in_location: GEO:1234
        diagnosis:
          id: CODE:D0001
          name: headache
          code_system: CODE:D
          mappings:
            - HP:0002315
            - http://purl.obolibrary.org/obo/SYMP_0000504
            - http://www.wikidata.org/entity/Q86
        procedure:
          id: CODE:P0001
          name: trepanation
          code_system: CODE:P
          subtype: personinfo:OperationProcedureConcept
    current_address:
      street: 1 foo street
      city: foo city
```

currently json_loader/dumper loads assumes what is returned will be a YAMLRoot - I don't think we want to change the signature but it would be good to have an alternate mechanism to load into a list
