### ISSUE TITLE
slot_usage -- injects a global slot into the namespace

### ISSUE THREAD

**Issue by jiaola** [linkml/linkml#59]
-- can be ugly. We need a policy on this.

Example

---- Input ---
```
classes:
   c1:
      slot_usage:
         s1:
            key: true
            required: true
            
         
   c2:
      slot_usage:
         s1:
            identifier: true
            required: false
```
   
------- output ---
```
slots:
    s1:
        key: true
        identifier: true
        required: ???
    c1_s1:
        is_a: s1
    c2_s1:
        is_a: s1

        
classes:
    c1:
        slots:
            - c1_s1
    c2:
        slots:
            - c2_s1
            
        

classes:
    c1:
        slots
        - s1
        
    c2:
       is_a: c1
       slot_usage:
          s1:
            required: true
slots:
    s1: 
       domain_of:
       - c1
    c2_s1:
       is_a: s1
       domain_of:
       - c2
         
classes:
    c1:
        slots:
        - s1
        
    c2:
        slots:
        - c2_s1
        
    slot_usage:
        - s1
```
