### ISSUE TITLE
Schemas with a slot "name" that includes no additional metadata are not handled by SchemaLoader

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#626]
```yaml
id: http://x.org

default_range: string
types:
  string:
    base: str
    uri: xsd:string
    
slots:
  name:
```

Causes:

```
ValueError: name must be supplied
```

This is fixed by either:

- calling the slot something other than "name"
- adding information to the name field

in fact even adding `{}` works:

```yaml
id: http://x.org

default_range: string
types:
  string:
    base: str
    uri: xsd:string
    
slots:
  name: {}
```

so it's easily resolved, but it is an unusual bug
