### ISSUE TITLE
Illegal entities or unmapped slot_uris in owl gen should fail hard

### ISSUE THREAD

**Issue by matentzn** [linkml/linkml#638]

**Comment by nlharris** [comment]
This doesn't sound like an issue that only Chris can address. Maybe @sujaypatil96 can tackle this one?

**Comment by sierra-moxon** [comment]
@matentzn - I think I understand what you mean here, is this a good representation of an example that is broken?

```
prefixes:
   test: https://test.org/

classes:
   foo:
      slots:
         - bar

slots:
   bar:  
     slot_uri: not_a_great_prefix:13345
 
```

**Comment by matentzn** [comment]
For the first issue yes! For the second one:

> If you put () or other special chars in the in the class Ids, OWL is generated but is not parseable afterwards

this should work: 

```
prefixes:
   test: https://test.org/

classes:
   foo(rab):
      slots:
         - bar

slots:
   bar:  
     slot_uri: not_a_great_prefix:13345
```
