### ISSUE TITLE
Have option in json/yaml loader/dumper to use implicit containers and container slots

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#646]
A common pattern is making a container class with `X_set` objects for every class X

e.g. if a schema has persons, organizations, places then having

```
  Container:
    attributes:
      person_set:
        multivalued: true
        range: Person
        inline: true
      ...
```

this simplifies json/yaml serialization in that one container object can hold the entire database

it can be tedious and redundant to describe these especially if the schema has many classes

@deepakunni3 proposes a different way here:

https://github.com/linkml/linkml-validator#input-data-as-a-dictionary-of-objects

we would simply have a top level dictionary keyed by class name

TBD

1. do this formally as a schema pre-processing step where these are added
2. do this implicitly where the loaders and dumpers (optionally) detect this structure

the advantage of 1 is that things like json-schema validation 'just work' on the parent structure

1 can be subdivided into an approach where this is a schema helper tool that would compile a new schema OR it could be an implicit schema conversion that happens prior to other processing

however, 2 is maybe simpler
