### ISSUE TITLE
Take into account descendants of a range class when generating JSON Schema

### ISSUE THREAD

**Issue by deepakunni3** [linkml/linkml#652]
This request is pertaining to the jsonschemagen.py and the use-case can be best described as follows:

If I have the following schema,

```yaml
id: https://w3id.org/Example-Schema
name: Example-Schema
description: >-
  An Example Schema
version: 0.0.0
imports:
  - linkml:types

prefixes:
  linkml: https://w3id.org/linkml/
  example: https://w3id.org/example/

default_prefix: example

classes:
  c1:
    slots:
        - prop1

  c2:
    is_a: c1
    slots:
        - prop2

  c3:
    is_a: c1
    slots:
      - prop3

  named thing:
    slots:
      - prop4


slots:
  prop1:
    required: true

  prop2:
    range: string
    required: true

  prop3:
    range: string
    required: true

  prop4:
    range: c1
```

Then the jsonschema generated by the jsonschema-gen looks as follows:

```json
{
   "$defs": {
      "C1": {
         "additionalProperties": false,
         "description": "",
         "properties": {
            "prop1": {
               "type": "string"
            }
         },
         "required": [
            "prop1"
         ],
         "title": "C1",
         "type": "object"
      },
      "C2": {
         "additionalProperties": false,
         "description": "",
         "properties": {
            "prop1": {
               "type": "string"
            },
            "prop2": {
               "type": "string"
            }
         },
         "required": [
            "prop1",
            "prop2"
         ],
         "title": "C2",
         "type": "object"
      },
      "C3": {
         "additionalProperties": false,
         "description": "",
         "properties": {
            "prop1": {
               "type": "string"
            },
            "prop3": {
               "type": "string"
            }
         },
         "required": [
            "prop1",
            "prop3"
         ],
         "title": "C3",
         "type": "object"
      },
      "NamedThing": {
         "additionalProperties": false,
         "description": "",
         "properties": {
            "prop4": {
               "$ref": "#/$defs/C1"
            }
         },
         "required": [],
         "title": "NamedThing",
         "type": "object"
      }
   },
   "$id": "https://w3id.org/Example-Schema",
   "$schema": "http://json-schema.org/draft-07/schema#",
   "additionalProperties": true,
   "metamodel_version": "1.7.0",
   "properties": {},
   "required": [],
   "title": "Example-Schema",
   "type": "object",
   "version": "0.0.0"
}
```

If we look at the JSON Schema definition for `NamedThing` above we see that `prop4` has a reference to class `C1`. 

Class `C1` has two children: `C2` and `C3`.

Typing the property `prop4` to just the parent class `C1` means that the additional properties of the subclasses (`C2` and `C3`) are ignored.

Instead, it would be much more useful if the generated schema was as follows:

```json
{
   "$defs": {
      "C1": {
         "additionalProperties": false,
         "description": "",
         "properties": {
            "prop1": {
               "type": "string"
            }
         },
         "required": [
            "prop1"
         ],
         "title": "C1",
         "type": "object"
      },
      "C2": {
         "additionalProperties": false,
         "description": "",
         "properties": {
            "prop1": {
               "type": "string"
            },
            "prop2": {
               "type": "string"
            }
         },
         "required": [
            "prop1",
            "prop2"
         ],
         "title": "C2",
         "type": "object"
      },
      "C3": {
         "additionalProperties": false,
         "description": "",
         "properties": {
            "prop1": {
               "type": "string"
            },
            "prop3": {
               "type": "string"
            }
         },
         "required": [
            "prop1",
            "prop3"
         ],
         "title": "C3",
         "type": "object"
      },
      "NamedThing": {
         "additionalProperties": false,
         "description": "",
         "properties": {
            "prop4": {
               "oneOf": [
                  {
                     "$ref": "#/$defs/C1"
                  },
                  {
                     "$ref": "#/$defs/C2"
                  },
                  {
                     "$ref": "#/$defs/C3"
                  }
               ]
            }
         },
         "required": [],
         "title": "NamedThing",
         "type": "object"
      }
   },
   "$id": "https://w3id.org/Example-Schema",
   "$schema": "http://json-schema.org/draft-07/schema#",
   "additionalProperties": true,
   "metamodel_version": "1.7.0",
   "properties": {},
   "required": [],
   "title": "Example-Schema",
   "type": "object",
   "version": "0.0.0"
}
```

where `prop4` can be of type `C1` OR `C2` or `C3`.

Intuitively, this is more inline with what we expect when we define range constraints for a slot in linkml.

This also helps in validation where the `target_class` can be the parent class and still validate all subclass instances and not just the parent class instance.

Of course, one caveat of enumerating all descendants of the range class is a large list of `$ref` for a property. 

A way around this would be to have this enumeration be optional with default being `False`.
