### ISSUE TITLE
What schema slot should be used to indicate the source of an element?

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#654]
Example use case: when importing or converting mixs for use in nmdc schema

@turbomam and @sujaypatil96 were thinking of using from_schema but this is readonly and populated by the loader

```yaml
  from_schema:
    domain: element
    range: uri
    readonly: supplied by the schema loader
    description: id of the schema that defined the element
    notes:
      - A stronger model would be range schema_definition, but this doesn't address the import model
    slot_uri: skos:inScheme
```

Instead I think https://w3id.org/linkml/source should be used

Adding a FAQ entry should close this issue
