### ISSUE TITLE
pydantic objects do not work with loader/dumper framework

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#659]
Currently we provide two paths for generating python datamodels:

 - gen-python (standard): uses dataclasses plus dataclass shim, includes dependencies on runtime
 - gen-pydantic (experimental): uses pydantic, and a lighter-weight OM with fewer dependencies

The python DM works well for object manipulation but is not yet integrated into the rest of the framework

it currently doesn't work with the loader/dumper framework

e.g. the current yaml/json dumpers rely on the fact that all class inherit from YAMLRoot, such that when as_json_object is called the results are a valid JsonObj, which implements methods that conform to plain json.dumps.

We could make the pydantic models inherit in the same way but I think this may cause problems. I think we should use the native pydantic way, which assumes everything inherits from BaseModel, which implements `dict()`:

https://pydantic-docs.helpmanual.io/usage/exporting_models/

however the generated pydantic classes don't inherit from any base

**Comment by ialarmedalien** [comment]
Has any more work been done on this?

With a bit of fairly simple hackery, I can load and dump data in a pydantic model. E.g. generate the pydantic model for the example Person schema and then edit the file as follows:


```py
# add line
from linkml_runtime.utils.yamlutils import YAMLRoot

metamodel_version = "None"
version = "None"


# edit this class
class WeakRefShimBaseModel(BaseModel, YAMLRoot):
    __slots__ = '__weakref__'

    def __copy__(self):
        return self.dict()
```

I can now run something like this:

```py
    yl = YAMLLoader()
    yd = YAMLDumper()

    pyd_people = yl.load(person_data, target_class=pydantic_person.Container)
    print(yd.dumps(pyd_people))
```

output:
```
persons:
- id: P:001
  name: fred bloggs
  primary_email: fred.bloggs@example.com
  age_in_years: 33
- id: P:002
  name: joe schmoe
  primary_email: joe.schmoe@example.com
  has_employment_history:
  - started_at_time: 2019-01-01
    is_current: true
    employed_at: ROR:1
  has_familial_relationships:
  - related_to: P:001
    type: SIBLING_OF
  has_medical_history:
  - started_at_time: 2019-01-01
    in_location: GEO:1234
    diagnosis:
      id: CODE:D0001
      name: headache
    procedure:
      id: CODE:P0001
      name: trepanation
  - started_at_time: 2019-01-02
    in_location: GEO:1234
    diagnosis:
      id: CODE:D0002
      name: hole in the head
    procedure:
      id: CODE:P0001
      name: decapitation
organizations:
- id: ROR:1
  name: foo
```
