### ISSUE TITLE
Treating a slot as both inlined and not inlined

### ISSUE THREAD

**Issue by deepakunni3** [linkml/linkml#664]
Apologies in advance if the issue header is a bit confusing. I was struggling with how to phrase this issue.

### Scenario

If I have a schema:

```yaml
id: https://w3id.org/test-schema
name: test-schema
version: 0.0.1
description: >-
  A test schema

imports:
- linkml:types

default_prefix: ex

prefixes:
  ex: https://www.example.com/
  linkml: https://w3id.org/linkml/


classes:

  class A:
    slots:
      - id
      - name
      - type

  class X:
    slots:
      - prop1
      - prop2

  class Y:
    is_a: class X


slots:

  id:
    range: string

  name:
    range: string

  type:
    range: class X

  prop1:
    range: string

  prop2:
    range: string

```

The focus here is the `type` slot on `class A`.

Generated JSON Schema:
```
gen-json-schema example-schema.yaml
```

```json
	"ClassA": {
		"additionalProperties": false,
		"description": "",
		"properties": {
			"id": {
				"type": "string"
			},
			"name": {
				"type": "string"
			},
			"type": {
				"$ref": "#/$defs/ClassX"
			}
		},
		"required": [],
		"title": "ClassA",
		"type": "object"
	},
```

Generated Python dataclasses:
```
gen-py-classes example-schema.yaml
```

```py
class ClassA(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = EX.ClassA
    class_class_curie: ClassVar[str] = "ex:ClassA"
    class_name: ClassVar[str] = "class A"
    class_model_uri: ClassVar[URIRef] = EX.ClassA

    id: Optional[str] = None
    name: Optional[str] = None
    type: Optional[Union[dict, "ClassX"]] = None

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        if self.id is not None and not isinstance(self.id, str):
            self.id = str(self.id)

        if self.name is not None and not isinstance(self.name, str):
            self.name = str(self.name)

        if self.type is not None and not isinstance(self.type, ClassX):
            self.type = ClassX(**as_dict(self.type))

        super().__post_init__(**kwargs)
```

### Question

How can I write my example schema YAML such that:

`ClassA.type` can have one of the following value types: `string`, `dict`, instance of `ClassX`

where,
- `string` is referring to an ID of an instance of `ClassX`
- `dict` is referring to an inlined representation of `ClassX` as a dict
- 'instance of `ClassX`' is referring to an instantiated instance of `ClassX`

i.e. the generated Python dataclasses looks like so:

```py
@dataclass
class ClassA(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = EX.ClassA
    class_class_curie: ClassVar[str] = "ex:ClassA"
    class_name: ClassVar[str] = "class A"
    class_model_uri: ClassVar[URIRef] = EX.ClassA

    id: Optional[str] = None
    name: Optional[str] = None
    type: Optional[Union[str, dict, "ClassX"]] = None
```

and generated JSON Schema:

```json
      "ClassA": {
         "additionalProperties": false,
         "description": "",
         "properties": {
            "id": {
               "type": "string"
            },
            "name": {
               "type": "string"
            },
            "type": {
               "oneOf": [
                  {
                     "type": "string"
                  },
                  {
                     "$ref": "#/$defs/ClassX"
                  }
               ]
            }
         },
         "required": [],
         "title": "ClassA",
         "type": "object"
	}
```

Now I am not sure if this is something that can be expressed in the YAML at the moment or is not allowed by design.

Perhaps having a union of string, dict, and instance of a class as possible values for a field is too permissive and weakens the expression of the model and thus its intent?

### Use Case

The use case may be niche, but this comes up when validating data objects against a schema
- where the incoming data can be in embedded form (slots with range classes; are inlined)
- where the incoming data can be in non-embedded form (slots with range classes; are not inlined and just has a string ID that refers to an object that exists)

This is less of a feature request and more for a discussion. 

If there are features that can be spun off of this discussion then I'd be happy to make new tickets to track those :)

**Comment by cmungall** [comment]
There are a few ways to approach this:

1. strict schema, lenient instantiation with auto-repair
2. lenient schema

We kind of have 1 at the moment, if you use linkml-validate currently it will first go via python objects which do a lot of repair on post-init

- #464 

But it sounds like you are more interested with 2. This could indeed be done with unions (though translation to json-schema not supported for these yet)

More later....

**Comment by cmungall** [comment]
I meant the any_of construct in linkml
https://linkml.io/linkml/schemas/experimental.html#unions-as-ranges

you could do:

my_slot:
  range: Foo
  any_of:
     - inlined: true
     - inlined: false

in future this will be translated to jsonschema in the expected way

**Comment by deepakunni3** [comment]
Thank you for the link!

I don't think `inlined` is possible for `any_of`. I seem to be running into issues when trying to parse the yaml with linkml.

Instead, I found the following to work:

```yaml
  my_slot:
   inlined: true
    any_of:
        - range: foo
        - range: string
```
