### ISSUE TITLE
Use designates_type field when generating datamodels to auto-populate the field

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#672]
Some schemas use https://w3id.org/linkml/designates_type specify that a field is used to hold the (linkml) class instantiated, e.g.

```yaml
  category:
    is_a: type
    domain: entity
    range: category type
    designates_type: true
```

this could be leveraged in e.g. pydanticgen to populate a default for that field

- if the range is uriorcurie, use the curie of the class, e.g. biolink:Gene
- if string, use the localid
