### ISSUE TITLE
best practice for units of measure

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#706]
We frequently need to encode the unit for a measurement. LinkML allows this to be modeled different ways

1. baking a unit into a slot, e.g. `depth_in_meters` range: float
2. using a QUDT-like datamodel. E.g. NMDC, Phenopackets does this

Example in phenopackets

https://phenopacket-schema.readthedocs.io/en/latest/value.html#rstvalue

```yaml
value:
    quantity:
        unit:
            id: "UO:0000316"
            label: "cells per microliter"
        value: 24000.0
        referenceRange:
            unit:
                id: "UO:0000316"
                label: "cells per microliter"
            low: 150000.0
            high: 450000.0
```

Phenopackets recommends UO

https://phenopacket-schema.readthedocs.io/en/latest/recommended-ontologies.html#units-of-measurement

The phenopackets schema is easy to represent in linkml - we would have a UnitOntologyTerm class (or similar) with fields id, label...

But is this an area we should be using dynamic enums?

FHIR includes a value set for UCUM

http://hl7.org/fhir/ValueSet/ucum-units

Should we adopt the analogous practice?

Note that we can now get URIs for UCUM from https://units-of-measurement.org/

**Comment by cmungall** [comment]
> how may we specify multiple reference ranges,

I think this is a modeling question for phenopackets - I would make reference range multivalued and provide a context object alongside each reference range. The context object could hold anything from basic properties like age and sex or ways of indicating that I have recently exercised or eaten a large meal

Similarly for representing the analyte that would be an individual schema modeling question - the unit system would give you cells/mL (or in UCUM, `{Cells}/uL`)

Note that FHIR discourages this: 

https://build.fhir.org/ucum.html
> 
Curly braces {} in the code element are discouraged. Curly braces provide additional descriptive text in the code expression but do not contribute to the meaning of the code.

But there is no way to overload the analyte in the unit encoding - this should be a separate field in your schema

> Is the idea to support URIs for UCUM codes as one of multiple possible unit IDs?

There is a separate project that is experimenting with encoding UCUM codes as URIs:

https://units-of-measurement.org/

However, this is not complete

The proposed unit metamodel for linkml allows for use of the ucum code directly rather that as a URI

e.g

https://github.com/linkml/linkml-model/blob/main/examples/unit-example.yaml#L60-L64

```yaml
  height_in_cm:
    range: float
    unit:
      ucum_code: cm
      exact_mappings:
        - UO:0000015
```

**Comment by cmungall** [comment]
Here are some more examples

if you have a field in your database that takes a floating point value that represents a person's height in centimeters:

```
slots:
  ## Example 1: unit is a property of the slot/field ("baked in")
  height_in_cm:
    range: float
    unit:
      ucum_code: cm
      iec61360code: UAA375
      exact_mappings:
        - UO:0000015 ## centimeter
        - uom:cm
      has_quantity_kind: PATO:0000119 ## height
```

All of the annotations on the unit is optional, but if `unit` is specified, then at least one piece of information (e.g. UCUM, or exact mappings) must be specified

A second example shows how we can create a type to reuse a definition:

```yaml
types:
  KilogramValue:
    typeof: float
    unit:
      ucum_code: kg

slots:
  ## Example 2: unit is a property of the scalar type;
  ## this is equivalent to making it a property of the slot/field,
  ## however, the type can be reused in multiple places
  weight_in_kg:
    range: KilogramValue
```


If we don't use baked-in units and instead have a measurement object that takes a tuple of value plus unit:

```yaml
classes:
  Measurement:
    description: 
    attributes:
      unit_code:
        range: UnitCodeEnum
      numeric_value:
        range: float

enums:
  UnitCodeEnum:
    permissible_values:
      cm:
        unit:
          ucum_code: cm
      m:
        unit:
          ucum_code: m
      inches:
      feet:
```
