### ISSUE TITLE
Add a class_usage metamodel slot for adapting a class to a particular schema

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#710]
Analogous to how a class can localize a slot using `slot_usage`, we should allow schemas to localize usage of imported classes with `class_usage` (and analogously for `enum_usage`)

For example, s1 defines a class Person, with 4 fields, where name is a required field.

s2 wants to reuse, but wants to relax the required to recommended, and add 2 fields

s2 imports s1, and adapts person

```
import:
  - example:personinfo
 
classes:
  ...
class_usage:
  Person:
    slot_usage:
       name:
         required: false
    slots:
      - additional1
      - additional2
       
```

alternatively

```
import:
  - example:personinfo
 
classes:
  Person:
    overrides:
       - personinfo.Person.  ## we are adapting this
    slot_usage:                    ## override existing slots
       name:
         required: false
    slots:
      - additional1
      - additional2
```

The semantics can be contrasted with inheritance:

- the "parent" class is not included, it is replaced
- semantics are non-monotonic, i.e. can override, not just refine

**Comment by putmantime** [comment]
Monarch uses a subset of Biolink we are naming The Monarch Biolink Specification.
We would like to declare the subsets in each ingest's yaml config.  This would include the biolink classes/assocations etc and would specific any overrides to the default that differ in the Monarch Spec.
Being able to generate and stay in sync with a linkml project to describe the schema, generate documentation and take advantage of linkml tooling would be highly beneficial for maintaining and making the monarch graph more accessible and interoperable.
Below is an example provided by @cmungall that would meet our requirements:
```

id: monarch-ingest-omim
description: ingest of g2d from omim
classes:
  gene:
    slots:
      - id
    id_prefixes:
      - OMIM ## will be mapped to NCBIGene
  disease:
    slots:
      - id
    id_prefixes:
      - OMIM  ## will be mapped to Mondo
  publication:
    slots:
      - id
    id_prefixes:
      - PMID
  gene to disease association:
    slots:
      - subject
      - predicate
      - object
      - publications
    slot_usage:
      predicate:
        equals_string: is_causative_mendelian_variant_of
    
```
