### ISSUE TITLE
Add ability to iterate over permissible values of enums in generated Python code

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#738]
**Is your feature request related to a problem? Please describe.**
Here is an example model (`personinfo.yaml`):
```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
default_range: string
  
classes:
  Person:      
    attributes:
      status:
        description: >-
          vital status of the person
        range: PersonStatus

enums:
  PersonStatus:
    permissible_values:
      ALIVE:
      DEAD:
      UNKNOWN:
```

I generated Python code from that model `gen-python personinfo.yaml > personinfo.py`. In my Python application I would like to be able to iterate over the possible values of the `PersonStatus` enum. 

**Describe the solution you'd like**
If the generated `PersonStatus` behaved similar to a standard Python enum I would expect to be able to do something like this:

```python
from personinfo import PersonStatus
statuses = [s.text for s in PersonStatus]
```

**How important is this feature?** Select from the options below:
• Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**
