### ISSUE TITLE
markdown generation: Separation of slots into 'own' and 'inherited' is problematic

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#74]
Currently the markdown separates things into own vs inherited. We don't really have such a strict division in blml. It's possible to refine a slot using slot_usage. Who 'owns' the slot then? Behind the scenes a new slot is created (which should be hidden from the user, conceptually it's the same slot).

I think it makes more sense to have a table with columns

 - slot id/name
 - REQ
 - description
 - domain
 - range
 - etc

Next to each slot slot we can have a '*' to indicate if that slot slot is not own and to state where it comes from

E.g.in https://cmungall.github.io/chemistry-ontology/

I have:

```yaml

classes:
 ...
 salt:
    is_a: chemical entity
    description: >-
      a chemical compound consisting of an ionic assembly of cations and anions.
    slot_usage:
      elemental charge:
        minimum_value: 0
        maximum_value: 0

slots:
  ...
  elemental charge:
    description: >-
      number of protons minus number of electrons
    domain: chemical entity
    range: integer

```

this results in slightly confusing docs with a weird arrow:

# Type: salt

a chemical compound consisting of an ionic assembly of cations and anions.

URI: [chemont:Salt](http://w3id.org/chemontSalt)

![img](http://yuml.me/diagram/nofunky;dir:TB/class/[ChemicalEntity]^-[Salt&#124;elemental_charge:integer%20%3F;id(i):string],[ChemicalEntity])

## Parents

 *  is_a: [ChemicalEntity](ChemicalEntity.md) - An entity that can be described using using chemical properties.

### Own

 * [salt➞elemental charge](salt_elemental_charge.md)  <sub>OPT</sub>
    * range: [Integer](types/Integer.md)

### Inherited from chemical entity:

 * [id](id.md)  <sub>REQ</sub>
    * range: [String](types/String.md)
