### ISSUE TITLE
add decimal, double types 

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#777]
**Is your feature request related to a problem? Please describe.**
Using the math function in java with @julesjacobsen we noticed that we need the double data type (64-bit number vs. 32 bit) representation in linkml
maybe need other types too - decimal, etc. 

• Low - it's an enhancement but not crucial for work
• Long-term - 6 months - 1 year

**Comment by cmungall** [comment]
Actually I have misspoked today, we have both:

```yaml
  float:
    uri: xsd:float
    base: float
    description: A real number that conforms to the xsd:float specification

  double:
    uri: xsd:double
    base: float
    description: A real number that conforms to the xsd:double specification
```

The uri gives the intended semantics:

 - [xsd:float](https://www.w3.org/TR/xmlschema11-2/#float)
      - _The float datatype is patterned after the IEEE single-precision 32-bit floating point datatype [[IEEE 754-2008]](https://www.w3.org/TR/xmlschema11-2/#ieee754-2008).  Its value space is a subset of the rational numbers.  Floating point numbers are often used to approximate arbitrary real numbers._
 - [xsd:double](https://www.w3.org/TR/xmlschema11-2/#double)
       - _The double datatype is patterned after the IEEE double-precision 64-bit floating point datatype [[IEEE 754-2008]](https://www.w3.org/TR/xmlschema11-2/#ieee754-2008).  Each floating point datatype has a value space that is a subset of the rational numbers.  Floating point numbers are often used to approximate arbitrary real numbers._

Both of these map to python:float, which is in fact the correct semantics to accurate fulfil the spec:

https://docs.python.org/3/tutorial/floatingpoint.html
https://stackoverflow.com/questions/6663272/double-precision-floating-values-in-python

_Python's built-in float type has double precision (it's a C double in CPython, a Java double in Jython)_

We also have:

```yaml
  decimal:
    uri: xsd:decimal
    base: Decimal
    description: A real number with arbitrary precision that conforms to the xsd:decimal specification
```
