### ISSUE TITLE
Include mappings to language-specific scalar types / datatypes in types.yaml

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#794]
currently in types.yaml:

```yaml
  string:
    uri: xsd:string
    base: str
    description: A character string

  integer:
    uri: xsd:integer
    base: int
    description: An integer

  boolean:
    uri: xsd:boolean
    base: Bool
    repr: bool
    description: A binary (true or false) value
```

This shows a Python bias, as can be seen by the definition of base and repr

```
  base:
    domain: type_definition
    description: python base type that implements this type definition
    inherited: true
    comments:
      - every root type must have a base
      - the base is inherited by child types but may be overriden.  Base compatibility is not checked.
    in_subset:
      - basic

  repr:
    domain: type_definition
    range: string
    description: the name of the python object that implements this type definition
    inherited: true
    in_subset:
      - basic
```

currently when writing generators for other languages or frameworks we do something like embed a TYPEMAP in code. It would be better to make this more declarative

We should keep base and repr to avoid breaking anthing

we could do

```yaml
  string:
    uri: xsd:string
    base: str
    java: String
    rust: ...
    description: A character string
```

but that has obvious issues of metamodel stability

better would be

- exact_mappings, using language as prefix (are there standard URIs for datatypes in different languages)
- aliases, with a convention `java.String`
- structured_aliases

We could use the same conventions for handling reserved words when generating dataclasses
