### ISSUE TITLE
Treatment of slots with range typeof string, iri, etc - treat as object property?

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#8]
(low priority)

Currently this will be translated to an OP

```
types:
  label type:
    typeof: string
    description: >-
      A string that provides a human-readable name for a thing

slots:
  name:
    is_a: node property
    aliases: ['label', 'display name']
    domain: named thing
    range: label type
    description: >-
      A human-readable name for a thing
    in_subset:
      - translator_minimal
    mappings:
      - "rdfs:label"
```

The generated OP has no range constraint. Additional class slots get translated into subClassOf axioms, e.g.

![image](https://user-images.githubusercontent.com/50745/59538820-e68e0980-8eaf-11e9-9476-0833f045a35c.png)

Note that in OWL we are forced to choose AP vs DP vs OP. No punning across these. Use of APs for rdfs:label etc is useful for classes since we are talking about the class but not an individual. However, arguably there is less need for APs in OWL2 now that we can pun on class (use an OP for labels). 

There are a number of options here with pros and cons

## Treat as OPs and put types in domain of discourse

Here `label type` in the above schema would be treated as a class, and `name` as an OP.

this is coherent but is obviously different from how people do this at the moment.

We also clearly have an issue here if we use rdfs:label as the IRI here as we do illegal punning between AP and OP.

One possibility is to model it this way, but to have a defined transform literalify/deliteralify, e..g 

```
?x blmod:name [a blmod:label type ;
                            blmeta:has-value "fred"]
<=>
?x rdfs:label "fred"
```

## Specify OWL type in model

E.g in the definition of `name` state that this is owl:AP. Similarly for other slots we may want to declare as DPs.

The advantage is that introduces no illegal punning if we reuse existing property IRIs from RDFS, OBO, etc

The disadvantage is that can't use in logical axioms.

## Use DPs

Again this would cause illegal punning if we reuse IRIs such as `rdfs:label`.
