### ISSUE TITLE
DataType names don't allow ":" in them?

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml#806]
**Is your feature request related to a problem? Please describe.**
Rather than "string" I had been using "xsd:token" in the range of many slots to capture that there's no carriage return or tabs in the values.  SchemaView() doesn't seem to mind this but command line gen-yaml is throwing an error:  
`ValueError:  type: "xsd:token" - ":" not allowed in identifier`
with this in schema.yaml :
```
types:
  xsd:token:
    name: xsd:token
    description: 'A string that has no whitespace; i.e., after any occurrence of #x9
      (tab), #xA (linefeed), or #xD (carriage return).'
    base: str
    uri: xsd:token
```
**Describe the solution you'd like**
Can ":" show in data type? Or do you want me to make up some colonless data type name like xsdToken ?

**How important is this feature?** Select from the options below:
• Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by cmungall** [comment]
yes, this is by design, you have the `uri` field for the uri

It's a stylistic choice, but I wouldn't call this xsdToken any more than we call strings xsdStrings. If you think "token" is a good name for what you want to capture then just call it "token". I wouldn't say make up a name - choose a name carefully that reflects the intent and also is consistent with broader conventions.

**HOWEVER** it seems that your description contradicts that of xsd:token. See http://books.xmlschemata.org/relaxng/ch19-77319.html

Your description says a "string that has no whitespace". This is different from xsd:token, which is essentially whitespace normalization.

I don't know if it's a mistake in your description or a mismatch, but either way you can make the semantics clear by using a `pattern` on the type.

I would model as:

```yaml
types:
  NoWhitespaceString:
    typeof: string
    pattern: '^\\S+$+'
    description: A string that has no whitespace
  WhitespaceNormalizedString:
    uri: xsd:token
    typeof: string
    pattern: '^\\S+{ \\S+)*$+'
    description: A non-empty string that has no whitespace other than the space (#x20) and has no contiguous spaces.
    comments:
       - xsd calls the equivalent concept a token but this is confusing and contradicts with how token is used e.g. in NLP
```
