### ISSUE TITLE
Prefix with hyphenated name won't validate JSON

### ISSUE THREAD

**Issue by galund** [linkml/linkml#807]
**Describe the bug**
(This bug is similar but not the same as <https://github.com/linkml/linkml/issues/757>.)

A prefix with a hyphenated name causes a `NameError` when compiling to Python in order to validate some JSON.

**To Reproduce**
1. Create a very basic schema with a hyphenated prefix, such as:

```
id: https://example.com/test
name: test-schema
prefixes:
  linkml: https://w3id.org/linkml/
  some-prefix: https://example.com/test1-prefix-name
imports:
  - linkml:types
default_prefix: some-prefix
classes:
  TestClass:
    attributes:
      testProperty:
```

2. Attempt to validate from JSON against that schema eg by running `linkml-validate -s linkml-schemas/basic.yml examples/test.json`

**Expected behavior**
Validation should proceed as if `some-prefix` in the example above were replaced with `someprefix`.

**Actual behavior**
```
  File "[...]/lib/python3.10/site-packages/linkml_runtime/utils/compile_python.py", line 47, in compile_python
    exec(spec, module.__dict__)
  File "test", line 36, in <module>
NameError: name 'SOME' is not defined
```

**Additional context**
