### ISSUE TITLE
Declaring a slot as required can sometimes force inlined-as-dict in pythongen

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#811]
Example:

```yaml
id: https://w3id.org/linkml/test/inline
title: test inline
name: test-inline

prefixes:
  linkml: https://w3id.org/linkml/
  t: https://w3id.org/linkml/test/inline/

default_prefix: t
default_range: string

imports:
  - linkml:types

classes:

  Container:
    slots:
      - entries

  Entry:
    slots:
      - type
      - info

slots:
  type:
    # bug: setting required=true forces entries to be inlined_as_dict
    required: true
  info:
    description: additional information about the issue
  entries:
    range: Entry
    multivalued: true
```

```
✗ poetry run gen-python  tests/test_issues/input/linkml_issue_INLINE_AS_DICT.yaml | grep -A4 -B12 inlined_as
@dataclass
class Container(YAMLRoot):
    _inherited_slots: ClassVar[List[str]] = []

    class_class_uri: ClassVar[URIRef] = T.Container
    class_class_curie: ClassVar[str] = "t:Container"
    class_name: ClassVar[str] = "Container"
    class_model_uri: ClassVar[URIRef] = T.Container

    entries: Optional[Union[Union[dict, "Entry"], List[Union[dict, "Entry"]]]] = empty_list()

    def __post_init__(self, *_: List[str], **kwargs: Dict[str, Any]):
        self._normalize_inlined_as_dict(slot_name="entries", slot_type=Entry, key_name="type", keyed=False)

        super().__post_init__(**kwargs)
```

there is an easy workaround, just add an explicit inlined_as_list: true, but this shouldn't be necessary
