### ISSUE TITLE
For a given slot, minimum and maximum values should be show on the slot page

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#862]
https://linkml.io/linkml-model/docs/all_members/

E.g to state that all members of a list are between 1 and 10

```yaml
all_members:
  x:
    range: integer
    minimum_value: 10
    maximum_value: 10
```
