### ISSUE TITLE
The current comment on transitive_form_of is interpreted as a dict in some situations

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#864]
Ie

```yaml
  transitive_form_of:
    range: slot_definition
    description: If s transitive_form_of d, then (1) s holds whenever d holds (2) s is transitive (3) d holds whenever s holds and there are no intermediates, and s is not reflexive
    comments:
      - Example: ancestor_of is the transitive_form_of parent_of
```

yields a comment of `{'Example':   'ancestor_of is the transitive_form_of parent_of'}`, which is **not a string** but can be _coerced_ into a string
