### ISSUE TITLE
ugly as_dict() of slot_group's range_expression

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#865]
I think the only useful thing in here is the `slot_conditions`. how can I parse that more beautifully?

```yaml
aliases: []
all_of: []
alt_descriptions: {}
annotations: {}
any_of: []
broad_mappings: []
close_mappings: []
comments: []
deprecated: null
deprecated_element_has_exact_replacement: null
deprecated_element_has_possible_replacement: null
description: null
exact_mappings: []
exactly_one_of: []
examples: []
extensions: {}
from_schema: null
imported_from: null
in_language: null
in_subset: []
is_a: null
mappings: []
narrow_mappings: []
none_of: []
notes: []
rank: null
related_mappings: []
see_also: []
slot_conditions:
  ? !!python/object/new:linkml_runtime.utils.yamlutils.extended_str
    args:
    - is_grouping_slot
    state:
      _len: 16
      _s: &id001 !!python/object:linkml_runtime.utils.yamlutils.YAMLMark
        buffer: null
        column: 10
        index: 50845
        line: 1735
        name: <file>
        pointer: null
  : !!python/object:linkml_runtime.linkml_model.meta.SlotDefinition
    abstract: null
    alias: null
    aliases: []
    all_members: {}
    all_of: []
    alt_descriptions: {}
    annotations: {}
    any_of: []
    apply_to: []
    asymmetric: null
    broad_mappings: []
    children_are_mutually_disjoint: null
    close_mappings: []
    comments: []
    conforms_to: null
    created_by: null
    created_on: null
    definition_uri: null
    deprecated: null
    deprecated_element_has_exact_replacement: null
    deprecated_element_has_possible_replacement: null
    description: null
    designates_type: null
    disjoint_with: []
    domain: null
    domain_of: []
    equals_expression: 'True'
    equals_number: null
    equals_string: null
    equals_string_in: []
    exact_mappings: []
    exactly_one_of: []
    examples: []
    extensions: {}
    from_schema: null
    has_member: null
    id_prefixes: []
    identifier: null
    ifabsent: null
    imported_from: null
    in_language: null
    in_subset: []
    inherited: null
    inlined: null
    inlined_as_list: null
    inverse: null
    irreflexive: null
    is_a: null
    is_class_field: null
    is_grouping_slot: null
    is_usage_slot: null
    key: null
    last_updated_on: null
    list_elements_ordered: null
    list_elements_unique: null
    local_names: {}
    locally_reflexive: null
    mappings: []
    maximum_cardinality: null
    maximum_value: null
    minimum_cardinality: null
    minimum_value: null
    mixin: null
    mixins: []
    modified_by: null
    multivalued: null
    name: !!python/object/new:linkml_runtime.linkml_model.meta.SlotDefinitionName
      args:
      - is_grouping_slot
      state:
        _len: 16
        _s: *id001
    narrow_mappings: []
    none_of: []
    notes: []
    owner: null
    path_rule: null
    pattern: null
    range: null
    range_expression: null
    rank: null
    readonly: null
    recommended: null
    reflexive: null
    reflexive_transitive_form_of: null
    related_mappings: []
    relational_role: null
    required: null
    role: null
    see_also: []
    shared: null
    singular_name: null
    slot_group: null
    slot_uri: null
    source: null
    status: null
    string_serialization: null
    structured_aliases: {}
    structured_pattern: null
    subproperty_of: null
    symmetric: null
    title: null
    todos: []
    transitive: null
    transitive_form_of: null
    usage_slot_name: null
    values_from: []
source: null
structured_aliases: {}
title: null
todos: []
```
