### ISSUE TITLE
slot doc pages generated by docgen should show cardinality as well as domain and range

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#882]
https://linkml.io/linkml-model/docs/identifier/

should at least say `0..1`

some examples include the biolink section for "domain and range": 
[anatomical_context_qualifier](https://biolink.github.io/biolink-model/docs/chemical_gene_interaction_association_anatomical_context_qualifier.html)  (this uses a specific flavor of markdowngen that we should not use, but it does have at least an example to code to as a first pass.  I think we can make more defined sections than this :)).

**Comment by turbomam** [comment]
Shouldn't https://linkml.io/linkml-model/docs/class_uri/ say the domain is ClassDefinition (or class expression or something like that?)

The new docs are nice, but this seems like a regression

**Comment by cmungall** [comment]
This is an issue with docgen in general. It is better enough that we are
rolling it out selectively especially as these issues are easy to fix. But
can we try and do this systematically? Was someone working on the parity
table?

**Comment by sierra-moxon** [comment]
@cmungall  documents a potential design in[ this ticket](https://github.com/linkml/linkml/issues/74) (contents copied below for ease of reading)

From Chris:
Currently, the markdown separates things into own vs inherited. We don't really have such a strict division in blml. It's possible to refine a slot using slot_usage. Who 'owns' the slot then? Behind the scenes a new slot is created (which should be hidden from the user, conceptually it's the same slot).

I think it makes more sense to have a table with columns

 - slot id/name
 - REQ
 - description
 - domain
 - range
 - etc

Next to each slot slot we can have a '*' to indicate if that slot slot is not own and to state where it comes from

E.g.in https://cmungall.github.io/chemistry-ontology/

I have:

```yaml

classes:
 ...
 salt:
    is_a: chemical entity
    description: >-
      a chemical compound consisting of an ionic assembly of cations and anions.
    slot_usage:
      elemental charge:
        minimum_value: 0
        maximum_value: 0

slots:
  ...
  elemental charge:
    description: >-
      number of protons minus number of electrons
    domain: chemical entity
    range: integer

```

this results in slightly confusing docs with a weird arrow:

# Type: salt


a chemical compound consisting of an ionic assembly of cations and anions.

URI: [chemont:Salt](http://w3id.org/chemontSalt)


![img](http://yuml.me/diagram/nofunky;dir:TB/class/[ChemicalEntity]^-[Salt&#124;elemental_charge:integer%20%3F;id(i):string],[ChemicalEntity])

## Parents

 *  is_a: [ChemicalEntity](ChemicalEntity.md) - An entity that can be described using using chemical properties.

## Referenced by class


## Attributes


### Own

 * [salt➞elemental charge](salt_elemental_charge.md)  <sub>OPT</sub>
    * range: [Integer](types/Integer.md)

### Inherited from chemical entity:

 * [id](id.md)  <sub>REQ</sub>
    * range: [String](types/String.md)
