### ISSUE TITLE
LinkML-to-RDF/Turtle converter brings ambiguity

### ISSUE THREAD

**Issue by nataschake** [linkml/linkml#886]
Hi!
I work with the elements of addresses. I have defined a list of states of the USA and a list of country FIPS codes as enumerations in yaml file [addr.yaml](https://gist.github.com/nataschake/5762f062ae7146496b0ffe244efb6e91) and define a class Address.
```
name: Addresses
description: Information about addresses
id: http://example.com/resource/address/
imports:
- linkml:types
default_curi_maps:
  - semweb_context
prefixes:
...
default_prefix: c
default_range: string
enums:
  State:
    name: State
    description: states of the United States
    from_schema: http://example.com/resource/State/
    permissible_values:
      AL:
        text: AL
        description: Alabama
...(omitted)
      BC:
        text: BC
        description: British Columbia, Canada
...(omitted)
  FIPS:
    name: FIPS
    description: Country of the world. Its FIPS
    from_schema: http://example.com/resource/FIPS/
    permissible_values:
      "na":
        text: "na"
        description: >- 
            one of: Aland Islands; Bonaire, Sint Eustatius and Saba; United States Minor Outlying Islands
      AF:
        text: AF
        description: Afghanistan
      AL:
        text: AL
        description: Albania
...(omitted)
      BC:
        text: BC
        description: Botswana
...(omitted)
slots:
  addressState:
    name: addressState
    from_schema: http://example.com/resource/address/
  addressFIPS: 
    name: addressFIPS
    from_schema: http://example.com/resource/address/
classes:
  Address:
    name: Address
    from_schema: http://example.com/resource/address/
    slots:
      - addressState
      - addressFIPS
    slot_usage:
      addressState:
          name: addressState
          range: State
      addressFIPS:
          name: addressFIPS   
          range: FIPS

```

I explicitly claim that I need to disambiguate the "origins" of the enum values, by writing that
```
enums:
	State:
	name: State
	from_schema: http://example.com/resource/State/
...
and 
	FIPS:
	name: FIPS
	from_schema: http://example.com/resource/FIPS/
...
``` 

Transforming it to Turtle with
```
$ gen-rdf .\addr.yaml >addr.ttl
```
lost those schemas mentioning, so in TTL file [addr.ttl](https://gist.github.com/nataschake/af7b9d316cfe6bb066be0a3f8f58c30d) I have

```
<http://example.com/resource/address/Addresses> a linkml:SchemaDefinition ;
    linkml:enums <http://example.com/resource/address/FIPS>,
        <http://example.com/resource/address/State> ;

    linkml:slots <http://example.com/resource/address/Address_addressFIPS>,
        <http://example.com/resource/address/Address_addressState>,
        <http://example.com/resource/address/addressFIPS>,
        <http://example.com/resource/address/addressState> ;
...
<http://example.com/resource/address/AF> skos:definition "Afghanistan" .
...
<http://example.com/resource/address/AL> skos:definition "Alabama",
        "Albania" .
...
<http://example.com/resource/address/BC> skos:definition "Botswana",
        "British Columbia, Canada" .
...
```
and I cannot find any mentioning of "original" schemas http://example.com/resource/State/ and http://example.com/resource/FIPS/

Enum elements "AL", "BC", initially *written to be taken* from different schemas, are merged into one schema, http://example.com/resource/address/, and introduce ambiguity.

The question is: how to disambiguate (possibly equally named) elements of different enumerations using LinkML language capabilities OR LinkML-to-RDF/Turtle transformer capabilities? 
p.s. [FIPS](https://en.wikipedia.org/wiki/List_of_FIPS_country_codes) and [USA States](https://en.wikipedia.org/wiki/List_of_U.S._state_and_territory_abbreviations) are fixed and cannot be arbitrarily changes
