### ISSUE TITLE
LinkML-to-RDF/Turtle converter introduces extra slots as compared to LinkML-to-OWL/Turtle

### ISSUE THREAD

**Issue by nataschake** [linkml/linkml#889]
Hi!
In yaml file [addr.yaml](https://gist.github.com/nataschake/5762f062ae7146496b0ffe244efb6e91) according to the LinkML instructions I define slots `addressState` and `addressFIPS` as follows: 
```
slots:
  addressState:
    name: addressState
    from_schema: http://example.com/resource/address/
  addressFIPS: 
    name: addressFIPS
    from_schema: http://example.com/resource/address/
```
And then in the `classes` clause I declare usage of those slots:
```
classes:
  Address:
    name: Address
    from_schema: http://example.com/resource/address/
    slots:
      - addressState
      - addressFIPS
    slot_usage:
      addressState:
          name: addressState
          range: State
      addressFIPS:
          name: addressFIPS   
          range: FIPS
```

it shows that I need `addressState` and `addressFIPS`.

Transforming it to Turtle with
```
$ gen-rdf .\addr.yaml >addr.ttl
```
brings two more slots, `Address_addressFIPS` and `Address_addressState` declared via `linkml:is_a`, so in the TTL file [addr.ttl](https://gist.github.com/nataschake/af7b9d316cfe6bb066be0a3f8f58c30d) I have

```
<http://example.com/resource/address/Addresses> a linkml:SchemaDefinition ;
(...omitted)    
linkml:slots <http://example.com/resource/address/Address_addressFIPS>,
			 <http://example.com/resource/address/Address_addressState>,
			 <http://example.com/resource/address/addressFIPS>,
			 <http://example.com/resource/address/addressState> ;
(...omitted)
<http://example.com/resource/address/addressFIPS> a linkml:SlotDefinition ;
    skos:inScheme <http://example.com/resource/address/> ;
    linkml:definition_uri <http://example.com/resource/address/addressFIPS> ;
    linkml:domain_of <http://example.com/resource/address/Address> ;
    linkml:owner <http://example.com/resource/address/Address> ;
    linkml:range <http://example.com/resource/address/string> ;
    linkml:slot_uri <http://example.com/resource/address/addressFIPS> .
(...omitted)
<http://example.com/resource/address/Address_addressFIPS> a linkml:SlotDefinition ;
    skos:inScheme <http://example.com/resource/address/> ;
    skos:prefLabel "addressFIPS" ;
    linkml:definition_uri <http://example.com/resource/address/addressFIPS> ;
    linkml:domain <http://example.com/resource/address/Address> ;
    linkml:domain_of <http://example.com/resource/address/Address> ;
    linkml:is_a <http://example.com/resource/address/addressFIPS> ;
    linkml:is_usage_slot true ;
    linkml:owner <http://example.com/resource/address/Address> ;
    linkml:range <http://example.com/resource/address/FIPS> ;
    linkml:slot_uri <http://example.com/resource/address/addressFIPS> ;
    linkml:usage_slot_name "addressFIPS" .
	
<http://example.com/resource/address/Address> a linkml:ClassDefinition ;
    skos:inScheme <http://example.com/resource/address/> ;
    linkml:class_uri <http://example.com/resource/address/Address> ;
    linkml:definition_uri <http://example.com/resource/address/Address> ;
    linkml:slot_usage [ ] ;
    linkml:slots <http://example.com/resource/address/Address_addressFIPS>,
        <http://example.com/resource/address/Address_addressState> .
(...omitted)
```
However, transforming `addr.yaml` to OWL/Turtle with 
```
$ gen-owl --no-metaclasses .\addr.yaml >addr.owl.ttl
```
brings exactly the slots I've declared explicitly, `addressState` and `addressFIPS`: 
```
(...omitted)
c:addressFIPS a owl:ObjectProperty ;
    rdfs:label "addressFIPS";
    rdfs:range linkml:String .

c:addressState a owl:ObjectProperty ;
    rdfs:label "addressState" ;
    rdfs:range linkml:String .
	
c:Address a owl:Class ;
    rdfs:label "Address" ;
    rdfs:subClassOf [ a owl:Restriction ;
            owl:maxQualifiedCardinality 1 ;
            owl:onClass c:FIPS ;
            owl:onProperty c:addressFIPS ],
        [ a owl:Restriction ;
            owl:maxQualifiedCardinality 1 ;
            owl:onClass c:State ;
            owl:onProperty c:addressState ] .
```
and there are no `Address_addressFIPS rdfs:subPropertyOf addressFIPS` statements and similar, as well as `Address_addressFIPS` definition.
 
My concern is that these two transformers provide different semantics: 
- OWL/Turtle transformer keeps the number and names of slots as in the initial model, but it does not handle `linkml:is_a` statement. 
- RDF/Turtle transformer introduces extra slots, linearly depending on the number of occurrences of the same slot in slot_usages.

A possible solution can be either to add `rdfs:subPropertyOf` statements to the metamodel of OWL/Turtle transformer to have agreed with RDF/Turtle transformer semantics *OR* to exclude extra slots statements from RDF/Turtle transformer flow.
(I'm using linkml version 1.3.1)
