### ISSUE TITLE
gen-graphviz no duplicate classes

### ISSUE THREAD

**Issue by andrecastro0o** [linkml/linkml#890]
I was wondering if it would be possible to add, to gen-graphviz the capacity to avoid duplicating classes, when they are referred more than once in the following example, where `Person`, is a class, but also the range or slot `parent`.

```yaml
id: https://w3id.org/linkml/examples/personinfo
name: personinfo
prefixes:
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types
default_range: string
classes:
  Person:
    slots:
      - full_name
      - parent
slots:
  full_name:
  parent:
    range: Person
```

the generated graphviz image contains 2 classes Person. `gen-graphviz -f png person.yaml -o person` 

![person](https://user-images.githubusercontent.com/1690557/182389790-10b61625-5799-40cf-b752-0d1887a8e40e.png)

`gen-graphviz -f dot person.yaml -o person` 

```dot
digraph {
	graph [bb="0,0,147.99,123"];
	node [label="\N"];
	Person	 [height=0.5,
		label=Person,
		pos="71.547,105",
		width=0.95686];
	full_name	 [color=blue,
		height=0.5,
		label=string,
		pos="30.547,18",
		width=0.84854];
	Person -> full_name	 [color=blue,
		label=full_name,
		lp="63.547,61.5",
		pos="e,29.4,36.257 51.943,90.09 45.644,84.232 39.325,76.991 35.547,69 32.254,62.032 30.617,53.941 29.892,46.283",
		style=solid];
	parent	 [color=blue,
		height=0.5,
		label=Person,
		pos="113.55,18",
		width=0.95686];
	Person -> parent	 [color=blue,
		label=parent,
		lp="114.55,61.5",
		pos="e,106.44,35.663 81.669,87.608 84.948,81.761 88.518,75.159 91.547,69 95.318,61.334 99.114,52.866 102.47,45.07",
		style=solid];
}
```

**How important is this feature?**
• Low - it's an enhancement but not crucial for work
