### ISSUE TITLE
Derive structured patterns or basic patterns from string_serialization

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#906]
Given:

```yaml
default_range: string
classes:
  Person:
    first:
    last:
    full:
      string_serialization: "{last} {first}"
```

Derive:

```yaml
    full:
      pattern: "\\S+ \\S+"
```

alternatively:

```yaml
settings:
  string: "\\S+"

...

    full:
      structured_pattern:
        syntax: "{string} {string}"
```
