### ISSUE TITLE
Rename schema_fixer to linter and add additional checks and repairs

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#909]
We have a class SchemaFixer:

https://github.com/linkml/linkml/blob/596bedfb0b5a3abd611fa627aaff04c3ae19510b/linkml/utils/schema_fixer.py#L20-L23

This should be renamed to something like Linter

We may want to move it out of utils, as utils is becoming a big grab-bag

Some additional functionality:

- report on missing descriptions
- naming conventions and style checks
     - CamelCase for classes
     - snake_case for slots
     - CamelCase for enums
     - ALL_CAPS or snake_case for PVs

We may want to have a mechanism to suppress this where deviation is intentional, e.g.

```
name: biolink
annotations:
   schema.style: TitlesAsNames
```

Not everything can be repaired by the linter - e.g missing descriptions. However, schema-automator can suggest missing descriptions (by looking up entities with the same IRI). So there is an argument for having the linter live in SA, but I think the downsides outweigh this

**Comment by pkalita-lbl** [comment]
You beat me to making this issue! I'll copy what I had proposed here, but it's roughly the same:

* * *

I propose adding a `linkml-lint` CLI. There is a lot of prior art to draw inspiration from (for example: [ESLint](https://eslint.org/), [Flake8](https://flake8.pycqa.org/en/latest/)). But I see the basic outline as:
* Command line interface that accepts a single schema file or directory of schema files as an argument
* Configuration provided by a config file. The file can be provided by command line option or otherwise it looks for certain predefined filenames (c.f. ESLint's `.eslintrc.json` file). If all else fails a default configuration is used.
* Configuration consists of a set of rules and possible options for those rules. (c.f. https://eslint.org/docs/latest/rules/)
* Some rules may be auto-fixable, so command line options like `--auto-fix` or `--check-only` would be useful
* The output of the command is a report listing rule violations. Ideally this includes where to find the violation (minimally the schema file location), the severity (linters often have a concept of warning-level violation vs error-level violations), and wether the violation is auto-fixable (if run in `check-only` mode).
* The report should be able to be produced in different formats (e.g. Markdown, JSON, TSV)

A few rules that I could imagine as a first pass:

```yaml
# Report empty values for elements with recommended: true
recommended:
  level: off | warn | error
  include: []  # Only element names in this list are checked if not empty
  exclude: []  # All elements except the ones in this list are checked

# Report occurrences of `slot_usage` without underlying `slot`
missing-slot:
  level: off | warn | error

# Report occurrences of enum permissible values which do not match given format
permissible-value-format:
  level: off | warn | error
  format: snake | camel | kebab | <regex>
```

It could also be worth considering incorporating generic YAML formatting rules via https://github.com/adrienverge/yamllint
