### ISSUE TITLE
Sync linkml generators with linkml-model

### ISSUE THREAD

**Issue by deepakunni3** [linkml/linkml#919]
There is a growing need to sync the linkml generators with linkml-model.

There are many slots in linkml-model that provides a lot of expressivity in terms of semantics. But these slots aren't translated into its appropriate representation by linkml generators.

The examples below are specific to the owl generator (`gen-owl`):

#### `values_from`

With the following linkml representation,

```yaml
...
classes:
  named thing:
    slots:
      - id
      - name
      - has code

slots:
  id:
    identifier: true

  name:
    range: string

  has code:
    values_from:
      - loinc
```

we get the following OWL,

```ttl
...

ex:NamedThing a owl:Class,
        linkml:ClassDefinition ;
    rdfs:label "named thing" ;
    rdfs:subClassOf [ a owl:Restriction ;
            owl:onClass linkml:String ;
            owl:onProperty ex:id ;
            owl:qualifiedCardinality 1 ],
        [ a owl:Restriction ;
            owl:maxQualifiedCardinality 1 ;
            owl:onClass linkml:String ;
            owl:onProperty ex:name ],
        [ a owl:Restriction ;
            owl:maxQualifiedCardinality 1 ;
            owl:onClass linkml:String ;
            owl:onProperty ex:has_code ] .

ex:has_code a owl:ObjectProperty,
        linkml:SlotDefinition ;
    rdfs:label "has code" ;
    rdfs:range linkml:String .
...
```

**Note:** There is no translation of `values_from` slot into OWL.

#### `subclass_of`

With the following linkml representation,

```yaml
...
classes:
  named thing:
    subclass_of: BFO:0000001
    slots:
      - id
      - name

slots:
  id:
    identifier: true

  name:
    range: string
```

we get the following OWL,

```ttl
...
ex:NamedThing a owl:Class,
        linkml:ClassDefinition ;
    rdfs:label "named thing" ;
    rdfs:subClassOf [ a owl:Restriction ;
            owl:maxQualifiedCardinality 1 ;
            owl:onClass linkml:String ;
            owl:onProperty ex:name ],
        [ a owl:Restriction ;
            owl:onClass linkml:String ;
            owl:onProperty ex:id ;
            owl:qualifiedCardinality 1 ] .
...
```

**Note:** There is no triple that states `ex:NamedThing rdfs:subClassOf BFO:0000001`.

#### `minimum_cardinality` & `maximum_cardinality`

With the following linkml representation,

```yaml
...
classes:
  named thing:
    slots:
      - id
      - name
      - has code

slots:
  id:
    identifier: true

  name:
    range: string

  has code:
    multivalued: true
    minimum_cardinality: 3
    maximum_cardinality: 10
```

We get the following OWL,

```ttl
...
ex:NamedThing a owl:Class,
        linkml:ClassDefinition ;
    rdfs:label "named thing" ;
    rdfs:subClassOf [ a owl:Restriction ;
            owl:maxQualifiedCardinality 1 ;
            owl:onClass linkml:String ;
            owl:onProperty ex:name ],
        [ a owl:Restriction ;
            owl:allValuesFrom linkml:String ;
            owl:onProperty ex:has_code ],
        [ a owl:Restriction ;
            owl:onClass linkml:String ;
            owl:onProperty ex:id ;
            owl:qualifiedCardinality 1 ] .

ex:has_code a owl:ObjectProperty,
        linkml:SlotDefinition ;
    rdfs:label "has code" ;
    rdfs:range linkml:String .
...
```

**Note:** There is no mention of minimum and maximum cardinality for `ex:has_code` property.

---

Also, in many of the cases it is not clear which slots apply to which technology/formalism. The linkml-model YAML states which slot is part of which subset (OwlProfile, ObjectOriented, etc.) but it is missing in the documentation.

### Suggestions

- It would be great if we could have a matrix that shows which slots are valid for which technology/formalism. This would not just be helpful for users but also for us developers to see if a particular slot has been implemented in the appropriate generator responsible for a technology/formalism
- Better tests that would cover the scenarios in the matrix

I think the suggestions I am making are not new. But I am hoping to use this feature request as a way of pushing efforts into getting the generators up to date with the model. And doing so in a way that can identify cases where a generator fails to keep up with the model in the future.
