### ISSUE TITLE
Add support for full SSSOM integration

### ISSUE THREAD

**Issue by ialarmedalien** [linkml/linkml#922]
**Use Case**

* I want to maintain mappings to various external systems but don't want to have the mapping metadata scattered across numerous files. 
* I want to be able to specify mappings using the richness that SSSOM provides (see also #256)
* I want to be able to extract a full 3+ star mapping from the linkml schema file.
* Ideally I'd also be able to add information about how to transform the external object to generate the local version.

**Back-of-napkin Ideas**

Include mapping metadata in the header for the schema using the SSSOM terms; not all metadata will be required as some is already supplied in the schema. Example:

```yaml
sssom_mapping_sets:
- mapping_set_id: datacite_manual
  mapping_set_description: hand-crafted mappings to DataCite
  mapping_set_version: 0.1.6
  object_source_version: https://purl.org/datacite/v4.4
  license: CC-BY-4.0
  author_id: orcid:0000-0002-7356-1779

- mapping_set_id: osti_auto_match
  mapping_set_description: mappings extracted via regex
  mapping_set_version: 0.0.1
  object_source_version: https://www.osti.gov/biblio/
  license: CC0
  author_id: ORCID:0000-0001-9557-7715
```

Add a new tag, `sssom_mappings`, and specify the mappings using the SSSOM vocab:

```yaml
classes:
  Resource:
    attributes:
      identifier:
        description: resolvable persistent unique ID for the resource
        identifier: true
        required: true
        sssom_mappings:
        - mapping_set_id: datacite_manual
          predicate_id: skos:exactMatch
          object_id: DataCite:id
          mapping_justification: semapv:ManualMappingCuration
          confidence: 1.0
          comment: this is an awesome mapping!
          
        - mapping_set_id: osti_auto_match
          object_id: OSTI:osti_id
          predicate_id: skos:relatedMatch
          mapping_justification: semapv:AutomatedStringMatch
          confidence: 0.2
```

sssom-py already generates `subject_id` and `subject_label` so no need to include them in the sssom mapping

Adding the `mapping_set_id` allows you to separate out mappings and supply separate metadata for each.

As a stretch goal, I'd love to be able to define the transforms required to convert the external mapping to the local version (I know this topic is under discussion more generally -- what language to use, etc., and if it's even appropriate). The model I am thinking of is [perl Moose's attribute coercion](https://code-maven.com/slides/perl/moose-person-05), with its specification of the source type and the appropriate transformation required (and the language/syntax used for the transform).

In the magical dream world scenario, transforms encoded in the linkml file would be added to the python code generated from linkml to allow data from external systems to be auto-converted to the local schema. I haven't yet thought about this is great depth as Python dataclasses and pydantic lack the sophistication of Moose so some sort of hackery would be involved. Other non-py options might be to use an existing transform or templating language (e.g. XSLT, mustache, jinja) that already has tools available to reduce the implementation burden.

**How important is this feature?**
• Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?**
• Short-term - 2-4 weeks

**Additional context**

We have been generating mappings over the past week, and the more information that we can store about them in one central location, the better. In the short term I may add the information to the local schema using my own tag system ( 😱 ), but obviously it would be better to have something official if this is something that other linkml users may find helpful.
