### ISSUE TITLE
Making equivalentClass assertions in linkml

### ISSUE THREAD

**Issue by deepakunni3** [linkml/linkml#932]
Not sure if this is already possible with the current metamodel but it would be very helpful to be able to mark a class in a schema be equivalent to another class, where the another class is in the same schema or an external schema or an external ontology.

For example, using linkml I would like to say:

```yaml

my gene:
  description: "My gene in my schema"
  equivalent_to: "SO:0000704"

```

and get the following via gen-owl:

```
ex:MyGene owl:equivalentClass SO:0000704 .
```

@turbomam suggested `class_uri` but that seems to translate to `ex:MyGene skos:exactMatch SO:0000704`.
