### ISSUE TITLE
Add support for designates_type in all generators

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#945]
[designates_type](https://w3id.org/linkml/designates_type) is a metamodel boolean slot that can indicate that a slot is intended to hold the value of the instantiated class.

This should minimally constrain things such that the value is an enum of allowed classes (descendants of the holder class)

It can also dynamically determine how a field can be instantiated. Consider data

```yaml
objects:
  - type: my:Person
    ssn: NNN
  - type: my:Pizza
    topping: ...
```

with a schema:

```yaml
  Object:
    attributes:
      type:
         designates_type: true
         range: uriorcurie
   Person:
     is_a: Object
     attributes:
       ssn:
   Pizza:
     is_a: Object
     attributes:
       topping:
```

where objects' range is the parent of Person and Pizza (or linkml:Any). The type field determines how each object is instantiated to a class, and thus what to check (people shouldn't have toppings and pizzas don't have ssns).

Just as with any other slot, the range of the slot that is designated as holding the type is determined by `range`, with the additional conventions:

- if range is `uri` then the full URI would be used
- if range is `uriorcurie` as above then either MAY be used but the CURIE should be the canonical form (we should have a separate type added for strict CURIEs)
- if the range is `string` then the value should be the class name

Currently linkml-owl has a limited form of this
