### ISSUE TITLE
linkml-beginner questions regarding CSV support

### ISSUE THREAD

**Issue by joshmoore** [linkml/linkml#947]
I'm evaluating solutions for a fairly common ETL problem:

 - Multiple users provide data in CSV.
 - Curators define the common schema.
 - Future data should be validated against the schema
 - as well as ingested into a triple store for searching.

But I would additionallylike a way to export the cleaned & resolved data based on the schema. (It need not be identical.)

linkml seems to provide much of the functionality that I need. (Thanks, :heart:!) But I get the feeling that at the moment CSV is (quite reasonably) a second-class citizen. I'm interested to find out if you think with _moderate_ development support could be added for the following:

* [ ] "column aliases": currently the CSVs contain column name strings that I would not want to be modeled elsewhere. Could these be tolerantly converted to something more official (without the user needing to update their spreadsheets)?

* [ ] [inlining](https://linkml.io/linkml/schemas/inlining.html#inlining-with-non-json-serializations): e.g. for CSV data based on the duplicated column names

**Comment by cmungall** [comment]
Thanks @joshmoore!

Yes, you're right there has been less emphasis on CSVs but this is becoming increasingly important for a lot of groups.

We can definitely make some incremental improvements - we do want to make sure that these align with the longer term strategy.

column aliases: I think a general purpose mechanism for different aliases for different purposes:

 - various rules for avoiding reserved words and conforming to field name rules for python. java, sql
 - following local conventions (e.g. javaSlotNames)

What is the best mechanism for providing these? These could always be configurations passed from outside but I think it's good to model directly; could be:

 - the existing structured_alias system
 - mappings, designating reserved prefixes for csv, java, python, etc
 - annotations

inlining: I see you have found this page https://linkml.io/linkml/data/csvs.html#on-the-fly-denormalization which alludes to the existing mechanism for inlining (using https://github.com/cmungall/json-flattener/). But there are many kinds of strategies for flattening and deflattening:

 - https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.io.json.json_normalize.html
 - https://github.com/wnameless/json-flattener
 - https://csvjson.com/json2csv

There are also more general frameworks like YARRRML for doing data transformations. Mapping a nested object to a flat columnar structure could be seen as a subset of a more general data transformation/mapping mechanism. Some initial ideas [in this deck](https://docs.google.com/presentation/d/1ctgT1IfwPjnFQO2Q0sYlM8qk0wiB2_32JyeKyN4Uf8k/edit)

So to answer more directly

- aliases, yes, this should be a small lift
- inlining: I suggest trying the existing system and reporting back where you see improvements could be made in the short term

**Comment by joshmoore** [comment]
It turns out that the column aliasing is simple enough in a preprocessing step that I combine it with xlsx2csv before starting my linkml workflow. (Once I know more about the internals of linkml, I'll look for a place to potentially apply the aliasing.)

The inlining really does seem to be a much more critical piece. Without it, the only workaround I foresee is having a large number of TSVs (and/or sheets in a XLSX) to represent all the structured metadata. I imagine this will prove difficult to use for the clinicians. 


For example:

## schema
```
  Properties:
    description: |-
      Bnode representing personal properties associated with a patient.
    slots:
      - label
    attributes:
      age:
        slot_uri: foaf:age
        range: integer
      birth_date:
        slot_uri: schema:birthDate
        range: date
      gender:
        slot_uri: schema:gender
        range: GenderEnum

  Subject:
    description: |-
      Core patient class.
    slots:
      - id
    attributes:
      ... other properties ...
      properties:
        slot_uri: sio:SIO_000223
        range: Properties
        inlined: true

  Root:
    description: |-
      Root container for the primary identifiers in this dataset.
    tree_root: true
    slots:
      - subjects

slots:
  subjects:
    slot_uri: gbm:TBD_contains
    range: Subject
    inlined: true
    inlined_as_list: true
    multivalued: true
  id:
    identifier: true
    slot_uri: dcterms:identifier
    range: uriorcurie
```

## data

```tsv
id	birth_date	age	gender
subject:0	1953-05-17	62	F
subject:1	1964-06-19	50	M
subject:2	1957-12-16	57	F
subject:3	1960-03-23	55	M
subject:4	1948-05-07	67	M
subject:5	1958-07-13	56	M
subject:6	1991-06-09	23	F
subject:7	1949-10-14	65	M
subject:8	1972-04-10	43	F
subject:9	1954-01-08	61	M
subject:10	1947-03-23	68	M
subject:11	1941-06-15	73	M
subject:12	1971-05-02	44	M
subject:13	1947-06-29	68	F
subject:14	1974-11-10	41	M
subject:15	1951-12-08	63	M
subject:16	1955-11-06	60	M
subject:17	1942-05-16	73	M
subject:18	1975-07-11	41	M
```

lead to:

## output

```
linkml-convert -f tsv -t json -s schema.yaml -C Root -S subjects out.tsv
...
ValueError:  Unknown argument: birth_date = '1953-05-17'
 Unknown argument: age = 62
 Unknown argument: gender = 'F'
```
