### ISSUE TITLE
Defining range of a type or category field

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml#95]
Often we want to add a `type` slot to a model.

biolink-model includes [bl:category](https://w3id.org/biolink/vocab/category) which is a subtype of https://w3id.org/biolink/vocab/type, which has slot_uri rdf:type. Currently we state the range as classoruri

The `type` slot can be any owl Class, but the category slot is intended to be any class in the model.

I tried making the range of `category` be `meta:class`, but this is doesn't work

 - I can't reference meta:class or class without importing biolinkml:meta, but if I do this it introduces clashes, e.g I have `name`
 - I can make a stub class `class` and give it a class_uri of meta:class but this still creates a distinct entity

For type-like slots, we would like mechanisms to be able to state the range of a slot is:

 - any instance of an owl:Class
 - any instance of a meta:Class, i.e. something that is listed under `classes` in the defined datamodel
 - any subclass of a specified class in a datamodel

**Comment by wdduncan** [comment]
Is the use of the label 'type' and issue? For NMDC, can change the label to something else (e.g. 'category').

**Comment by cmungall** [comment]
The name is not an issue

**Comment by cmungall** [comment]
@hsolbrig could we have a special class of enums for this? We wouldn't manually populate it. Instead we would say something like:

```yaml
id: my_schema
...
slots:
  category:
    discriminator: true
    range: category_enum
enums:
  category_enum:
    pv_formula: linkml
    code_set: my_schema
```
