### ISSUE TITLE
Recommended rule set for linter

### ISSUE THREAD

**Issue by pkalita-lbl** [linkml/linkml#965]
Currently the linter makes use a [file that defines defaults](https://github.com/linkml/linkml/blob/main/linkml/linter/config/default.yaml) for every rule. To be as unopinionated as possible the default `level` of each rule is `disabled`. When a user provides a configuration file, the user's configuration is merged into the defaults at runtime to produce a final configuration used for linting.

I think it would be useful to define a recommended rule set as well. It would be used in two ways.

If no config file is provided (either by passing the `--config` command line argument or the existence of a `.linkmllint.yaml` file in the current working directory), the recommended rule set would be used.

Additionally, the recommended rule set can be extended by custom configuration files. Currently linter configuration files are a list of rules at the top level. E.g.:
```yaml
# current
a_rule_name:
  level: error
```
I propose moving the rules specifications under a `rules` top-level key and adding an `extends` top-level key. If the values of `extends` is `recommended` then the user's rule configurations will be merged into the recommended set and then merged into the defaults at runtime to define the final configuration. For example:
```yaml
# proposed
extends: recommended
rules:
  a_rule_name:
    level: error
```
If the recommended rule set has `level: warning` for `a_rule_name`, it will be overridden to have `level: error`. But otherwise the user will get the recommended rule set.

I would propose the following as the recommended rule set:
```yaml
recommended:
  level: warning
no_xsd_int_type:
  level: error
no_invalid_slot_usage:
  level: error
standard_naming:
  level: warning
canonical_prefixes:
  level: warning
```

The `recommended` (that's the one that flags missing descriptions) and `standard_naming` rules tend to generate a lot of failures for large existing schemas that I looked at (biolink, NMDC), but I think they could help get new projects on the right track from the start.
