### ISSUE TITLE
gen-linkml CLI tool does not honor (default) --mergeimports parameter

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml#969]
`gen-linkml` advertises a `--mergeimports` parameter and even states that merging is the default state, as compared to `--no-mergeimports`

>   --mergeimports / --no-mergeimports
                                  Merge imports into source file
                                  (default=mergeimports)

However, the output of running the MIxS schema through `gen-linkml` does not contain the imports

```shell
poetry run gen-linkml \
		--format yaml \
		--mergeimports \
		--no-materialize-attributes model/schema/mixs.yaml
```

---

```yaml
name: MIxS
description: Minimal Information about any Sequence Standard
id: http://w3id.org/mixs
imports:
  - linkml:types
  - checklists
  - core
  - agriculture
  - food_animal_and_animal_feed
  - food_farm_environment
  - food_food_production_facility
  - food_human_foods
  - symbiont_associated
  - host_associated
  - microbial_mat_biofilm
  - miscellaneous_natural_or_artificial_environment
  - plant_associated
  - sediment
  - soil
  - wastewater_sludge
  - water
  - human_associated
  - human_gut
  - human_oral
  - human_skin
  - human_vaginal
  - air
  - built_environment
  - hydrocarbon_resources_cores
  - hydrocarbon_resources_fluids_swabs
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/
  mixs.vocab:
    prefix_prefix: mixs.vocab
    prefix_reference: https://w3id.org/mixs/vocab/
  MIXS:
    prefix_prefix: MIXS
    prefix_reference: https://w3id.org/mixs/terms/
  MIGS:
    prefix_prefix: MIGS
    prefix_reference: https://w3id.org/mixs/migs/
default_prefix: mixs.vocab
```
