### ISSUE TITLE
in a collection of Person objects, linkml-validate only checks that the collection object itself is valid, not the content of the collection's objects

### ISSUE THREAD

**Issue by sierra-moxon** [linkml/linkml#975]
For the schema:
```
classes:
  PersonCollection:
    description: >-
      A collection of things
    slots:
      - entries
  NamedThing:
    description: >-
      The most generic type of entity that has a name
    abstract: true
    slots:
      - id
      - name
      - birth_date
      - age_in_years
  Person:
    is_a: NamedThing
    slots:
      - primary_email
      - vital_status
      - pets
  Animal:
    is_a: NamedThing
    slots:
      - species
      - breed
      - color
      - weight_in_mgs
slots:
  vital_status:
    description: living or dead status
    required: true
  entries:
    description: A collection of things
    multivalued: true
    range: Person
  pets:
    description: a collection of animals that lives with and is taken care of by a person.
    multivalued: true
    range: Animal
```
should:
`% linkml-validate -s src/linkml_tutorial_schema/schema/linkml_tutorial_schema.yaml src/data/examples/Persons.yaml --target-class=PersonCollection`
return no errors with this example data?
```
entries:
  - id: P:001
    name: fred bloggs
    primary_email: fred.bloggs@example.com
    age_in_years: 33
    pets:
      - animal:001
      - animal:002
```
I would expect it to fail because my P:001 is missing vital_status
but it succeeds (it returns 'None' which I am assuming means 'successfully validates' - is this a valid assumption?) - what am I doing wrong in my schema?

If I validate on the Person class itself, with the same data (without the 'entries' collection), it fails to validate as expected.
